### ISSUE TITLE
Vandalized ZIM

### ISSUE THREAD

**Issue by 12to-the12** [kiwix/kiwix-desktop#1003]
I'm aware this isn't the correct place to post this issue, but I was unable to find a ticket tracker for the ZIM archives on the kiwix.org page. If somebody has more information than me, please redirect me to the correct place to post this.

I just downloaded the latest full Wikipedia zim archive over torrent and wanted to report that it's been vandalized. The page on Africa is just the word N*****s repeated 241141 times.

**Comment by kelson42** [comment]
@12to-the12 This is a known issue, we will publish a new version soon.
