### ISSUE TITLE
Windows desktop version freezes on startup

### ISSUE THREAD

**Issue by lepatachou** [kiwix/kiwix-desktop#1005]
Hi,
I'm trying to use the latest version of Windows (kiwix-desktop_windows_x64_2.3.1-2.zip) and the program freezes on startup. The main window remains white and the processor is at maximum. The problem exists on Windows 11. On another Win10 machine it works fine.
I reinstalled MS Visual C++ framework, the problem remains the same.
Any advice on where this could come from?
Thanks

**Comment by Jaifroid** [comment]
I'm running this version of kiwix-desktop on my Windows 11 machine, and it doesn't manifest this behaviour. Did you find a solution?

**Comment by Jaifroid** [comment]
Seems to be a duplicate of #879 or #885.
