### ISSUE TITLE
Attempt to use Offline/Local file zims from the "Other" category fail

### ISSUE THREAD

**Issue by madusmacus** [kiwix/kiwix-desktop#1013]
Latest Windows 10 - Kiwix Version  2.3.1

Any Attempt to use Offline/Local file zims below end in error (error is listed below)

100r-off-the-grid_en_2023-09.zim
www.ready.gov_en_2023-06.zim
opentextbooks_en_all_2023-08.zim
courses.lumenlearning.com_en_all_2021-03.zim

One common issue is that all these zims are categorised under "Other"
but i believe the are all good zims because the Kiwix-Js thing that microsoft store has opens them

Resultant error below
"Error
The requested URL can not be loaded because service workers are not supported here.
If you use Firefox in Private Mode, try regular mode instead.
If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost."

I am a coder but dont want to start poking around in your code :¬)

**Comment by madusmacus** [comment]
Update: i tried a newer than latest version
[kiwix-desktop_windows_x64_2.3.1-2.zip](https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.3.1-2.zip)      2023-04-28 10:19  121M

Sadly no difference the error persists

**Comment by mgautierfr** [comment]
As said, those zim (sadly) need service workers and (sadly) kiwix-desktop doesn't support it.

You can start a server (from kiwix-destkop) and access it using localhost url.

**Comment by madusmacus** [comment]
Ahh I understand now thanks :¬) and very fast

**Comment by madusmacus** [comment]
only reopened because it was added to the 2.4.0 timeline
please close if i did wrong
