### ISSUE TITLE
search issue ,return results while displaying there is no result

### ISSUE THREAD

**Issue by xiaoyifang** [kiwix/kiwix-desktop#1014]
When use the fulltext search ,  the page return : "No results were found for"
but there are results returned also.
![image](https://github.com/kiwix/kiwix-desktop/assets/105986/0fc56b0e-a80b-4454-93b8-ad00a5e158e6)

search term :  平方
zim file:
https://www.mirrorservice.org/sites/download.kiwix.org/zim/wikipedia/wikipedia_zh_mathematics_mini_2023-10.zim

**Comment by kelson42** [comment]
@xiaoyifang Thank you for your bug report. It looks like the bug has been fixed in the current dev version (you can check with the [nightly](https://download.kiwix.org/nightly/)):
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/2a90b647-224c-4db8-b1c8-516b1b8cb5a7)
