### ISSUE TITLE
Change description text for Linux package

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#102]
Seen on [flathub](https://flathub.org/apps/details/org.kiwix.desktop), and told by Higher Powers that changes should be requested here.

The current text reads: 
"(..) these can be opened by Kiwix even if you are no connection whatsoever."

are -> have
connection -> connectivity

**Comment by nedrichards** [comment]
Overall the appdata needs a fair bit of work actually. It should have a screenshot, OARS tags and release tags ideally. Also I'm pretty sure that XGPL isn't a valid SPDX licence.

**Comment by mgautierfr** [comment]
Fixed by #103
