### ISSUE TITLE
kiwix takes very long to open on power saving mode

### ISSUE THREAD

**Issue by 2-www** [kiwix/kiwix-desktop#1030]
on power saving mode, kiwix can take minutes to open, while on balanced it opens in a second

version 2.3.1 flatpak

**Comment by Jaifroid** [comment]
I'm not sure there's anything we can do about this. Power-saving mode in any OS will lower your CPU maximum usage and may affect performance in other areas as well, so performance will inevitably be hit...

**Comment by kelson42** [comment]
There is nothing we can really do here.
