### ISSUE TITLE
On Ubuntu, full screen functionality is broken

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-desktop#1031]
I've just installed `sudo apt install kiwix`. I'm using Ubuntu 23.10 on ThinkPad X1. My user interface language is Hebrew.

When I click the full screen button, one of the things happens:
1. The screen becomes all black and I don't see anything.
2. I see an animation of the window maximizing itself, and it gets stuck halfway through.

I can press Ctrl-F11 to get back from that state to a normal window. However, the actual full screen functionality doesn't work.

Thanks.

**Comment by kelson42** [comment]
Wayland related bug, I believe we already have a ticket about that...

**Comment by kelson42** [comment]
Other Wayland fullscreen issue is #365. Not sure if this is a duplicate!?

**Comment by kelson42** [comment]
Duplicate and upstream. Once #1033 implemented, this will vanish.
