### ISSUE TITLE
The usage of the "Filter language" message is unclear

### ISSUE THREAD

**Issue by amire80** [kiwix/kiwix-desktop#1032]
This is a question about the message `"language-searcher-placeholder": "Filter language"`

I suspect that it's no actually used anywhere.

I tried finding it in the actual app, but no matter where I clicked, I couldn't see it.

It may be used in `void KiwixChoiceBox::showPlaceholder()`, but that method doesn't seem to be called anywhere. However, the last time I wrote any C++ code was in 2011, so I might be wrong.

If it's not used, it should be removed.

If it used somewhere, it would be great to clarify in qqq what does it mean exactly or perhaps change the message itself. Maybe changing it to "Filter by language" could be clearer.

**Comment by kelson42** [comment]
@amire80 Filter sidebar has been totally rewitten but still not released. Have you tried with http://download.kiwix.org/nightly/2024-01-23/ ?

**Comment by kelson42** [comment]
@juuz0 Do the old unused strings have been removed properly from the master in English during your effort to rewrite the library?

**Comment by kelson42** [comment]
@juuz0 ?

**Comment by juuz0** [comment]
@kelson42 Sorry for the delay! But yes, in my knowledge, they were already removed.

Regarding @amire80 question, this particular `language-searcher-placeholder` can be found at https://github.com/kiwix/kiwix-desktop/blob/693b7b1ea569c80f497db508b880db5de959e0fc/src/kiwixchoicebox.cpp#L215 - as you can see, that full string depends on the type (language, category, etc.)

**Comment by mgautierfr** [comment]
So what left is to add description in qqq to help translator.

**Comment by ShaopengLin** [comment]
Not familiar with the qqq.json syntaxes. I am wondering if simply adding context for `"searcher-placeholder"` is enough for the translations. The prefix just needs a direct translation I believe.

If not I can just add context for all three of the filters.

**Comment by amire80** [comment]
There's no special syntax. Just write the context documentation in the qqq file with the same key as in the en file.

Or you can simply write it as a comment here and I'll add it.
