### ISSUE TITLE
Port to qt6

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#1033]
Needed for : https://github.com/kiwix/kiwix-build/issues/594 and #1029

**Comment by adamlamar** [comment]
I began looking at this.

* Ubuntu 22.04 Jammy includes Qt 6.2.4. I am not sure if upgrading to 6.2 will fix all the issues, but it should help.
* I ran the recommended `clazy` and it came back mostly with some missing Q_OBJECT macros and a few recommendations to change string handling. When I started to compile with Qt 6.2.4, I ran into a bunch more issues like renamed classes etc.

A few questions:

1. Will kiwix-desktop need to support compiling for both qt5 and qt6 for a period of time? Looks like I can add version checks
2. Will we need to support 6.2.4 for distros like debian/ubuntu, and also support 6.3+ for other environments?

**Comment by kelson42** [comment]
Very promising!

> Will kiwix-desktop need to support compiling for both qt5 and qt6 for a period of time? Looks like I can add version checks

It would be better, but I don't think this would be reasonable to expect this if very conplicated to achieve.

> Will we need to support 6.2.4 for distros like debian/ubuntu, and also support 6.3+ for other environments?

Not sure about the differences betwenn 6.2 and 6.5, but we definitly target 6.5 to fix problems related to h264.

**Comment by adamlamar** [comment]
Gotcha, I will plan to support both for now, and if it turns out to be too hard then I'll back that out. So far it seems doable with some macro magic.

**Comment by adamlamar** [comment]
Here's what I've got so far: https://github.com/kiwix/kiwix-desktop/pull/1046
