### ISSUE TITLE
Windows 11 - Kiwix desktop "not responding" freezing

### ISSUE THREAD

**Issue by awisniewski** [kiwix/kiwix-desktop#1037]
Hello,
Glad this offline tool is available for Wikipedia.
I like the basics of this program and really want to enjoy it but I'm struggling.
The application freezes and goes (Not responding) when I download a library file.

I've even tried downloading stuff I didn't necessarily want but was small file....example "Ray Charles" 1.79 MB
Clicking Download , program goes unresponsive and windows task bar says (Not responding).
Sometimes it unlocks after 3-5 minutes (timed), other times I force close the app after 5 minutes. 
(https://github.com/kiwix/kiwix-desktop/assets/11380254/a075c04a-8b4c-4a9e-bae0-2e548b29e0d3)

My computer has a Intel Core I5 CPU that was just built last year....so nothing very old here.
Internet download speeds: 90Mbps download, 12Mbps upload

Kiwix Desktop: Version: 2.3.1  
[Downloaded from https://kiwix.org/en/applications/            and Unzipped ]

Windows 11  Home Edition (22h2)

I'm not seeing any Antivirus alerts or blocks. 

Is there something I can check as far as logs?

**Comment by Jaifroid** [comment]
While this sounds like a bug, as a workaround you do know you can download archives from outside the app, right? Go to library.kiwix.org. If you need filenames you can also use download.kiwix.org. Then just open the file from within the app.

**Comment by kelson42** [comment]
@veloman-yunkan Is that one of the scenarios you are currently investigating/fixing?

**Comment by veloman-yunkan** [comment]
@kelson42

Yes and no. #87 which was a starting point for my work was about issues with huge downloads. However after some study of the code responsible for download management it became obvious that it is plagued with numerous bugs. So now my objective is to redesign & clean it up so that most bugs are eliminated automatically. I won't be satisfied with a situation that no obvious bugs are left, instead I am aspiring to achieve a design that obviously contains no bugs.

**Comment by awisniewski** [comment]
> While this sounds like a bug, as a workaround you do know you can download archives from outside the app, right? Go to library.kiwix.org. If you need filenames you can also use download.kiwix.org. Then just open the file from within the app.

Thank you!  I wondered about direct downloads and didn't find anything at first glance. This is great. Thank you.
Also very happy to hear of the quick response to having the issue looked into. You guys are great.

Just wanted to note I tried Kiwix on my Windows 10 Home, 22H2.  Worked great.

One other note on the issue with my my Windows 11 machine. After Kiwix freezes and and if it unlocks on the download.
One strange thing is the position that you were in the download window as far as scrolling down say to midway, resets and the available downloads list goes back to the top.

**Comment by kelson42** [comment]
Fixed by https://github.com/kiwix/kiwix-desktop/pull/1038

**Comment by CrimsonicSniper** [comment]
^ #1228
