### ISSUE TITLE
Wikipedia

### ISSUE THREAD

**Issue by lecouvie** [kiwix/kiwix-desktop#1039]
I have managed to download the text wikipedia of 59g and the images for wikipedia of 150g. How do i combine them so that when I search for an article I get both?  

thanks for the support

norm

**Comment by veloman-yunkan** [comment]
Are you talking about ZIM files (though currently there are no ZIM files larger than 102G on https://download.kiwix.org/zim/wikipedia/)? If yes, then the larger file should contain both images and text, hence you don't have to combine it with the smaller file.

**Comment by lecouvie** [comment]
Yes, I must have added the 59g and 102g by mistake. Thanks for the info!

**Comment by kelson42** [comment]
@lecouvie It's not really possible for the moment to search in many ZIM files at the same time using Kiwix Desktop. But this is something we still have to implemente. See for example https://github.com/openzim/libzim/issues/734
