### ISSUE TITLE
icon of file is not displayed

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-desktop#105]
on arch linux the icon is not displayed.
```
$ /tmp/kiwix-desktop_x86_64_2.0-beta1.appimage 
add widget
Unknown property icon
```

![image](https://user-images.githubusercontent.com/825568/52500954-76106c80-2bdf-11e9-88de-52fd7401a5d1.png)

**Comment by kelson42** [comment]
@soloturn Have you tried the beta2? Have you tried the flathub pacakge https://wiki.kiwix.org/wiki/Flatpak_%26_Flathub ?

**Comment by soloturn** [comment]
tried now flatpack as well. there the icon is displayed in "all files". seems to be an appimage thing, see #104. that i need to re-launch kiwix to see a downloaded file in "local files" is a different issue i gues?

**Comment by kelson42** [comment]
@soloturn What about the beta2 in appimage format? The last problem seems to already reported at https://github.com/kiwix/kiwix-desktop/issues/93

**Comment by soloturn** [comment]
where is the beta2 appimage? there is no nightly isn't it?

**Comment by kelson42** [comment]
@soloturn All releases are available at https://download.kiwix.org/release/kiwix-desktop/

**Comment by kelson42** [comment]
@soloturn I think this pb is fixed. A feedback on your side would be welcomed.
