### ISSUE TITLE
[Linux] Close Buttton on Other Tabs Closes the Displayed Tab Instead

### ISSUE THREAD

**Issue by ShaopengLin** [kiwix/kiwix-desktop#1053]
On Linux, the close button on tabs seems to only close the currently displayed tab, irrelevant of which tab the close button is located on. The problem is displayed in this video:

https://github.com/kiwix/kiwix-desktop/assets/39098000/a7b748c6-9bc4-446c-8ee5-200476ee7e81

I supposed this was the code that was handling tab closures, and it seems to be the case. This issue doesn't seem to be present on Windows, which means it might be an OS-dependent behavior. The middle button close functionality works fine, and it uses indexes of clicked tabs to close tabs. I have a method to retrieve a tab index (not merged) based on the widget which might be useful #1048? 
![Screenshot from 2024-03-07 12-35-58](https://github.com/kiwix/kiwix-desktop/assets/39098000/e3b02498-adf2-4120-b999-385b20591c19)

**Comment by kelson42** [comment]
I I can not reproduce the problem with dev version (and Qt6). I kind of believe this might already have been fixed.

**Comment by riftsandroses** [comment]
Couldn't find any errors in the closeTab(int index) logic. Working on verifying the index calculation by checking how currentIndex() is updated.

**Comment by kelson42** [comment]
@ShaopengLin Any chance you could fix that bug? This is actually a pretty serious one!

**Comment by ShaopengLin** [comment]
I will see what I can do. I am navigating to see how to get the widget that triggered the closeAction event.
