### ISSUE TITLE
On closing the nth tab, (n+1)th tab becomes the active tab

### ISSUE THREAD

**Issue by vinurk** [kiwix/kiwix-desktop#1055]
As shown in the video, i have three tabs open.
When the 1st tab is active tab, and I close the 2nd tab, 3rd tab becomes the active tab.
Expected result: The currently active tab should stay active no matter which tab is closed.
![Tab demo](https://github.com/kiwix/kiwix-desktop/assets/67734434/154d5282-c858-474b-9419-9b4b27f76b44)

**Comment by kelson42** [comment]
@vinurk Thank you for the bug report but this bug has already been reported and a PR is ongoing.

**Comment by vinurk** [comment]
Could you please direct me to the PR, i believe #1054 is a different issue..?

**Comment by ShaopengLin** [comment]
Yeah this is a different issue and still present even after I fixed my issue. Though this should be a easy fix changing index movements after tab closure, or is just fixed after Veloman refactors the code..
