### ISSUE TITLE
REGRESSION: Fullscreen shortcut (F11) not working on WSL

### ISSUE THREAD

**Issue by sgourdas** [kiwix/kiwix-desktop#1067]
I am using WSL (with Ubuntu on Windows 11) and I noticed that F11 is not working. As shown below, even while navigating the menu, a shortcut for the action is not available (pressing the button works).

![Screenshot_3](https://github.com/kiwix/kiwix-desktop/assets/57002743/2b606f4f-a494-4c75-9c0d-f70d0ccbe5b2)

Printing the value of  `QKeySequence::FullScreen` it gives an empty string. So I assume that because it is launching from WSL into the Windows environment, it cannot handle deciding what platform it is in, so it ends up undefined.

I will make a fix for the issue, since it might be possible to happen in other instances as well and it also helps during development.

**Comment by kelson42** [comment]
AFAIK rhe key sequences are not always the same depending the OS. The fullscreen key sequence has already been discussed in other tickets.... so not sure at this stage if this is a bug.

**Comment by sgourdas** [comment]
Yeah, I have noticed that it differs from OS to OS. Details on how Qt handles it are on the FullScreen part of [qKeySequence](https://doc.qt.io/qt-6/qkeysequence.html#StandardShortcuts-enum).

To explain better, the issue is on some edge scenarios like launching kiwix-desktop from WSL into Windows, where that sequence is not mapped to anything and results in it being undefined. IMO this solves that case.

I am not sure how possible/often of an occurrence it is, but I though since I was at it I might add the functionality, if it is helpful.

**Comment by kelson42** [comment]
> AFAIK rhe key sequences are not always the same depending the OS. The fullscreen key sequence has already been discussed in other tickets.... so not sure at this stage if this is a bug.

@sgourdas Looks like you don't have read the ticket like you said, at least not https://github.com/kiwix/kiwix-desktop/issues/304. As a consequence I believe you have broken the feature. `F11` shortcut is not working anymore on Ubuntu. 
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/213dc7d0-0b35-4028-b0a6-8ef1b901b662)

**Comment by sgourdas** [comment]
Sorry @kelson42 but I indeed had not seen #304. Despite that, my commit does not change the behavior described in that issue.

My change only applies to cases were discrepancies occur on weird setups like mine (WSL), where the OS is not sure what to chose. Specifically, as you can see in the code the shortcut is only hardcoded to `F11` **when `QKeySequence::FullScreen` is empty/undefined.** 
```
const auto fullScreenKeySeq = QKeySequence(QKeySequence::FullScreen).isEmpty()
                                ? Qt::Key_F11
                                : QKeySequence::FullScreen;
CREATE_ACTION_ICON_SHORTCUT(ToggleFullscreenAction, "full-screen-enter", gt("set-fullscreen"), fullScreenKeySeq);
```


On your case I see that the shortcut has been set to `B`, which is very odd, but should have in any case came from a resolution of `QKeySequence::FullScreen` which is strange as that is not even in the [Standard Shortcuts Table](https://doc.qt.io/qt-6/qkeysequence.html#standard-shortcuts).

So I can provide a fix for this, may you please confirm if:
- This issue has been reported more than once
- This is indeed the shortcut assigned to fullscreen and is not only visual. Does pressing `B` toggle fullscreen on your setup?


@veloman-yunkan could we have your opinion here as well please?

**Comment by veloman-yunkan** [comment]
It looks like the original fix for this ticket was correct and an error was introduced by [my suggestion for improvement](https://github.com/kiwix/kiwix-desktop/pull/1068#discussion_r1535232017). The compiler should have hinted at the error via a compilation warning but warnings are usually ignored unless they are made to be treated as errors. We were given a second chance to spot the issue via code review when [`-Werror` was enabled](https://github.com/kiwix/kiwix-desktop/pull/1051) a little later, but I was not smart enough to recognize it.

I have now fixed the bug in #1080.

**Comment by kelson42** [comment]
@veloman-yunkan Should we compile with -Wall?

**Comment by veloman-yunkan** [comment]
@kelson42 We can try to.
