### ISSUE TITLE
Add ability to browse in multiple languages

### ISSUE THREAD

**Issue by b16r05** [kiwix/kiwix-desktop#107]
This is probably going to be a very unusual feature request. Say a user's primary language is English. But, he also uses French, for example, as his secondary language. With both language zim files downloaded... maybe the ability to switch to a different language can be added, just like it is on the official wikipedia website... so basically, IF a page for a particular entry exists in another language, THEN, that/those language(s) are shown, ELSE, nothing is shown available for particular entries in another language. I must admit I haven't read how zim works... compressed pages, expansion on the fly, etc. or if this is even possible or already available : )

**Comment by mgautierfr** [comment]
It could be interesting.
However we are far from be able to do this for now.

It is most on the kiwix-desktop side to check that a "same" zim in different language is available and check if the "identical" page exists. (With all the difficulty that the url/title would probably different because languages are different)

**Comment by b16r05** [comment]
Yes, I understand about the current status of the project. Thank you for considering it and adding the "enhancement" tag. I just looked at how it is done on Wikipedia Official. 

For the entry on fish, you have this in English
https://en.wikipedia.org/wiki/Fish

and clicking on the French link on the left you get 
https://fr.wikipedia.org/wiki/Poisson

I knew the en and fr, but just noticed the translation fish>Poisson. So, they must have some database of words/translations/pointers, redirects, etc. Kiwix could mirror a copy locally, especially if multiple zim files are downloaded by users. 

Just a few thoughts... and want to leave it here : )

**Comment by kelson42** [comment]
@jetownfeve21 Would that be doable after you have improved the whole handline? If not how much work would be needed?

**Comment by kelson42** [comment]
This is mostly a request for openzim/mwoffliner, at least first.
