### ISSUE TITLE
Remember current tab from previous user session

### ISSUE THREAD

**Issue by ShaopengLin** [kiwix/kiwix-desktop#1073]
#1048 introduced the feature to reopen tabs on start-up. However, on many browsers (Firefox, Chrome), the current tab is also being kept track of when restoring user sessions. It would be good UX to have this feature.

One thing to discuss is: that we are not currently reopening invalid Zim tabs, empty tabs, settings tabs, etc. Users could be on one of those tabs from the previous session, including the library tab. How should we define the behavior of our tab reopenings?

**Comment by kelson42** [comment]
> One thing to discuss is: that we are not currently reopening invalid Zim tabs, empty tabs, settings tabs, etc. Users could be on one of those tabs from the previous session, including the library tab. How should we define the behavior of our tab reopenings?

Remembering these tabs is probably the right thing to do AFAP.

**Comment by ShaopengLin** [comment]
@kelson42 If we were to re-open all tabs(including invalid ones), should we have a designated, "404 not found" page? Or should we just leave it blank? Also tagging @mgautierfr since he also mentioned about this behavior back in the original issue.

**Comment by ShaopengLin** [comment]
If I get it correctly, we can simply open them as blank pages at the moment. We can achieve the functionality first and then open another issue for creating dedicated error message tabs.

**Comment by kelson42** [comment]
> If I get it correctly, we can simply open them as blank pages at the moment. We can achieve the functionality first and then open another issue for creating dedicated error message tabs.

I confirm. You can go ahead with the implementation.
