### ISSUE TITLE
Crash if Xapian triggers an exception

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1074]
I have such a crash scenario by running a search with a corrupted ZIM files with dev version of Kiwix Desktop on Linux:
```
Handling request QUrl("zim://fe516a05-6c7a-38ce-8ef6-1fdeecbb8f3d.search?content=fe516a05-6c7a-38ce-8ef6-1fdeecbb8f3d&pattern=paris ")
terminate called after throwing an instance of 'Xapian::DatabaseCorruptError'
Aborted (core dumped)
```

Kiwix should not crash in such a scenario but print a proper error like Kiwix Serve:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/2bb0ec15-2f6a-4383-a584-fa09b593b3d3)

We should do this proper error handling for Xapian based suggestions as well (if not already done).

See also https://github.com/kiwix/kiwix-apple/issues/622

**Comment by kelson42** [comment]
@veloman-yunkan It seem nothing might have to be done here, see https://github.com/openzim/libzim/issues/870#issuecomment-2042827654. Please confirm then so we can close this ticket.

**Comment by veloman-yunkan** [comment]
@kelson42 I provided a fix that works with the current code and will keep working after the proposed fix is implemented in `libzim`.
