### ISSUE TITLE
Unable to open zim file on Ubuntu16.04 x64 LTS.

### ISSUE THREAD

**Issue by SYCstudio** [kiwix/kiwix-desktop#108]
Hi,

I'm a Linux user. I have downloaded the latest "wikipedia_en_all_novid_2018-10.zim" from the https://wiki.kiwix.org. But I got "Unable to load '/home/***/wikipedia_en_all_novid_2018-10.zim'. Are you sure this is a ZIM file?" when I want to open it with kiwix-0.9-linux-x86_64.

I check the md5 and it was correct. So I try other files, such as "wikipedia_zh_all_novid_2018-07"or"wikisource_en_all_novid_2018-10",and they all work good.

I try to use the newest version for kiwix. I tried kiwix-0.10-linux-x86_64 ,but it still not working.I also tryed kiwix-desktop_x86_64_2.0-beta2.appimage, but the terminal showed:

```bash
./kiwix-desktop_x86_64_2.0-beta2.appimage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_kiwix-VbywUs/usr/bin/../lib/libpng16.so.16)
./kiwix-desktop_x86_64_2.0-beta2.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_kiwix-VbywUs/usr/bin/../lib/libsystemd.so.0)"
```

I know a little about appimage. I used to create one on an Ubuntu18.04 and I find it could not run on Ubuntu16.04. But the one created on Ubuntu16.04 can run well in Ubuntu18.04. Maybe here is the same reason.

At last, I succeded to load this file with the chrome-extension of Kiwix. But it is not convenient to open an zim file in this way. I find some issues about this problem on Github and the fourm, but it seems that this problem is still not fixed, at least on Linux.

Something maybe useful:

OS:Ubuntu16.04 LTS x64  
Tryed : kiwix-0.9-linux-x86_64,kiwix-0.10-x86_84,kiwix-desktop_x86_64_2.0-beta2.appimage,kiwix-chrome_2.5.0  
Succeded : kiwix-chrome_2.5.0  
Chrome version:Version 71.0.3578.98 (Official Build) (64-bit)

Sorry for trouble you.

**Comment by kelson42** [comment]
@SYCstudio Thank you for your feedback. Should work if you install last Kiwix Desktop 2.0 beta from Flathub, see https://flathub.org/apps/details/org.kiwix.desktop

**Comment by SYCstudio** [comment]
It works. Thanks.

Why not update this method on https://wiki.kiwix.org/wiki/Software ? I think it will help more people who have the same problem.

**Comment by kelson42** [comment]
Yes, we will update the wiki
