### ISSUE TITLE
Compile without warnings

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1087]
Kiwix should be able to compile without warnings. Once achieved we should put proper compiler options to report any warning in error.

**Comment by kelson42** [comment]
@ShaopengLin until PR review moves forward, can you move on this issue?

**Comment by ShaopengLin** [comment]
I am having a hard time getting the build system working on Windows. Is there any documented step on it?

**Comment by kelson42** [comment]
@ShaopengLin Yes, not easy and this even changing currently. Please tackle the provlem on linux first.

**Comment by ShaopengLin** [comment]
@kelson42 Maybe I missed some details, but we are already treating warnings as errors in Linux. #1085 seems to be a Windows-specific problem.

**Comment by kelson42** [comment]
I will check again but as I have open the issue, the compilation had warning on Linux so the acI was not failing because of this.

**Comment by ShaopengLin** [comment]
Any updates? I cannot observe any warnings other than on Qt 5.12.8, where the warnings are rather, from Qt source code.

**Comment by kelson42** [comment]
Ok, then closing for the moment and will reopen when Insee a warning in the CI.
