### ISSUE TITLE
Can not play ted_en_business_2018-07.zim  video

### ISSUE THREAD

**Issue by hamkido** [kiwix/kiwix-desktop#109]
It doesn't work on all the zim video.

**Comment by kelson42** [comment]
The problem here is the mp4/h264 format. This was an attempt to move on, but we fail. We will come back to webm. Using kiwix-serve and Firefox/Chrome will allow to see everything fine. This is a workaround. No fix on Kiwix Dekstop needed. @hamkido Thank you anyway for reporting the pb.
