### ISSUE TITLE
[Bug] Internet Encylopedia of Philosophy is broken on Linux

### ISSUE THREAD

**Issue by Extroonie** [kiwix/kiwix-desktop#1093]
I downloaded internet-encyclopedia-philosophy_en_all_2024-02, and opening it Kiwix on Linux (AppImage) shows this:

![image](https://github.com/kiwix/kiwix-desktop/assets/42417143/cf5867ab-e2d2-408c-8641-cc8cfa9055fa)

However, it seems to work here: https://library.kiwix.org/viewer#internet-encyclopedia-philosophy_en_all_2024-02/A/iep.utm.edu/

**Comment by kelson42** [comment]
@Extroonie Thank you for your bug report. this is a know issue. Actually a limitation of Kiwix Desktop we are working to fix. But this will be live in a few months, not before. In the meantime here is a workaround https://github.com/kiwix/kiwix-desktop/issues/487#issuecomment-1531146541
