### ISSUE TITLE
Support for previewing online books

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1100]
Currently in `kiwix-desktop` one cannot preview a book from the online library directly in `kiwix-desktop`. They have to visit https://library.kiwix.org using their web-browser and find the book of interest. Having the ability to preview books with a single click will improve the user experience.

**Comment by kelson42** [comment]
I support the feature request

**Comment by kelson42** [comment]
@ShaopengLin Sounds straight forward to me. Would you be able to provide a mockup of a „preview“ button?

**Comment by ShaopengLin** [comment]
> @ShaopengLin Sounds straight forward to me. Would you be able to provide a mockup of a „preview“ button?

What type of behaviour do we want?
- Open the link to another browser.
- Open the link in Kiwix-Desktop. Qt Webview should be able to load the website through HTTP request to https://library.kiwix.org/.

**Comment by kelson42** [comment]
@ShaopengLin Open the link in external browser, behaviour should be the same like opening an external link in ZIM content.

**Comment by ShaopengLin** [comment]
I have some potential mockups

1. This is pretty straightforward and keeps the same feel of the UI. One problem is, that once the download starts, users cannot preview the website anymore.
![Screenshot from 2024-05-12 23-14-30](https://github.com/kiwix/kiwix-desktop/assets/39098000/7a419dcf-47ea-495f-8744-b470a5069667)

2. Having the preview button in the description solves the issue from _1._. The downside is that it isn't as readily apparent to the user.
![Screenshot from 2024-05-12 23-44-58](https://github.com/kiwix/kiwix-desktop/assets/39098000/cf9d435e-0c88-4098-84ff-c714bed27a69)

3. Having another column for preview solves both. 
![Screenshot from 2024-05-12 23-51-49](https://github.com/kiwix/kiwix-desktop/assets/39098000/44da9bb3-90b1-4e36-a5cb-69fe106cb7ab)

All 3 are doable and personally, I am leaning toward _2._ or _3._. The code for the download column is pretty cohesive currently, and handling an extra preview button makes its responsibility way too complicated.

**Comment by kelson42** [comment]
@ShaopengLin The 2 is the best to me IMHO, but please put the preview link after the description (instead of before).

**Comment by ShaopengLin** [comment]
Do we want the preview button to persist after the download? 

If so:
To confirm, what are the book URL rules on https://library.kiwix.org/? The download URL is no longer provided by the library after it has been downloaded so I cannot extract the book URL then.

From what I have seen, our book URLs are formatted as:
- name + '\_' + (flavor + '\_' ) (if exist) +  date (yyyy-mm)

**Comment by kelson42** [comment]
> @kelson42 Do we want the preview button to persist after the download?

No, should be only available for online library.

**Comment by veloman-yunkan** [comment]
> @ShaopengLin The 2 is the best to me IMHO, but please put the preview link after the description (instead of before).

Let's first implement this feature as an additional entry in the context menu. Once it works a button or a link can be added in a follow-up PR.

**Comment by veloman-yunkan** [comment]
@kelson42 Note that the functionality was implemented via a context menu entry (which kind of makes this feature somewhat hidden). Maybe it makes sense to open a ticket for conspicuous UI for the preview action.

**Comment by kelson42** [comment]
@veloman-yunkan Good enough for me at this stage
