### ISSUE TITLE
Kiwix-desktop doesn't compile on Fedora 40 with Qt5

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#1105]
This seems to be a Qt issue : https://bugreports.qt.io/browse/QTBUG-123153

This issue is a tracking issue of the upstream bug.

**Comment by mgautierfr** [comment]
It is Qt5

**Comment by kelson42** [comment]
@mgautierfr Upstream affected version if Qt6.8, but maybe Qt5 is affected as well... or this is another ticket...
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/67ad8bce-7e35-461d-ba39-d0dcdecf2046)

Maybe we should just try to write our code differently?

**Comment by mgautierfr** [comment]
It is a issue on Qt side.
I've already added a comment on the upstream issue telling that I'm impacted on Qt5 too.

**Comment by xvitaly** [comment]
Should be fixed in [FEDORA-2024-784f049ccd](https://bodhi.fedoraproject.org/updates/FEDORA-2024-784f049ccd). This update contains the [fix](https://src.fedoraproject.org/rpms/qt5-qtbase/c/664f24855f26ccaee2501b26a50108b054bf19e2?branch=rawhide).

**Comment by xvitaly** [comment]
I'm not a Qt maintainer. I simply emailed the maintainers and they applied the fix.

**Comment by mgautierfr** [comment]
> @mgautierfr Can you check? You will need to download and install qt5-qtbase{,-devel} directly [from Koji](https://koji.fedoraproject.org/koji/buildinfo?buildID=2451245) until it reaches testing/stable.

Koji version installed and kiwix-desktop is compiling. Thanks for pinging Qt maintainer.
Can I put a confirmation somewhere to help validate the pkg ? (I already have a fedora account)

**Comment by xvitaly** [comment]
>  Can I put a confirmation somewhere to help validate the pkg ? (I already have a fedora account)

Yes. Give positive karma to this update in Bodhi.

**Comment by kelson42** [comment]
@mgautierfr I'm not very sure about the impact of this issue? Is that Fedora specific? If not which versions of Qt are exactly impacted? I wonder why we are not impacted at all on Debian/Ubuntu? Finally I would ask if this really makes sense to keep this tivket open here in our repo?

**Comment by kelson42** [comment]
Upstream bug has ben fixed
