### ISSUE TITLE
Kiwix crashes whenever I try to download Wikipedia (Windows 11, Latest Version, Portable)

### ISSUE THREAD

**Issue by TheGr8Coder** [kiwix/kiwix-desktop#1106]
Whenever I try to install Wikipedia (Images), it crashes after 5 seconds every time.

Specs
Windows 11
Core i3 1005G1
20GB RAM
1TB SSD (300GB Free)

**Comment by kelson42** [comment]
@mgautierfr Which version? Have Oungriednwith latest nighlty https://download.kiwix.org/nightly/2024-05-11/kiwix-desktop_windows_x64_2024-05-11.zip ?

**Comment by TheGr8Coder** [comment]
no, let me try.
but i have been using the desktop Microsoft store app to download.
so, I have another question, that can I use the download from ms store for portable version?

**Comment by kelson42** [comment]
@Jaifroid @TheGr8Coder Might that be this is a bug report for the wrong repository?

**Comment by TheGr8Coder** [comment]
What do you mean? Please specify

**Comment by TheGr8Coder** [comment]
Also, in the given nightly, Kiwix lags immediately after download.
Also, another thing to point out, that when the original Kiwix (portable) lagged, after like 20 secs, the file will appear as completed downloaded (50gb) in file explorer, but on opening it in kiwix shows that the download is invalid.

**Comment by Jaifroid** [comment]
@TheGr8Coder If you are referring to the Microsoft Store version of Kiwix JS (PWA) then this is the wrong repository. This is the repository for Kiwix Desktop, which is a different version of the app.

Are you trying to download the full ~100GB English Wikipedia with images? Downloading that ZIM inside the app is probably not going to work. Instead, I recommend you download it with https://www.qbittorrent.org/. On the Wikipedia ZIM's download page, you'll see a link to a torrent file. If you click on that, qBittorrent will open and ask you where you want to save the archive. This method is much more resilient for such a large file.

You can get torrent files either in the app's download library, or directly from https://library.kiwix.org (when you click the thin "Download" button on a tile, you will be offered a torrent download amongst other choices).

**Comment by Jaifroid** [comment]
> Also, in the given nightly, Kiwix lags immediately after download.
> 
> Also, another thing to point out, that when the original Kiwix (portable) lagged, after like 20 secs, the file will appear as completed downloaded (50gb) in file explorer, but on opening it in kiwix shows that the download is invalid.

If you installed the version @kelson42 linked to, then that is Kiwix Desktop. I'm not sure what "lags" means in this context? Do you mean the app becomes unresponsive? In any case, with either Kiwix JS Electron (portable) or with Kiwix Desktop, it's not recommended to download enormous archives in-app, as you will likely run into timeout issues or incomplete downloads. 50GB is too small for full English Wikipedia with images, so it sounds like you had a partial download which got aborted.

**Comment by kelson42** [comment]
@TheGr8Coder Where (link?) have you exactly downloaded Kiwix?

**Comment by TheGr8Coder** [comment]
Thanks! I will try the method by Jaifroid.
