### ISSUE TITLE
Windows 10 - Not Settings Menu, All Files Does Nothing  (windows_x64_2.0-alpha6-1)

### ISSUE THREAD

**Issue by Intrepid-MR** [kiwix/kiwix-desktop#1107]
RE: kiwix-desktop_windows_x64_2.0-alpha6-1
Windows 10 22H2

After running Kiwix, the following issues occur:
1. "Settings" is missing from the menu.
2.  Clicking on "All Files" does nothing.

**Comment by kelson42** [comment]
This is a super old verwion of the software. Plase try with latest release https://kiwix.org/en/applications/

**Comment by Intrepid-MR** [comment]
The ONLY Windows version available at https://kiwix.org/en/applications/
is in fact:  2.0-alpha6-1
There is NO more recent Windows version.

**Comment by kelson42** [comment]
Sorry we have created a regression here

**Comment by rgaudin** [comment]
@Intrepid-MR thank you for reporting ; we only provide a single link to the latest version. You made no mistake but we introduced a bug in the redirection (the link is always the same but its redirection target changes with new releases).
