### ISSUE TITLE
TED videos only play for 2 seconds

### ISSUE THREAD

**Issue by garuffalo** [kiwix/kiwix-desktop#111]
Preconditions:
Hardware: Dell Latitude D630 (2.4Ghz Intel Core2Duo; Intel 965GM graphics; 8GB RAM)
Operating System: Linux Mint 19.1
Kiwix Version Installed: org.kiwix.desktop (2.0-beta3 Flatpak)

Steps to reproduce:
Download TED Talks videos within Kiwix application (tried Global Issues and Design)
Select a video and click Play button

Actual and expected result:
On any video selected, when Play button is clicked, there is audio and video, but only for 2 seconds. Only 2 seconds on any video. (Tested about 10 videos.)

Additional Information:
Other Kiwix non-video compilations, e.g., Stack Exchange articles, display without issue.

**Comment by kelson42** [comment]
@garuffalo Thank you for reporting this problem. We are aware about it. We need to rebuild the ZIM files with the webm container (for the videos).

**Comment by garuffalo** [comment]
Updated to org.kiwix.desktop 2.0-beta4 (Flatpak) but had problems crashing, so I tried the Appimage version of the same application. In the Appimage version the same Ted videos did play!!! There was a little issue with the fullscreen button being non-functional, and the keyboard shortcut for "Zoom In" was inconsistent with what was stated in the menu (Ctrl+Shift++ worked, but not Ctrl++). But the videos played!!! There were some other minor glitches with the Appimage also, which I can post if you'd like.

**Comment by kelson42** [comment]
@garuffalo OK, strange...Would you be able to open a bug for the crash with the beta4 please?

**Comment by kelson42** [comment]
@garuffalo I need to try to reproduce the pb.

**Comment by garuffalo** [comment]
Actually I did open an issue "#117 Kiwix 2.0-beta4 will not launch". Perhaps I should have titled it "Kiwix 2.0-beta4 crashes at launch", because the Kiwix window briefly comes into view for a second before crash. Behaviour is still the same, so it would seem redundant open another issue.

**Comment by kelson42** [comment]
Do you still have problem with this newly created ZIM file? https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-09.zim. I suspect a problem with the ZIM file itself.

**Comment by garuffalo** [comment]
Kiwix Flatpak, Version : 2.0-rc2 played the newly created ZIM file video completely. Player controls worked, except fullscreen and picture-in-picture did not. But the video did play just fine.
