### ISSUE TITLE
Few improvements around Settings directories

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1113]
See what I have:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/de139c76-cc1a-4be3-b7c1-227e864e468f)

Here are the problems:
* The whole directory (if long) is not displayed. I propose to implement proper ellipsis display (ending with ...)
* We should have a hint, when move over the directory, displaying the whole path
* Right click on the path, should allow to copy it

**Comment by kelson42** [comment]
@sgourdas Can you please start with that one?

**Comment by sgourdas** [comment]
@kelson42 i agree with your comments, but one note:

>I propose to implement proper ellipsis display (ending with ...)

I think it would be better to make it start with `...` not end). The last part of a directory seems more indicative to me, than the first.

**Comment by kelson42** [comment]
@sgourdas I reopen, why the monitor directory has not been fully treated?! 

![Image](https://github.com/kiwix/kiwix-desktop/assets/1029718/0d0912b9-b3f0-4aa5-a084-12fb7d9737fe)

**Comment by sgourdas** [comment]
@kelson42 good question. Will open a new PR to sync the changes.
