### ISSUE TITLE
Document properly the paths where data and configuration are saved/loaded

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1114]
We should have in the GitHub wiki a page which should have one entry per thing we save on the local filesystem with the following information:
* file which is saved
* Purpose
* When it is written/updated
* Default path on Linux
* Default path on Windows
* Customisable: yes/no

Here a few comments helpful:
* https://github.com/kiwix/libkiwix/issues/1085#issuecomment-2119204311
* https://github.com/kiwix/kiwix-desktop/issues/694#issuecomment-2049562023
* https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)

**Comment by kelson42** [comment]
@sgourdas That would be the next task to do.

**Comment by kelson42** [comment]
@sgourdas Everything clear on this issue? Anything stopping you to move forward?

**Comment by sgourdas** [comment]
@kelson42 I will have a WIP published soon, for a second look.

**Comment by sgourdas** [comment]
@kelson42 I published a V1. I would appreciate some directions if possible, since I am not sure about my workflow.

**Comment by kelson42** [comment]
@sgourdas where it is? link?

**Comment by sgourdas** [comment]
[Here](https://github.com/kiwix/kiwix-desktop/wiki/Data-and-Configuration-File-Paths) you are

**Comment by kelson42** [comment]
@sgourdas Sorry for the late feedback. I would like to see things in a table format. I have created a stub of one at the top of the page. Please complete it and put real paths so this is to figure out where are things.

**Comment by sgourdas** [comment]
@kelson42 I moved the information in your table. For files like `library.xml` where the path is evaluated in a series of steps how would you like to present the information? 

Specifically for this as per mgautierfr's [comment](https://github.com/kiwix/kiwix-desktop/issues/461#issuecomment-644628800) is goes like:

1. Use library.xml in local directory if it exists
2. Use system/user library.xml if it exists
3. Move library.xml from old/wrong directory to new/good one.
4. Else, create a system library.xml and use it.

**Comment by sgourdas** [comment]
> $APPDATA is not clear, please replace by something clearer which fit to the reality

I tried to make the paths shorter using `$APPDATA` for `%appdata%`. Maybe using `%appdata%` is better or do you prefer the full path?

> ZIM path can be customisable in the app itself, why there is a cross?

With `Customisable` do we mean that the **path** can be changed? Or that its **use-case** can be customized? 
In the first case would it be clearer to call it `Modifiable`?

> What is the different between kiwix-desktop.session and kiwix-desktop.conf, it is really not clear why we have two files?

`kiwix-desktop.session` is used for the app's automatic session information whereas `kiwix-desktop.conf` is used for user specific settings. I changed the wording to make it more clear.

**Comment by kelson42** [comment]
> > $APPDATA is not clear, please replace by something clearer which fit to the reality
> 
> I tried to make the paths shorter using `$APPDATA` for `%appdata%`. Maybe using `%appdata%` is better or do you prefer the full path?

Clearly, I needed the full path

> > ZIM path can be customisable in the app itself, why there is a cross?
> 
> With `Customisable` do we mean that the **path** can be changed? Or that its **use-case** can be customized? In the first case would it be clearer to call it `Modifiable`?

Yes "customisable" means that you can change the path.
 
> > What is the different between kiwix-desktop.session and kiwix-desktop.conf, it is really not clear why we have two files?
> 
> `kiwix-desktop.session` is used for the app's automatic session information whereas `kiwix-desktop.conf` is used for user specific settings. I changed the wording to make it more clear.

Sorry but with your sentence you neither explain what are the differences (what means exactly "automatic session information"??????) nor why?

Sorry for the very long time without reaction my side, but it was taking to many back and forth. I have updated the wiki page and will close that ticket so we can move forward even if we have still a few question marks unfortunately.

**Comment by kelson42** [comment]
Read the result at https://github.com/kiwix/kiwix-desktop/wiki/Data-and-Configuration-Files
