### ISSUE TITLE
Add support of IPv6 IP to the HTTP daemon mode

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1119]
Once https://github.com/kiwix/libkiwix/pull/1074 is merged

**Comment by mgautierfr** [comment]
@aryanA101a, now that kiwix/libkiwix#1074 is merged, kiwix-desktop fails to build as the API has changed. Can you fix at least the compilation on kiwix-desktop side please ?

**Comment by kelson42** [comment]
> @aryanA101a, now that [kiwix/libkiwix#1074](https://github.com/kiwix/libkiwix/pull/1074) is merged, kiwix-desktop fails to build as the API has changed. Can you fix at least the compilation on kiwix-desktop side please ?

Handled in #1121
