### ISSUE TITLE
ZIM file icon is not associated properly with *.zim file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#112]
Install of beta4 with Flathub on Ubuntu 18.04 and navigating in the filesystem via default file browser. That said, double click on the file opens Kiwix properly with the ZIM file content.

**Comment by kelson42** [comment]
It does not have to be the Kiwix icon, if a custom ZIM icon could be put, it would be even better.

**Comment by mgautierfr** [comment]
We have found with @jetownfeve21 how to associate an icon to a zim file.

@schoenbaechler Would it be possible that you create an icons for the zim files ?
Probably base on the app icons but something that looks more like a file. Thanks :)

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Please use this one as long as we don't have something better https://github.com/kiwix/kiwix-xulrunner/blob/master/kiwix/chrome/icons/default/zim.icns

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Do you have fix it on Windows or Linux? With my Flathub installation and RC1, my ZIM files have no specific icon (anymore?)
