### ISSUE TITLE
Fix breaking changes introduced by the new libkiwix api

### ISSUE THREAD

**Issue by aryanA101a** [kiwix/kiwix-desktop#1121]
Breaking changes:
```
1. std::map<std::string,IpAddress> getNetworkInterfaces()
2. std::string getBestPublicIp(bool ipv6)
```

**Comment by kelson42** [comment]
We should also update minimal version requested, but this requires to release libkiwix (whoch should happen soon IMHO).

**Comment by veloman-yunkan** [comment]
@kelson42 I think we have to decide if it's OK to bump the major version of libkiwix or we'd better amend the support for IPv6 in `libkiwix` so that the old API is preserved.

**Comment by kelson42** [comment]
> @kelson42 I think we have to decide if it's OK to bump the major version of `libkiwix` or we'd better amend the support for IPv6 in `libkiwix` so that the old API is preserved.

@veloman-yunkan have no strong opinion beside the strict respect of semantic versionning. Do you have a concrete and prefered way to move forward?

**Comment by veloman-yunkan** [comment]
> Do you have a concrete and prefered way to move forward?

No, I don't.

**Comment by kelson42** [comment]
@veloman-yunkan Looking a bit more in details, I believe we can modify the libkiwix to just make a minor release (so keep backward compatibility). This sounds the best approach to follow if confirmed that this is trivial to fix the libkiwix. Do you?

**Comment by kelson42** [comment]
Reopening as we have a few points open.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Looking a bit more in details, I believe we can modify the libkiwix to just make a minor release (so keep backward compatibility). This sounds the best approach to follow if confirmed that this is trivial to fix the libkiwix. Do you?

Yes, I do.

**Comment by veloman-yunkan** [comment]
> Reopening as we have a few points open.

I think those points rather belong to `libkiwix`

**Comment by kelson42** [comment]
> > Reopening as we have a few points open.
> 
> 
> 
> I think those points rather belong to `libkiwix`

Yes, @veloman-yunkan May I ask you to make straight the libkiwix patch?

**Comment by veloman-yunkan** [comment]
Sure, will do

**Comment by veloman-yunkan** [comment]
Done (kiwix/libkiwix#1093)
