### ISSUE TITLE
wikispecies category filtering fails

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#113]
I get no result

**Comment by mgautierfr** [comment]
It seems that both `wikispecies_en_all_nopic_2018-08` and `wikispecies_en_all_novid_2018-08` are tagged with `wikimedia`, not `wikispecies`

**Comment by kelson42** [comment]
@mgautierfr thx. I have ask to put the tag properly https://github.com/openzim/zim-requests/issues/144. That said, I wonder about the added value of a category with only one entry. I'm in favour of removing it.

**Comment by mgautierfr** [comment]
I've use d the list of directories in http://download.kiwix.org/zim/ as category list.
This is a temporary solution and we should use a better one (create it dynamically based on the real content available)

**Comment by kelson42** [comment]
@mgautierfr I'm not interested in a dynamic category listing. I want a static one. Please remove the category "wikispecies". This is useless. I will probably remove the directory anyway too.

**Comment by mgautierfr** [comment]
> I'm not interested in a dynamic category listing

You should. Having a static list is not a good things. We have plan to integrate kiwix-serve (or equivalent) in kiwix-desktop and android. This means that there will be no official serve and each server may have its own categories. If we have a static list, we will have empty categories displayed and empty categories we don't know about not displayed.
