### ISSUE TITLE
Unable to change download directory (windows 11)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#1136]
From a user:

> I tried to install Kiwix on a flash drive using my Windows computer. After putting it on a flash drive I created a folder in the Kiwix directory called "downloads" and went to the program settings to set the download location to "downloads". However, the program kept locking up from the flash drive so I decided to install it on the computer. However, now, every time I run Kiwix, it tries to create the download directory on the flash drive and crashes the computer trying to do some download operation. Even when I completely erase all Kiwix files and reinstall, it still makes these same folders when I run the new install and still crashes the computer. I cannot get Kiwix to stop trying to make a folder and start downloading to it.

**Comment by kelson42** [comment]
@sgourdas The user obviously tries with version 2.3.1 but we should try to reproduce and see how ot behaves now and if it is a new bug or a duplicate. Can you do that please?

**Comment by sgourdas** [comment]
@kelson42 I tried to reproduce the issue taking the below steps:

1.  Plug USB to Windows
2.  Copy over the kiwix for Windows folder
3.  Create `downloads` folder inside the kiwix directory
4.  Run `kiwixdesktop.exe`
5.  Change the download path in settings (point to the newly created `downloads` folder)
6.  Downloaded a new zim file (which went into the new folder)
7.  Opened the new file and it displays correctly
8.  Exited kiwix
9.  Ejected USB
10.  Run local `kiwixdesktop.exe`
11.  Check download path on settings (it is still pointing to the ejected USB's `downloads` folder)
12.  Try to download a new zim file, I get the below:
![image](https://github.com/kiwix/kiwix-desktop/assets/57002743/a1e1ab21-6f40-4934-ad97-2e4861442806)
13.  Changed the path to a local one
14.  Downloaded a new zim file (goes correctly in the new path)
15.   Opened the new file and it displays correctly

Tested with version 2.3.1

**Comment by kelson42** [comment]
So fixed, the user should try with a nightly.
