### ISSUE TITLE
flatpak linux arm64 not working offline

### ISSUE THREAD

**Issue by magdesign** [kiwix/kiwix-desktop#1137]
while the flatpak version runs nicely when we are online, it will not display the offline wiki when offline.

**Comment by kelson42** [comment]
@magdesign Thank you for your bug report but this is a bit too short. What are the steps you do and what do you get exactly (when you are offline)?

**Comment by magdesign** [comment]
i installed the kiwix flatpak on an alpine linux arm64 device. 
downloaded the ~50gb wiki offline library, linked the app to the custom location of the download. when opening kiwix while connected to the internet, it opens and displays the wikipedia files. when launching kiwix while beeing offline, its empty and i can not do anything...

**Comment by veloman-yunkan** [comment]
> linked the app to the custom location of the download

@magdesign How did you *"link the app to the custom location of the download"*?

**Comment by magdesign** [comment]
manualy selecting the location in home folder, since i downloaded the huge file previously on  a computer..

**Comment by veloman-yunkan** [comment]
So you just opened the file via the File menu (or Ctrl+O)?

**Comment by veloman-yunkan** [comment]
Is your file located on a local drive? From what you are telling the first guess is that it is located on a network drive that becomes unavailable when your system is offline. Can you access that file outside the kiwix app in offline mode?

**Comment by magdesign** [comment]
i used kiwix on a linuxmobile device. installed as flatpak. the offline wiki was on the same device in the home folder. when i had internet access everything worked as expected. but when i turned on the device to look up something when there was no internet connection, it did not display the wiki. i am sure its something simple, like it can not grab the fonts or whatever. however, in need of storage i installed on offline llm instead, in hope the answers it gives me are more or less true.
someone else must test and re-open this issue if they run into the same bug. thanks for taking your time.
