### ISSUE TITLE
Can't Be able to click on the Search Bar.

### ISSUE THREAD

**Issue by Ritvyk** [kiwix/kiwix-desktop#114]
The search bar is not active and it is not responding to the click.
Couldn't be able to click on the search bar so that i can input and search something.
version i tried : https://www.kiwix.org/en/downloads/kiwix-reader/ 
Name- Kiwix Reader Portable Version For Windows.

**Comment by kelson42** [comment]
@Ritvyk Could you please make give the step-by-step procedure you are following? Do you have ZIM file loaded?

**Comment by Ritvyk** [comment]
@kelson42 No i haven't any ZIM file preloaded. But i Tried several times to click on the search bar for input but it isn't responding on the click. Currently Working on it Budd!

**Comment by kelson42** [comment]
@Ritvyk Which version exactly from the software do you have? What is your operating system?

**Comment by Ritvyk** [comment]
@kelson42 The version is downloaded  https://www.kiwix.org/en/downloads/kiwix-reader/ from this link and 4-beta version the operating system I am currently using is Windows !0 32-Bit

**Comment by kelson42** [comment]
@Ritvyk I guess you use a version we don't maintain anymore here (website should be updated). Please try with Kiwix-desktop https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-beta4.zip

**Comment by Ritvyk** [comment]
@kelson42  it's a 64-Bit version. I need 32 bit Version

**Comment by kelson42** [comment]
We won't provide 32 bits. So, if I correctly understand this bug report is about an older version of Kiwix-Desktop.
