### ISSUE TITLE
Endless OS Encyclopedia

### ISSUE THREAD

**Issue by HomeroBretas** [kiwix/kiwix-desktop#1141]
Hello everyone. I am an Endless OS user and I noticed that the Encyclopedia software in the Endless System is not updated for Brazilian users, who speak Portuguese_BR. I have also asked the Endless OS team to update the information in this software several times. But I have not been successful with them. So I would like to ask the developers of the Kiwix project to contact Endless to solve the problem: The information that appears in the Endless Encyclopedia about Brazil and its current president is out of date, compromising the learning of the Software user. Thank you very much.
Homero Bretas - Brazil

**Comment by kelson42** [comment]
@HomeroBretas I don't know exactly how works the reader of Endless and I can obviously not speak for them. Even if we work together with Endless, I don't believe asking them would change anything about what they plan to do. But, I believe that you have a custom based version of Wikipedia in Portugues thta we have built for Endless. Latest version of that file is available at https://mirror.download.kiwix.org/zim/.hidden/endless/wikipedia_pt_endless_maxi_2024-05.zim.

**Comment by HomeroBretas** [comment]
Thank You Very Math.
________________________________
De: Kelson ***@***.***>
Enviado: quarta-feira, 10 de julho de 2024 14:53
Para: kiwix/kiwix-desktop ***@***.***>
Cc: HomeroBretas ***@***.***>; Mention ***@***.***>
Assunto: Re: [kiwix/kiwix-desktop] Endless OS Encyclopedia (Issue #1141)


@HomeroBretas<https://github.com/HomeroBretas> I don't know exactly how works the reader of Endless and I can obviously not speak for them. Even if we work together with Endless, I don't believe asking them would change anything about what they plan to do. But, I believe that you have a custom based version of Wikipedia in Portugues thta we have built for Endless. Latest version of that file is available at https://mirror.download.kiwix.org/zim/.hidden/endless/wikipedia_pt_endless_maxi_2024-05.zim.
