### ISSUE TITLE
Title tab left padding is not OK

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1142]
See
![image](https://github.com/user-attachments/assets/e35e6a69-ff28-442a-9f85-7f7d79370f5e)

Pretty sure this is a regression, but not clear when it has been introduced

**Comment by kelson42** [comment]
@ShaopengLin Can you please fix this quickly?

**Comment by ShaopengLin** [comment]
@kelson42 I can make the PR anytime but I do not know what it was looking like before. Was it just a small padding before the title?

**Comment by ShaopengLin** [comment]
This is also very correlated with #594. I have realized several problems now in the Right-to-left and Left-to-right layout, and will make a summary there.

**Comment by kelson42** [comment]
@ShaopengLin Everywhere the padding shouldbe the same on top, bottom, right and left. Here this is the case. You should have the same padding on the left like on the right. my guess this is something like 2px.
