### ISSUE TITLE
Library download spinner is not aligned properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1145]
Should be aligned/centered properly with the "Download" link
![image](https://github.com/user-attachments/assets/564419ed-26f2-46bb-bd68-162be19d28c3)

**Comment by kelson42** [comment]
@ShaopengLin Any chance you coukd fix that one quickly?

**Comment by ShaopengLin** [comment]
I think so. We are manually painting these so I will shift it.
