### ISSUE TITLE
Check that the download can be saved to the target file-system

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1148]
One of the issues behind #916 seems to be that a large download is saved to a FAT32 filesystem that has enough free space but cannot host files larger than 4GiB. Our pre-download checks must be enhanced.

**Comment by charanbhatia** [comment]
hi, can you please assign this issue to me. I want to work on this.

**Comment by kelson42** [comment]
@charanbhatia You should create the primitive in the libkiwix and do it in a way it is very quick to execute and without side effect. How would such a function look like and work to your opinion?
