### ISSUE TITLE
ZIM file downloaded in a monitored directory by an external tool may fail to be added to the library automatically

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1150]
When `kiwix-desktop` monitors a directory it attempts to add new ZIM files to the library only when they appear. If a ZIM file is being downloaded by an external tool (that at the beginning of the download creates the file using its final name, rather than using a temporary file name indicating that the download is in progress and renaming upon completion), the attempt to open the ZIM file will most likely fail, it will be considered invalid and won't be added to the library. If the download completes during the same `kiwix-desktop` session that will go unnoticed by `kiwix-desktop`. However, once `kiwix-desktop` is restarted the file will appear in the library.

**Comment by veloman-yunkan** [comment]
I am not sure if we should fix this issue. I filed it so that it is at least documented.

**Comment by kelson42** [comment]
@veloman-yunkan Not even sure myself this is a bug... how would look like the fix?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Not even sure myself this is a bug... how would look like the fix?

@kelson42 Currently directory monitoring only pays attention to new entries in the monitored directory. It should be enhanced to also check the modification timestamps of ZIM files. Then if a file is updated since it was last attempted to be opened (with no success), then we should try to add it again.

I am going to implement it now.
