### ISSUE TITLE
Icon is distorded

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#1153]
On Windows 11, the app's icon, either in Explorer or in the taskbar is distorded. Other icons are OK.

<img width="324" alt="Screenshot 2024-07-26 at 11 23 05" src="https://github.com/user-attachments/assets/3a40084c-d50f-40df-ad88-445b614a458e">

<img width="314" alt="Screenshot 2024-07-26 at 11 23 16" src="https://github.com/user-attachments/assets/2611a919-5e2c-4467-86e7-cc0ec2e26aa0">

**Comment by kelson42** [comment]
@sgourdas Can you please fix that one?
