### ISSUE TITLE
Kiwix prepper issue

### ISSUE THREAD

**Issue by ua2pants** [kiwix/kiwix-desktop#1157]
New on here so I apologize for my ignorance. I recently purchased the prepper package of kiwix and put it on a 512gb sd card. Flashed and did get it working.

My issue however, is there a way to also use raspberry OS as a desktop but still have access to the prepper package?

**Comment by kelson42** [comment]
@ua2pants Thank you for reaching to us but this repository is for an other solution. Please write to the Kiwix Hotspot service desk per email at hotspot@kiwix.org.

**Comment by ua2pants** [comment]
Thank you for reaching out to me, I am new to all of this and just sent
them an email.

Thank you for your time and I hope you have a good night!

Sincerely,
Josh
