### ISSUE TITLE
Add code of conduct to repo

### ISSUE THREAD

**Issue by darigovresearch** [kiwix/kiwix-desktop#1158]
Thought it would be helpful to add the code of conduct like in the android repo https://github.com/kiwix/kiwix-android?tab=coc-ov-file

**Comment by kelson42** [comment]
We should do that at organisaion level, where we should have already something IMHO

**Comment by kelson42** [comment]
@darigovresearch Thank you for reporting this issue. I have put one at the organisation level so it applies to all repositories, see https://github.com/kiwix/.github/blob/main/CODE_OF_CONDUCT.md
