### ISSUE TITLE
Portable Kiwix, allow to custom all local storage/configuration locations

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1166]
In a case of a portable Kiwix (running on a portable USB drive for example), we want to keep everything local on USB drive. We don't want to interfere with a potential local instance. Therefore, none of the [data and configuration files](https://github.com/kiwix/kiwix-desktop/wiki/Data-and-Configuration-Files) should be written [at the usual locations](https://github.com/kiwix/kiwix-desktop/wiki/Data-and-Configuration-Files).

A portable Kiwix is technically defined when there is (an empty) file `.portable` just beside the Kiwix binary. Detecting the presence of that file will activate the portable mode.

The portable mode will read/write the data files to another (predefined) location positioned relatively position to the Kiwix binary:
* `data/kiwix-desktop.session`
* `data/kiwix.session`
* `data/*.zim`
* ...

In such a mode nothing should be written outside the local Kiwix `data` directory.

This issue superseeds [older issuer #630](https://github.com/kiwix/kiwix-desktop/issues/630)

**Comment by sgourdas** [comment]
@kelson42 for implementation purposes, if the `.portable` is present, can I assume that the packager will have also created the `data` directory as well?

**Comment by kelson42** [comment]
> @kelson42 for implementation purposes, if the `.portable` is present, can I assume that the packager will have also created the `data` directory as well?

Yes you can

**Comment by sgourdas** [comment]
Since `getDataDirectory()` will need to be modified, so as to not complicate things with libkiwix, I will wait a bit on this until #1169 is merged.

**Comment by kelson42** [comment]
@sgourdas Any news here?

**Comment by sgourdas** [comment]
Ok, I will start parallel work on this
