### ISSUE TITLE
Kiwix 2.0-beta4 will not launch.

### ISSUE THREAD

**Issue by garuffalo** [kiwix/kiwix-desktop#117]
**Preconditions:**
Hardware: Dell Latitude D630 (2.4Ghz Intel Core2Duo; Intel 965GM graphics; 8GB RAM)
Operating System: Linux Mint 19.1
Kiwix Version Installed: org.kiwix.desktop (2.0-beta4 Flatpak)

**Steps to reproduce:**
   I have had Kiwix 2.0 (Flatpak 2.0-beta4) running, although with random crashes. After downloading and opening several new .zim files, Kiwix is not launching at all. Terminal output of launch is attached. (output.txt)
[output.txt](https://github.com/kiwix/kiwix-desktop/files/3025645/output.txt)

**Further observations:**
Ran flatpak update in terminal. I believe it applied an update to org.gnome.Platform/x86_64/3.28
After that, Kiwix still not launching. However, now, different terminal output (output2.txt)
[output2.txt](https://github.com/kiwix/kiwix-desktop/files/3025646/output2.txt)

**Actual and expected result:**
Tried many times to launch Kiwix, using Terminal or Linux Mint Menu. Failed each time. Tried restarting computer; still failed.

**Additional Information:**
Note that I have put .zim files in /home/bobz/.var/app/org.kiwix.desktop/data/kiwix directory, which I hope is the proper location! Can you confirm?

Zim files appear to function properly using kiwix.js, with Chrome browser.

**Comment by kelson42** [comment]
@garuffalo Thank you for your bug report. Would you be able please to run `zimdump -C` (to check ZIM file integrity) on your ZIM files? You can find it as part of the zim-tools https://download.openzim.org/release/zim-tools/

**Comment by garuffalo** [comment]
I verified all my ZIM files with zimdump, as you requested. All files returned result, "checksum ok".
[output3.txt](https://github.com/kiwix/kiwix-desktop/files/3026544/output3.txt)

**Comment by mgautierfr** [comment]
What is the output of `flatpak list` ?

**Comment by mgautierfr** [comment]
On a newly installed linux-mint, I have no problem to run kiwix-desktop.

My output of `flatpak list -d`:
```
Ref                                                Origin  Active commit Latest commit Installed size Options       
org.kiwix.desktop/x86_64/stable                    flathub 5751174552cc  -              19,0 MB       system,current
org.freedesktop.Platform.html5-codecs/x86_64/18.08 flathub 6ebb408b6e25  -               8,8 MB       system,runtime
org.gtk.Gtk3theme.Mint-Y/x86_64/3.22               flathub 853079368347  -             318,0 kB       system,runtime
org.kde.Platform/x86_64/5.12                       flathub 5539ccd35690  -               1,2 GB       system,runtime
```

**Comment by kelson42** [comment]
@garuffalo Could you please confirm this is still a problem with the latest RC?

**Comment by garuffalo** [comment]
No problem with launch now. Kiwix, Flatpak Version : 2.0-rc2
Have not used kiwix-desktop for some time. Seems much better now.
