### ISSUE TITLE
Kiwix refuses to read ZIM file

### ISSUE THREAD

**Issue by lands39** [kiwix/kiwix-desktop#1173]
File in question: https://download.kiwix.org/archive/zim/wikipedia/wikipedia_en_wp1-0.8_orig_2010-12.zim

Desktop app refuses to read the file along with the kiwix server running on my NAS. SHA256 has been confirmed to match the checksum listed on the site (610f742648d8360241326ea73b440329e198eacb27b9142667853260f9c51ae6).
![image](https://github.com/user-attachments/assets/bc3110a2-048c-4f12-b440-ac9314eed2c3)

**Comment by kelson42** [comment]
@lands39 Thank you for your bug report, what is the version of Kiwix you use?

**Comment by lands39** [comment]
i'm not sure, its the latest version of the desktop reader that was available on the site. the kiwix server on linux also doesn't seem to find it, i'm not sure what version this is or how to check.

**Comment by kelson42** [comment]
I will check but this ZIM file is almost 15 years old, pretty possible that there is a problem to read it.

**Comment by lands39** [comment]
how would i make it compatible with whatever the current standard is? if i can't, what software do i need to view this? i haven't really played around with kiwix too much so i don't really know how it works apart from "funny file gives me webpage"

**Comment by kelson42** [comment]
@lands39 Closing the issue, please reopen if with latest ZIM/Kiwix you still have problems.

**Comment by lands39** [comment]
how do i re-open this? i was using the latest version and it doesn't work.

**Comment by lands39** [comment]
i downloaded this old file because i wanted to look at some old info.
