### ISSUE TITLE
"Stack_exchange" category should be "Stack Exchange"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#118]

**Comment by mgautierfr** [comment]
In fact it should be "stackexchange" because it is the used tag.
Or you should have a translation system. But then, free tag is not the right way to categorize content in this case.

**Comment by kelson42** [comment]
@mgautierfr It is "Stack Exchange" https://en.wikipedia.org/wiki/Stack_Exchange, and this is the label for the tag "stack_exchange". None of this should be translated.

**Comment by mgautierfr** [comment]
Yes, I know this is "Stack Exchange". But the tag is `stackexchange`, not `stack_exchange`.
There is no distinction for now between the tag value and what is displayed to the user (tag label).

But the tag label is part of the UI, and if we do the things right (what I really want to do), we must translate it. I don't know how "Stack Exchange" is translated in other language, but Wikipedia (for example) has different names in different languages (https://en.wikipedia.org/wiki/List_of_Wikipedias#List)
