### ISSUE TITLE
Do Not Save Translation for Filters in Settings Session

### ISSUE THREAD

**Issue by ShaopengLin** [kiwix/kiwix-desktop#1185]
From [#1175 comment](https://github.com/kiwix/kiwix-desktop/pull/1175#discussion_r1725694230)

1. We should only need to store a list of strings, the filter keys, in the session. The problem comes with backward compatibility as the previous sessions are now invalid. Need to discuss how to best approach this issue.

2. KiwixChoiceBox needs to adapt to the new session management.

**Comment by ShaopengLin** [comment]
@kelson42 @veloman-yunkan if we are ok with that one time lost, then indeed we can make this change directly. This then should come with #1175, as it will not introduce a huge detour.  If you all agree could you close this? I will make the modification back over at #1175.

**Comment by veloman-yunkan** [comment]
Fixed by #1175
