### ISSUE TITLE
kiwix-desktop.exe did not open wikipedia_de_all_maxi_2023-01.zim more

### ISSUE THREAD

**Issue by Tinkerpete** [kiwix/kiwix-desktop#1196]
I use kiwix-desktop.exe from kiwix-desktop_windows_x64_2.0.1-1 for years with the wikipedia_de_all_maxi_2023-01.zim!

When i today try to open the zim file kiwix endet without any comment! Any idea?

- Windows 10 Home
- 22H2
- 19045.4780
- AMD Ryzen 9 3950X 16-Core Processor 
- 32,0 GB

**Comment by kelson42** [comment]
@Tinkerpete Would you be able please to try with latest development version of Kiwix? https://download.kiwix.org/nightly/2024-09-05/kiwix-desktop_windows_x64_2024-09-05.zip

**Comment by kelson42** [comment]
@Tinkerpete Any news?

**Comment by Tinkerpete** [comment]
I have now try 'wikipedia_de_all_maxi_2024-05.zim' and the newest kiwix_desktop and it works.

But before i had nothing aware changed and from one day to the next it did not work more. I want to know what can the reason for this!

**Comment by kelson42** [comment]
@Tinkerpete It's very unclear to me what goes wrong, but I suspect that for some reason the ZIM wil has been slightly corrupted and latest dev version can besser deal with it.

**Comment by Tinkerpete** [comment]
Since I haven't changed the kiwix program or the Zim file in the last few years, it can't really have anything to do with it. A different Zim file also led to the termination. It should rather have something to do with an update of the operating system, or perhaps a file handle has somehow not been deleted.

Does kiwix do anything special when handling the large Zim files? Something that other programs don't do? I would really like to know what the problem is, because a local Wikipedia is very important to me and if it stops working from one day to the next, it is not trustworthy for me.         

Translated with DeepL.com (free version)
