### ISSUE TITLE
ZIM file downloadable from browser but not from kiwix

### ISSUE THREAD

**Issue by stemy2** [kiwix/kiwix-desktop#1197]
Hello,

I tried with no success to download the wikipedia ZIM file, but kiwix says "this download is not available". So i tried to download it from https://download.kiwix.org, and it works.  i don't get it.

**Comment by kelson42** [comment]
@stemy2 Does it still fails with Kiwix Desktop? If "yes" can you please share a screenshot?

**Comment by stemy2** [comment]
Sadly, the screenshot is not very informative.

![Screenshot_20240905_181117](https://github.com/user-attachments/assets/790df225-0a34-4850-8d22-9a5213859ecf)

**Comment by kelson42** [comment]
@stemy2 Indeed! May I ask you to try with the latest dev version? https://download.kiwix.org/nightly/2024-09-05/ please?

**Comment by kelson42** [comment]
@stemy2 Any feedback?
