### ISSUE TITLE
Kiwix Doesn't Work

### ISSUE THREAD

**Issue by okanakinci** [kiwix/kiwix-desktop#12]
Latest Kiwix Linux Version doesn't work on Ubuntu 18.04 and Linux Mint 19.

Here is the terminal outputs:

```
okan@okan-Inspiron-3542:~$ /home/okan/Genel/kiwix/kiwix
XPCOMGlueLoad error for file /home/okan/Genel/kiwix/xulrunner/libxul.so:
/home/okan/Genel/kiwix/xulrunner/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
Couldn't load XPCOM.
```

**Comment by kelson42** [comment]
@okanakinci Yes, there is no solution for that problem, only a workaround `sudo ln -sf /usr/lib/libz.so.1 xulrunner/libz.so.1`. We hope to release kiwix-desktop 2.0 soon.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-xulrunner#511
