### ISSUE TITLE
"+" tab width is too big

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1210]
This seems very new to me and as such a regression
![image](https://github.com/user-attachments/assets/08a7ea0c-7c8e-4c6a-8378-27930883ec5e)

**Comment by kelson42** [comment]
@ShaopengLin Do you have an idea when this regression might have been introduced?

**Comment by ShaopengLin** [comment]
@kelson42 I believe it has been there from the start, it was just not apparent when we didn't add borders to tabs in v2.3 versions. Once veloman responds to the changes in #1198, my fix should carry this issue over.

**Comment by ShaopengLin** [comment]
@kelson42 We should close this as #1198 has merged
