### ISSUE TITLE
Kiwix desktop (Windows 10) never lists anything regardlers of how I filter it

### ISSUE THREAD

**Issue by alienbogart** [kiwix/kiwix-desktop#1211]
I am using the Kiwix desktop on Windows 10. First I tried using the `Version : 2.0.1` which I installed via [scoop](https://scoop.sh/). I thought maybe that version was bugged, so I uninstalled the one from Scoop and installed it with the zip directly from the website. It reports to be `Version: 2.3.1`.  Still, no matter which filters I choose, nothing is displayed for me to download. It doesn't matter the language, Category, Content Type, etc. Nothing shows ever.

![2024-09-14 14_12_27-New Issue · kiwix_kiwix-desktop — Mozilla Firefox](https://github.com/user-attachments/assets/b50a2d8d-b688-455b-aae0-5b964fb6d0d0)

**Comment by kelson42** [comment]
@alienbogart Hi. Thank you for your bug report. We are just a few days away of releasing version 2.4.0 pf Kiwix-Desktop. This new release fixes hundreds of issues. Would you be able please to give a try to (this still in development) version https://download.kiwix.org/nightly/2024-09-14/kiwix-desktop_windows_x64_2024-09-14.zip and let us know if it works better for you?

**Comment by kelson42** [comment]
@alienbogart Any feedback?
