### ISSUE TITLE
Kiwix-Desktop (dev) segfault on Ubuntu if I just close the Windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1214]
Closing the Windows just after starting Kiwix Desktop make the app segfaulting:
```
$ ./kiwix-desktop 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
add widget
Segmentation fault (core dumped)
```

Same bug if I just clikc CTRL+Q

**Comment by veloman-yunkan** [comment]
@kelson42 I am confused. What "Windows" are you talking about?

**Comment by kelson42** [comment]
@veloman-yunkan My bad, I meant "Closing the window", hope this is clearer.

**Comment by kelson42** [comment]
@veloman-yunkan Are you able to reproduce it?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Are you able to reproduce it?

@kelson42 No. I run a Qt5 build of `kiwix-desktop` under Ubuntu 22.04.

**Comment by veloman-yunkan** [comment]
> `qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

and there is no such message when I run `kiwix-desktop`

**Comment by kelson42** [comment]
Now, on the same machine, I can not reproduce the bug. Closing. Sorry for the hassle.
