### ISSUE TITLE
Compiling Kiwix-Desktop with Qt6 is now too complicated

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1216]
I can not compile easily Kiwix with Qt6 anymore, at least with the version 6.4 which is the one shipped with the most recent version of Ubuntu.

A few weeks ago it was compiling fine, so to my perspective this is a regression. It seems it has been introduced with https://github.com/kiwix/kiwix-desktop/pull/1205 but I don't understand right now all the rationals behind this decision.

To me - with my understanding - this change has been made wildly without considering that:
* The compilation script (project) does not check this properly anymore
* We can not distribute Kiwix for Ubuntu anymore using Qt6 (at least for the moment)
* This request the instalation and usage of third party Qt, but the documentation has not been updated properly. 
* For obvious reason, we don't want to release on cutting-edge versions which are not packaged/distributed/made available broadly

If this is not possible to rollback to Qt6.4 (because TTS feature, ....) then please fix the the project and the README.

**Comment by kelson42** [comment]
@sgourdas Any chance you could complete this issue? This is a blocker for https://github.com/kiwix/kiwix-desktop/issues/44

**Comment by sgourdas** [comment]
@kelson42 can you provide the error you are getting?

**Comment by kelson42** [comment]
@sgourdas I have no error, I have just no clue how to get and compile against a Qt which is not the one of the system.

**Comment by sgourdas** [comment]
@kelson42 I am having trouble understanding what changes of #1205 are affecting and how the compilation with Qt 6.4.

**Comment by kelson42** [comment]
@sgourdas is right, the compilation against Qt 6.4 is only a problem in the #1143, not in `main HEAD`.
@ShaopengLin Can you please implement this issue, this is important for testing the PR #1143 but this will be also useful for Linux users having an older version of distribution but still wanting to develop on Kiwix-Desktop with Qt6.

**Comment by ShaopengLin** [comment]
@kelson42 Could you elaborate on

> can not compile easily

I have installed specifically **Qt 6.4.0** on my machine and it compiles fine (with and without the speech module). I do not have the most recent Ubuntu version and I have reasons not to upgrade my laptop due to various compatibility issues.

Without more information I am just shooting in the dark.
