### ISSUE TITLE
Dev appimage version is not able to play well all videos, all the time

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1219]
Steps to reproduce:
* Download recent ZIM with videos https://library.kiwix.org/#lang=eng&q=ted+connect
* Download recent appimage https://download.kiwix.org/nightly/2024-09-29/kiwix-desktop_x86_64_2024-09-29.appimage
* Play the first video top left (just click on play button and nothing else)
* I get systematically this
![image](https://github.com/user-attachments/assets/dfe2358c-b782-4e95-905a-a797b7742ef5)

It should work actually, my dev version compiled locally (with a slightly recenter version of Qt) works!

**Comment by veloman-yunkan** [comment]
I confirm the issue. Old videos play fine. New videos don't. The same problem is present when building and running kiwix-desktop Ubuntu 20.04 focal. So it is an issue with an old version of Qt being used. What should we do about it?

**Comment by kelson42** [comment]
@veloman-yunkan What are the perspectives of building against a more recent version of Qt in appimages.

**Comment by veloman-yunkan** [comment]
> [@veloman-yunkan](https://github.com/veloman-yunkan) What are the perspectives of building against a more recent version of Qt in appimages.

@kelson42 Do you mean still building on Ubuntu 20.04 focal but using a more recent version of Qt? Or building on a more recent distribution of Ubuntu? The later solution is likely to make the appimage unusable on older distributions.

**Comment by kelson42** [comment]
Decision has been made to compile appimage on Ubuntu 22.04.

**Comment by veloman-yunkan** [comment]
Appimage cannot be built on Ubuntu 22.04 using the same process, as `linuxdeployqt` [refuses to work on such a new OS](https://github.com/probonopd/linuxdeployqt/issues/340#issuecomment-1694617215). I will try to find out if the problem can be circumvented by switching from `linuxdeployqt` to [`linuxdeploy`](https://github.com/linuxdeploy/linuxdeploy/) + [`linuxdeploy-plugin-qt`](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/).

**Comment by kelson42** [comment]
@veloman-yunkan Have you considered to you go-appimagetool to fix this? See #1165

**Comment by veloman-yunkan** [comment]
> [@veloman-yunkan](https://github.com/veloman-yunkan) Have you considered to you go-appimagetool to fix this? See [#1165](https://github.com/kiwix/kiwix-desktop/issues/1165)

No I haven't. Replacing `linuxdeployqt` with [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy/) + [linuxdeploy-plugin-qt](https://github.com/linuxdeploy/linuxdeploy-plugin-qt/) has worked and is the solution implemented in kiwix/kiwix-build#771.
