### ISSUE TITLE
Searching with non-latin characters in English sources is not working

### ISSUE THREAD

**Issue by sananjalka** [kiwix/kiwix-desktop#1223]
Hello.

I am on Kiwix 2.3.1. on Linux MInt 21.2

My problem is that in the zim files of English Wikipedia or English Wiktionary searching any word with any non-latin characters returns no results. This applies to searching inside the application and in server mode in browser. 

Searching with non-latin characters works however for example in Finnish or Swedish language zim files.

**Comment by kelson42** [comment]
@sananjalka Can you please share an example, what you get and what you expect?

**Comment by sananjalka** [comment]
After this I noticed that even if I wait for those suggestions to show up, selecting "Düsseldorf (Fulltext search) yields no results. But if I type "London", select "London (Fulltext search) and press enter, I get a list of pages that contain the word "London" (although the list is not very long, so it possibly can't contain _all_ the pages containing that word.

**Comment by sananjalka** [comment]
Testing in Wiktionary-En:

If I enter the search string "head" and immediately press enter, I get a full-text search page of articles which contain the word "head", including the article "head".

If I enter the search string "head" and wait a couple of seconds, I get the following recommendations, and if I press enter after those having shown up, I get directly into the article "Head".
![Image](https://github.com/user-attachments/assets/a7c9fe00-4be8-41bb-9169-10226b8c8ad3)


On the other hand, if I enter the search string "pää" and immediately press enter, I get the following result:
![Image](https://github.com/user-attachments/assets/6286d0e2-0350-40bd-a9b2-9ec1af2a1a90)

If I enter the search string "pää" and wait a couple of seconds, I get the following recommendations:
![Image](https://github.com/user-attachments/assets/7243627e-671d-496b-b4fb-101358ee97e1)
First of all, they display the letter "ä" as some kind of code. But even dismissing that, interestingly enough, the article "pää" (which exists) is not in that recommendation list at all, even though it would be the most accurate and simple result. In the recommendation list are idioms that contain the word "pää", but not the article for the word "pää" itself.

**Comment by kelson42** [comment]
@sananjalka Thank you for all the clarification. We just have released the new version `2.4.1` of Kiwix. I have tested everything again and I can not reproduce this very specific examples you have shared with us. This is not much of a surprise to me as we have made many fixes around this search box. Would you be able to install latest version and test again to confirm us this works for you too?

**Comment by kelson42** [comment]
@sananjalka Closing for the moment, but please let me know if you still have a problem and I will reopen the issue.
