### ISSUE TITLE
Not all math is being rendered in both desktop and js

### ISSUE THREAD

**Issue by Aphexus** [kiwix/kiwix-desktop#1225]
I downloaded the mathoverflow zim and the mathtex is not being rendered in any of it in the browser, js, or desktop versions. The math in wikipedia is being rendered so this seems like some configuration issue? Since it's basically the same data(latext) it should generally work across the board and likely is something not properly being configured in the mathoverflow zim like it is in the wikipedia. It likely shouldn't be that hard to get it to work?

**Comment by kelson42** [comment]
@aphexus Thank you for reporting this bug. This is a problem with the ZIM itself. See https://github.com/kiwix/kiwix-desktop/issues/1225. I will close this issue as the bug is already tracked there.
