### ISSUE TITLE
Unable to start kiwix server Raspberry pi 4 after editing sudo nano /etc/systemd/system/kiwix.service

### ISSUE THREAD

**Issue by Hansolokhalifa** [kiwix/kiwix-desktop#1226]
I edited kiwix service to add more vims but now I cannot sudo systemctl enable kiwix or sudo systemctl start kiwix to launch the server. I have no idea what to do.

**Comment by kelson42** [comment]
Are you using Kiwix Hotspot?

**Comment by Hansolokhalifa** [comment]
Yes I believe I was using the hotspot version. I could never get my vims to launch and have tried another option for now. I tried for two days non stop trying to get it to work. Thank you for responding. Does this run on orangepi? I am not using my raspberry pi for another project now.

**Comment by kelson42** [comment]
@Hansolokhalifa Really difficult to help you as for the moment:
* I have no clue what "vims" are?
* I'm not even sure which software (version?) coming from us you exactly have deployed on your RPI? What have you downloaded exactly?
* What is the problem you have (step by step description), what you get and what you expect.

**Comment by veloman-yunkan** [comment]
> * I have no clue what "vims" are?

I think it is "ZIMs" mistyped (though @Hansolokhalifa used it twice in different messages so the mistake may be more than a typo).

**Comment by kelson42** [comment]
@Hansolokhalifa Any feedback? We need more information or I will have to close the issue.

**Comment by kelson42** [comment]
Clsing for the moment, will be reopne if needed information are delivered.
