### ISSUE TITLE
Not enough storage available issue

### ISSUE THREAD

**Issue by EmmaMcCarthy-401** [kiwix/kiwix-desktop#1227]
I'm trying to download Wikipedia in my E: Drive and it had about 160gb of space left and the whole Wiki files were about 102gb. The download went normally uptill 89gb but later started showing **Not enough storage available problem**. How do I fix this? I have Kiwix version 2.3.1 on my Windows 11 OS.

![Image](https://github.com/user-attachments/assets/585cb0ed-78ad-448c-8d41-d0b4ce8146f7)

**Comment by veloman-yunkan** [comment]
For some reason the information about the progress of your download has been lost (otherwise the last column for the Wikipedia line shouldn't read "Download"). Pressing the "Download" button attempts to initiate a new download an obviously there is not enough room for it.

Can you please check the contents of your **C:\Users\\**_USERNAME_**\AppData\Roaming\kiwix** directory (or **C:\Users\\**_USERNAME_**\kiwix**, if the previous one doesn't exist)? Does it contain a file named __kiwix.session__? Also please look in your download directory on drive E: for a file name ending in ".aria2" (if no such file is there then your best option to complete the mysteriously interrupted download is via a bittorrent downloader).

**Comment by kelson42** [comment]
Considering all the fixes brought o version 2.4.0, I would no recommend to invest too much time on this now.

**Comment by EmmaMcCarthy-401** [comment]
> For some reason the information about the progress of your download has been lost (otherwise the last column for the Wikipedia line shouldn't read "Download"). Pressing the "Download" button attempts to initiate a new download and obviously there is not enough room for it.
> 
> Can you please check the contents of your **C:\Users\**_USERNAME_**\AppData\Roaming\kiwix** directory (or **C:\Users\**_USERNAME_**\kiwix**, if the previous one doesn't exist)? Does it contain a file named **kiwix.session**? Also please look in your download directory on drive E: for a file name ending in ".aria2" (if no such file is there then your best option to complete the mysteriously interrupted download is via a bittorrent downloader).



> For some reason the information about the progress of your download has been lost (otherwise the last column for the Wikipedia line shouldn't read "Download"). Pressing the "Download" button attempts to initiate a new download and obviously there is not enough room for it.
> 
> Can you please check the contents of your **C:\Users\**_USERNAME_**\AppData\Roaming\kiwix** directory (or **C:\Users\**_USERNAME_**\kiwix**, if the previous one doesn't exist)? Does it contain a file named **kiwix.session**? Also please look in your download directory on drive E: for a file name ending in ".aria2" (if no such file is there then your best option to complete the mysteriously interrupted download is via a bittorrent downloader).

How do I continue the interrupted download via Bittorrent?

**Comment by EmmaMcCarthy-401** [comment]
> Considering all the fixes brought o version 2.4.0, I would no recommend to invest too much time on this now.

So do you recommend to download the 2.4.0 version and restart the download?

**Comment by veloman-yunkan** [comment]
> Or how do I start the interrupted download using Bittorrent?

Based on [these instructions](https://superuser.com/a/218396) you should follow these steps:

1. Download the bittorrent file from https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2024-01.zim.torrent
2. Start the bittorrent download using **E:\Wikipedia** as the target directory. Also make sure that the "Skip hash check" or equivalent checkbox in the torrent settings is disabled (or enabled if it rather reads something like "Perform hash check" instead)
3. When the bittorrent download completes, you can additionally verify the integrity of the downloaded file by checking its SHA256 checksum against https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2024-01.zim.sha256

**Comment by veloman-yunkan** [comment]
> > Considering all the fixes brought o version 2.4.0, I would no recommend to invest too much time on this now.
> 
> So do you recommend to download the 2.4.0 version and restart the download? But there isn't any 2.4.0 version?

2.4.0 is in a pre-release stage, but even if was already available I don't think that it would automatically resume the download.

**Comment by EmmaMcCarthy-401** [comment]
> > Or how do I start the interrupted download using Bittorrent?
> 
> Based on [these instructions](https://superuser.com/a/218396) you should follow these steps:
> 
> 1. Download the bittorrent file from https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2024-01.zim.torrent
> 2. Start the bittorrent download using **E:\Wikipedia** as the target directory. Also make sure that the "Skip hash check" or equivalent checkbox in the torrent settings is disabled (or enabled if it rather reads something like "Perform hash check" instead)
> 3. When the bittorrent download completes, you can additionally verify the integrity of the downloaded file by checking its SHA256 checksum against https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2024-01.zim.sha256

This worked! Thank you so much! I can browse whole of Wikipedia offline now!
