### ISSUE TITLE
Error: download failed. Javascript Alert

### ISSUE THREAD

**Issue by SonoftheBaconator** [kiwix/kiwix-desktop#1233]
Windows 7 Pro 64 bit
Kiwix 2.0
When I try to download something I get the "Error: download failed" message.
Above, it says "Javascript Alert - data:text/html;charset=UTF-8,%..." (long string of characters)

I found one thread where it said changing the destination folder and restarting Kiwix would solve it but it didn't work for me. Any suggestions?

**Comment by SonoftheBaconator** [comment]
Correction Kiwix 2.3.1, not 2.0

**Comment by kelson42** [comment]
@SonoftheBaconator I would wait release of 2.4.0 considering we have fixed so many things related to download... and the test again.

**Comment by kelson42** [comment]
@SonoftheBaconator It's unclear when it will be released exactly, but there is almost no tickets left in the milestone. Release ticket is #1000.
