### ISSUE TITLE
Settings tab is not scrollable

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1261]
The content of the Settings tab is not scrollable. When the `kiwix-desktop` window is made smaller than needed to display the Settings tab, opening the latter changes the size of the application window.

Because of #1260 under Windows not all of the settings fit on my 14 inch laptop screen and there is no way to access those on the bottom.

**Comment by heropj** [comment]
Hlo @veloman-yunkan could you please assign this issue to me? I would like to work on it.
Thank you!
