### ISSUE TITLE
windows web interface library card language icon overflow

### ISSUE THREAD

**Issue by silencelen** [kiwix/kiwix-desktop#1263]
the language icons at the bottom left of the library cards overflow

This is using the stock windows desktop gui version
![Image](https://github.com/user-attachments/assets/5d9359a3-1586-46b2-932d-a0b435ab0a5a)
![Image](https://github.com/user-attachments/assets/5cd261d1-0a69-49c4-80cf-1ee196af6297)

**Comment by kelson42** [comment]
@silencelen Thank you for the bug report. This bug has been fied already and will vanish in release 2.4.0 to come soon. See https://github.com/kiwix/libkiwix/issues/908
