### ISSUE TITLE
Marc, I need help again

### ISSUE THREAD

**Issue by K7WLD** [kiwix/kiwix-desktop#1268]
For Marc (or whoever...) - You helped me recently on how to download the ZIM files during the recent server collapse.  Now I have about ten ZIM files downloaded, but when I try to open them up, either I am asked if they are a trusted source, at which point the app seems to just freeze up - (nothing happens after that,) or, in the second instance, I get past the security window, the file title appears in the body of the window, and a message appears, telling me that the file is loading, but it just loads FOREVER, as long as it took to download Wikipedia when I started trying to work with Kiwix.  Again, can you please help me with this nagging problem?

Terry Hamilton
hamilter@nwi.net

**Comment by Popolechien** [comment]
User also reached out via email, we'll take it there.
