### ISSUE TITLE
Launch Flatpack kiwix-desktop from the command line

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#127]
After installing the Kiwix dekstop flatpak package (through Flathub), it should be possible to launch the application using a terminal:
```
$ kiwix-desktop
```

**Comment by birros** [comment]
Flatpak doesn't expose any cli command from an app, for collision reasons, but there are **two manual methods to bypass this missing** :

1) Create an alias to `kiwix-desktop` and save it in user's shell conf : `alias kiwix-desktop='flatpak run org.kiwix.desktop'`
2) Or add `/var/lib/flatpak/exports/bin` and `$HOME/.local/share/flatpak/exports/bin` to user's `PATH` env variable, then you can use `org.kiwix.desktop` as cli command

**Comment by kelson42** [comment]
@birros Hmmm, sad. None of this is really user friendly. We hardly can expect that the lambda user do that.

**Comment by mgautierfr** [comment]
To run a application installed through flatpak (ie org.kiwix.desktop) you must run `flatpak run org.kiwix.desktop`

> @birros Hmmm, sad. None of this is really user friendly. We hardly can expect that the lambda user do that.

Lambda user will launch kiwix desktop using its desktop environment. And as flatpak package export a `.desktop` file, kiwix-desktop is present is the menu/launcher/... of the desktop environment.

**Comment by kelson42** [comment]
@birros @mgautierfr Thank you for your educated feedbacks. Looks like this is not something doable properly for now... and indeed this is not a big problem.
