### ISSUE TITLE
Borders of "white" dialog windows have been removed (at least on Windows)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1272]
So we have a window white on white
![Image](https://github.com/user-attachments/assets/6a076a59-917e-4d81-83fd-4e176083a542)

**Comment by veloman-yunkan** [comment]
2.3.1 release of `kiwix-desktop` has the same issue (under Windows). Under Linux the dialog looks nicer because when the dialog opens the main window is slightly dimmed.

**Comment by veloman-yunkan** [comment]
This seems to be specific only to the "Local Kiwix Server" dialog. Other dialogs have borders.
