### ISSUE TITLE
In a Windows build, layout of the GUI is unaffected by usage of RTL UI language

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1277]
I am a little unsure if this is indeed a bug, since I only tested by starting `kiwix-desktop` from Git bash shell by setting `LANG` to arabic:

```bash
LANG=ar ./kiwix-desktop.exe
```

Under Linux this results in the GUI layout being changed to RTL:

![Image](https://github.com/user-attachments/assets/e5801c05-558c-4e57-ae00-5cb0b71db163)

Under Windows, the layout is unaffected (only the UI language is changed):

![Image](https://github.com/user-attachments/assets/16ff4ab3-288b-44f2-bbba-435fbc3416bd)

But maybe that's not the correct way of specifying the locale under Windows.

**Comment by kelson42** [comment]
99% sure this is not the way to change the system locale in Windows.

**Comment by kelson42** [comment]
I will close this, pretty sure it works fine if the locale is changed properly. This is anyway a Qt builtin.
