### ISSUE TITLE
Fix window title (replace "MainWindow")

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#129]
Kiwix Desktop Windows title is always "MainWindows - Kiwix".

It should be:
* "HTML article title - Kiwix" in case a content tab is open
* "Library - Kiwix" in case the library is open (please think that "Library" should be localised like any other part of the UI).

**Comment by jetownfeve21** [comment]
For the Library case, is it necessary to differentiate the remote library of the local one ?

**Comment by kelson42** [comment]
@jetownfeve21 this is not necessary
