### ISSUE TITLE
[suggestion] [feature] if we paste a wiki url in the search box it should open the page

### ISSUE THREAD

**Issue by y1111** [kiwix/kiwix-desktop#1297]
now. it gives and error : No results were found for "[url]" . this should work like if i paste a link it opens
and also in the android app we could even set the app to open Wikipedia links.

and it could have a setting to: search in online Wikipedia when it doesnt found something in the offline database .  and it could auto add to a db, like having a "cached" db in zim , so every time u take smt online it auto save in this db .
 and also this could be a browser extension too. for anytime u open a wiki page it saves in this db and then became available in the oflline program.

**Comment by kelson42** [comment]
@y1111 I'm not in favour of this feature request, the searchbar is not an URL bar. If you really want to have an URL bar, I recommend to use Kiwix Server.
