### ISSUE TITLE
remote library isn't refreshed after starting many downloads

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#134]
After starting a download with "stack" set with the search bar, there in no books displayed anymore.
But it doesn't appened always, maybe it depends on the number of books to display, or number of simultaneous download.

![image](https://user-images.githubusercontent.com/47149116/56416261-9ec47a80-6290-11e9-8c1b-765c9798af0c.png)

**Comment by kelson42** [comment]
@jetownfeve21 I don't understand this bug report, in particular: 

> "stack" set with the search bar

,

**Comment by jetownfeve21** [comment]
filtering search result with the search bar doesn't always work after starting  downloads.
To reproduce this bug : 
-select "all files" in the sidemenu
-filter results with the searchbar (when the bug appened it was with the "stack" research)
-download many books
Sometimes the page's refresh doesn't seem to work and then no books are displayed.

**Comment by kelson42** [comment]
@jetownfeve21 thx for the explanation. Sounds quite important to fix IMO.

**Comment by jetownfeve21** [comment]
This happened when many downloads are launched simultaneously
