### ISSUE TITLE
Sort by name, date, content type, size

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#139]
Add the possibility to sort books by clicking on the column's header.

![image](https://user-images.githubusercontent.com/47149116/57219401-457e7a00-6ff8-11e9-8f90-6f0a841a44e9.png)

**Comment by kelson42** [comment]
@jetownfeve21 For the online catalogue, this should probably be done server-side.

**Comment by jetownfeve21** [comment]
@kelson42 If we implement the sort on the local books, kiwix-desktop can manage the sort of the remote books too ?
