### ISSUE TITLE
Implement ALT+Home keyboard shortcut to open the welcome page of a ZIM

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#141]
Pressin ALT+Home should:
* open the welcome page of the ZIM file in the current content tab (if there is a tab with content open)
* do nothing otherwise

See also #58

**Comment by mgautierfr** [comment]
I'm a bit confuse with this.
As said by @schoenbaechler in #58, there is no home button and it is intended. The main reason for this is that we don't really need it (home page is just a default page and doesn't really provide a home functionality (and what would it be ?))

If we add shortcut to go to the home page,  we will have an action only usable through a shortcut. And this shortcut will never be displayed anywhere. I'm pretty sure that no one will use it in this condition.

---
I don't say we don't need a home button (it have to be discuss on the design point of view). But if we add a "go home" action, we must not just add a shortcut.

**Comment by schoenbaechler** [comment]
Hey @mgautierfr

[As per concept](https://github.com/kiwix/kiwix-desktop/wiki/kiwix-desktop-2-concept), there is a way to access the welcome page of a file:

> [A click on „Open“ leads users to the home page of the corresponding book](https://wikimedia.invisionapp.com/share/7UIVNGPS9CA#/screens/300338424) in a new tab next to „Kiwix library“. It also adds a book specific search filter in the app’s address bar.

If there’s really a need to access the welcome page, we could think about providing a setting that a new tab opens the welcome page of the ZIM file that is currently used/active. If there’s no active ZIM file, it would open a blank tab.

![303981034](https://user-images.githubusercontent.com/5031003/58549064-fa2c4580-820a-11e9-9fc3-596c6b1183aa.png)

I’d argue that the “real“ home of the Kiwix app is the library (“Ctrl + E”), so if the keyboard shortcut “Alt + Home” is an established shortcut and broadly used by people, I suggest to map it to the Kiwix library tab.

Hope that makes sense?

Also saying hi to @kelson42 👋
