### ISSUE TITLE
Two Kiwix-Desktop instances can be run in parallel

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#147]
I don't think this is really something we want... or we should guaranty that everything will works fine. Is that the case? A Singleton Windows seems more appropriate.

**Comment by yashasvi-goel** [comment]
Can I work on this issue?

**Comment by kelson42** [comment]
@yashasvi-goel I would recommend to present your approach to solve the problem first as a comment.

**Comment by yashasvi-goel** [comment]
I plan on using a  mutex-based approach. The mutex variable will store the PID of the instance. Every time the instance is launched, it will check the variable and hence the program state.

**Comment by mgautierfr** [comment]
That's the main idea. However a full solution should be a bit more complex.

At startup of the application, we should check if there is already a running application. If there is one, the second application should not just quit (or refuse to launch). It should communicate with the first application to "forward the argument" (ie, if we try to open a zim by clicking on it on the file browser/or after a download from a we browser, the second application should forward the "open zim file" command to the first one. This way the zim file is opened in the first application).

GApplication has this feature but we use Qt and the QApplication has not. https://forum.qt.io/topic/59223/qt-single-instance-application/5 speak about this. There is a base application (https://code.qt.io/cgit/qt-solutions/qt-solutions.git/tree/qtsingleapplication/) that could be used by
kiwix-desktop.
