### ISSUE TITLE
Kiwix server option

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#152]
I'm looking how to use the kiwix server option with the new kiwix release.

**Comment by kelson42** [comment]
@LAfricain There is not one but we are currently building it https://github.com/kiwix/kiwix-desktop/issues/85. This should be done in the next 2 weeks.

**Comment by LAfricain** [comment]
Ok well I will wait for it.

**Comment by Popolechien** [comment]
@LAfricain Hello, can you reach out at contact@kiwix.org? We're trying to figure out where deployments take place, what the use cases are and how to bring better content, and I'd be happy to have a quick chat with you.
