### ISSUE TITLE
kiwix-desktop sometimes crashes when opening a zim file from file explorer

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#160]

**Comment by LAfricain** [comment]
I experienced the same problem. With the same zim (wp in eng) on a exfat key, copied on the hard disk of the computer impossible to read, both on key and on computer, kiwix crashed. But the same zim on an ext4 hard disk is red good (I'm not sure it is linked to the file system, I'm just describing the situation)

**Comment by kelson42** [comment]
@jetownfeve21 Have you been able to understand what goes wrong here?

**Comment by LAfricain** [comment]
On Fat32, with a split wiki file, it crash again. I don't know if it is the key.

**Comment by jetownfeve21** [comment]
@mgautierfr 
I think this is due to line 52 (urlschemehandler.cpp) but I don't really understand why
![image](https://user-images.githubusercontent.com/47149116/58865408-ccd21280-86b6-11e9-826c-3fef8f73dec7.png)
