### ISSUE TITLE
Another crash scenario with Kiwix Desktop

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#165]
1 - download http://tmp.kiwix.org/wikipedia_en_articlelist_2019-05-libzim5.zim
2 - open it
3 - type just "d" in the search bar
4 - Application crash

Testing on Linux with 2.0 beta4

**Comment by jetownfeve21** [comment]
It's the same crash that #160. I think that it can happen for every opening zim operation, I have this crash often with a page saved in the reading list

**Comment by kelson42** [comment]
@jetownfeve21 This is not a crash by opening... this is a crash by searching (suggestions).

**Comment by jetownfeve21** [comment]
I was wrong it's not linked to the crash related in #160 but to the getDirent() method of the libzim
![image](https://user-images.githubusercontent.com/47149116/58712733-749ec600-83c1-11e9-9426-c59bb647f756.png)
