### ISSUE TITLE
Kiwix Reader 2.0 Search Bar is very slow

### ISSUE THREAD

**Issue by HDMP** [kiwix/kiwix-desktop#167]
I have a few problems with the new Kiwix Reader and the .zim Files.

When I open an .zim File and try to search for an Article it takes up to more than 4 Seconds until the Text is shown in the Search Bar. Besides that, there is also the problem, that not all Pictures in the Articles are loaded correctly (see attached images).

It's very important to for our Users that the typing in the search bar is fast and that all Pictures on all Articles are shown, because they are used to the old reader where everything worked perfectly..

I thought kiwix is slow, because of the big "novid" files. But I also tested it with "nopic" and it was also pretty slow (maybe 0.5-1 second faster)

I checked all the MD5Sums and they should be correct

I tested this with the following .zim Files:

- wikipedia_de_all_nopic_2018-11.zim
0A3339573698B2D3D9885FDCF1A6A20A

- wikipedia_de_all_novid_2018-11.zim
d52265311ea1b70c0430964fa8a51845

- wikipedia_fr_all_novid_2018-10.zim
4B5A91DD1F0B2266E1717BA87A8D8B63

and the following OS:

- Windows Server 2012 R2
- Windows 10

Kiwix Reader Version:

- 2.0-beta4-11-ga005a5c

I also tested the "wikipedia_de_all_novid_2018-06.zim" File. All pictures there are shown perfectly, but the search bar is still pretty slow.
I think the problem with the pictures comes from the .zim files. If it would get updated correctly it'll probably would work perfectly.
But the problem with the Search Bar comes from the new Reader. Is there any way how i could get it to work faster?

![kiwix_article_without_pic](https://user-images.githubusercontent.com/30300775/58942631-687a8600-877e-11e9-999a-9b058acb2c5b.png)
![kiwix_article_with_pic](https://user-images.githubusercontent.com/30300775/58942633-69131c80-877e-11e9-879d-c020ea76031d.png)

**Comment by garuffalo** [comment]
Same issue with the images here on Linux Mint 19.1. Can't view anything with kiwix-desktop (see #117) but saw this while viewing an article on wikipedia_en_all_novid_2018-10.zim using kiwix-js 2.5.0. So I also believe it must be the .zim file. Only noticed it on one article (subject: Bob Dylan).

**Comment by HDMP** [comment]
With "wikipedia_de_all_maxi_novid_2019-08.zim" all Images work perfectly (sadly there isn't a new .zim File for the french Wikipedia).

The problem with the Search Bar still remains. I hope this get fixed soon with a new Version of the Kiwix-Reader.

**Comment by kelson42** [comment]
The problem with the images is not related to Kiwix-desktop, the ZIM file has just missing images. But there is a speed problem with the suggestion system.

**Comment by kelson42** [comment]
The speed problem should have been fixed. To be tested with Kiwix-Desktop 2.0 rc2.

**Comment by LAfricain** [comment]
I have still this problem on Ubuntu with the last appimage.

**Comment by kelson42** [comment]
@LAfricain Yes, this still problem, see #274. This is meanwhile a TOP prio problem (pinned issue).

**Comment by kelson42** [comment]
@LAfricain 2.0 has a specific bug which even make things worth! 2.0.1 to be release with a fix in one or two days.

**Comment by LAfricain** [comment]
Ok thank you.

**Comment by LAfricain** [comment]
In the new release it's better, but when we type in the search bar it's still slow. Maybe it can be better to type and have a open page with all the possibilities, as a search engine does in a webbrowser?

**Comment by kelson42** [comment]
@LAfricain Please try to comment on open tickets, here #274. Currently the most interesting running is on #265. One time that fixed, it will worked a lot better (still maybe not perfectly).
