### ISSUE TITLE
VCRUNTIME 140 error message with Kiwix-desktop on my Sony VAIO Windows 7 

### ISSUE THREAD

**Issue by JamescJIII** [kiwix/kiwix-desktop#168]
I downloaded the Kiwix install, unzipped it to my USB drive, then inserted it on my Windows 7 desktop and ran the Kiwix-desktop.exe app. The archives came up and worked perfectly, just as I expected.  I then tried using the same USB drive on my Sony VAIO Windows 7 notebook and got a VCRUNTIME 140 error message.  I looked up the error message and found the C++ runtime was missing so I ran vc_redistx6.exe on the Kiwix distribution. Kiwix now loads but only display the menus and none of the archives will load.   It looks as if ‘Kiwix-Desktop.exe only runs correctly on my desktop. 
Should I wait until Kiwix 2.0 for Windows is ready in June, of if there are other measures, I should be taking let me know what they are.

**Comment by kelson42** [comment]
@JamescJIII Thank you for your feedback. Which version of Kiwix Desktop are you running exactly? You also say "Kiwix now loads but only display the menus", what does that mean exactly? You says also "none of the archives will load", does that mean you are able to go to the library and load a file manually? If "yes" what happen then?

**Comment by JamescJIII** [comment]
Thanks for responding. I downloaded and installed this version: kiwix-desktop_windows_x64_2.0-beta4.zip<https://ftp.nluug.nl/pub/kiwix/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-beta4.zip>
https://ftp.nluug.nl/pub/kiwix/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-beta4.zip

The top-level text menus display and will expand when clicked to show second level menus, however clicking on the second level menu did nothing. This usually brings up an archive which I could open and read. Nothing opens on any of the second level menus. I did not try going to the library directly to load a file.
But rather than spending a lot of time trying to debug this version, please let me know when the new version of Kiwix is available for download later this month. I will unzip it to a USB drive and try again.
Thanks
James

**Comment by JamescJIII** [comment]
Thanks so much for your response. Out of town now but will return on Sunday and upload everything.
James

Sent from my handheld

On Sep 13, 2019, at 1:40 AM, Kelson <notifications@github.com<mailto:notifications@github.com>> wrote:


@JamescJII
Are you sure you use the beta rc2?
cayou please upload your library.xml file here?
What is the exact kiwix-manage command you have run?

**Comment by JamescJIII** [comment]
[Readme.docx](https://github.com/kiwix/kiwix-desktop/files/3614256/Readme.docx)



[XML_Files_kiwix-desktop_windows_x64_2.0-rc2.zip](https://github.com/kiwix/kiwix-desktop/files/3614259/XML_Files_kiwix-desktop_windows_x64_2.0-rc2.zip)
I hope you will be able to use what I have included as the directories are too big to upload. Let me know what else is needed.

**Comment by mgautierfr** [comment]
The paths set in the `library.xml` seem wrong
(`..\..\..\..\..\..\M:\Kiwix-content\wikipedia_en_chemistry_novid_2019-05.zim`, `..\..\Downloads\wikipedia_en_computer_2017-04.zim`). From your directory structure, they should be something like `..\Kiwix-content\wikipedia_en_chemistry_novid_2019-05.zim` (The path is relative to the `library.xml` file.)

> The Library.XML file was stored on my C:\ drive under user\appdata\roaming and I copied it to the USB drive in the directory containing Kiwix-desktop [From your docx]

If you copy only the `library.xml` (or change the relative path between the `library.xml` and the zim files), it will not work anymore.

**Comment by InettaFund** [comment]
I think that I will need to employ a consultant to help me get this working. If interested please contact me directly via email.

**Comment by kelson42** [comment]
@InettaFund Please send and email to contact at kiwix.org explaining briefly your need and the service expectation and we will make you an offer.

**Comment by InettaFund** [comment]
After lots of trial and error, I finally got the library.xml file built and the content to display properly when Kiwix load.
Thanks
