### ISSUE TITLE
Change profile/download path in Settings

### ISSUE THREAD

**Issue by gmikhail** [kiwix/kiwix-desktop#170]
Now the program downloads the file on the system disk, regardless of its location. What in some cases may cause the disk to become full, which causes, complete freeze of kiwix-desktop and OS.

The following fixes are required (by priority):
- By default, the download should be in the current working folder (now everything is download into the system disk)
- Pre-calculate free space and warn about its shortage before download
- Ability to change the download path

kiwix-desktop_windows_x64_2.0-beta4 (2.0-beta4-11-ga005a5c)
Win 10, 128GB SSD

**Comment by kelson42** [comment]
@gmikhail Thank you for your feedback. The plan is to offer a way to change the profile location (something similar to the old kiwix-xulrunner). And yes, the software shoudl check if there is enough disk place, I have created a ticket for that here #171

**Comment by kelson42** [comment]
@jetownfeve21 Is that ticket fixed?

**Comment by jetownfeve21** [comment]
No there is still the profile directory that can not be changed for now

**Comment by kelson42** [comment]
@jetownfeve21 I want to but this ticket on stall for the moment as i believe:
* Moving the profile is touchy
* Most of the added value is already achieved with the download location feature

**Comment by autolyk** [comment]
It seems Kiwix checks space only on system drive. I have enough space on the disk download directory's disk, but no enough on system disk. And I got "not enough storage available" error message.
(Windows 7, Kiwix Desktop x64 2.0.1-1)

**Comment by Fubar1** [comment]
I am getting an error "not enough storage space" for an 89GB file even though the download directory has 2TB of space, C Drive has over 500GB, program drive has 1TB.

**Comment by kelson42** [comment]
@Fubar1 Your comment has nothing to do with this ticket. But you report a real bug which has been meanwhile fixed, see #868.

**Comment by kelson42** [comment]
Closing as the feature has been implemented

**Comment by michaeljakob** [comment]
There is still no way to set download folder.

**Comment by kelson42** [comment]
@michaeljakob which version do you use!

**Comment by 0o0will0o0** [comment]
> [@michaeljakob](https://github.com/michaeljakob) which version do you use!

Well, the current version on Windows only downloads on the main drive with no way to change the destination. Crazy it's been 5 years with no fix.

**Comment by kelson42** [comment]
@0o0will0o0 Crazy you are not able to run/use  latest version 2.4.0!

Your comment is not helpful and pretty respectless.

**Comment by 0o0will0o0** [comment]
> [@0o0will0o0](https://github.com/0o0will0o0) Crazy you are not able to run/use latest version 2.4!
> 
> Your comment is not helpful and pretty respectless.

Crazy how I'm using 2.4.1 and it still doesn't let you change the directory. Maybe you should be helpful.

**Comment by kelson42** [comment]
> > [@0o0will0o0](https://github.com/0o0will0o0) Crazy you are not able to run/use latest version 2.4!
> > 
> > Your comment is not helpful and pretty respectless.
> 
> Crazy how I'm using 2.4.1 and it still doesn't let you change the directory. Maybe you should be helpful.

Please share a screenshot of the settings.

**Comment by 0o0will0o0** [comment]
![Image](https://github.com/user-attachments/assets/315003ff-35ac-47f3-a861-0871081d6a4a) I'm sorry for being an AH. I'm just stressed out rn. Thank you seriously for any input you give.

**Comment by kelson42** [comment]
@0o0will0o0 You install Kiwix for someone who needs it and we are even ;)

**Comment by 0o0will0o0** [comment]
> [@0o0will0o0](https://github.com/0o0will0o0) You install Kiwix for someone who needs it and we are even ;)

I will do that; I already know someone who said today that they missed using encyclopedia programs back in their school days, and I got just the app for their phone.
