### ISSUE TITLE
Better display of the tags 

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#172]
For now all tags are separated by a ";", and some are not very user meaningfull (gbf, nopic).

![image](https://user-images.githubusercontent.com/47149116/59091572-eb7f1600-890f-11e9-93f9-5074f01b284b.png)

**Comment by kelson42** [comment]
@jetownfeve21 They should not be displayed like this.

**Comment by mgautierfr** [comment]
Replacing the `;` by a space is nice but we should fix https://github.com/kiwix/kiwix-lib/issues/131 at a moment to be able to correctly display the content type.
(Remove the category, interpret _ftindex, nopic, novid and display a better name, ...)
