### ISSUE TITLE
Bad "fullscreen" position icon in contextual menu

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#176]
The icon is behind the text, see screenshot:
![scr](https://user-images.githubusercontent.com/1029718/59593014-753d9900-90f1-11e9-81dc-7ae9a37d876e.png)

Tested on GNU/Linux with beta5

**Comment by kelson42** [comment]
The "Quit fullscreen" contextual menu entry suffers of the bug too.

**Comment by kelson42** [comment]
The is a bug in QT, see https://bugreports.qt.io/browse/QTBUG-74655). This will should be fixed in Qt 5.12.5 to be release end of 08/2019.

**Comment by kelson42** [comment]
Monitor new versions here https://download.qt.io/official_releases/qt/5.12/

**Comment by kelson42** [comment]
5.12.5 still not released unfortunately

**Comment by kelson42** [comment]
@mgautierfr You pointed first to this ticket on Qt side... but I just remarked that in kiwix-build we use QT 5.10 (and not 5.12)... so we should not be impacted by it at all!

**Comment by jetownfeve21** [comment]
@kelson42 
It has been fixed with the 5.13.1 
![Peek 2019-09-06 12-20](https://user-images.githubusercontent.com/47149116/64421045-f2e5c500-d0a0-11e9-8e76-c94ae9ca1c84.gif)

**Comment by kelson42** [comment]
Fixed in Windows and Flatpak, we might have still a problem with the appimage version

**Comment by kelson42** [comment]
@mgautierfr What should we do with that ticket? It has been fixed in most case. Any quick way to fix it for appimage as well?

**Comment by kelson42** [comment]
I close this ticket, there is nothing more we can do here, we need to move to a recent version of Qt.
