### ISSUE TITLE
German Wikipedia missing

### ISSUE THREAD

**Issue by probonopd** [kiwix/kiwix-desktop#18]
German Wikipedia appears to be missing, at least it cannot be found by searching "wiki" and choosing "Deutsch" from the language menu.

![german](https://user-images.githubusercontent.com/2480569/43008379-6e4990a8-8c2a-11e8-83be-5382145f8448.png)

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-xulrunner#512
