### ISSUE TITLE
Remember open tabs over restart

### ISSUE THREAD

**Issue by BigKananga** [kiwix/kiwix-desktop#186]
A small suggestion for a feature: how about opening the last opened zim file automatically? I think this would help many people that are using only one zim file.

**Comment by kelson42** [comment]
Here in fact, the experience has shown that what people might want is just keep track of the last open tracks. That means:
* Same ZIM files
* Same articles
* Same vertical/horizontal position in articles

**Comment by BigKananga** [comment]
@kelson42 
Yes, but without the last article or at least optional. I think the main page should be started by default.
An option for opening the last session like in browsers would be also nice.

**Comment by mgautierfr** [comment]
Yes we should have some kind of session management (and config also)

**Comment by bissjoe** [comment]
It would be notably useful when the ZIM files are not located in C:\Users, since in that case those files do not appear in the Library (maybe this is another issue: https://github.com/kiwix/kiwix-desktop/issues/93).
I for one don't like to keep my documents in C:\users, but instead on my D drive.

**Comment by Popolechien** [comment]
Pushing (or un-staling) it as another major partner also requested the feature.

**Comment by ynikitenko** [comment]
I also wanted to support this feature. In fact, I don't need my last tabs, but it would be great if I didn't have to select the ZIM file every time I start the program! In Kiwix 0.9 I could use my previous ZIM file. Thank you. I'm mostly using Kiwix for the Wiktionary.

**Comment by ShaopengLin** [comment]
Would love to work on this. I am thinking of using QSettings to retrieve web view URLs from tabbar class. Restoring them later within Mainwindow as an initial support. Later on, this could be extended to use QSessionManager in case multiple instances might be running on the same filesys.
