### ISSUE TITLE
Enhancement: add an icon to Windows executable

### ISSUE THREAD

**Issue by BigKananga** [kiwix/kiwix-desktop#187]
Another small suggestion for a feature: add an icon to Windows executable. If zim files are linked with Kiwix this icon would be also applied for zim files. Same for desktop shortcuts.

**Comment by kelson42** [comment]
@jetownfeve21 Maybe you can help to fix that one quickly? Old EXE icon are here https://github.com/kiwix/kiwix-xulrunner/tree/master/desktop.. but maybe you can achieve to make one in better resolution from data in https://commons.wikimedia.org/wiki/Category:Logos_of_Kiwix or https://wiki.kiwix.org/wiki/Category:Visuals

**Comment by mgautierfr** [comment]
Following the documentation here (https://doc.qt.io/qt-5/appicon.html) would do the job.
