### ISSUE TITLE
Typos in Readme file

### ISSUE THREAD

**Issue by xurror** [kiwix/kiwix-desktop#189]
The readme file contains some grammatical typos
in the line  

"You may want to simply open the kiwix-desktop project in QtCreator and compile the project from here (We will may have to also update PKG_CONFIG_PATH)."

**Comment by kelson42** [comment]
@xurror Can you please make a PR?

**Comment by xurror** [comment]
@kelson42 From what I see it's resolved in https://github.com/kiwix/kiwix-desktop/pull/190 
I guess I don't need to make a PR anymore.

**Comment by kelson42** [comment]
@xurror yes, thx for reporting
