### ISSUE TITLE
Rework how we handle categories.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#193]
I dislike how we handle the categories.
There is no real separation between what is displayed and what is done.
So we end with silly and special case hacks to handle "all", "other", "stack exchange".
And we can be pretty sure that other special case will appear (without speaking of translation problem)

We should think how we handle this and make a better system.

**Comment by kelson42** [comment]
@mgautierfr You have proposed a dynamic system (not sure if we have a system here) and I think we could think about that... but what I don't understand is why we don't have now - in the current system - a simple mapping table with tag <-> label key? That seems simple and that is what is done in Kiwix iOS.

**Comment by mgautierfr** [comment]
>  but what I don't understand is why we don't have now - in the current system - a simple mapping table with tag <-> label key

Because we have to implement it. And maybe because we never finish this discussion https://github.com/kiwix/kiwix-desktop/issues/118
And we decided to go "the simpler (short therm) way"

**Comment by rgaudin** [comment]
Please follow-up on [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317)
