### ISSUE TITLE
Kiwix Desktop for Windows x64 2.0 beta 5 extremely slow, freezes

### ISSUE THREAD

**Issue by Victor-Craeton** [kiwix/kiwix-desktop#194]
Trying to load and navigate "wikipedia_en_all_novid_2018-10.zim", file is 78.0GB.

File loads correctly, and at first appears to be just fine, and is mostly responsive when clicking hyperlinks on pages that are already displayed, though some sluggishness is evident.  When trying to search for an article in the search box up top, there is an extremely delayed response.  A couple characters initially show up, but the rest appears roughly 10-20 seconds after you stop typing.  Articles do return/appear as search results under the search bar, but when clicked, or when Enter is pressed, it displays the intended name of the article in the search box/bar, but no content is ever actually displayed.

Kiwix Desktop appears to launch multiple processes of "Qt Qtwebengineprocess".  Sometimes they sit at 0% CPU usage, other times, I've had as many as five show up in the Task Manager, with CPU usage at 100%.  Even when Qt Qtwebengineprocess is at 0% CPU usage, aria2c.exe is using anywhere from 7%-14.5% CPU, doing nothing at all, with no requests made to the program in over five minutes.

Occasionally, when searching for an article, or closing out of an article tab, Monitor 1 blackscreens, Monitor 2's windows show a loss of the Windows 10 theme, and the titlebar appears with a Windows 7 style, then after about 15 seconds, Monitor 1 comes back online, with both monitors now displaying windows themes properly again, and the Kiwix Desktop app having closed with no error message.

**Comment by kelson42** [comment]
@Victor-Craeton Thank you for your bug report. To me the most obvious problem is that the suggestion system in the search bar is indeed really slow. In particular with big ZIM files. This has for example already been report here #167. This is a priority to fix.

**Comment by I338** [comment]
I think the main issue isn't that it is slow, but that the fact that the search holds up the appearance of typed characters. Because of this behaviour, it's hard to tell if there are typos in the search terms, because it's held up by actual search.

**Comment by kelson42** [comment]
Problems should have been fixed now. Will be available in 2.0 rc2.
