### ISSUE TITLE
Add/Change UI to have a more conventional menu bar for file/edit/view/help options, o

### ISSUE THREAD

**Issue by Victor-Craeton** [kiwix/kiwix-desktop#197]
Per #195, which has been closed, I never realized after using the app for about an hour that the three dots on the right were a file/edit/view menu button.  I'm not new with computers or software by any means, but the current UI setup was not intuitive to me.

I suggest either an addition or change to the UI to have a more conventional menu bar for file/edit/view/help options, or a bar of icons for all of the features in the current "..." icon.

<s>New Tab can be made into a tab with a +, mimicking popular web browsers.  The close tab feature with the X on the tabs was highly intuitive and useful.</s> See #36

**Comment by mgautierfr** [comment]
We have a design defined by @schoenbaechler here https://github.com/kiwix/kiwix-desktop/wiki/kiwix-desktop-2-concept

My personal POV is that I'm not a designer and so I have no POV :)
I follow the design because I assume that a designer will do better choice than me (a developer)

**Comment by xurror** [comment]
I think its a good idea to have menu bar like most other desktop apps

**Comment by kelson42** [comment]
I'm meanwhile convinced that we have a UX problem here. I propose to just an icon on the toolbar directly to open a local file. I propose this logo:
![image](https://user-images.githubusercontent.com/1029718/74427267-0d457b00-4e57-11ea-8f67-a987de9fb319.png)
