### ISSUE TITLE
kiwix-desktop_windows_x64_2.0-beta5 seems to not start if non-ascii character in the path

### ISSUE THREAD

**Issue by bissjoe** [kiwix/kiwix-desktop#203]
This question is nontechnical, but I was told on kiwix.org that I needed to go to github if I had an issue with the software. So here I am.

1.  I downloaded kiwix-desktop_windows_x64_2.0-beta5 on 2019-07-05.
2.  I unzipped it.
3.  I double-clicked vc_resistx64.exe. Installation for C++ redistribuables proceeded.
4.  I rebooted my computer.
5.  I double-clicked kiwix-desktop.exe.

Nothing happened, except a background process named "kiwix-desktop.exe" that I can see in the Task Manager. But after a while it disappears.

What did I do wrong?
Or is it that kiwix-desktop does not work properly on Windows 10 64-bit home editition?

**Comment by kelson42** [comment]
@bissjoe It should!

**Comment by bissjoe** [comment]
@kelson42 I started it manually from the command line.
Again the same background process appeared in the Task Manager, but no window.

Maybe I should provide de the following information:

- Windows 10 version 1809 (17763.557)
- Language: French.
- Operating system and kiwix installed on a SSD.

**Comment by kelson42** [comment]
@bissjoe This is a bug definitly. If you have Kiwix on the main disk, does it work better?

**Comment by bissjoe** [comment]
My C drive is my SSD. I copied the kiwix folder to my D drive, which is a hard disk. Now it works!

**Comment by kelson42** [comment]
@bissjoe Interesting. So, depending where you put your Kiwix directory, it works or does not work. Could you give us please:
* The exact paths on which you have tried to put the Kiwix directory
* The filesystem of each disk

**Comment by bissjoe** [comment]
C drive:
- Type of disk: SSD
- Filesystem: NTFS
- Path of kiwix: C:\Installateurs\Kiwix 2.0 bêta\kiwix-desktop_windows_x64_2.0-beta5\

D drive:
- Type of disk: HDD
- Filesystem: NTFS
- Path of kiwix: D:\kiwix-desktop_windows_x64_2.0-beta5\

Please note that I kept for now the installation of kiwix 0.9, which is located in C:\wikipedia\. But this does not seem to interfere with kiwix installed on my D drive.

**Comment by bissjoe** [comment]
I just moved kiwix from
C:\Installateurs\Kiwix 2.0 bêta\kiwix-desktop_windows_x64_2.0-beta5\
to
C:\Progs\kiwix\

and now it works! Is it possible that the "ê» in the old path was not recognized?

**Comment by kelson42** [comment]
@bissjoe That is my strong suspicion! Thank you very much for this analysis, we will try to reproduce the problem based on this.
