### ISSUE TITLE
Create deb package for 32 and 64 bits

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#204]
I build this packages for Ubuntu on my [ppa](https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac).
But probably sometimes I will need help to do it. I can send the debian folder if you want.

**Comment by kelson42** [comment]
@LAfricain Thank you very much for your PR. We love Debian and Ubuntu at Kiwix. Your effort is really welcome. I will let @legoktm, official Kiwix Debian packager, give you a feedback. This should happen in the next days. Just for your information, this is the link to the Kiwix Debian packaging team http://debian.kiwix.org

**Comment by legoktm** [comment]
hi @LAfricain! I'd appreciate it if you could share your debian folder. Would you be interested in collaborating on the package for Debian itself? I'm currently working on updating the libzim and libkiwix dependencies, but any help you can provide on packaging the kiwix-desktop itself would be greatly appreciated.

**Comment by LAfricain** [comment]
I can help but really I don't know very well how to package often it is @Ordissimo who helps me!! You can take everything you need in my ppa.
But the best  will be probably to create a proper kiwix ppa.
But If you create a package for libzim and libkiwix, it will be also easier for me to package kiwix-deskop.

**Comment by kelson42** [comment]
@LAfricain Do you have uploaded somewhere the source code/configuration to create the deb file of the PPA?

**Comment by LAfricain** [comment]
Yes from the official kiwix server.

**Comment by kelson42** [comment]
@LAfricain No this this the source of the software, what @legoktm asks for are the sources/configuration to build the DEB package.

**Comment by LAfricain** [comment]
Ah, no I did it myself with the help of Ordissimo.

**Comment by kelson42** [comment]
@LAfricain So you don't want to publish them?

**Comment by LAfricain** [comment]
Why not? Everything is already published on my ppa.

**Comment by kelson42** [comment]
@LAfricain Your PPA has the DEB binary packages, not the sources/configuration/scripts used to build it.

**Comment by LAfricain** [comment]
On the ppa you can get everything, just go https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac/+packages and toggle the arrow on the package.

**Comment by kelson42** [comment]
@LAfricain Just as an example, this is the kind of thing @legoktm is asking for. Here the stuff for the libzim package https://salsa.debian.org/debian/zimlib/tree/master/debian

**Comment by LAfricain** [comment]
@kelson42 Yes I understand well! You can find everything on the ppa, please look better:https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac/+sourcefiles/kiwix-desktop/2.0-beta5-7/kiwix-desktop_2.0-beta5-7.debian.tar.xz

**Comment by kelson42** [comment]
@LAfricain Thx, forgot indeed to check if the PPA had the source packages. sorry.

**Comment by rgaudin** [comment]
Thank you @LAfricain for your work. Could @Popolechien check that the metadata and icon matches what we are using on other platforms?

```
Package: kiwix-desktop
Description: Wikipedia offline reader
 Kiwix allows you to read and search through offline content
 as they were online. Similar to a browser, Kiwix works with
 the highly compressed ZIM file format.
 .
 Features:
    * Pure ZIM file reader
    * Case and diacritics insensitive full text search engine
    * Bookmarks & Notes
    * ZIM base HTTP server
    * PDF/HTML export
    * Localized
    * Search suggestions
    * ZIM file Index capacity
    * Tabs navigation
```

![kiwix](https://user-images.githubusercontent.com/57929/62831562-d5e4e000-bc21-11e9-94c6-0bdc53510fab.png)

Also, I've noticed that someone published a kiwix software in the Ubuntu store. It's called `kiwix-ryanjyoder`.
It's from the [Snap Store](https://snapcraft.io/kiwix-ryanjyoder) and is actually just kiwix-tools binaries: `kiwix-ryanjyoder.kiwix-manage`, `kiwix-ryanjyoder.kiwix-read`, `kiwix-ryanjyoder.kiwix-search` and `kiwix-ryanjyoder.kiwix-serve`.

The description is not ideal ; it never says that it's command line tools so it's somewhat deceptive when installed from the Ubuntu Store UI.

![VirtualBox_ubuntu19-desktop_09_08_2019_10_13_52](https://user-images.githubusercontent.com/57929/62831622-d0d46080-bc22-11e9-8ca8-93db6d3da978.png)

Given it's the only result for a `kiwix` search on those stores, it would help if @kelson42 could reach that person and share effort so that we have two proper `kiwix-desktop` and a `kiwix-tools` products there.

**Comment by Popolechien** [comment]
@rgaudin Looks good to me.
Regarding Ubuntu, let's randomly ping @ryanjyoder (hopefully this is the same person)?

**Comment by LAfricain** [comment]
I just build an new release (rc2) on my ppa.

**Comment by mgautierfr** [comment]
> Regarding Ubuntu, let's randomly ping @ryanjyoder (hopefully this is the same person)?

I think it is : https://github.com/ryanjyoder/kiwix-snap

The best is probably to open issues there.

**Comment by ryanjyoder** [comment]
Hey, sorry I missed this thread (too many github notifications :/). I'm not clear on what you're asking. Would you like me to remove the snap to reduce confusion? Or update it so it's more relevant? If you're interested in packaging kiwix as a snap I'd be glad to contribute to that. Ideally, it'd get upstreamed and I could remove my namespaced snap.

**Comment by rgaudin** [comment]
@ryanjyoder thanks for your reply. I think there are several things that we want:

* a package for kiwix-tools (that's what you are currently offering). This should be renamed as it is not _Kiwix_ but the kiwix tools.
* a package for kiwix-desktop (what @LAfricain is currently offering in his PPA).

Ideally, both would be served as snap (we already provide AppImage and Flatpack) and as a debian package. We already have a [debian team](https://tracker.debian.org/teams/kiwix-team/) but it requires packaging/updating all the libs.

@LAfricain I think we should use your PPA to update our debian recipes.

@ryanjyoder if you could rename your snap, that's be great. I'll try and open issues on your repo to polish it a bit and maybe we'll merge that later. How difficult would it be to create a snap for kiwix-desktop as well?

**Comment by LAfricain** [comment]
In my ppa I have also the kiwix-tools package.

**Comment by popey** [comment]
Hi. I stumbled on this issue today. I'm a Snapcraft Developer Advocate so I'd like to help get a kiwix-desktop snap published in the store. In between recovering from a Christmas eating coma and seeing relatives, I took a first stab at making a kiwix-desktop snap. Unfortunately I'm failing at building a newer libzim than exists in 18.04. 

Here's the yaml: https://github.com/popey/kiwix-desktop-snap

Here's how it failed.

```
Building libzim                                                                                       
meson snapbuild                                                                                       
The Meson build system                                                                                
Version: 0.52.1                                                                                       
Source dir: /root/parts/libzim/build                                                                  
Build dir: /root/parts/libzim/build/snapbuild                                                         
Build type: native build                                                                              
Project name: libzim                                                                                  
Project version: 5.1.0                                                                                
Appending CFLAGS from environment: ' -I/root/stage/include'                                                                         
Appending CPPFLAGS from environment: ' -I/root/stage/include'                                         
Appending CXXFLAGS from environment: ' -I/root/stage/include'                                         
Appending CPPFLAGS from environment: ' -I/root/stage/include'                                         
Appending CFLAGS from environment: ' -I/root/stage/include'                                                                         
Appending CPPFLAGS from environment: ' -I/root/stage/include'                                         
C compiler for the host machine: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")            
C linker for the host machine: GNU ld.bfd 2.30     
Appending CXXFLAGS from environment: ' -I/root/stage/include'                                                                       
Appending CPPFLAGS from environment: ' -I/root/stage/include'                                                                       
C++ compiler for the host machine: c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C++ linker for the host machine: GNU ld.bfd 2.30                                                                                                                                                             
Host machine cpu family: x86_64           
Host machine cpu: x86_64                           
Checking for size of "off_t" : 8                   
Found pkg-config: /usr/bin/pkg-config (0.29.1)     
Run-time dependency zlib found: YES 1.2.11                                                            
Run-time dependency liblzma found: YES 5.2.2                                                          
Run-time dependency xapian-core found: YES 1.4.5   
Run-time dependency threads found: YES                                                                
Run-time dependency icu-i18n found: YES 60.2       
Run-time dependency GTest found: YES (building self)                                                  
Program libzim-compile-resources found: YES (/root/parts/libzim/build/scripts/libzim-compile-resources)                                                                                                                                                                 
Configuring config.h using configuration                                                              
Program cython3 found: YES (/usr/bin/cython3)                                                                                                                                                                
Run-time dependency python3 found: YES 3.6                                                                                                                                                                   
Build targets in project: 8                                                                                                                                                                                  
Found ninja-1.8.2 at /usr/bin/ninja                                                                   
ninja                                                                                                 
[1/56] Generating resources with a custom command.                                                                                                                                                           
stopwords/en ['stopwords', 'en']                                                                      
stopwords/he ['stopwords', 'he']                                                                      
stopwords/fra ['stopwords', 'fra']      
[45/56] Linking target test/cluster.                                                                  
FAILED: test/cluster                                                                                  
c++  -o test/cluster 'test/9f86d08@@cluster@exe/cluster.cpp.o' 'test/9f86d08@@cluster@exe/gtest-all.cc.o' 'test/9f86d08@@cluster@exe/gtest_main.cc.o' -I/root/stage/include -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group src/libzim.so.5.1.0 -pthread /usr/lib/x86_64-linux-gnu/liblzma.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libxapian.so /usr/lib/x86_64-linux-gnu/libicui18n.so /usr/lib/x86_64-linux-gnu/libicuuc.so /usr/lib/x86_64-linux-gnu/libicudata.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/../src:$ORIGIN' -Wl,-rpath-link,/root/parts/libzim/build/snapbuild/src      
test/9f86d08@@cluster@exe/gtest_main.cc.o: In function `RUN_ALL_TESTS()':                                                           
/usr/src/googletest/googletest/src/gtest_main.cc:34: multiple definition of `main'                                                  
test/9f86d08@@cluster@exe/cluster.cpp.o:/root/parts/libzim/build/snapbuild/../test/cluster.cpp:414: first defined here                                                                                                                                                  
collect2: error: ld returned 1 exit status                        
[50/56] Compiling C++ object 'test/9f86d08@@uuid@exe/gtest-all.cc.o'.                                                               
ninja: build stopped: subcommand failed.                          
```

I'm no expert in googletest nor libzim, so any suggestions most welcome!

Do we need a separate issue for the snap build, rather than clutter this issue up?

**Comment by kelson42** [comment]
@popey I would really like to push an official snap package and we will hwlp you but I would really like you to open a new ticket for that please.

**Comment by Ordissimo** [comment]
Le 2019-12-26 13:25, Alan Pope a écrit :
> Hi. I stumbled on this issue today. I'm a Snapcraft Developer Advocate
> so I'd like to help get a kiwix-desktop snap published in the store.
> In between recovering from a Christmas eating coma and seeing
> relatives, I took a first stab at making a kiwix-desktop snap.
> Unfortunately I'm failing at building a newer libzim than exists in
> 18.04.
Hi
Using the lafricain79 depot
It uses zimlib - 6.0.2
https://launchpad.net/~lafricain79/+archive/ubuntu/lafricainenvrac/+packages

**Comment by Ordissimo** [comment]
Apply this correctif :
```
Description: <short summary of the patch>
 TODO: Put a short summary on the line above and replace this paragraph
 with a longer explanation of this change. Complete the meta-information
 with other relevant fields (see below for details). To make it easier, the
 information below has been extracted from the changelog. Adjust it or drop
 it.
 .
 zimlib (6.0.2-1ubuntu1) bionic; urgency=medium
 .
   * Update github release
Author: L'Africain <lafricain79@gmail.com>

---
The information above should follow the Patch Tagging Guidelines, please
checkout http://dep.debian.net/deps/dep3/ to learn about the format. Here
are templates for supplementary fields that you might want to add:

Origin: <vendor|upstream|other>, <url of original patch>
Bug: <url in upstream bugtracker>
Bug-Debian: https://bugs.debian.org/<bugnumber>
Bug-Ubuntu: https://launchpad.net/bugs/<bugnumber>
Forwarded: <no|not-needed|url proving that it has been forwarded>
Reviewed-By: <name and email of someone who approved the patch>
Last-Update: 2019-09-27

--- zimlib-6.0.2.orig/test/cluster.cpp
+++ zimlib-6.0.2/test/cluster.cpp
@@ -409,9 +409,10 @@ TEST(CluterTest, read_extended_cluster)
 
 
 }  // namespace
-
+/*
 int main(int argc, char** argv)
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }
+*/
--- zimlib-6.0.2.orig/test/dirent.cpp
+++ zimlib-6.0.2/test/dirent.cpp
@@ -262,8 +262,9 @@ TEST(DirentTest, redirect_dirent_size)
 
 }  // namespace
 
+/*
 int main(int argc, char** argv)
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
-}
+}*/
--- zimlib-6.0.2.orig/test/header.cpp
+++ zimlib-6.0.2/test/header.cpp
@@ -72,9 +72,9 @@ TEST(HeaderTest, read_write_header)
 }
 
 }  // namespace
-
+/*
 int main(int argc, char** argv)
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
-}
+}*/
--- zimlib-6.0.2.orig/test/template.cpp
+++ zimlib-6.0.2/test/template.cpp
@@ -76,9 +76,9 @@ TEST_F(TemplateTest, Link)
 }
 
 }  // namespace
-
+/*
 int main(int argc, char** argv)
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
-}
+}*/
--- zimlib-6.0.2.orig/test/uuid.cpp
+++ zimlib-6.0.2/test/uuid.cpp
@@ -116,9 +116,9 @@ TEST(UuidTest, output)
   ASSERT_EQ(s, "550e8400-e29b-41d4-a716-446655440000");
 }
 };
-
+/*
 int main(int argc, char** argv)
 {
   ::testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
-}
+}*/
```

**Comment by Ordissimo** [comment]
This may also be necessary :
```
--- zimlib-4.0.1.orig/test/meson.build
+++ zimlib-4.0.1/test/meson.build
@@ -1,7 +1,6 @@
 
 
 tests = [
-    'cluster',
     'dirent',
     'header',
     'uuid',
```

**Comment by kelson42** [comment]
With the help of @legoktm we will relaunch our Launchpad.net PPA.

**Comment by LAfricain** [comment]
Great! Be free to use all the stuff of my ppa.

**Comment by kelson42** [comment]
@legoktm is working on a package which should be available in our PPa in the next few weeks.

**Comment by kelson42** [comment]
It's pending in debian https://ftp-master.debian.org/new/kiwix_2.0.4-1.html and soon in our PPA https://wiki.kiwix.org/wiki/Ubuntu_PPA

**Comment by kelson42** [comment]
@LAfricain Please test it and let us know if you have any problem (new ticket)
