### ISSUE TITLE
Incorrect handling of hyperlinks for articles with slash(es) in the URL

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-desktop#206]
In relation to https://github.com/kiwix/kiwix-js/pull/498 (and see in particular comment https://github.com/kiwix/kiwix-js/pull/498#issuecomment-511320797), it seems that kiwix-desktop_windows_x64_2.0-beta5 is not dealing correctly with articles that are in a subdirectory. This currently affects Stackexchange ZIMs, whereby clicking on a hyperlink (e.g. to a tag/category) from an article is currently broken in the desktop application ("Your file was not found").

Please note that this has interactions with https://github.com/openzim/mwoffliner/issues/726 . For example, the current landing page of `wikivoyage_en_all_novid_2019-06.zim` has this URL:

`Wikivoyage%3AOffline_reader_Expedition/Home_page`

Note the forward slash. Hyperlinks to other pages on this page should have an extra `../` in front of them, but they do not currently (and they currently work, nevertheless, in Kiwix Desktop). That issue has been fixed in mwoffliner https://github.com/openzim/mwoffliner/issues/726 , so that when a new ZIM is produced using the same landing page, Kiwix Desktop will probably be unable to follow the link correctly (as is currently the case with subdirectories in Stackexchange ZIMs). Therefore, it will need fixing in Kiwix Desktop (and other readers based on libzim, I think). _EDIT: Although wikivoyage_en_all_novid_2019-07.zim works in Kiwix Desktop beta, it is because of https://github.com/openzim/mwoffliner/issues/904, and not because this issue has actually been fixed._

@kelson42, we could do with some advice on how to handle this situation in Kiwix JS. If we fix the Stackexchange issue, we break Kiwix JS working with the current (buggy) Wikivoyage. If we don't fix, we will probably have a broken Wikivoyage on the next release of Wikivoyage, if it uses the same landing page URL. So catch 22.

Pinging @mossroy so he is aware of this issue.

**Comment by Jaifroid** [comment]
To reproduce this issue with Stackexchange ZIMs:

* Open a Stackexchange ZIM. I used `mathoverflow.net_eng_all_2018-08.zim`
* Go to any question page
* Click on a tag on that page. You will get "Your file was not found".

See example from screenshots below. It is caused by the fact that once we are on a question page, we are in the subdirectory `/question/`. The hyperlinks on that page therefore have an extra `../` in front, but Kiwix Desktop beta seems to ignore this, and instructs its web view to navigate incorrectly to `tag/nt-number-theory/1.html` instead of `../tag/nt-number-theory/1.html`. You can see the incorrect directory it ends up in by looking in the search box of second screenshot.

Article "Polynomial bijection from Q×Q to Q?"
![image](https://user-images.githubusercontent.com/4304337/62006700-0580ec00-b13c-11e9-9bf5-4c48651a0645.png)

Clicking on nt.number-theroy or open-problems tags:
![image](https://user-images.githubusercontent.com/4304337/62006712-39f4a800-b13c-11e9-8f36-2a8b3e17f621.png)

**Comment by kelson42** [comment]
@Jaifroid Thank you having properly reported this bug
@mgautierfr I'm able for now to confirm the bug, but I expect this to work properly as we have a lot of URLs with slashes in a lot of (StackExchange) ZIM files.

**Comment by kelson42** [comment]
@Jaifroid My advices are clear (1) don't encode slashes in URLs (2) don't implement any workaround for buggy ZIM in the readers.

**Comment by Jaifroid** [comment]
@kelson42 Thank you!

**Comment by jetownfeve21** [comment]
I didn't succeed to find a solution to this problem, I think we have to set up the Qt webengine to  interpret correctly relative path but I don't know how to do it. To illustrate the problem, the  QWebEnginePage emits the signal QWebEnginePage::linkHovered(const QString &url) when the mouse hovers over a link where the parameter contains the target URL of the link, but in our case the Url is already wrong if the path begins with "../".

**Comment by Jaifroid** [comment]
@jetownfeve21 I don't know the Desktop app's code, but the way we currently do it in Kiwix JS (when not using the Service Worker) is that we intercept the click event (or for a web view, the Fetch event) and rewrite the URL as necessary. A neater alternative might be to set a base URL for the web view, so that links are automatically calculated correctly by the browser engine, though it can have knock-on effects that need careful testing.

**Comment by jetownfeve21** [comment]
@Jaifroid We already rewrite the URL when needed, but the event for that already catches a wrong URL, for example the URL "../tag/creation" becomes "/question/tag/creation" where there is no way to identify it as a wrong URL. Maybe we can add a rule that modify the URL each time that there is the "question/tag" pattern but I find this quite dirty

**Comment by Jaifroid** [comment]
@jetownfeve21 You're right, that would be very dirty, and there's no way for you to code for every case of a subdirectory.

From our experience, I suspect that the code is not setting the URL of the webview correctly. It could be because it is being set with a percent-encoded forward slash, in which case the browser engine won't realize it's in a subdirectory, or else maybe you need to set an explicit base tag (shouldn't really be necessary).

Example:

Let's say you have browsed to a question in a Stackexchange ZIM. The URL of the web view should be set to (e.g.):
```
/A/question/1.html
```
Then, if on that page the browser engine finds a relative link like `../tag/epistemology/1.html`, it will correctly calculate the URL to navigate to as:
```
/A/tag/epistemology/1.html
```
If, however, the webview's URL had been set to `A/question%2F1.html`, the browser engine will calculate a bad result. This could be due to not URI decoding at the right point, or to an unnecessary URI encoding step.

This was a problem we grappled with quite a lot, compounded by the fact that some Wikimedia ZIMs were incorrectly encoded (now fixed). However, Stackexchange ZIMs have always been correctly encoded, so they're a good test case.
