### ISSUE TITLE
Kiwix Desktop is really slow to start. Why?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#208]
On my computer it takes beetween 4-5 seconds to starts whereas Firefox takes 1 second. 4-5 seconds is a long time, after 2-3 seconds you start to believe that the app does not start. This is on my Linux computer but @Jaifroid had the same comment on a Windows system.

**Comment by jetownfeve21** [comment]
@kelson42 Does it happen with all versions (flatpak, dev version, appimage) ?

**Comment by kelson42** [comment]
These are my tests. Just starting and closing manually the windows.

```
$ time flatpak run org.kiwix.desktop 
Gtk-Message: 17:12:24.842: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:12:24.842: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Library directory : "/home/kelson/.var/app/org.kiwix.desktop/data/kiwix"
[2:15:1216/171226.895401:ERROR:address_tracker_linux.cc(177)] Could not bind NETLINK socket: Address already in use (98)
add widget
"2a28e9cf3f369909"
session saved

real	0m3.683s
user	0m0.017s
sys	0m0.008s
```

and

```
$ time ./kiwix-desktop_x86_64_2.0-rc4.appimage 
Library directory : "/home/kelson/.local/share/kiwix"
add widget
double free or corruption (out)
Aborted (core dumped)

real	0m2.291s
user	0m0.292s
sys	0m0.080s
```

The flatpak version is for me really slower. It takes almost 2 seconds beetween `Library directory : "/home/kelson/.var/app/org.kiwix.desktop/data/kiwix"` and `[2:15:1216/171226.895401:ERROR:address_tracker_linux.cc(177)] Could not bind NETLINK socket:`.

... but it knows more local files I have loaded separately (not downloaded with Kiwix). That fact is strange... but that might explain why it slower.

@jetownfeve21 So I have two questions:
* Why the flatpak version has more files in the local library than the appimage?
* Does the app has to load all the ZIM files before displaying the window?

**Comment by jetownfeve21** [comment]
@kelson42 the flatpak version uses another directory for the library as you can see in the debug :  flatpak : `Library directory : "/home/kelson/.var/app/org.kiwix.desktop/data/kiwix"`
appimage : `Library directory : "/home/kelson/.local/share/kiwix"`
so it's two different libraries 

At the start of Kiwix-desktop, the program reads the library.xml file to create a instance of `kiwix::Book` class foreach zim in the library.xml file. But this class `kiwix::Book` only contains metadata about the zim such as the id, the title, the tags etc... 
How many zim do you have ?

**Comment by kelson42** [comment]
@jetownfeve21 Maybe 10. Reading the XML file can not take so long in itself.

**Comment by jetownfeve21** [comment]
@kelson42 with about twenty files it starts normally on my computer

**Comment by kelson42** [comment]
@jetownfeve21 What does "normaly" mean? How long does it take? Can you make the same experiment I made?

**Comment by jetownfeve21** [comment]
I mean it doesn't feel slow

```
$ time flatpak run org.kiwix.desktop
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

(process:2): Gtk-WARNING **: 21:52:04.016: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 21:52:04.146: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:52:04.146: Failed to load module "canberra-gtk-module"
Library directory : "/home/luddens/.var/app/org.kiwix.desktop/data/kiwix"
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
add widget
session saved
flatpak run org.kiwix.desktop  0,03s user 0,02s system 1% cpu 3,668 total

```

**Comment by kelson42** [comment]
@jetownfeve21 I don't really understand why your `time` command does not print the same as mine... but I guess the real number of seconds is `3,668`?! Your test runs pretty exactly on the same amount of time like mine.

**Comment by jetownfeve21** [comment]
@kelson42 In fact the app starts more slowly the more files there are

With ~20 zims : 
![kiwix-start](https://user-images.githubusercontent.com/47149116/71077270-652d7180-2187-11ea-985f-3d249f0af7f4.gif)

Without any zims : 
![kiwix-without-zim](https://user-images.githubusercontent.com/47149116/71077303-76767e00-2187-11ea-9c69-e4bab0ef5079.gif)

**Comment by jetownfeve21** [comment]
@kelson42 Maybe we can add a splashscreen ?

**Comment by kelson42** [comment]
@jetownfeve21 No, the loading should not be longer the more we have files. They should be load asynchronously.

**Comment by mgautierfr** [comment]
Probably related to kiwix/kiwix-tools#319

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Would be good to check if the loading is more or less instantaneous now (the "trust library" kiwix-lib PR has been merged). If "yes", that would allow to close that one as well.

**Comment by kelson42** [comment]
To me it has fixed the problem. I close the ticket.
