### ISSUE TITLE
URL is not written in the bottom bar

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#209]
By being over the link/clicking on it.

**Comment by jetownfeve21** [comment]
@kelson42  I don't understand which behaviour is expected ?

**Comment by kelson42** [comment]
@jetownfeve21 @mgautierfr @schoenbaechler I'm not so sure myself. What tells us the new design mockups?

**Comment by kelson42** [comment]
URLs should not be displayed in the statusbar, which will be removed. But the shiuld be dispalyed in a small overlay like on FF or Chrome.
