### ISSUE TITLE
aria2c leaves tmp data at the end of download

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-desktop#211]
**Reported by kelson42 on 2013-03-29 18:01 UTC**
New version of aria2c can fix that using --rpc-save-upload-metadata=falsehttp://aria2.sourceforge.net/manual/en/html/aria2c.html#cmdoption--save-session

**Comment by kelson42** [comment]
This should be checked again...

**Comment by kelson42** [comment]
This is not the case anymore with kiwix-desktop 2.0
