### ISSUE TITLE
Default library does not match language settings

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#212]
There are too many zim files available for comfortable or relevant browsing. When in the library, the application should by default offer content in the language Kiwix is set in (e.g. Kiwix is in French -> files shown in download library are in French)
![language setting](https://cloud.githubusercontent.com/assets/21675885/20705553/a26e8f98-b623-11e6-8059-0ee4160150a8.png)

**Comment by mgautierfr** [comment]
There is not setting page in kiwix-desktop for now. But the default for now is to display the remote content only for the detected language of the system. (ie, if you are using a french system, by default the remote content displayed is filtered by french language.)
This can be change in the "Browse By language" in the left menu.

**Comment by kelson42** [comment]
@mgautierfr Perfect then, was not 100% sure this is why I have moved this ticket from kiwix-desktop 1.0 repo..
@Popolechien Would be nice if you could confirm this is OK for you and close the ticket

**Comment by Popolechien** [comment]
Confirmed, thanks. The ticket was for 0.9 anyway.
