### ISSUE TITLE
Norwegian Wikipedia (Norsk bokmål) is missing from the catalog

### ISSUE THREAD

**Issue by digitalgutenberg** [kiwix/kiwix-desktop#213]
The download itself exists and can be found here: download.kiwix.org/portable/wikipedia/kiwix-0.9+wikipedia_nb_all_2016-08.zip

However, I'm told that there is no entry for Norwegian (Norsk Bokmål) in the library.xml file: http://ftp.fau.de/kiwix/library/library.xml 

The client therefore doesn't find any entry for the Norsk Bokmål wikipedia.

**Comment by kelson42** [comment]
@digitalgutenberg So, with Kiwix Desktop 2.0 for Linux/Windows, the problem does not occur anymore.
