### ISSUE TITLE
Search engine does not work well with Debian unstable and Ml

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-desktop#214]
**Reported by kelson42 on 2011-03-13 09:26 UTC**
file: http://tmp.kiwix.org/tmp/ml-collection.zim
pattern: വ്യാകരണഗ്രന്ഥങ്ങളിൽ
title: കേരളപാണിനീയം/നാമാധികാരം/വിഭക്തിപ്രകരണം
text snippet: [...]  ദ്വിതീയ എന്ന ക്രമത്തിലുള്ള പേരാണു് മറ്റുള്ള വ്യാകരണഗ്രന്ഥങ്ങളിൽ
കാണുന്നതു്. [...]

Search the give pattern dives "no result"

**Comment by kelson42** [comment]
To be checked again

**Comment by kelson42** [comment]
I can not reproduce the problem anymore.
