### ISSUE TITLE
Kiwix-desktop crashes immediately after opening on the raspberry pi

### ISSUE THREAD

**Issue by User234324** [kiwix/kiwix-desktop#221]
**I tried to install kiwix-desktop on my raspberry pi (latest Raspbian OS) via flathub as descriped in the official kiwix-wiki, but kiwix-desktop crashes immediately after starting. Only an empty window opens for a few seconds and I get the following error message in the terminal:**

**pi@raspberrypi:~ $ flatpak run org.kiwix.desktop**
```
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/pi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

libEGL warning: DRI2: failed to authenticate
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
"/home/pi/.var/app/org.kiwix.desktop/data/kiwix"
0
add widget
Unable to find target for this triple (no targets are registered)

```
**I already tried to set the XDG_DATA_DIRS environment variable, but the application still crashes. May someone of you can figure out a way to fix this problem.**

**Comment by kelson42** [comment]
@User234324 RPI has a ARM architecture. The Flathub package is for x86_64. Therefore, this is expected that the flathub package fails. For now we don't provide binaires for Linux ARM. See related issue https://github.com/kiwix/kiwix-build/issues/153.
