### ISSUE TITLE
kiwix-serve does not work with Linux Flatpack/Flathub

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#222]
From the UI everything is OK. I click "start server". I get the server started, I can even see it in the list of processes:
```
$ ps aux | grep kiwix-serve
kelson   16635  0.8  0.3 359516 24896 tty2     Sl+  06:39   0:00 /app/bin/kiwix-serve -a2 -p8181 -l /home/kelson/.var/app/org.kiwix.desktop/data/kiwix/library.xml
kelson   16644  0.0  0.0  14756  1008 pts/0    S+   06:39   0:00 grep --color=auto kiwix-serve
```

But if I try to access the service then no HTTP response and the process vanishes... so I guess we have a crash at the first call.

If I run the same `library.xml` with my own `kiwix-serve`, everything works fine, so this is not a problem with the `library.xml`.

**Comment by jetownfeve21** [comment]
![image](https://user-images.githubusercontent.com/47149116/63360261-587e4580-c36e-11e9-9495-e4bfe2a07787.png)

It seems that there is some problem with this library

**Comment by kelson42** [comment]
@jetownfeve21 OK. I don't really understand why starting kiwix-serve should depend from libgtk!

**Comment by jetownfeve21** [comment]
@kelson42 I don't know too
Some threads say that this error can be due to the fact that it runs a 32-bits program on a 64-bits computer. Is it the case of kiwix ?

**Comment by kelson42** [comment]
@jetownfeve21 Kiwix-Desktop is only 64 bits... so obviously I run it on a 64 bits system.

**Comment by kelson42** [comment]
Works for me now :)
