### ISSUE TITLE
kiwix-desktop_x86_64_2.0-rc1.appimage core dumped under ArchLinux

### ISSUE THREAD

**Issue by exaos** [kiwix/kiwix-desktop#225]
- Platform: ArchLinux with latest apps.
- AppImage file: kiwix-desktop_x86_64_2.0-rc1.appimage
- Error output:

```
$ ./kiwix-desktop_x86_64_2.0-rc1.appimage 
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
"/data/users/vivodo/.local/share/kiwix"
0
/tmp/.mount_kiwix-BNDTNb/usr/libexec/QtWebEngineProcess: relocation error: /tmp/.mount_kiwix-BNDTNb/usr/libexec/QtWebEngineProcess: symbol _ZN7content22localtime64_r_overrideEPKlP2tm version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference
[1]    26777 trace trap (core dumped)  ./kiwix-desktop_x86_64_2.0-rc1.appimage
```

**Comment by kelson42** [comment]
@exaos Have you tried with the flatpack/flathup package? Does it wok better? What is the exact version of your Archlinux?

**Comment by exaos** [comment]
@kelson42 

- Kenerl: 5.2.7-arch1-1-ARCH
- glibc: 2.29
- nvidia-dkms/utils: 430.40

I'm not familiar with flatpack/flathup, so I didn't try it.

**Comment by kelson42** [comment]
I guess this arch version has just too old dependences. But you could also use https://aur.archlinux.org/packages/kiwix-desktop/

**Comment by soloturn** [comment]
i created https://aur.archlinux.org/packages/kiwix-desktop-git which uses newest code from git, just in case kiwix-desktop gets outdated.
