### ISSUE TITLE
Text/GUI is unreadable when using default KDE dark theme

### ISSUE THREAD

**Issue by corecontingency** [kiwix/kiwix-desktop#226]
![](https://user-images.githubusercontent.com/54042889/62919742-70dfd600-bd58-11e9-97a8-54bb8575121f.png)

As you can see, the text is white, on a white background, making it basically impossible to read.

I am using Arch Linux, with KDE and Wayland. My Qt and GTK theme are both set to the KDE's default dark theme, Breeze Dark.

Issue seems to persist whether I use the appimage, the flatpak, or even the AUR package:
https://aur.archlinux.org/packages/kiwix-desktop.

I have also tried using xWayland (using `env QT_QPA_PLATFORM=xcb`) and base Xorg, and the issue still persists.

**Comment by CodeJoule** [comment]
Seconded. I really want to read my ZIMs, which is possible, but I have to tip the screen a different way so I see it under a different contrast and then I have to squint my eyes really hard to pick out any of the white-grey letters to be able to use the GUI. It is really terrible.

Wouldn't an easy fix be to let Plasma handle the background color? My guess is that Plasma, in an effort to generate the dark theme, makes the text white-ish, but for some reason can't make the background dark. So it's white-on-white.

I am using Manjaro Plasma and Xorg. Both Qt and GTK themes are set to dark as well.

**Comment by CodeJoule** [comment]
A temporary hack to fix this, I found, is to launch `kiwix-desktop` with a modified KDE variable:
`env XDG_CONFIG_HOME=/usr/share/color-schemes/BreezeLight.colors kiwix-desktop`
You can also look in `/home/$USER/.local/share/color-schemes/` for any other light color schemes you might have.
A popup will appear saying "Configuration file "/usr/share/color-schemes/BreezeLight.colors/kiwix-desktoprc" not writable," but I think it's fine. The words appear normally using this hack! Yay!
![image](https://user-images.githubusercontent.com/10947374/74358825-f7f91f80-4d76-11ea-9b8a-49ac54c03d69.png)
Users shouldn't have to figure this workaround out, though, so an official fix would be nice.

**Comment by mgautierfr** [comment]
We should probably force the text color to be black in our css file to be sure that text is always visible.

**Comment by kelson42** [comment]
I'm again forcing anything as long as the standard solution work fine. Unfortunately we don't respect the OS/Display manager theme. That should be fixed with #320.

**Comment by kelson42** [comment]
Handle dark mode problem with #320
