### ISSUE TITLE
Replace vue.js HTML by native Qt (was: vue.js should not be part of the source code)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#230]
Only our source code should be part of it. This should be downloaded at the build time.

**Comment by xurror** [comment]
Do you suggest the file be removed?

**Comment by kelson42** [comment]
@xurror This is not what I have written

**Comment by xurror** [comment]
Oh, I think I didn't understand the issue properly

**Comment by xurror** [comment]
> Only our source code should be part of it. This should be downloaded at the build time.

Please can you explain better what you mean

**Comment by kelson42** [comment]
By moving the library to Qt, the problem should vanish.

**Comment by kelson42** [comment]
Ticket will de facto vanish when we move the library to pure Qt.

**Comment by kelson42** [comment]
Closing this ticket in favour of #665 683

**Comment by mgautierfr** [comment]
> Closing this ticket in favour of #665

@kelson42 This is not a duplicate of #665 for me.

**Comment by kelson42** [comment]
Where is the discrepence? Where is still used vue.js outside the library?

**Comment by kelson42** [comment]
Sorry, #683
