### ISSUE TITLE
Printing fails on Windows 10

### ISSUE THREAD

**Issue by Flash1XD** [kiwix/kiwix-desktop#235]
_Version: 2.0-rc1-1-g24da6a5_
Printing is not working on Windows 10 (tested on Build 1809).

The print function produces an error message
**"an error has occured while printing"**
 and generates/ prints an empty page.

**Comment by jetownfeve21** [comment]
@Flash1XD I can't reproduce the bug with the kiwix-desktop_windows_x64_2.0-rc3 version, can you retry on your computer with the new version ?

**Comment by kelson42** [comment]
@jetownfeve21 @Flash1XD I would good here to have a specific ZIM file/article to secure everybody works with the same test.

**Comment by Flash1XD** [comment]
@jetownfeve21 @kelson42 I've testet it with the current Version. Congratulations! The bug is fixed. Printing is now working in kiwix-desktop_windows_x64_2.0-rc3 on Windows 10 build 1903. (can't test on build 1809 anymore due to upgrade)
Good job! Ticket can be closed now.
