### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#237]
In order to support the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your reader:

* is feeding itself from the OPDS stream (using a local cache/copy or not)
* is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.
* is using the [centralized Categories List](https://github.com/kiwix/kiwix-tools/issues/317)
* is using the new tags only for flavours and full-text index.

**NOTE**: This issue for planning purposes, OPDS and libkiwix **does not support** those features at the moment.

**Comment by kelson42** [comment]
I don't know if this is a consequence or not, but the category system is broken to me. Most of the time I get no result at all.

**Comment by kelson42** [comment]
@jetownfeve21 @mgautierfr What is the status here? Which parts are done?

**Comment by mgautierfr** [comment]
- [x] is feeding itself from the OPDS stream (using a local cache/copy or not)
- [x] is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.
- [ ] is using the centralized Categories List
- [x] is using the new tags only for flavours and full-text index.

**Comment by kelson42** [comment]
Considering that we only need to get https://github.com/kiwix/kiwix-desktop/issues/934 implemented and this one is in doing. I'll close this ticket as this is mostly a duplicate now.
