### ISSUE TITLE
Implement "Donate to Kiwix" menu item

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#249]
Like showed here https://www.dropbox.com/sh/p621jd89x1c6hpi/AAB3whrF3DoJZqZTJ535gPr0a/02-exports?dl=0&preview=kiwix-server-01%402x.png&subfolder_nav_tracking=1

**Comment by jetownfeve21** [comment]
@kelson what is this action supposed to do exactly ?

**Comment by kelson42** [comment]
Open the following link https://donate.kiwix.org

**Comment by jetownfeve21** [comment]
@kelson42 Should we change the shortcut even if it represents a heart, I can't use it on my keyboard because I have to use the shift key to do a "3" but doing that the "<" key become a ">"

**Comment by kelson42** [comment]
@jetownfeve21 No, please keep the shortcut like it is.
