### ISSUE TITLE
Open a download filepicker if content can not be displayed by the qtwebengine

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#26]
For example, with the Gutenberg ZIM file, we have a lot of EPUB. Currently, clicking on an EPUB makes nothing. A download/open filepicker (of the operating system) should be displayed instead.

**Comment by jetownfeve21** [comment]
@kelson42 do you have other example, the gutenberg zim file is too big for my connection :)

**Comment by jetownfeve21** [comment]
@kelson42 what is the purpose of this filepicker ?

**Comment by kelson42** [comment]
@jetownfeve21 The filepickers purpose is to allow to save the file or open it with a third party app.
