### ISSUE TITLE
Handle suggestions list properly to have a fluid UX

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#265]
To avoid to slow down the whole system. See https://github.com/kiwix/kiwix-desktop/issues/43#issuecomment-529819752 for more details about the idea.

All of this needs to be revamped/tested with ZIM files with really a lot of articles like `wikipedia_en_all_mini_2020-04.zim`.

**Comment by kelson42** [comment]
@jetownfeve21 This problem is still there. For example if I do:
```
$ time curl "http://localhost:8080/suggest?content=wikipedia_en_all_mini_2020-04&term=emmanuel"
[
  {
    "value" : "Mar Emmanuel Emmanuel",
    "label" : "Mar Emmanuel Emmanuel"
  },
  {
    "value" : "Emmanuel",
    "label" : "Emmanuel"
  },
  {
    "value" : "Emmanuel Segura",
    "label" : "Emmanuel Segura"
  },
  {
    "value" : "Emmanuel Petit",
    "label" : "Emmanuel Petit"
  },
  {
    "value" : "Emmanuel Noterman",
    "label" : "Emmanuel Noterman"
  },
  {
    "value" : "Emmanuel Cathedral",
    "label" : "Emmanuel Cathedral"
  },
  {
    "value" : "Emmanuel Association",
    "label" : "Emmanuel Association"
  },
  {
    "value" : "Emmanuel Agbadou",
    "label" : "Emmanuel Agbadou"
  },
  {
    "value" : "Emmanuel Palomares",
    "label" : "Emmanuel Palomares"
  },
  {
    "value" : "Emmanuel Arthur",
    "label" : "Emmanuel Arthur"
  },
  {
    "value" : "emmanuel ",
    "label" : "containing 'emmanuel'..."
  }
]


real	0m0.043s
user	0m0.007s
sys	0m0.012s
```

I get a response really quickly in `0.043s`.

But if I type "emmanuel" at a normal type speed in the searchbox of Kiwix-Desktop it takes edges (more than 5s on my computer) to return the proper suggestions.

I don't exactly know the reason, but I suspect the that:
* Each time I type a letter a suggestion search is done (probably that should not happen if I type quickly)
* The search someone block each other or the last one have to wait the first one (should not be the case, somehow the later one shoudl probably kill the first ones).

**Comment by LAfricain** [comment]
In the new release it's better, but when we type in the search bar it's still slow. Maybe it can be better to type and have a open page with all the possibilities, as a search engine does in a webbrowser?
