### ISSUE TITLE
Kiwix-server doesn't work on kiwix-server

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#266]
When I try to start kiwix-server option in kiwix desktop, I have an error: "An error has occured"
![kiwix-error](https://user-images.githubusercontent.com/19690477/65702307-c80fe080-e050-11e9-8f20-1a58006d6b84.png)

I use the deb from the ppa. Do we need kiwix-tool to make it working?

**Comment by mgautierfr** [comment]
You need the kiwi-server binary yes. Either in the same directory than kiwix-desktop or in the PATH.
So yes, you need kiwix-tools deb (if it exists)
