### ISSUE TITLE
Management of unavailable online file is broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#267]
1 - A file is not available online but available in the OPDS stream (file has been removed in the backend
2 - Try to download it
3 - Download starts (at least visually in the library)
4 - of course not data are retrieved.... and after a while I decide to stops the download

Then the app crashs
```
$ flatpak run org.kiwix.desktop 
Gtk-Message: 10:10:17.522: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:10:17.522: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Library directory : "/home/kelson/.var/app/org.kiwix.desktop/data/kiwix"
add widget
"2a28e9cf3f369909"
Downloading "http://library.kiwix.org:80/catalog/search?lang=eng&count=0"
Downloading "http://library.kiwix.org:80/catalog/search?lang=eng&count=0"
"2a28e9cf3f369909"
Downloading "http://library.kiwix.org:80/catalog/search?lang=fra&count=0"
terminate called after throwing an instance of 'kiwix::AriaError'
  what():  Active Download not found for GID#2a28e9cf3f369909
```

The app should not start in a first place and display a proper error. That said the app should also not crash. Two problems to fix.

**Comment by jetownfeve21** [comment]
@kelson42 I fixed a crash related to the OPDS but I'm not sure it's the same problem as yours.
Is the file that causes the crash still in the opds stream from http://library.kiwix.org/catalog/search?lang=eng&count=0 ?

**Comment by kelson42** [comment]
@jetownfeve21 The library.kiwix.org catalog is refreshed at least one time a day, so it is not anymore in the OPDS. Just propose a patch an I will check if the problem is fixed.
