### ISSUE TITLE
kiwix-desktop x64_2.0-rc3 doesn't launch on Windows 10

### ISSUE THREAD

**Issue by mkathuri** [kiwix/kiwix-desktop#268]
Hi, I downloaded Kiwix from the website today and after extracting the zip to a folder on my desktop, installed the vc++ redistributable provided with the zip package and restarted my system.

Running kiwix for the first time post reboot, I executed the kiwix-desktop.exe file but nothing showed up. The process was still showing up in task manager. After a few minutes of using my PC, I suddenly got this popup.
![image](https://user-images.githubusercontent.com/26147403/65834357-b308ab00-e2f7-11e9-9556-b73274b9a82f.png)

Seems like it couldn't launch aria2c downloader properly. But the command aria2c.exe --help seems to work just fine on my system. Am I missing something here? Please let me know if any more information is needed.

**OS**: Windows 10 1903 up-to-date

**Comment by kelson42** [comment]
@mkathuri Which version of Kiwix Desktop for Windows to you use?

**Comment by mkathuri** [comment]
Its this one: http://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-rc3.zip

**Comment by kelson42** [comment]
@mkathuri OK, at a first look I can not reproduce the problem. Could you share with us the full path in which the `kiwix-desktop.exe` can be found?

**Comment by mkathuri** [comment]
I've hosted the contents at this location: C:\Users\Maheep Kathuria\Desktop\kiwix

**Comment by kelson42** [comment]
@mkathuri Sorry if I ask you many questions, but I just try to narrow down the problem:
* If you move the `kiwix` directory right to `C:\` doe you have the same problem?
* You had another version of Kiwix running before?

**Comment by mkathuri** [comment]
@kelson42 no problem. I'm facing the same trouble if I move it to C:\kiwix. I already tried this based on a hunch that it might be a rare issue of whitespaces in paths.
I used a previous version (probably 0.9) on my system a year ago without any issues.

**Comment by kelson42** [comment]
@mkathuri Thank you very much for all your quick answer. I don't have any other question and we will have to wait the expertise of one of the developers. This might take a few months, just want to warn you. As a workaround, I recommend to download the ZIM files directly from:
* https://wiki.kiwix.org/wiki/Content_in_all_languages
* https://download.kiwix.org/zim

Hope this is an acceptable workaround for you. We will come back to you with additional questions or solutions as soon as we can. Thank you for your patience.

**Comment by kelson42** [comment]
@mkathuri We have found an other user in India with the same problem. An other question. If you launch from the command line kiwix-desktop, do you see other error in the terminal?

**Comment by mkathuri** [comment]
@kelson42 I face the same issues with command line launch.

**Comment by kelson42** [comment]
@mkathuri OK, but do you see something printed, like more information about the error occurring?

**Comment by mkathuri** [comment]
It immediately frees the console as soon as it is launched and shifts to the next prompt. Nothing is printed on the console.

**Comment by kelson42** [comment]
@mkathuri Thank you again for your feedbacks... We continue the investigation...

**Comment by nakeTuk** [comment]
I faced with exactly same problem. After version 0.9 only "2.0 alpha3" started correct.
Updated Win10.

**Comment by kelson42** [comment]
@mkathuri Thank you for coming back to us. Indeed aria2c has been introduced around that time and the app does not start because aria2c is not starting somehow properly. Do you have a custom firewall or similar running on your system which would avoid aria2c XML/RPC communication port to be open?

**Comment by mkathuri** [comment]
I tried the 2.0 rc3 build and alpha4 with firewall disabled. Still shows nothing.
@kelson42 Doesn't kiwix produce any log file(s) I can refer to (or submit it to you guys for inspection, if required)? Or any command-line switch to produce some debug logging on console?

**Comment by kelson42** [comment]
@mkathuri I have created #272 and it should be implemented next week. You would be then able to run a nightly build and hopefully we will then see the exact `aria2c.exe` command and see what goes wrong. Thank you again for keeping track on this ticket.

**Comment by pierrejn-git** [comment]
Hello, I have the same problem with 2.0 rc3 with Windows 10 1903, both with 3 different PC. The VC+ is installed. No kiwix window appears.

**Comment by kelson42** [comment]
@pierrejn-git @mkathuri Would you be able to try with the latest nightly build? https://download.kiwix.org/nightly/2019-11-04/kiwix-desktop_windows_x64_2019-11-04.zip. The `aria2c` command (the downloader) should be printed with the error dialog. Then please share it with us.

**Comment by mkathuri** [comment]
Hi @kelson42 , I tried running the new nightly build on my system, and it still doesn't work. Two things happen now:
- When I start kiwix-desktop.exe from command-line (cmd.exe into the current directory), it doesn't print anything on the console and immediately the next prompt is displayed.
- Of the two runs that I was able to test, a large window (probably the main program window) popped up after an average of 10 minutes and immediately vanished, before I could even see its contents. The error popup is now no longer showing, but kiwix-desktop still refuses to start.

Unfortunately, as of now, I'm no longer using Windows 10 as I need to do some development work for which I had to shift entirely to Arch Linux, so I will no longer be able to test this issue from here on.

**Comment by kelson42** [comment]
@mkathuri Thank you for your constant feedback on this, we will still try to fix it... but if we fail to find seomone with a reproduction case, might be challenging.

**Comment by niemand-deu** [comment]
My aria2c installation on Gentoo neither supports BitTorrent nor rpc. It crashes after five attempts failing to create a downloader with a segmentation fault.
I planned on using Kiwix with custom zim files, but it seems like it can't run fully offline yet due to the reliance on createDownloader running successfully.

**Comment by kelson42** [comment]
@niemand-deu Please open another ticket. This ticket is for Windows and you use Linux.

**Comment by yashendra2797** [comment]
Happening with me on rc4. Double clicking kiwix-desktop.exe does nothing. I can find the exe in Task Manager though.

**Comment by pierrejn-git** [comment]
Hello I had the same problem with the rc3 installer but now the rc4
unzip kiwix-desktop.exe is working first time!

Le 04/01/2020 à 19:10, Yashendra Shukla a écrit :

**Comment by kelson42** [comment]
Small feedback about this problem. We have no reproduction case at all and we don't know what goes wrong for the impacted users neither how to fix it (of course). We keep this ticket open in an attempt that at some point we better understand it.

**Comment by yashendra2797** [comment]
Damn. Any way I can help?

**Comment by kelson42** [comment]
@yashendra2797 Have you installed `vcredist.exe` properly? What is the output if you launch Kiwix from the terminal `cmd.exe`?

**Comment by JonathanCool** [comment]
I can reproduce the problem on my laptop.  Using Win10 home latest version ( with all updates from microsoft as of now ).  I noticed that my version of "VC Redistribuables" is much more recent then the ones from the kiwix package ( so it won't install the older version included ) My version is 14.20.27508.  I tried only rc3, rc4 and Beta5 which all failed, but after reading the comments here, I'll try the older Alpha3 to see if it works.  I can run test builts if needed.  I also tried running the program from the command-line and get the same results ( it shows nothing, returns immediatly to the command line like an empty program. )

**Comment by kelson42** [comment]
@JonathanCool Was just answering you per email to comment on this ticket :) Happy to see you have been even quicker. We are really interested to fix that bug, your help might be decisive.
@mgautierfr It seems we have a reproduction case of this mystery bug and by a developer wanting to help to identify & fix the root cause. It would be really much appreciated if you could give here any guidance needed. Maybe one approach here, would be to build the Windows CI git Github actions so @JonathanCool can see which commands are run to compile on Windows? (see #132)

**Comment by mgautierfr** [comment]
@JonathanCool, I've sent you a message on slack. I've you received it ?

**Comment by JonathanCool** [comment]
> @JonathanCool, I've sent you a message on slack. I've you received it ?

sorry, I was expecting an email notification if I got a message there so I didn't go check my messages. I got it now.

**Comment by kelson42** [comment]
@mgautierfr awesome

**Comment by mkathuri** [comment]
I'm back just in time to confirm the fix working with nightly build: https://download.kiwix.org/nightly/2020-02-08/kiwix-desktop_windows_x64_2020-02-08.zip

A minor annoyance, however is still visible in the form of an extra command line window: 
![image](https://user-images.githubusercontent.com/26147403/74096259-89bc1f00-4b22-11ea-9472-b32d3b8cf4d2.png)

Is this intended behavior? If not, is there any way to hide it?

Thank you once again for all your hard work. :)

**Comment by kelson42** [comment]
@JonathanCool Does the last nightly runs fine for you as well?

**Comment by JonathanCool** [comment]
I confirm it works.  I also see the same extra command-line Windows which is a minor annoyance for me but it should be fairly simple to hide it once it ran.  sometimes simply adding 'Exit' at the end of a script does the job, and if running MFC then you can find the Windows and sent it a 'HIDE_WINDOWS" message after it's creation if it needs to be there.

**Comment by JonathanCool** [comment]
When closing KIWIX-Desktop, the command-line window will briefly show "session saved" and immediatly close.  I assume that this window needs to be opened while kiwix is running, so this C++ command should hide it correctly : https://docs.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-showwindow?redirectedfrom=MSDN

**Comment by kelson42** [comment]
@JonathanCool @mkathuri I see there is a few (small) things left. I would recommend to open one or many other separate tickets to handle them. I'm concerned your feedback(s) might get lost otherwise.

**Comment by JonathanCool** [comment]
I created ISSUE #373 for this minor problem,  It does not stop the program from working well. 

Thank you for fixing this bug #268 which was much more important.

**Comment by yashendra2797** [comment]
> 
> 
> @JonathanCool @pierrejn-git yashendra2797 Does the last nightly runs fine for you as well?

Launches just fine. Facing #373, but at least this issue can be marked closed. Used 10 Feb 2020's nightly.
