### ISSUE TITLE
kiwix-desktop_windows_x64_2.0-alpha2 cannot open Zim file

### ISSUE THREAD

**Issue by gladteck** [kiwix/kiwix-desktop#27]
When Kiwix-Desktop starts I am prompted to locate a ZIM file and when i do I get this error: Cannot open C:/wikipedia_en_all_novid_2018-06(1).zim: Cannot convert path to wchar

**Comment by kelson42** [comment]
@gladteck Thank you for your bug report, @mgautierfr Do you have a glue what might happen here?

**Comment by kelson42** [comment]
I have a similar feedback here https://sourceforge.net/p/kiwix/discussion/604121/thread/9866779b/#51a0/2eb9/88a0/d196/1345

**Comment by kelson42** [comment]
Here a screenshot
![scr](https://user-images.githubusercontent.com/1029718/44703391-c5326d00-aa97-11e8-8b5d-ed41e00da94e.png)

**Comment by mgautierfr** [comment]
This is strange.
I can open a zim file in a Chinese directory without problem (`C:\Users\mgautier\Downloads\测试\wikisource_en_all_nopic_2018-03.zim`).
Your path doesn't use any "special" character, there should be no problem.

What is your system locale ? (Mine is French)
What is the ouput of the `dir` command in the cmd ?

This page may help somehow.
https://superuser.com/questions/1097217/determine-and-change-filename-encoding-on-windows

**Comment by mgautierfr** [comment]
Can you try with this version : http://download.kiwix.org/nightly/2018-08-28/kiwix-desktop_2018-08-28_issue27.zip ?
It rewrites a bit the way we convert the path to wchar, it may fix the issue.
If not, it will report the error code to help understand the problem.

**Comment by kelson42** [comment]
@mgautierfr I got a positive feedback regarding your fix from two different users. So I guess we can assume it works.

**Comment by gladteck** [comment]
With the help of the new revision in the way it converts the path to wchar , my zim file will now open! Great work! Thanks. http://download.kiwix.org/nightly/2018-08-28/kiwix-desktop_2018-08-28_issue27.zip

**Comment by kelson42** [comment]
:)
