### ISSUE TITLE
Stop Kiwix from creating vim files under AppData\Roaming

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#271]
Kiwix (kiwix-desktop_windows_x64_2.0-beta4) is keeping to create a vim file under AppData\Roaming that is the same name as the file that I opened in Kiwix. The created file is very huge but smaller than the original file which takes up space in C:. The original file is wikipedia_en_all_novid_2018-10.zim which is on another drive.

If that "shadow file " doesn't exist, Kiwix will create it using "aria2c.exe" in the folder of Kiwix when loading that file for the first time and aria2c.exe will write that huge file (50GB+) for several minutes.

If it already exists, sometimes Kiwix will download data from internet (with 98Mbps speed) and write to that file at 10MB/s+ and finally free space on C: is under 100MB and I found this problem. It seems that Kiwix is downloading some upgrade delta data for that vim file and store is in the shadow file. But where is Kiwix downloading from? There is no information of this downloading process at all in the UI, which makes it seem like a malware.

 Is this a bug or as designed? Is there a work around? Now I keep removing the "shadow file" to free up space in C: and Kiwix keeps recreating it.

**Comment by kelson42** [comment]
@wgt98 Thank you for your bug report. Could you please confirm the problem still occurs with the version 0.2rc3?

**Comment by kelson42** [comment]
@wgt98 any news?

**Comment by wgt98** [comment]
Seems fixed on 2.0rc3, and remembering last open/ctrl+scroll are all working now, so great. What a wasted of time to write the post.... Whether high speed updating/malware-looking problem is still there is not known since I block both exe's internet access at the first time.

**Comment by kelson42** [comment]
nice!
