### ISSUE TITLE
Autosize tab header

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#277]
Now the tab is of fixed width no matter how much text is in the title on the tab or how many tabs are there. The result is that the tabs fills all the screen width easily. Need the tab width to become shorter when there is too many tabs just like Chrome does, and even better if the tab can wrap the tab title text if the text is short.

**Comment by kelson42** [comment]
@wgt98 Im not sure I even understand the problem reported here. The ticket should be reprased to clearly explain it and the propose a solution.
