### ISSUE TITLE
New Tab Icon has two problems

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#282]
Problem 1
--------------

It is not positionned properly, it should be a few pixel left, so the margin is the same as of top and bottom.

![image](https://user-images.githubusercontent.com/1029718/68013641-bc39be80-fc8d-11e9-8057-c8cac2c7cdef.png)

Problem 2
--------------

When the mouse is over the background should change, probably to a lighter background or like the other button in the bar above.

**Comment by moadmmh** [comment]
I have downloaded Kiwix just few hours ago from the official Website (Ubuntu Desktop version) and i wanted just to add one thing here whenever i open a new window either by clicking on the button or ctrl+t it goes directly to my current page while it should give a new empty tab instead

**Comment by kelson42** [comment]
@moadmmh Please open a separate ticket.

**Comment by anshuldutt21** [comment]
Hi I would like to work on this issue.

**Comment by kelson42** [comment]
@anshuldutt21 You are welcome. Please open a PR when you are ready.

**Comment by anshuldutt21** [comment]
Hi actually I am facing a problem with the setup. After giving the command meson . build there was an error libzim not found. so I cloned the libzim repository, https://github.com/openzim/libzim. It worked but the next command (ninja -C build) fails saying that xapian.h file is missing. Can anyone please help me with this problem.

**Comment by kelson42** [comment]
@anshuldutt21 Have you read the README.md file?

**Comment by anshuldutt21** [comment]
Yes I am following the instructions of kiwix-lib where I met with this problem.

**Comment by kelson42** [comment]
@anshuldutt21 https://github.com/openzim/libzim/blob/master/README.md 

> The ZIM library relies on many third parts software libraries. They are prerequisites to the Kiwix library compilation. Following libraries need to be available:

>    Z (package zlib1g-dev on Ubuntu)
    LZMA (package lzma-dev on Ubuntu)
    ICU (package libicu-dev on Ubuntu)
    Xapian - optional (package libxapian-dev on Ubuntu)
    Google Test - optional (package googletest on Ubuntu)

**Comment by anshuldutt21** [comment]
Hi @kelson42 I am not able to find the xml file corresponding to the stye.css file in css folder. Can you please tell me where is it?

**Comment by kelson42** [comment]
@anshuldutt21 I'm not familiar wit the details how the app is built.

**Comment by jetownfeve21** [comment]
hi @anshuldutt21 !
Are you using the `kiwix-build` https://github.com/kiwix/kiwix-build command ?

**Comment by anshuldutt21** [comment]
Yes I used kiwix-build after which I used kiwix-desktop command to configure kiwix-desktop in laptop. I just cant find the xml  file for style.css file.

**Comment by jetownfeve21** [comment]
@anshuldutt21 There is a xml file which is the `mainwindow.ui` which is in `SOURCE/kiwix-desktop/ui/mainwindow.ui` but you will not be able to fix this issue this way.
Look at [this](https://forum.qt.io/topic/16924/set-backgroud-color-and-mouse-hover-highlighting-for-tabs-solved) for the background.
