### ISSUE TITLE
Where to get newest Wikipedia zim file

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#286]
There is no search result in Bing so I try to ask it here. In this link https://wiki.kiwix.org/wiki/Content_in_all_languages there is maxi for 2018-10, mini for 2019-9, nopic for 2019-10. 
Can I merge nopic-2019-10 and maxi-2018-10? What tool to use?
What is the best way to download the newest maxi database?

**Comment by kelson42** [comment]
We are making a new one.... but it takes time. Hopefully soon.

**Comment by wgt98** [comment]
Could there be a monthly update? Data availability is the same important as the tools for the goal of zim. Wikipedia has been blocked here for years - another reason for unreachable of Wikidpedia.
