### ISSUE TITLE
Search bar doens't search after copy/cut text from other programs

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#287]
Finally found the key: The problem only appear when:
(1) Be sure the cursor is in the search bar and is blinking, ready for input
(2) Switch to another program then switch back. When you switch back, be sure you click the item in Task Bar, not click the Kiwix UI, since if the cursor go away from the search bar, the problem will be fixed as described bellow.
(3) Continue to input in the search bar (not needed if the input is already completed before), then press enter or click the item in the live search drop down, now it won't show the selected page anymore,  whatever you continue to input and action.

The problem will disappear if you click other places in Kiwix like the page content and let the cursor go away from the search bar. Then when the focus goes back to the search bar again, the search bar will be cleared automatically , now the problem is fixed. If you do the above again, the problem will appear again. Seems that when focus go back to the search bar, some reinitialization code reset the corrupted status when you switch to another program while the focus is in the search bar.

If you click different tab headers while the focus is in the search bar, the problem won't be fixed since the focus is keeped in the search bar during this process. This also mean that the it is not the focus, but the reinitialization of the search bar that fix the problem.

**Comment by kelson42** [comment]
We need a concrete example, I strongly suspect this is uncorrelated with the amount of time the app is running.

**Comment by wgt98** [comment]
I'v edit the post, did you check it?

**Comment by kelson42** [comment]
@wgt98 I can not reproduce the problem. I guess you are simply coying other characters than juste "Dog" within your cut/paste.

**Comment by wgt98** [comment]
Dog is what I was using to try to make a reprodutable case. Now I'm still deal with this bug every day. I can't reopen it, can you reopen it and let's find the problem?

**Comment by kelson42** [comment]
@wgt98 Could you provide a screencast of the problem?

**Comment by wgt98** [comment]
Now there is new clues, please check the edited post above.

**Comment by kelson42** [comment]
@wgt98 I finally have been able to reproduce the problem (on Linux):
1 - Download the Wikimed ZIM file in English
2 - Open the ZIM file, welcome page of the ZIM should appear in the tab
3 - Type "heart" in the search box and ENTER
4 - Like expected the article "Heart" is directly opened
5 - Close the new tab created for "Heart" and come back to the ZIM main page (tab)
5 - Click again in the searbar and empty its content
6 - Open or switch to an other app
7 - Switch back to Kiwix (but without changing the focus within the Kiwix app, it should be kept withing the search bar)
8 - Type "heart" and ENTER
9 - Nothing happen, no article is open and no new tab is created

What we should get it:
- Like before the "Heart" article should be open in a new tab.
