### ISSUE TITLE
Full-text index for finding articles via search phrases

### ISSUE THREAD

**Issue by gcast20** [kiwix/kiwix-desktop#29]
When there is no wikipedia article on a subject, the wikipedia may still contain articles with information on the subject - an index that covers a wikipedia's full text would make it possible to identify such articles via appropriate search terms and search phrases. E.g., in kiwix 0.9 (Windows) it is possible to find information on a person for whom there is no article in the wikipedia, by entering their "first name last name" in quotation marks and any articles with the exact search phrase are then listed in the result window

**Comment by kelson42** [comment]
@gcast20 This is the fulltext search that you describe here, it runs each time you search something which is not directly available! How what you request is different from the fulltext search?

**Comment by gcast20** [comment]
@kelson42, sorry for the delay..
thanks for the hint: indeed, fulltext search, to the extent that it gives back a disambiguation term near the top of the search list, is a / can be a solution. I've tested the original case "Berlin" in the German wikipedia (wikipedia_de_all_maxi_2021-03.zim) and the latest version of kiwix for Windows (kiwix-desktop_windows_x64_2.0.5) and the fulltext search results yield the disambiguation page "Berlin (Begriffsklärung)" as the second hit, on which (of course/hopefully) the article on the city of Berlin appears at the very top. If the idea is to look for the disambiguation page of "overcrowded terms" like "Berlin" in the German wikipedia, the disambiguation page can be found more quickly by entering "Berlin Beg" - the index search immediately returns it at the top - the "Beg", though, is of course language dependent..

**Comment by kelson42** [comment]
I belive you are still talking about suggestions. The fulltext search is the page appearing when you type "Berlin" and click on the item "Berlin (Fulltext search)". "Berlin" is a term for which there is an article with the exact same name, so this does not match your first comment where you write "When there is no wikipedia article on a subject".

Maybe it is easier you just write a concrete example with:
* What you do
* What you get
* What you expect

**Comment by gcast20** [comment]
@kelson42 Indeed, sorry.. Had forgotten about the issue started on Aug 29, 2018.. 
What I do: I enter the name (that is, first name, last name, e.g. Tilly Grosser) of a person in kiwix in quotation marks or without
What I get: a full-text list of (possibly many) articles that contain the first name and/or the last name (typically only one in bold, by the way) but don't necessarily mention the very person
What I expect: besides articles that might mention either the first or second name also articles that mention both, and particularly that mention "Tilly Grosser" herself. In the German zim-file (wikipedia_de_all_maxi_2021-03.zim) that doesn't work - in this example, at least, but in the English zim-file (wikipedia_en_all_maxi_2020-09.zim) - the article on "Viktor Frankl", that I was looking for, appears near the top..

**Comment by kelson42** [comment]
@gcast20 Thx. The answer is: this is theoritically possible and even easy, but we don't provide this feature because this would imply to save for each word in the documents there position. The fulltext index would be significantly bigger and we have decided to better don't save the position of word. So, I guess this ticket will be unfortunately "WONT FIX".
