### ISSUE TITLE
"View Page Source" is broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#290]
It displays an empty tab. I propose to remove this feature.

**Comment by jetownfeve21** [comment]
@kelson42 
I cannot reproduce this issue, it doesn't work for all pages ?

**Comment by kelson42** [comment]
I can not find any ZIM file, any article which works for me with git master HEAD

![image](https://user-images.githubusercontent.com/1029718/68225671-1372c280-fff1-11e9-93f6-d527ea7514d1.png)

**Comment by jetownfeve21** [comment]
I don't have any issues with the master branch :(

**Comment by kelson42** [comment]
@jetownfeve21 I don't really see any added value for this anyway. I think we should simply remove it.
