### ISSUE TITLE
Unable to open Kiwix file

### ISSUE THREAD

**Issue by mohmad-null** [kiwix/kiwix-desktop#291]
Hi,
Using windows Kiwix 0.9, I downloaded a new file and it doesn't open. Yes your FAQ says that I should use 2.0 (and it does open in 2.0), but 2.0 is unusable! It has none of the features in 0.9, I can't even search with it!
Therefore I consider this a bug. You've created zim files that are not backwards compatible while the replacement is completely different and simply doesn't work.
2.0 is so different from 0.9 it should frankly be a different project that happens to read zim files.

**Comment by kelson42** [comment]
Thank you for your feedback. Kiwix 0.9 is not maintained. Old and new ZIM file should be open with Kiwix 2.0. If you have a specific problem please open a ticket in this repo. Here is the documentation about how to make a good bug report https://github.com/kiwix/overview/blob/master/REPORT_BUG.md
