### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by mohmad-null** [kiwix/kiwix-desktop#292]
So I was forced to upgrade to kiwix 2 because 0.9 can't open new files. :-(
Except I can't even search with it. I open wiki nopic, and type "lemon".
Bugs:
1) It takes about 5 seconds to get from the l to the e while my HDD thrashes around.
2) None of the results in the drop-down (about 3 of them) are for lemon. They're all something else.
3) If I press the magnifiying glass (what I presume to be search) it doesn't actually do anything.
4) Pressing Enter doesn't do anything either.

What is the point of a reader if you can't even get to files?

The last version of kiwix is so much better (and no, I'm not some die-hard old-skool user. I've not used kiwix in years (and then barely did), I just happen to have both of them in front of them and it's night and day).

**Comment by jetownfeve21** [comment]
@mohmad-null Can you share some screenshots please ?

**Comment by kelson42** [comment]
@mohmad-null This ticket talks for so many different things an we don't even have the content details, the kiwix version details, ... Please open one ticket per problem and explain clearly what is the problem an what you expect. We can not deal with such an unclear bug report.

**Comment by kelson42** [comment]
I close that one, really too fuzzy.
