### ISSUE TITLE
Doesn't remember a file

### ISSUE THREAD

**Issue by mohmad-null** [kiwix/kiwix-desktop#293]
2.0, windows. I add a file, do my stuff (well try to, 2.0 is unusable), close it, and re-open 2.0.
It doesn't remember the file.

**Comment by mohmad-null** [comment]
Nor does it even remember which directory I was in previously

**Comment by kelson42** [comment]
> Nor does it even remember which directory I was in previously

What do you mean exactly with "directory"? Do you have a step-by-step procedure explaining what you mean?

**Comment by jetownfeve21** [comment]
@mohmad-null Can you give us the specific file you used to allow us to better understand what happened

**Comment by kelson42** [comment]
@mohmad-null Without your help to better understanf your bug report, I will close this ticket.

**Comment by kelson42** [comment]
@mohmad-null No feedback, so I close the ticket. Might be a duplicate of #300, who knows!
