### ISSUE TITLE
Poor user interface

### ISSUE THREAD

**Issue by mohmad-null** [kiwix/kiwix-desktop#295]
The 2.0 interface (windows) makes no sense.
What are the glasses for?
Why does the search magnifiying glass turn into those glasses randomly?
Why does clicking those glasses turn them black? Nothing seems to have changed.
Where are the tooltips?
Why is something people are going to want to use rarely (finding new databases) so easy to find and use, yet something people are going to use commonly (zoom, random article) hidden under 3 clicks in the menu?

As a software developer myself, this is an alpha, there's no way it's an RC for a major release.

**Comment by kelson42** [comment]
thank you for your feedback.
