### ISSUE TITLE
Don't open an article twice in different tabs

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#296]
Steps:
* Open a ZIM
* Right click on link to A on the welcome page to open it in a new tab
* Right click on link to A on the welcome page to open it in a new tab

What you get:
2 tabs with the same article A.

What I want:
1 tab with the same article A (no duplicate in tabs)

**Comment by jetownfeve21** [comment]
I don't think that we should prevent duplicates, it can be usefull to have an article opened twice for example those that are very long, if the user doesn't want to scroll every time between different places of the same article he can open the article as many time as he wants.
Chrome and Firefox don't prevent the opening of the same page too.

**Comment by kelson42** [comment]
@jetownfeve21 You are 100% right.
