### ISSUE TITLE
Translate Kiwix Desktop 2.0 with Translatewiki

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#299]
Translatewiki should:
* load english master (bot)
* translate the strings in local languages (community)
* commit the translation in this repo (bot)

**Comment by kelson42** [comment]
@translatewiki The documentation about Qt i18n is available here https://doc.qt.io/qt-5/linguist-translators.html

**Comment by kelson42** [comment]
I reopen the ticket as we need to secure that these repo is properly read/written by @translatewiki. @Nikerabbit @Abijeet Would you be able to secure this?

**Comment by kelson42** [comment]
@translatewiki. @Nikerabbit @Abijeet  Would you please be able to configure the Translatewiki bot to import/export strings? Do I need to open a ticket somewhere else?

**Comment by Abijeet** [comment]
Hi @kelson42 - We've created a ticket on Phabricator to track the addition of this project to Translatewiki - https://phabricator.wikimedia.org/T251483

We should be able to finish this before the end of this week. Can you ensure that the translatewiki bot has read / write permissions to this repo?

**Comment by kelson42** [comment]
@Abijeet Thank you. @translatewiki is part of the "Kiwix" Github organization and should have write access to all our repositories. I have as well sent an invitation to the "OpenZIM" organization as we will have to sync other repositories there as well.

**Comment by Abijeet** [comment]
@kelson42 - The changes have been deployed. We're tracking the `master`, and pushing translations to the `translatewiki` branch. We've recently added functionality to create and submit a PR. Would you like to enable this for the Andorid and Desktop repositories?

Secondly, I would recommend adding some [message documentation](https://translatewiki.net/wiki/Translating:Localisation_for_developers#Message_documentation) to make it easier for translators. You can do that from here - https://translatewiki.net/wiki/Special:Translate?action=translate&group=kiwix-desktop&language=qqq&filter=

**Comment by Abijeet** [comment]
Changes pushed here - https://github.com/kiwix/kiwix-desktop/commit/c224a38be1b099222bfeb067051248cfe857382b

**Comment by kelson42** [comment]
@Abijeet Thank you very much, so far to me it looks good. I let the expert @mgautierfr @jetownfeve21 to review the PR I created based on the `translatewiki` branch.

**Comment by mgautierfr** [comment]
> Would you like to enable this for the Andorid and Desktop repositories?

Yes please. It would be nice to have PR created atomically.

**Comment by kelson42** [comment]
We need to be aware that this might create a PR two times a week! This might be a bit much.

**Comment by Abijeet** [comment]
> We need to be aware that this might create a PR two times a week! This might be a bit much.

If you don't merge the previous PR, the existing PR will be updated with the latest changes.

**Comment by kelson42** [comment]
@Abijeet Then this sounds really good to me, you can rollout it on Kiwix-Android and Kiwix-Desktop. Nice step forward which simplify the life of everybody.
