### ISSUE TITLE
Can't remember previous opened file

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#300]
I just moved both kiwix-desktop_windows_x64_2.0-rc3 and wikipedia_en_all_novid_2018-10.zim from another drive to C:, now kiwix can't remember files that I opened. The history list is always blank. Change zim file name or create symbol link from other drive to folder that contains the zim in C: doesn't work.

**Comment by kelson42** [comment]
@wgt98 What do you mean exactly with "can't remember"? Could you please provide step by step procedure with result and expecting result?

**Comment by wgt98** [comment]
Before when I opened kiwix-desktop_windows_x64_2.0-rc3, it will show the zim files I used before in a list in the first UI page. Then I can just click the file. Now the list is alwasy blank, I have to use menu to browse to open the file. 

This is hard to reproduce, all this happens after I move kiwix and the zim both to C:.

**Comment by kelson42** [comment]
@wgt98 Ok, will try to reproduce.

**Comment by wgt98** [comment]
Have you checked my edited bug report https://github.com/kiwix/kiwix-desktop/issues/287?

**Comment by wgt98** [comment]
Now I rebooted the computer and still can't remember. Move kiwix/zim to drive D: still not working. Maybe has something to do with registry. Need a way to reset everything about kiwix.

**Comment by kelson42** [comment]
@wgt98 Everything should be in `C:\Users\<your_user_name>\AppData\Roaming`, if you delete that directory, then all the settings of Kiwix Desktop should be reset.

**Comment by kelson42** [comment]
I confirm the bug, here is a clear reproduction case:
1 - Download https://download.kiwix.org/zim/other/skin-of-color-society_en_all_2019-11.zim
2 - Launch Kiwix Desktop rc3 for Windows
3 - Open manually `skin-of-color-society_en_all_2019-11.zim` from where you have saved it
4 - File opens properly
5 - Quit Kiwix
6 - Relaunch Kiwix and you see the `skin-of-color-society_en_all_2019-11.zim` in the local library. So far so good.
7 - Quite Kiwix
8 - Rename `skin-of-color-society_en_all_2019-11.zim` to `skin-of-color-society_en_all_2019-11_new.zim`
9 - Relaunch Kiwix and `skin-of-color-society_en_all_2019-11.zim` has disappeared from the local library which seems to me to make sense
10 - Open `skin-of-color-society_en_all_2019-11_new.zim` manually 
11 - File opens properly
12 - Quite Kiwix
13 - Relaunch Kiwix and the local library is empty

.... We should see `skin-of-color-society_en_all_2019-11_new.zim` in the local library

**Comment by wgt98** [comment]
The only thing in C:\Users\<your_user_name>\AppData\Roaming is kiwix.session. Deleting that can't solve the problem. There seems to be states save to other places. There seems to be no data in registry.

**Comment by kelson42** [comment]
@jetownfeve21 Where is the local library backuped on Windows?

**Comment by jetownfeve21** [comment]
@kelson42  The library path is displayed if the app is launched from a terminal

**Comment by wgt98** [comment]
@jetownfeve21 There is no output when invoked from Win10 command line.

**Comment by wgt98** [comment]
Now my kiwix-desktop_windows_x64_2.0-rc3 somehow can remember moved previous opened file again...

**Comment by jetownfeve21** [comment]
I found the problem but I'd rather talk to @mgautierfr  about it before correcting it.
