### ISSUE TITLE
Opening an article from the reading list closes it

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#302]
Why? I don't think it should.

**Comment by jetownfeve21** [comment]
What is the purpose of keeping the reading list open ? Unless the user wants to open many zim from his reading list, most of the time he will have to close it manually I think

**Comment by kelson42** [comment]
@jetownfeve21 You have a point, but this is not how the bookmark bar works with Firefox (it keeps open). Yes it will have to close it or use a keyboard shortcust.
