### ISSUE TITLE
Donate shortcut is wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#303]
It is `Ctrl+<,3` and it should be `Ctrl+<+3`

See https://www.dropbox.com/sh/p621jd89x1c6hpi/AAB3whrF3DoJZqZTJ535gPr0a/02-exports?dl=0&preview=menu-02%402x.png&subfolder_nav_tracking=1 for reference

**Comment by jetownfeve21** [comment]
@kelson42 
I try to display `Ctrl+<+3` instead of `Ctrl+<,3` but Qt doesn't seem to handle this correctly. Depending on how I try to do it, it displays nothing at all, a wrong shortcut (`Ctrl+O`), or "home page". The best I can have is `Ctrl+<,3` or `Ctrl+,<,3`

**Comment by kelson42** [comment]
@jetownfeve21 Then please use an easier shortcut. Would `Ctrl+D` work?

**Comment by jetownfeve21** [comment]
@kelson42 yes it works, should I implement it ?

**Comment by kelson42** [comment]
@jetownfeve21 yes please
