### ISSUE TITLE
Incoherences around Fullscreen/Un-fullscreen on Linux

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#304]
The shorcuts are partly wrong:
* On Windows this is OK with `F11`
* On Linux this is NOK with `CTRL + F11`, it should be only `F11` like on Firefox and Chrome

What is displayed as shortcut in the menu items:
* On Windows this is OK, we see `F11`
* On Linux this is NOK, we see `Ctrl + F11` it should be `F11`

**Comment by jetownfeve21** [comment]
For this shortcut we use the standard keyboard shortcut defined by Qt :
```
    SET_SHORTCUT(ToggleFullscreenAction, QKeySequence::FullScreen);

```
Here is the doc https://doc.qt.io/qt-5/qkeysequence.html
Indeed depending on the OS the shortcut is not the same

**Comment by kelson42** [comment]
@jetownfeve21 If Qt is buggy, please make a bug report at Qt level.

**Comment by jetownfeve21** [comment]
It's not a bug, for a lot of actions the shortcut is different depending on the OS

**Comment by kelson42** [comment]
@jetownfeve21 My ticket does not complain that they are different, please read it again.

**Comment by soloturn** [comment]
@kelson42 i think this currently works correctly. i set the gnome keyboard shortcut in gnome settings to f11 then f11 would fullscreen it. this works for all QT applications.

if this is not set at all in gnome settings, the default, gnome applications have no full screen. some kde applications react to ctrl-shift-f, qt applications do nothing or react to ctrl-f11. inconsistent, bref.

i did not see where the shortcut key is displayd in kiwix-desktop though ...

**Comment by kelson42** [comment]
@soloturn @jetownfeve21 It is not different for Firefox (and Chrome), whatever the OS, why Kiwix should do things differently?

**Comment by mgautierfr** [comment]
This not behave differently.
If the "toggle fullscreen" shortcut is not set at system level. Application use a default shortcut. For Firefox this is `F11`, for Qt it is `Ctrl+F11`. If you set a shortcut (I've tried with `F3`), both use the defined shortcut instead of the default one.
It is a pity that Qt decides to use a different shortcut for linux but that is.

If we force a specific shortcut on kiwix-desktop side, a user would not be able to set the shortcut.

**Comment by suterma** [comment]
Sorry to be a necromancer here, but as a first time user, I feel the urge to comment on behalf of the possibly many other first-time users:

I never have been using anything else than F11 to toggle fullscreen, both on Windows and Ubuntu, for both of Firefox and Chrome. While it may be technically true that the established default for Qt-Apps is CTRL-F11, as a user this is not relevant to me. I'll try to what I am used to, and if it is not working I feel that it is broken.

So, from a UX perspective, I strongly recommend to set it to F11 only, even at the cost of overriding some customized system behavior.

**Comment by mgautierfr** [comment]
I'm sorry but we will not change this.

> even at the cost of overriding some customized system behavior.

And then all users whom use something else than `F11` will complain.

If you what to use all the time `F11`, go in your desktop environment setting and set the fullscreen shortcut to `F11`. All application will (or should) use it.
