### ISSUE TITLE
On Windows menu is not visible if in fullscreen

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#305]
Steps to reproduce:
* Get the rc3 for Windows
* Launch Kiwix Desktop for Windows
* Click on the Fullscreen icon (or F11)
* Click on the 3-dots icon
* Nothing happens

I should see the corresponding menu appearing. If I leave the fullscreen mode, then it works again.

**Comment by soloturn** [comment]
for current master, on X this is also weird. click on the three dots, the menu appears. then one can move the kiwix window around, and the menu stays where it is. on wayland this is more subtle. when clicking quickly sometimes it opens out of position, but in normally it is correct. 

there is a relation to this one https://bugreports.qt.io/browse/QTBUG-68636 ? and the comment "Make sure widgets have sensible transientParents, and Qt Wayland will happily use that."

**Comment by jetownfeve21** [comment]
This is a known bug referred [here](https://bugreports.qt.io/browse/QTBUG-7556)
A solution provided by Qt is to use [this](https://doc.qt.io/qt-5/qwindowswindowfunctions.html#setHasBorderInFullScreen)

**Comment by kelson42** [comment]
@jetownfeve21 Then we should implement the Qt solution I guess :) ?

**Comment by jetownfeve21** [comment]
Yes, it was for me to avoid losing the links
