### ISSUE TITLE
Search + open article should not open a new tab

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#307]
It should open the article in the current tab.

**Comment by kelson42** [comment]
@mgautierfr What exactly lead you to think that we should do open a new tab?

**Comment by kelson42** [comment]
@Popolechien Your feedback would be welcome here.

**Comment by Popolechien** [comment]
I have no strong opinion either way, but if there's multizim search enabled I would find it cool to be able to read or hear about one topic, search and find more info without losing my inital reading (example use case: listening to a TED talk and suddenly wanting to check a corresponding Wikipedia article on neurology).

**Comment by kelson42** [comment]
@Popolechien You don't have to loose your old stuff. You just do like in a browser, you open a new tab and to your search.

**Comment by Popolechien** [comment]
@Kelson - same difference, yes. I don't know what the conventional design wisdom about this is. Maybe Abbey or Robin would know?

**Comment by kelson42** [comment]
> @Kelson - same difference, yes. I don't know what the conventional design wisdom about this is. Maybe Abbey or Robin would know?

@schoenbaechler ?

**Comment by kelson42** [comment]
I have merged the PR as I'm confident this is the right thing to do. Please reopen the ticket if we have new facts.
