### ISSUE TITLE
Ubuntu filepicker is really too primitive

### ISSUE THREAD

**Issue by genericnerd99** [kiwix/kiwix-desktop#31]
Ubuntu running Alpha 3 - when opening file, there is no way to select a network or USB drive
Windows running Alpha 3 - perfect thank you!

**Comment by genericnerd99** [comment]
hey @kelson42 "disk" shows up for my microsd card, nothing else for network drives
if i manually type the path /media/$USER/disk/zim file - it works! so i think its just the visual navigation
thanks

**Comment by kelson42** [comment]
I have renamed the issue and I confirm it. I think something similar is reported here (@genericnerd99 please confirm).

Basically we get this:
![3foup](https://user-images.githubusercontent.com/1029718/45491428-fda99a80-b769-11e8-8845-34c151bc325b.png)

... and we want this:
![b3muh](https://user-images.githubusercontent.com/1029718/45491438-04d0a880-b76a-11e8-8ca1-35b97d0c0bc7.png)

with, like reported first but not visible in the example screenshot, and easy and direct access to both network drives and external devices.

**Comment by genericnerd99** [comment]
BINGO! thank you

**Comment by mgautierfr** [comment]
This seems to be a problem related to the appimage.
Inside a appimage, Qt use a "wrong" file selector.
When using directly the binary, the right file selector is used.

**Comment by kelson42** [comment]
@mgautierfr Interesting... maybe a problem fixed if we moved to Flatpack?

**Comment by kelson42** [comment]
@mgautierfr Yes, it is :) Let's publish Kiwix Desktop on Flathub to get a one click install!

**Comment by kelson42** [comment]
See #88 for the Flathub publication
