### ISSUE TITLE
Youtube video player displays a control which is not actionable

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#310]
See:
![image](https://user-images.githubusercontent.com/1029718/69592924-cc785b80-0ff7-11ea-9656-a099bac83564.png)

What is strange is that this control is not displayed at all on the kiwix-serve based version library.kiwix.org/skin-of-color-society_en_all (you have to play the video)

**Comment by kelson42** [comment]
@rgaudin Maybe the explanation is on the ZIM side?

**Comment by rgaudin** [comment]
Icon makes me think it's a Picture-in-Picture feature. I don't think it appears on any other platforms we tested but I remember seeing it there.

I think we should try to disable it. Doc is not clear but looking at [spec](https://w3c.github.io/picture-in-picture/), adding `disablePictureInPicture` to the video element should disable it. Will have to test it to confirm.
