### ISSUE TITLE
Characters unreadables when browsing for a new zim

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#313]
Just see the picture:
![caractere_illisibles](https://user-images.githubusercontent.com/19690477/69775246-2a2ab600-1166-11ea-93a1-2d7d1d870df9.png)

**Comment by kelson42** [comment]
@LAfricain It happened that I had this problem as weel, but only with the dev/self-compiled version and a reboot of the OS has solved the problem. Same for you?

**Comment by LAfricain** [comment]
>a reboot of the OS has solved the problem

Nope!

**Comment by kelson42** [comment]
@LAfricain Do you have the problem with our Flatpak/Flathub version or a self-compiled version or something else?

**Comment by LAfricain** [comment]
With the version on the ppa build with the sources.

**Comment by kelson42** [comment]
@LAfricain Obviously, we don't provide support for the packaging part you have created. But if the problem occurs as well with a fresh compiled version based on git HEAD, then please provide a step-by-step procedure with all the details about the environment so we get a chance to reproduce the problem?

**Comment by LAfricain** [comment]
I don't think the problem come from the package of the ppa, it's only a compiling process, if I install in on my OS with your source I do exactly the same. Now I can try to do an update with the git HEAD.

**Comment by kelson42** [comment]
I'm really sure this is environment problem and not due to a bug in Kiwix Desktop. Unfortunately none of us can help you more on this.

**Comment by LAfricain** [comment]
I'm sorry to write again in a closed bug, but I have still this problem with the last release. I think I have a problem with some fonts kiwix can't read, or my system? libaria?

**Comment by mgautierfr** [comment]
Do you have the issue with the kiwix-desktop we are building (flatpack/appimage) ?

**Comment by LAfricain** [comment]
No with the kiwix I pushed on my ppa with the last commits. With the appimage I have an other windows, not beautiful, but yes the characters are okay with the appimage.
Do you know why I have this different windows?

**Comment by mgautierfr** [comment]
The appimage embed its own Qt. Depending of your system, it may fail to find "something" and fallback to another fileselector window. It is pretty difficult to debug as everything is on the Qt side.
