### ISSUE TITLE
Add the reading of pdf in kiwix-desktop

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#317]
Currently a pdf in a zim (in apersonnal zim for this example), when you try to read a pdf, Kiwix-desktop propose only to download it. 
What is expected is the possibility to read it directly with the default reader, or with some tools in Kiwix.

**Comment by kelson42** [comment]
We can not do this and we won't. Kiwix is a ZIM (HTML) reader, not more.

**Comment by LAfricain** [comment]
>Kiwix is a ZIM (HTML) reader, not more.

Yes I know, but all web browser read pdf, and currently  it's just to open it with the default reader rather the file browser? it's so difficult?

**Comment by kelson42** [comment]
Yes, it is not straight.

**Comment by cjohnsto-nz** [comment]
I would like to reopen this. Kiwix JS opens PDFs in an external reader. Why can't Kiwix Desktop do this?

**Comment by kelson42** [comment]
@cjohnsto-nz please open a new ticket if opening of pdf in external app does not work properly.
