### ISSUE TITLE
kiwix server does not fork

### ISSUE THREAD

**Issue by Boruch-Baum** [kiwix/kiwix-desktop#321]
When using the linux appimage for kiwix 2.0-rc4, starting the 'local kiwix server' works only as long as the kiwix desktop gui window is open. It should fork to a separate background process and persist after closing the desktop instance.

**Comment by kelson42** [comment]
@Boruch-Baum I disagree with that. If you want to have a standalone kiwix-serve. Please use `kiwix-serve` separately. It's distributed as part of the Kiwix Tools https://download.kiwix.org/release/kiwix-tools/

**Comment by Boruch-Baum** [comment]
If so, then why have the option to launch a server from within the desktop GUI?
