### ISSUE TITLE
Kiwix serve IP address is not configurable

### ISSUE THREAD

**Issue by Boruch-Baum** [kiwix/kiwix-desktop#322]
Using the linx appimage version of kiwix 2.0 rc4, the port for the kiwix server can be configured, but not the IP address. I noticed this because I was evaluating the version on a machine with multiple network connections (ethernet and wifi). I was expecting the default to be localhost on 127.0.0.1, which would be the correct default security-concsious setting to not open the port. As it stands, kiwix (arbitrarily?) chose one of the network-facing routes.

Further, in my case kiwix chose a route that was physically disconnected at the time, so because there is no way alter the default, the server is useless on my local network.

**Comment by kelson42** [comment]
@Boruch-Baum Or it should listen on all interfaces/IPs?

**Comment by Boruch-Baum** [comment]
I've never heard of other servers behaving that way, and I don't know what implications there might be to doing that. Whatever you choose to do, let it respect the privacy and security of the user.

**Comment by kelson42** [comment]
@Boruch-Baum At least, that problem is not a regression in comparison with Kiwix Desktop 1.0 if I understand properly :)

**Comment by Boruch-Baum** [comment]
Having the server on 127.0.0.1 is useful for two cases:

1) people who don't want the kiwix desktop window open, and prefer using their web browser. BTW, using the web interface, one gets back the ability to invert colors, and one has access to other browser plug-ins for kiwix content.

2) Multi-user systems. You may be primarily focused on personal work-stations such as laptops, but linux is designed as a multi-user OS, so a single linux instance could be serving any number of kiwix users on localhost.

**Comment by Boruch-Baum** [comment]
My environment uses a very slightly hacked version of the old kiwix 0.9 for linux, and the kiwix server defaults to 127.0.0.1, so prior versions of kiwix *did* default there. I have an init script (thank you, SysV init) that launches the daemon at boot, setting only the port:
```
pgrep -a kiwix
$ 1132 kiwix-serve --port 8000 --library --daemon /media/Data/kiwix/library/library.xml
```

**Comment by kelson42** [comment]
This is more a feature request than a bug.

**Comment by kelson42** [comment]
Once https://github.com/kiwix/libkiwix/issues/613 is fixed (in the next days), it should be easy to implement an IP chooser at kiwix-desktop level.

**Comment by kelson42** [comment]
@mgautierfr @juuz0 I propose to solve this with:
* A port text/number input in the kiwix-serve dialog… and remove the port setting ins the general settings panel.
* Provide a selectbox based on the list of IPs provided by the libkiwix

… and this would replace the read-only string we propose currently. Does that sounds a good solution?

**Comment by juuz0** [comment]
@kelson42 Fine with me 
Though I thought we are listening to all interfaces (hence 127.0.0.1 should work fine too) so providing the best IP was enough. Or is this changing now that only the IP chosen by user should be listened (?) 

> Provide a selectbox based on the list of IPs provided by the libkiwix

This will require little changes in https://github.com/kiwix/libkiwix/issues/613 - getAllNetworkInterfaces() is private right now

**Comment by kelson42** [comment]
We should definitly have an option toblisten to all interfaces/ips... so 0.0.0.0... andbues we should nake this method/function public.
