### ISSUE TITLE
Create an Installer for Windows (msi or exe)

### ISSUE THREAD

**Issue by amirrammari** [kiwix/kiwix-desktop#323]
Hello, Kiwix desktop is a portable app.
Please create an installer for Windows (MSI or EXE)
Thanks.

**Comment by kelson42** [comment]
@amirrammari Is that not a duplicate of  #314 ?

**Comment by amirrammari** [comment]
#314 is the package for Windows 10 (`.AppX` `.AppxBundle` `.Msix` `.MsixBundle` `.MsixUpload` `.AppxUpload` `.XAP`)
I need an installer for windows 7 (.MSI or .EXE)

**Comment by kelson42** [comment]
As far as I know the installation process on Windows7 is not different from Windows10

**Comment by amirrammari** [comment]
Ok, I will close this issue.

**Comment by amirrammari** [comment]
Ok, you can close this issue.
