### ISSUE TITLE
Cancel "Find in page" highlighting

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#325]
Now when search in a loaded page, the searched key word will be highlighted, but there is no way to remove the highlights. Maybe there need to be a difference between hide-search-window and cancel-search-clear-highlights.

**Comment by kelson42** [comment]
@wgt98 I don't think we have any regression here. But "yes" clicking on the article should unselect the selected words in the page. For the rest I have the feeling it works properly (like in a browser).

**Comment by wgt98** [comment]
“clicking on the article should unselect the selected words in the page” why? It is hiding the search window that should clear the highlights. Considering Kiwix's search window is a pane which occupy a lot of space instead of a small floating window like in Chrome, the highlights can be keeped while hiding the search window, but there need to be another way to clear the search like provide a clear button in the search window which hide the search window and clear highlights.

**Comment by kelson42** [comment]
@wgt98 We won't rethink that feature. It should work like in Firefox and Chrome. If I have missed a way to cancel the "fin in page", please let me know which one.

**Comment by kelson42** [comment]
>  Considering Kiwix's search window is a pane which occupy a lot of space instead of a small floating window like in Chrome

I agree with that, I have open a dedicated ticket. See #327

**Comment by wgt98** [comment]
Why that is not a problem? In Chrome, you find something, it is highlighted. Then you ESC to cancel the search, highlights are removed. But in Kiwix, when you ctrl+F to hide the search pane, highlights are still there, the only way to clear highlight is to search a non-empty keyword that doesn't exist. BTW there seems to be no refresh function for now?

**Comment by kelson42** [comment]
* CTRL-F should not hide the search page (like in FF and Chrome)
* ESC should hide and deselect
