### ISSUE TITLE
Open in a new tab does not work fine with external links

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#326]
On my Windows 10 with kiwix-desktop_windows_x64_2.0-rc3, when ctrl+clicking an external url in a page, Kiwix opens an empty tab then Chrome(the default system url opener) is started for that url.

**Comment by kelson42** [comment]
@wgt98 I can not reproduce start problem neither on my Windows10 nor on my Linux. A screencast would be helpful probably. What is your version of Kiwix Desktop?

**Comment by wgt98** [comment]
I'v updated the problem, it should be ctrl+click.

**Comment by kelson42** [comment]
@wgt98 Yes, double click as well. All these action, if external link should not create a new empty tab. It should work like for a normal link.

**Comment by kelson42** [comment]
@jetownfeve21 What is the status here?

**Comment by jetownfeve21** [comment]
@kelson42 I asked for help on the #qtwebengine IRC channel and also  on Qt's forum but no answers for the moment.
https://forum.qt.io/topic/111151/how-to-intercept-ctrl-click-on-external-links

**Comment by kelson42** [comment]
@jetownfeve21 I reopen this ticket as this still fails to me. On the top of the that the context menu entry. It is written "Open link in new tab" and it should be written "Open link in Web browser".
