### ISSUE TITLE
Remove "Reload" context menu

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#328]
I don't see any value to it. Just make things more complex. I want to have it removed.

![image](https://user-images.githubusercontent.com/1029718/70388015-a9ad5600-19ac-11ea-8041-df881d16d7dc.png)

**Comment by iamprayush** [comment]
Hi, I'm new here and I'd like to help out. Can I get some guidance as to where to start?

**Comment by jetownfeve21** [comment]
@iamprayush Can you compile and run kiwix-desktop on your computer ?

**Comment by iamprayush** [comment]
@jetownfeve21 yes, I've done the setup. I just need some direction towards the starting point in the codebase. Where should I be looking to make the changes?

**Comment by jetownfeve21** [comment]
@iamprayush look at this PR
https://github.com/kiwix/kiwix-desktop/pull/306

**Comment by kelson42** [comment]
@iamprayush Any news?

**Comment by iamprayush** [comment]
@kelson42 Apologies for taking so long but I can't seem to find where this Reload button is implemented. A little guidance would be helpful.

**Comment by jetownfeve21** [comment]
@iamprayush it is implemented by Qt itself, you can't find it in our code

**Comment by larrytal** [comment]
Can I help with this? @kelson42 @iamprayush @jetownfeve21

**Comment by iamprayush** [comment]
@larrytal I haven't been able to figure out how to make the change. You can go ahead and take over if you like.

**Comment by kelson42** [comment]
@larrytal Yes, you can. Might not be the easiest start...
