### ISSUE TITLE
Closing a page auto scrolls the page on the right to top

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#329]
Suppose tab1 with page1 and tab2 with page2. Tab2 is on the right of Tab1, when closing page1, page 2 is auto scrolled to the top. Page 2 should have keep its scroll state.

**Comment by kelson42** [comment]
@wgt98 Good catch. I confirm.

**Comment by wgt98** [comment]
@kelson42 I found that Kiwix-serve+Chrome has very good experience. Even the on the fly search slow prolem disappears. What about focusing Kiwix-desktop as a Kiwix-serve GUI, start the server on start (best to be in process) and adding some UI for server settings like port/local_or_public?

**Comment by kelson42** [comment]
@wgt98 this is off topic here.
