### ISSUE TITLE
Clicking search bar textbox auto clear the textbox

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#330]
When clicking the search bar textbox, the text (commonly the title of the page) in the textbox is cleared. Now when clicking the page again, the previous title in the textbox won't be restored which is sort of inconsistent.

Potential improvement: clicking search bar auto select all text in search bar instead of clearing it. Or, when clicking the page after clicking the auto-clearing search bar, resotre the page title in the search bar. Auto select is recommended, since when need to copy the page title, I can't select the text in the search bar now which will be cleared when clicked, instead I have to select the title in the page and copy it which may need a scroll-to-the-top action.

**Comment by kelson42** [comment]
@wgt98 I'm not sure how it should behave. If the searchbox is left empyt, it might make sense to restore the title. But otherwise it might be a bad idea to remove a what has been typed there by losing the focus.

**Comment by kelson42** [comment]
> Now when clicking the page again, the previous title in the textbox won't be restored which is sort of inconsistent.

I think this is the only thing to fix. Search bar loosing focus should display again the current tab title.

And "yes", it is impossible to select that way the title of the page.
