### ISSUE TITLE
A Kiwix-serve GUI mode

### ISSUE THREAD

**Issue by wgt98** [kiwix/kiwix-desktop#332]
I found that Kiwix-serve+Chrome have very good experience at least on Windows. Now Kiwix-desktop can start Kiwix-serve with a click, but it is a external server process and there is no UI to config the server ports etc. For Chrome users its best if there is a mode (started with a start parameter) in which Kiwix-desktop works mainly as a GUI for Kiwix-serve, like:
(0) Start the server in process on start.
(1) Load/download/upgrade zim files (already have these features)
(2) Config the server, like port number/localhost_or_public
(3) Default UI is server management, not zim browsing.

**Comment by kelson42** [comment]
@wgt98 You can configure the port in the settings. I don't want this approach because at the end it creates more problems than it solves.

**Comment by wgt98** [comment]
@kelson42 Have use Chrome+Kiwix-desktop started Kiwix-serve, the experience is so perfect that why not focus on Kiwix-serve?
