### ISSUE TITLE
fullscreen does not work on wayland

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-desktop#339]
when using wayland on gnome fullscreen hides the window away. same on weston. for gnome start with:
```
QT_QPA_PLATFORM=wayland kiwix-desktop
```

**Comment by kelson42** [comment]
Which version of Kiwix? Which OS? What are the steps to reproduce the problem?

**Comment by soloturn** [comment]
current kiwix-desktop from master, arch linux, https://aur.archlinux.org/packages/kiwix-desktop-git

**Comment by kelson42** [comment]
@soloturn This package is not an official one, we don't provide support for it. I recommend to report the problem to the AUR package maintainer. Please check our Flathub package https://flathub.org/apps/details/org.kiwix.desktop, it should work well.
