### ISSUE TITLE
Kiwix scrollbar style should be fixed

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#34]
According to the design (https://wikimedia.invisionapp.com/share/7UIVNGPS9CA#/screens/301783616), it should be:
* broader
* Other top/down icons
* flat design

**Comment by ab1nash** [comment]
@kelson42 I want to work on this issue. I am new to open source, so can you help me get started?

**Comment by kelson42** [comment]
@ab1nash Great, carry on :)

**Comment by ab1nash** [comment]
@kelson42 does kiwix have an IRC or anything of the sort for communication?

**Comment by kelson42** [comment]
@ab1nash yes, #kiwix on Freenode

**Comment by mgautierfr** [comment]
@ab1nash do not hesitate to ping me on irc (I'm starmad)

**Comment by ab1nash** [comment]
@mgautierfr certainly. But I was wondering if we could have some more permanent form of comms because whenever I log out of my PC, it logs me out of irc, which makes it difficult to follow what has been going on. Is there a way to prevent this? Otherwise, something like discord would be great!

**Comment by kelson42** [comment]
@ab1nash We have a slack channel. Write an email to kelson at kiwix .org to get an invitation.

**Comment by ab1nash** [comment]
@kelson42 @mgautierfr I will try to make the sidebar broader and introduce a down icon. Further, could you explain what you mean by flat design?

**Comment by kelson42** [comment]
@ab1nash Like in the design. Do you have access to it?

**Comment by ab1nash** [comment]
No. Trying to figure out which part corresponds to the sidebar

**Comment by kelson42** [comment]
Here is an example about how should look like the scrollbar:
![image](https://user-images.githubusercontent.com/1029718/62384342-6badaa80-b552-11e9-8c17-84bd9b424c39.png)

**Comment by ab1nash** [comment]
@kelson42 I think I will drop this issue and take up some other one. Thanks!

**Comment by kelson42** [comment]
IMO we can live for the moment with what we have.
