### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by larrytal** [kiwix/kiwix-desktop#348]
I followed all the installation steps. 
I did kiwix-build, I installed packages, Compilation was successful but when I tried to run kiwix-desktop, it gave me this error:  

`kiwix-desktop: error while loading shared libraries: libkiwix.so.8: cannot open shared object file: No such file or directory`  

I added the recommended paths to the env variables and refreshed the `ld` database but the error won't go away. I'm using Ubuntu 19.10.

**Comment by kelson42** [comment]
@larrytal Please give all the commands and corresponding output.
