### ISSUE TITLE
Long dash versus short dash

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#352]
Why the local server window title has a long dash before "Kiwix" whereas the main window title has a short dash?

**Comment by jetownfeve21** [comment]
![image](https://user-images.githubusercontent.com/47149116/73257330-de2ada80-41c3-11ea-9d31-d821c1418cec.png)
![image](https://user-images.githubusercontent.com/47149116/73257348-e6831580-41c3-11ea-9940-b6fba743eb8d.png)

It's strange, it isn't the case every time

**Comment by kelson42** [comment]
@jetownfeve21 Same problem for the main window? I don't really care if this is long or short, but it should be harmonized.

**Comment by jetownfeve21** [comment]
For the main window it seems constant with a short dash

**Comment by kelson42** [comment]
@jetownfeve21 Just put a long dash for the main window with `src/mainwindow.cpp` and it should make the job.

**Comment by jetownfeve21** [comment]
@kelson42 The local kiwix server window title will still be inconsistant, is it ok if I change this one with a short dash instead ? I can completely remove " - kiwix" from it too otherwise

**Comment by kelson42** [comment]
@jetownfeve21 yes, go to the short dash.
