### ISSUE TITLE
Replace tab's title ellpsis by a fade-out

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#358]
We currently use an ellipsis (`...`) if the title of the tab is to big to fit to the tab. But we should have a fade out instead. Like in the mockup, see:
![image](https://user-images.githubusercontent.com/1029718/73072233-ff828280-3eb4-11ea-85af-3cc977a7ebc2.png)

**Comment by yashasvi-goel** [comment]
Can I work on this issue?

**Comment by kelson42** [comment]
@yashasvi-goel Yes :)

**Comment by yashasvi-goel** [comment]
I have written the CSS for completing this task. I'm unable to replace the CSS in place of setElideMode().

**Comment by kelson42** [comment]
> I have written the CSS for completing this task. I'm unable to replace the CSS in place of setElideMode().

@mgautierfr @jetownfeve21 Any idea?
@yashasvi-goel Please make a WIP PR.

**Comment by kelson42** [comment]
fade-out seems to need to reimplement our own analog of QTabBar so it can worth 10+ hours. I doubt if it really that important

Alternatively, we can do a research to see maybe that change will come in new versions of Qt; or file a bug otherwise, hope someone else will implement it

Also, I can search if any other open source application have it. Firefox and Chromium doesn't use Qt, but probably there Konquerror in KDE, or some other web-browser or some other Qt-based app have those tabs

I looked into the implementation of QTabBar, and didn't see other way as to copy and tune that code

**Comment by kelson42** [comment]
@asashnov  I don't understand why you would need to subclass `QTabBar`. What is the problem exactly with the current PR? You apply a style to the `QTabBar::tab` which is only the text part of tab, so if the ext is short, the `QTabBar::tab` has a short width.. and so the fadout applies in the middle of the tab?

**Comment by asashnov** [comment]
@kelson42 Yes, It would not be a big problem if fadeout applies to the end of the tab.  But tab text is aligned to center now, and it is not customizable with `text-align: left` because it is not supported by QTabBar (only by QPushButton and QProgressBar).
https://doc.qt.io/qt-5/stylesheet-reference.html#list-of-properties

**Comment by kelson42** [comment]
@asashnov Can you measure the width of the text and apply conditionaly the fadeout style?

**Comment by asashnov** [comment]
@kelson42 two things to consider here:
* on Mac and Linux the text in tab is centered (see screenshot)
* we cannot apply fadeout style to the individual tab, only to all of them.

Here is the screenshot from Linux, on Mac maybe similar:
![Screenshot from 2020-12-02 18-53-16](https://user-images.githubusercontent.com/5078434/100869467-ad948b00-34cf-11eb-8e02-ce4b2348d3f2.png)

**Comment by asashnov** [comment]
We can carry about the selected tab only, by measuring text width and applying the style for long tab titles. But then we can see faded or not labels in the other (non-active) tabs depending on the selected.

**Comment by asashnov** [comment]
Also, I looked through KDE screenshots in Google Pictures and haven't seen fade-out in tabs.

**Comment by kelson42** [comment]
@asashnov Th fade outapply to the roght of the text widget, there is no way to force its size so it fill the tab container?

**Comment by asashnov** [comment]
@kelson42 The current style looks like to be applied using relative size:

```
    color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,
           stop: 0.8 #2A2A2A, stop: 1.0 #E1E1E1);
```
So 0 is the beginning of text, 0.8 is 20% to the end, and 1 is the end:

![Screenshot from 2020-12-02 19-15-49](https://user-images.githubusercontent.com/5078434/100871543-0ade0b80-34d3-11eb-8d42-bcbf0dcb49b1.png)

(in this picture, the right leg of the second A in tab header is faded out).

**Comment by kelson42** [comment]
@asashnov I'm not sure to fully understand your last comment like an answer to my latest question... An other approach would be to put the fade-out on the cross picture and make the text going behind it

**Comment by asashnov** [comment]
@kelson42 I'll see if I can expand the text widget to the whole tab header area.

**Comment by asashnov** [comment]
A style sheet can be applied only to a Widget.
But one tab in QTabBar is not a widget itself, it's a part of QTabBar.

There are 'Sub-Controls' and 'Pseudo States' which can restrict the appliance
of the style to specified parts of a widget:
    
https://doc.qt.io/qt-5/stylesheet-syntax.html

The tabs support the `:only-one`, `:first`, `:last`, `:middle`,
`:previous--selected`, `:next-selected`, `:selected` pseudo states:

https://doc.qt.io/qt-5/stylesheet-reference.html

So not possible to select tabs by number (let's say, 3 and 5 with long texts).
There are few opened issue on QT about that:

* https://bugreports.qt.io/browse/QTBUG-72063  (have tab num in a selector)
* https://bugreports.qt.io/browse/QTBUG-840 (set background per-tab)
* https://bugreports.qt.io/browse/QTBUG-11202 (duplicate)

Qt documentation also provides several examples on customization QTabBar,
but again, there is no sample of how to style an individual tab:

https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar

KDE Konsole application uses tabs and allows to enter an arbitrary Qt Style Sheet to customize it. But it's not possible to customize individual tabs also:

https://docs.kde.org/trunk5/en/applications/konsole/tabbarstylsheet.html
https://docs.kde.org/trunk5/en/applications/konsole/tabbarstylsheet.html

**Comment by asashnov** [comment]
The current implementation uses drawing on top after QTabbar in paintEvent().

**Comment by asashnov** [comment]
Currently PR https://github.com/kiwix/kiwix-desktop/pull/538 is in 'Changes Requested' state, but this status is wrong, I uploaded a new code:

<details>
  <summary>5 screenshots from GitHub pull requests</summary>

![1-PR in change requested state](https://user-images.githubusercontent.com/5078434/108632330-e3c72280-74a0-11eb-8831-a5b27a7394e5.png)

![2-try to see which exactly change requested](https://user-images.githubusercontent.com/5078434/108632332-e9bd0380-74a0-11eb-9439-f44bbbc5f7ae.png)

![3-updated the code and commented](https://user-images.githubusercontent.com/5078434/108632335-ef1a4e00-74a0-11eb-9e15-4d4c2130c51a.png)

![4-view changes button doesnt work](https://user-images.githubusercontent.com/5078434/108632336-f2add500-74a0-11eb-982f-f7fa67315d87.png)

![5- the change is not found](https://user-images.githubusercontent.com/5078434/108632340-f7728900-74a0-11eb-950e-f46b9f1c92f4.png)

</details>

I though it may be a known bug in GitHub, but it's not: In GitHub documentation and on the Internet I haven't found any sign that GitHub Pull Request and 'requested changes' can be break by `git rebase`.
