### ISSUE TITLE
Fullscreen is broken on Wayland.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#365]
If using the wayland compositor, the fullscreen functionality hide the window. Switching back to normal display the window correctly.

It is a wayland/QT bug (https://bugreports.qt.io/browse/QTBUG-58574), there is nothing we can do to fix the issue.

Maybe we could detect that we are on Wayland and deactivate the fullscreen functionality to at least avoid the user to "lose" its Window.

**Comment by kelson42** [comment]
@mgautierfr I don't know for now how to deal with that. Let's put that aside for the moment. Thank you for the analysis.

**Comment by kelson42** [comment]
ping @soloturn

**Comment by kelson42** [comment]
Implementing #1033 will fix this ticket as well.
