### ISSUE TITLE
Replace library icon (Kiwix logo) in left tab

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#371]
I'm not really happy with the logo of Kiwix to represent our library:
* It does not really looks good (really small)
* It does not represent properly a library

I would prefer an other one like:
![image](https://user-images.githubusercontent.com/1029718/73952676-8c8afa00-48ff-11ea-8809-e9b96525e651.png)

Or black & white:
![image](https://user-images.githubusercontent.com/1029718/73952774-acbab900-48ff-11ea-8926-3686bdc70ce7.png)

**Comment by Popolechien** [comment]
Looks good to me.

**Comment by jetownfeve21** [comment]
@kelson42 Which one do you prefer ? 
![image](https://user-images.githubusercontent.com/47149116/74713656-4c921400-5229-11ea-8f8f-3e1eab6ef58a.png)

**Comment by kelson42** [comment]
the b&w

**Comment by kelson42** [comment]
@jetownfeve21 Finally not, try the colored one please.
