### ISSUE TITLE
opengl error radeonsi rc4-appimage

### ISSUE THREAD

**Issue by jamcinnes2** [kiwix/kiwix-desktop#372]
Not sure why it is trying to load radeonsi.. I use amdgpu.

libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib64/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi (search paths /usr/lib64/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
libGL error: failed to load driver: swrast
Library directory : "/home/xxxxx/.local/share/kiwix"
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Segmentation fault (core dumped)

**Comment by kelson42** [comment]
What is your linux distribution?

**Comment by jamcinnes2** [comment]
openSUSE Tumbleweed 64

**Comment by kelson42** [comment]
@jamcinnes2 Thank you for reporting, as a workaround I would recommend to use the Flathub version in the meantime.

Duplicate of #393
