### ISSUE TITLE
An extra Command-line windows showing when running Kiwix under Windows

### ISSUE THREAD

**Issue by JonathanCool** [kiwix/kiwix-desktop#373]
Version affected by this issue : The nightly build febuary 8th 2020.  

When executing "Kiwix-Desktop", the Kiwix windows shows correctly, but another window ( that looks like a "Command-line window" ) also shows.  It shows commands done while using Kiwix so it seems like it's required and the last thing it will show is "Session saved" right before closing when the Kiwix Window is closed.  (it closes by itself when Kiwix-desktop.exe is closed )

Workaround : Simply minimize the window and ignore it.  Not a major annoyance.

This command-line window could be hidden easilly using this command ( inside the kiwix-desktop.exe ) : https://docs.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-showwindow?redirectedfrom=MSDN

**Comment by jetownfeve21** [comment]
@mgautierfr Is this due to https://github.com/kiwix/kiwix-build/commit/ea9a195a86126cf5d65d8b7b060fa8b5ef7543a9 ?

**Comment by mgautierfr** [comment]
Yes, this is a mistake, it should not have been merged.

However, the best would be to keep this config for nightly build (this way we can have the output) and remove it for the release (and rc)
We could add the option in kiwix-build/appveyor based of how the build in appveyor is launch (cron or tag push)

**Comment by kelson42** [comment]
@jetownfeve21 @mgautierfr What is still left to do here? The cmdlin windows has disappeared of Kiwix-Desktop 2.0 but you wanted to do more?

**Comment by jetownfeve21** [comment]
@kelson42 The idea is to have the command line for the dev builds, I'm still working on it
