### ISSUE TITLE
Failed install / missing dll with Windows alpha3 

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#38]
Error message says VCRUNTIME140.dll is missing.

This is an OTRS message, I've asked the gentleman if he's tried reinstalling and gets the same message. Will keep you posted.

**Comment by mgautierfr** [comment]
Can you ask him to install the vc_redist dll ? (The installer is in the archive : `vc_redist.x64.exe`)

**Comment by kelson42** [comment]
@Popolechien Do you still have the pb with the beta1?

**Comment by Popolechien** [comment]
Nope. Closing that ticket.
