### ISSUE TITLE
Links broken in Sotoki ZIM files

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#384]
Steps:
* Download https://download.kiwix.org/zim/stack_exchange/3dprinting.stackexchange.com_en_all_2020-01.zim
* Click on the first question
* Click on the first question in the "Related" box (top right)

I get:
* Blanck page

I want:
* The proper article

Remark: Things work fine with kiwix-serve

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Please fix ASAP this bug, it has to work fine for 2.0 relase.

**Comment by jetownfeve21** [comment]
I think it's related to https://github.com/kiwix/kiwix-desktop/issues/206

**Comment by dattaz** [comment]
`js: Uncaught ReferenceError: jstProcess is not defined` pop in console log when click on these link

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Maybe this is the same as #206. I had totally forgotten about that bug. This should work out-of-the-box. If not then probably something fundamentally is wrong. This as to be fixed before 2.0.
