### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#388]
There is a new, slightly remodeled logo for Kiwix 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png
The app's icon needs to be updated accordingly

**Comment by Popolechien** [comment]
Ok obviously something is amiss here as the icon looks all vertically stretched. What would the optimal size and format be? Fully squared and ,svg?

**Comment by jetownfeve21** [comment]
@Popolechien The old logo was a 512*512 svg format image. It would be great to have a png format for the following size too : 
- 24*24
- 32*32
- 48*48
- 128*128
- 256*256

**Comment by kelson42** [comment]
@jetownfeve21 You can do that easily with https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg and configuring the size in the URL.

**Comment by Popolechien** [comment]
@kelson42 Except that this file is 512 × 417, so we'll have the same issue. I've asked @siemsie to generate a square one.

**Comment by siemsie** [comment]
Morning all. We agree that by "square one", you want the exact same logo with a transparent background, as an svg, right? It's just a dimension issue?

**Comment by Popolechien** [comment]
@siemsie Yes.

**Comment by siemsie** [comment]
[png scale.zip](https://github.com/kiwix/kiwix-desktop/files/4550333/png.scale.zip)
Take a look at these files. I used "export for web" function in illustrator – let me know if resolution is ok, otherwise I'll do it another way.

**Comment by Popolechien** [comment]
@siemsie Looks about right, thanks. Can you please send me an .svg version so I can update the file on Commons?

**Comment by siemsie** [comment]
[Logo-kiwix-bird.zip](https://github.com/kiwix/kiwix-desktop/files/4550404/Logo-kiwix-bird.zip)
There are 4 files – svg and png, larger scale, in black and white (negative). Thought it might be useful? FYI, all the files I create exist on the drive, I work straight out of there so that you have access as well.

**Comment by Popolechien** [comment]
@jetownfeve21 You can take the files from the zip here or as indicated by downloading the corresponding png from the commons file (see screenshot). 
I should note that on my screen the new file appears distorted but is, in fact, correct.

![Capture d’écran 2020-04-29 à 11 07 43](https://user-images.githubusercontent.com/21675885/80579039-b1c46b80-8a09-11ea-9708-faa218143c8a.png)

**Comment by kelson42** [comment]
The new icon is transparent, as a consequence, if the user has a dark mode then we don't see the icon anymore. This is what happens to me with the Flathub package.

**Comment by Popolechien** [comment]
Are we to understand you want it with a white background?

**Comment by kelson42** [comment]
yes

**Comment by kelson42** [comment]
I have updated the logo with a white background. Hopefully it works.

**Comment by Popolechien** [comment]
@kelson42 Quick question: we have an [inverted white logo](https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3-neg.svg) - is there any way to offer that one when switching to dark mode?

**Comment by kelson42** [comment]
@Popolechien I don't know, I don't believe so... but not sure. We have 1000 problems with dark-mode support, it is basically not implemented.
