### ISSUE TITLE
Fonts Hard To See

### ISSUE THREAD

**Issue by tlmnot** [kiwix/kiwix-desktop#391]
The fonts doesn't work well with manjaro thema.
![white-text-bug](https://user-images.githubusercontent.com/1029718/78167798-5e352100-744f-11ea-9471-b39bf0a39394.png)

**Comment by kelson42** [comment]
Which version of Kiwix desktop? How have installed it?

**Comment by tlmnot** [comment]
thats quick anyway i'm running 2.0-rc4 the lastest version.

**Comment by kelson42** [comment]
@tlmnot How have you installed it? Via Flathub? Self-compiled? Via the appimage?

**Comment by tlmnot** [comment]
Via appimage.

**Comment by kelson42** [comment]
Seems to be a duplicate of #226 and there is a workaround.
