### ISSUE TITLE
building fails with an Error - no member named ‘getBookByPath’

### ISSUE THREAD

**Issue by rikri** [kiwix/kiwix-desktop#396]
Hello,
I have probem with a build from git sources. Make is failing with an Error (trans. Chyba):

`src/library.cpp: In member function ‘QString Library::openBookFromPath(const QString&)’:
src/library.cpp:44:32: error: ‘class kiwix::Library’ has no member named ‘getBookByPath’; did you mean ‘getBookById’?
   44 |         auto& book = m_library.getBookByPath(zimPath.toStdString());
      |                                ^~~~~~~~~~~~~
      |                                getBookById
src/kprofile.cpp: In member function ‘void KProfile::startDownload(QWebEngineDownloadItem*)’:
src/kprofile.cpp:28:31: warning: ‘void QWebEngineDownloadItem::setPath(QString)’ is deprecated: Use setDownloadDirectory() and setDownloadFileName() instead [-Wdeprecated-declarations]
   28 |     download->setPath(fileName);
      |                               ^
In file included from /usr/include/qt/QtWebEngineWidgets/qwebenginepage.h:45,
                 from /usr/include/qt/QtWebEngineWidgets/qwebengineview.h:48,
                 from /usr/include/qt/QtWebEngineWidgets/QWebEngineView:1,
                 from src/contentmanagerview.h:4,
                 from src/contentmanager.h:7,
                 from src/kiwixapp.h:5,
                 from src/kprofile.cpp:3:
/usr/include/qt/QtWebEngineWidgets/qwebenginedownloaditem.h:125:10: note: declared here
  125 |     void setPath(QString path);
      |          ^~~~~~~
make: *** [Makefile:1763: library.o] Chyba 1
make: *** Čeká se na nedokončené úlohy…
==> CHYBA: Došlo k chybě v build().
    Rušení...
Error making: kiwix-desktop-git
`

Thank you.
rikri

**Comment by kelson42** [comment]
@rikri I think the problem is that you compile kiwix-desktop git master but don't use kiwix-lib git master. Could you confirm you still have the problem with kiwix-lib git master version?

**Comment by rikri** [comment]
@kelson42 Thank you for speedlight answer... ;-)
It may be, but doesn't seem so (nevertheless I'm no expert in github). I'm compiling package from aur.archlinux.org where is kiwix-lib version 9.0.1

`
pkgname=kiwix-lib
pkgver=9.0.1
pkgrel=1
pkgdesc="Library providing the Kiwix software core"
license=('GPL3')
arch=('armv7h' 'i686' 'x86_64')
depends=('libzim' 'pugixml' 'mustache=3.2.1' 'xapian-core' 'aria2' 'libmicrohttpd')
makedepends=('meson' 'gtest')
url='https://github.com/kiwix/kiwix-lib'
source=("https://github.com/kiwix/kiwix-lib/archive/${pkgver}.tar.gz")
sha256sums=(0e99329f870bc0cb2a51b1cce599f084cfdc4953cba97d178536959f2a9a865f)

build() {
	cd "${pkgname}-${pkgver}"
	# We want to ignore xapian ABI version mismatches
	arch-meson build -Dwerror=false
	ninja -C build
}

check() {
	cd "${pkgname}-${pkgver}/build"
	ninja meson-test
}

package() {
	cd "${pkgname}-${pkgver}/build"
	DESTDIR="${pkgdir}" ninja install
}
`

**Comment by kelson42** [comment]
Then you don't use git master head :) https://github.com/kiwix/kiwix-lib. I close the ticket as this is the explanation.
