### ISSUE TITLE
Use Qt resource system to load the right translation file

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#399]
Like @mgautierfr said in this [PR](https://github.com/kiwix/kiwix-desktop/pull/387) : 
> Qt already has a system to load a resource file specific to a lang. This is already use for the about.html resource. We have a "default" one in english (in resources/texts/about.html) and one specific to french in resources/texts/fr/about.html.
We could have the same things for the json file containing the translation. We could have a json file (texts.json) in resources/i18n and a texts.json per lang (resources/i18n//texts.json). This way we simply would have to ask to qt to load the resource and it will load the right resource for us.
> But saying that, it wouldn't protect us from a not up to date translation (with missing key).
Let's move with this PR. We have to think a bit more to see how (and if) we integrate the resource system.

**Comment by kelson42** [comment]
@jetownfeve21 Please explain which problem we have. I have read 3 times this comment, I still don't understand at all what is the problem you want to fix. I really hope we have now already "a system to load a resource file specific to a lang", "a default one in english", "a texts.json (or xml) per lang" and a solution which  "protect us from a not up to date translation".... because all of this are the absolute basics of any software localisation system!

**Comment by kelson42** [comment]
@jetownfeve21 Thx, please for the explanation. As improving this seems pretty easy, please just do it.

**Comment by jetownfeve21** [comment]
@mgautierfr After some time spent to implement it, I don't find it that useful. The main advantage is that using the same file's name in the code, Qt chooses the right file depending on the user's OS system for us. But we always want to check the english translation file as a reference so this behavior is more annoying than useful finally

**Comment by mgautierfr** [comment]
Yes, I agree for the classical use case. That why I said it wouldn't protect us from a not up to date translations and merge the PR.

However, if it is definitively not useful for the general case, it could be when we have a file that mostly contains text to translate (as about.html file). 
For now we have to do this ugly token replace : https://github.com/kiwix/kiwix-desktop/blob/master/src/about.cpp#L13-L26
It would be nice if we keep the plain file as it is and just make the translators translate the whole file.
And it is probably necessary as the things like the version or build-date may change position depending of the language. Arabic language probably want the version number before the "version" string.

I don't know if we can simply send a whole file to translate to wikitranslate.
Maybe @Nikerabbit can give us a hint here.

**Comment by Nikerabbit** [comment]
Which file? If you are talking about html files, then no, our interface don't scale to large strings, big files need to be split, and we have no parser for html files as it is not possible to have a fully generic one.

**Comment by kelson42** [comment]
Closing the issue. We don't have a real problem and the problem which might be tackle by this is not related to TW.

**Comment by mgautierfr** [comment]
>  We don't have a real problem and the problem which might be tackle by this is not related to TW.

We have a real problem. We are speaking of translating files like this one : https://github.com/kiwix/kiwix-desktop/blob/902ebb3402c15ae1a0c1bfd40444eb7d99e6a257/resources/texts/about.html
With the new translation system, we end with this file https://github.com/kiwix/kiwix-desktop/blob/master/resources/texts/about.html

You can see that we have something like : `<p>%%VERSION_LABEL%% : %%VERSION%%</p>`
Where the version is after (right) the version_label. This is ok for ltr language but not for rtl languages (where version will be written on left of version_label). Simply compose small string to have a full text will not work.
This is a small example, but some languages may need to reorganize the whole html to fulfill the specific needs of the language. (So translation system should not parse html to allow translators to change it)
