### ISSUE TITLE
Minimal font size configurable

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#4]
_From @kelson42 on January 18, 2018 20:5_

RMS idea.

_Copied from original issue: kiwix/kiwix-xulrunner#490_

**Comment by mgautierfr** [comment]
What is a "Minimal font size configurable" ?
It is already possible to change the zoom of a page.

**Comment by kelson42** [comment]
@mgautierfr Does the level of zoom is done related to the pixel depth of the screen? Which guarantee do we offer than we do not display a ZIM file in which the text is simply not readable?

**Comment by mgautierfr** [comment]
Ask Qt :)
We are using the integrated zoom feature QtWebEngine.

**Comment by kelson42** [comment]
OK, I propose to keep it like this. We should have a concrete problem to deal with IMO.
