### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by Sofi204** [kiwix/kiwix-desktop#401]
Hello.
i just downloaded the bulbagarden_en_all_maxi_2020-02.zim and wanted to watch it via kiwix.
Then I noticed that no pictures are shown.
Then I opened 2 other Zim files (wikiversity_de_all_maxi_2020-04.zim and wikivoyage_de_all_maxi_2020-03.zim )
But there are no pictures shown to me. A few weeks ago when I last used it, all pictures were still shown. 
I uninstalled the program and then installed it again, but the problem still remains.

Here is a screenshot.
---> https://www.bilder-upload.eu/bild-c88a2b-1586339703.png.html
![image](https://user-images.githubusercontent.com/1029718/79322655-69875280-7f0d-11ea-9785-b1aaa8e4b885.png)

What can I do?

**Comment by kelson42** [comment]
Please use Kiwix-Desktop 2.0. Kiwix Desktop 1.0 is deprecated.

**Comment by Sofi204** [comment]
Hello.

that helped.

thanks a lot
