### ISSUE TITLE
Library fonts should be sans serif and homogeneized

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#406]
It looks like the library lists items with three different types of fonts in two colors. I don't think this was part of the design brief
![image](https://user-images.githubusercontent.com/21675885/79139657-fbc91280-7db6-11ea-9d41-d33d535e4514.png)

**Comment by vishal-1408** [comment]
Hi , i want to work on this issue. Please assign it to me.

**Comment by vishal-1408** [comment]
hey kelson, I am a newbie in open source programming and I am really excited to work on this issue, but i am finding difficulties in building kiwix-desktop using kiwix-build as it was mentioned that kiwix-library must be compiled dynamically using kiwix-build. BUt when i tried to build kiwix-desktop, i received and error and didn't know how to resolve it. So i raised a new issue in kiwix-build, Can you please see into this issue and help me out ?

**Comment by mgautierfr** [comment]
Fixed by #495

**Comment by kelson42** [comment]
@vishal-1408 Thank you!

**Comment by vishal-1408** [comment]
Your welcome kelson 👍
