### ISSUE TITLE
Language listing is incorrect

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#407]
It looks like the language sorting is done by alphabetical order of each language's self description or ISO code (e.g. in the example below Welsh is listed under C because it is `cymraeg/cy` and German is `deutsch/de`:

![image](https://user-images.githubusercontent.com/21675885/79140364-2f586c80-7db8-11ea-840a-60dbf9e0423f.png)

This is not something an average user not privvy to these languages would/could know, and therefore to them they are as good as not listed.

The correct listing order should be that of the interface language (English in the case at hand, with Welsh among W languages and German along with other Gs).

**Comment by kelson42** [comment]
@jetownfeve21 Is that something you could fic easily?
