### ISSUE TITLE
Unable to download files on Windows with 2.0

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#409]
On Kiwix-desktop 2.0 / Windows 10. It probably has to do with the computer's settings (though there's nothing particular about it, ie no antivirus nor firewall) as another Win10 computer on the same network works fine.
Getting this weird-ass javascript error message:
![image](https://user-images.githubusercontent.com/21675885/79191284-7d0bbe00-7e26-11ea-86f6-e36f70f9c317.png)

**Comment by kelson42** [comment]
@Popolechien This is systematic? If "yes", what are the steps to get it displayed? Can you still use the library?

**Comment by kelson42** [comment]
I never have seen this dialog on GNU/Linux!

**Comment by jetownfeve21** [comment]
This alert message usually happens when aria2 set the download status to error, as @kelson42 asked, is it systematic ?

**Comment by Popolechien** [comment]
@jetownfeve21 yep, for every file, every time. Tried to unpack .zip file a second time, to no avail.

**Comment by mgautierfr** [comment]
I can reproduce this on my side.
It seems that it is yet again a problem with accents in the path (with the settings system that allow the user to change the download directory).
As a workaround, you can go to the setting and change the download directory (to the same directory or another one). Restart kiwix-desktop and it should work.

**Comment by kelson42** [comment]
@mgautierfr thank you very much for confirming this. I'm sorry to say that again, but this is obviously a TOP PRIO to fix before releasing 2.0.1. I let you organize yourself with @jetownfeve21 about the fix.

**Comment by mgautierfr** [comment]
You can test with this build : http://tmp.kiwix.org/ci/mgautier/wip_compile_windows/2020-04-15/kiwix-desktop_windows_x64_2020-04-15.zip

**Comment by Popolechien** [comment]
Yep, looks like it's been fixed
