### ISSUE TITLE
kiwix-desktop_windows_x64_2.0-alpha3 does not remember zim file location

### ISSUE THREAD

**Issue by gladteck** [kiwix/kiwix-desktop#41]
When you first start the program it "asks" where the zim file is and on restart "asks" again. kiwix-desktop_windows_x64_2.0-alpha3 does not reload zim file on restart nor remembers zim file location on restart.

**Comment by mgautierfr** [comment]
With last alpha (6), the zim location is added to the library.
So after a restart, the zim is still referenced and a user can click on "open"  button to open it.
