### ISSUE TITLE
Context dialogs should have a shadow

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#412]
Like here in the mockup:
![image](https://user-images.githubusercontent.com/1029718/79193487-04f3c700-7e2b-11ea-9da4-0221ca1a0f91.png)

**Comment by kelson42** [comment]
@asashnov Do you think this is doable?

**Comment by mgautierfr** [comment]
The menu is handled by Qt (and the shadow by the window manager). I'm not sure we can do something here.

**Comment by kelson42** [comment]
Seems doable https://www.qtcentre.org/threads/69318-How-to-modify-shadow-of-QMenu

**Comment by asashnov** [comment]
It's possible to do custom drawing in our window when context menu is showed.
But it may not be in align with a desktop user experience. As we support a lot of desktops, some of them may use shadow effect already, so we should detect if a desktop already has it.

The desktops we have:
* Windows Aero (with 3D effects)
* Classic Windows desktop (2D)
* Gnome Compiz (with 3D effects)
* KDE with Plazma (with 3D effects)
* Linux Mint with classic (2D)
* LXDE (minimalistic 2D desktop)
* Different MacOS versions have different shadow settings: https://apple.stackexchange.com/questions/73849/mac-os-x-10-7-window-shadow-params

So I don't think we should interfere those user experience. But if we really want, we can.

**Comment by kelson42** [comment]
@asashnov What kind of mechanism would be used to know if there is already a shadow applied?

**Comment by kelson42** [comment]
@mgautierfr Agree that this probably better to make nothing.
