### ISSUE TITLE
Does not seem to find / recognize newly downloaded zim files (Win10)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#417]
I had a bunch of zim files on my computer before even downloading Kiwix-desktop, and the application had no problem finding and listing them. I have since downloaded two more files from my browser and put them in the exact same folder, yet Kiwix fails to see and list them.

**Comment by mgautierfr** [comment]
Have you downloaded the zim file yourself or with kiwix-desktop ?
How kiwix fails to see them ? They are not listed in the content manager or, when you try to open a "external file" (Ctrl-O), the file browser doesn't show them ?

**Comment by Popolechien** [comment]
@mgautierfr They were downloaded from my browser and put in the same folder as other zim files that were downloaded from the application, yet are not listed in the Content manager. 
Files downloaded from Kiwix-desktop are properly identified and listed in the Content manager.

**Comment by mgautierfr** [comment]
kiwix-desktop doesn't automatically look for files in the directory but list only the files in the "library.xml".
If you download zims using kiwix-desktop or open them explicitly, they are added to the library and displayed.

(However, there are some issue on windows with user with accents, especially not saving the "library.xml". I am currently fixing this. Please do not play to much with this version if you have a accent in your user name, and I think it is the case)

**Comment by Popolechien** [comment]
Ok thanks. I guess I had an expectation of immediate listing based on the android experience.
I have a second computer with no accent in the username so can test around :-)
