### ISSUE TITLE
Download manager should give some sort of estimate

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#418]
When downloading a zim file it would be nice to have either an estimate Time to Completion or at least an indication of the current download speed:
![image](https://user-images.githubusercontent.com/21675885/79309881-4bb0f200-7efb-11ea-840d-5e8749e4428f.png)

**Comment by kelson42** [comment]
I believe this kind of computation should be even in the libkiwix.

**Comment by kelson42** [comment]
@veloman-yunkan Does aria2c deliver this kind of estimation?

**Comment by veloman-yunkan** [comment]
Current download speed is already displayed in the download progress field. aria2c doesn't provide information about estimated time to completion. Computing the latter on our own is possible though not trivial if we want it to work reasonably well for various corner cases.

**Comment by kelson42** [comment]
@Popolechien We have indeed the speed now, but not the estimated time to completion, see:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/2312f3cb-4d04-4530-80d3-c86c20b9634e)

... Is that good enough?

**Comment by Popolechien** [comment]
Yes perfect, thanks.
