### ISSUE TITLE
There should be a way to return to a zim file's home page

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#419]
Currently if I'm going through a given zim file there is no "home" button that would bring me back to the zim's landing page (much like there is already on Kiwix-serve, for instance).

**Comment by jetownfeve21** [comment]
@Popolechien There is a shortcut for this which is `ALT+Home` (see https://github.com/kiwix/kiwix-desktop/pull/144) but maybe we can add this option in a menu

**Comment by kelson42** [comment]
This is a duplicate of #58
