### ISSUE TITLE
Implement table of content

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#42]
This is a really old feature request, for Kiwix Desktop 1.0 too.

See this old ticket: https://sourceforge.net/p/kiwix/feature-requests/1000/

**Comment by kelson42** [comment]
The strategy here is:
* Implement ZIM API to retrieve TOC (here is the ticket for MWoffliner for example https://github.com/openzim/mwoffliner/issues/596)
* Implement client feature in Kiwix Desktop

**Comment by Jaifroid** [comment]
@knowledge-is-power Just to be clear, the ToC is not in the Wikipedia archives (not even hidden) so it needs to be constructed dynamically from the headers in the article. This isn't too hard, and some work was done on it in [this PR](https://github.com/openzim/mwoffliner/pull/1237), but then stalled. Reader software can implement a generic ToC if an article has H1, H2, H3 etc., but it's probably best done inside the ZIM.

Navboxes, etc., are another matter. These _are_ mostly in the Wikipedia ZIMs, but are hidden by the mobile style, so have to be force-unhidden (unless desktop CSS can be applied).

**Comment by Jaifroid** [comment]
@knowledge-is-power Just so you're aware, Kiwix JS isn't just a PWA, we also have installable packages for various platforms, and packages for Linux as well as Windows. See http://kiwix.github.io/kiwix-js-windows/kiwix-js-electron.html. Although it's not the full-featured Desktop app, it works very well with Wikimedia archives (and many others too). It's good to have options!

**Comment by kelson42** [comment]
Reminder: please one topic per ticket, here you mixed two topics which have nothing in common:
* box collapsing
* TOC

For the rest, the way forward is pretty known, we just need to have the development resources. It's an old problem, but this is on the roadmap and this will be fixed/implemented at some point.

**Comment by knowledge-is-power** [comment]
@kelson42  yeah I thought both issues were part of the same problem that's why I made a single ticket, sorry about that. now that its clear to me that they are unrelated, is it okay if i open a dedicated ticket for wiki navboxes/templates? (cuz this ticket is dedicated to ToC issue)

**Comment by juuz0** [comment]
I created a ticket here #869

**Comment by ShaopengLin** [comment]
@kelson42 Javascript Injection works fine. QWebEngineScript allows us to inject Javascript in separate files and we can also write the CSS styles over there. I can create a Mock up and you can advise on how to adjust the presentation (This is injected so it will feel foreign and we need a balance).
![Screenshot from 2024-08-07 23-33-42](https://github.com/user-attachments/assets/cc49bcd8-6c4d-48e6-a462-08f585fd33a2)

**Comment by kelson42** [comment]
@ShaopengLin So, far to late, but here is the mockup:
![image](https://github.com/user-attachments/assets/fd501797-bd7c-44da-b9df-c4ad2e1b3a1e)

You don't to implement all the refinements of this mockup (search, back/forth buttons, indicator of localisation in the page), but it has to be as a sidebar and clean.

**Comment by srd424** [comment]
Just jumping in to say .. I was really disappointed in the lack of TOCs, but have discovered that there is at least one chrome extension which generates them dynamically from page content, and it seems to work nicely with kiwix-serve: https://chromewebstore.google.com/detail/smart-toc/lifgeihcfpkmmlfjbailfpfhbahhibba

I'm sure there are others, still looking ..
