### ISSUE TITLE
Improve Kiwix Serve dialog look and feel

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#421]
It should be like this:
![image](https://user-images.githubusercontent.com/1029718/79323054-fcc08800-7f0d-11ea-8eb3-91f5921be6aa.png)

But it is like this:
![image](https://user-images.githubusercontent.com/1029718/79323679-cfc0a500-7f0e-11ea-9921-50109a940324.png)

or

like this:
![image](https://user-images.githubusercontent.com/1029718/79324262-9fc5d180-7f0f-11ea-906c-2db7db2b27cf.png)

**Comment by vishal-1408** [comment]
Hi, I would like to work on this issue and i wanted to know the requirements clearly ! the window should be resized or even the title bar must be removed? 

![Screenshot from 2020-07-24 20-32-06](https://user-images.githubusercontent.com/54095062/88405441-e79ca480-cdec-11ea-90d2-94b4353e77bc.png)

**Comment by kelson42** [comment]
I has o use pure Qt code

**Comment by kelson42** [comment]
@HanYoung-uwu As I see you seem to be interest in look & feel tickets. Maybe would be interested in that one. The goal is to have the correct style but as well to remove vue.js (and replace with pure Qt).

**Comment by HanYoung-uwu** [comment]
> @HanYoung-uwu As I see you seem to be interest in look & feel tickets. Maybe would be interested in that one. The goal is to have the correct style but as well to remove vue.js (and replace with pure Qt).

I'd rather re-write this app entirely in Qml than to try to port it to QWidget.

**Comment by kelson42** [comment]
@mgautierfr Do you remember why we have finally chosen not to use QML to define UI?

**Comment by mgautierfr** [comment]
> Do you remember why we have finally chosen not to use QML to define UI?

Because of the knowledge of the developer :)

**Comment by kelson42** [comment]
@HanYoung-uwu Defining the whole UI in QML now would be quite a bit of work I suspect, but could you just make the dialog box like this?
