### ISSUE TITLE
Unable to download one of two versions of the same zim-file

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#422]
Steps to reproduce:
- Look for Metakgp zim file (in English);
- Try downloading `maxi` and `nopic` versions: the latter downloads without any issue, the former crashesm again with some weird JS message:
![image](https://user-images.githubusercontent.com/21675885/79337872-9c8a1000-7f26-11ea-8690-125d2d2bd493.png)

It looks like a duplicate of #409 but I'm on another computer without any accent/Special character in the user path, and other downloads worked fine.

**Comment by kelson42** [comment]
@Popolechien I can not reproduce this problem on GNU/Linux... I suspect the problem here is totally different to what you guess.

**Comment by Popolechien** [comment]
Seems fixed with the latest build (as seen in #409 )
