### ISSUE TITLE
Kiwix Desktop 2.0.4 always quits with segfault on Ubuntu 18.04

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#423]
```
$ ./kiwix-desktop_x86_64.appimage 
Library directory : "/tmp"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
session saved
Segmentation fault (core dumped)
```

**Comment by kelson42** [comment]
Maybe related to #123?
Maybe related to #393

**Comment by kelson42** [comment]
I don't have this behaviour with 20.04 and https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.0.3.appimage. Closing the issue.

**Comment by kelson42** [comment]
Reopening the issue, because it happens again with Ubuntu 20.04 and the Debian package in our PPA:
```
$ kiwix-desktop 
Library directory : "/home/kelson/.local/share/kiwix"
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
aria2 tellActive failed : Invalid return code from ariaaria2 tellWaiting failed : Invalid return code from ariaadd widget
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid return code from aria
Aborted (core dumped)
```

But it works with the latest appimage https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.0.4.appimage

**Comment by kelson42** [comment]
@mgautierfr This might be related to Qt as the appimage uses Qt 5.9 and the deb package 5.12.

**Comment by mgautierfr** [comment]
> aria2 tellActive failed : Invalid return code from ariaaria2 tellWaiting failed : Invalid return code from ariaadd widget
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid return code from aria

It is probably a problem with aria interaction and the debian packaging.

**Comment by kelson42** [comment]
Probably a duplicate of #514
