### ISSUE TITLE
Video sound disjointed on Kiwix-Desktop (Linux & Windows)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#425]
Steps to reproduce:
- Kiwix desktop 2.0.1 on Windows10
- Download https://download.kiwix.org/zim/other/thaki_ar_tech_tricks_2020-04.zim
- Play any video - it's in arabic so just for comparison purposes let's go with [Translating webpages](https://www.youtube.com/watch?v=8cCq_39td_Y&list=PLkJWM09OI9C4cSo93ZGJKQJWggJD1aUNO&index=1) which is on Youtube.
- When playing this video, the speaker can be heard at 0:05 saying "merhaba" then starting a sentence, be interrupted, and restart the very same sentence around 0:12
- The issue appears with any video from the list. For instance with `Writing in Arabic` - starts at 0:05, sound restarts at 0:07. 

Videos also stop a few seconds before the end.

Tested the same zim file on Android and had no issue whatsoever.

**Comment by kelson42** [comment]
@Popolechien Do you have reproduced this problem an an other Windows computer?

**Comment by Popolechien** [comment]
@kelson42 yes

**Comment by kelson42** [comment]
@Popolechien Thank you very much for this bug report. I can confirm the problem with Kiwix-Desktop 2.0.1 on Linux (Flathub version). The same file served via kiwix-serve with firefox works perfectly. So this is a probably a problem with the reader part.

@mgautierfr Any idea what happens here?

**Comment by kelson42** [comment]
@rgaudin It seems somehow related to the video. Video about Mali does not have this pb. But video about skin done in March has a glitch as the beginning as well. I suspect we have here a correlation beetween (a bug?) in the content and in the reader.

**Comment by rgaudin** [comment]
One thing we could do is run this without `--low-quality` to check whether our compression has an impact on it.

**Comment by rgaudin** [comment]
FYI the **only** change we added was to set the target sample rate to 44Khz.

**Comment by kelson42** [comment]
* https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-12.zim seems not impacted
* https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-04.zim seems impacted

I suspect something has changed in the way the videos are encoded in the meantime.

I move the ticket to openzim/youtube as I believe there is more chances to fix the problem there.

**Comment by rgaudin** [comment]
Shouldn't we open a different ticket for youtube? That's probably a quick fix there but it looks like this is an upstream (Qt) bug that we should track.

Youtube is somewhat flexible in what it receives and sends and we're also creating ZIMs with videos from outside youtube. Fixing videos might not always be an option.

**Comment by rgaudin** [comment]
Closing in favor of #433 which compiles the various video playing issues.
