### ISSUE TITLE
Unable open zim file from Windows File Sharing (2.0.1)

### ISSUE THREAD

**Issue by chenshaoju** [kiwix/kiwix-desktop#429]
Sorry for my English.

Kiwix Version: 2.0.1 04/20/2020
Windows Version: Windows 7 SP1 x64 (Simplified Chinese)
Last know good version:  2.0-rc4 12/08/2019

Issue:
When I open zim file (in my case is `wikipedia_zh_all_maxi_2020-04.zim`) from NAS by through Windows File Sharing (Hostname is `shaoju-brix` , It's unable to open, Show a blank page and title is `about:blank`.

DEMO:
![samba](https://user-images.githubusercontent.com/515763/80301545-5dd24080-87d7-11ea-8707-bf01eac2060f.gif)

But, If I copy the zim file to the local disk and open it ,It's working perfectly.

The old version 2.0 rc-4 is working fine with Windows file Sharing (NAS) too.

DEMO:
![oldversion](https://user-images.githubusercontent.com/515763/80301643-c7eae580-87d7-11ea-8853-5a75ff729443.gif)

If need any information, please feel free to let me know.

Thank you.

**Comment by kelson42** [comment]
@chenshaoju Thank you for your bug report. We believe that should work fine with our very last release Kiwix Desktop 2.0.1. Loot at https://www.kiwix.org/en/downloads/kiwix-reader/ to download it and let us know if you still have the problem.

**Comment by kelson42** [comment]
@chenshaoju Thank you for your bug report. Sorry my first comment was not pertinent, I have removed it. Would you be able to copy here in text, the two paths (one with the NAS and the one local) where the ZIM files are? Might that be that the NAS path as chinese characters and the local one does not?

**Comment by chenshaoju** [comment]
Thank you for the reply, The path to my NAS is `\\shaoju-brix\BTDownloads\wikipedia_zh_all_maxi_2020-04.zim`, The local path from my computer is `E:\Temp\wikipedia_zh_all_maxi_2020-04.zim`, The path does not include Chinese characters.

The NAS is running Windows Server 2008 R2 with Simplified Chinese, Disk on NAS is using NTFS file system, And the path of the Sharing folder on NAS is `D:\BTDownloads\wikipedia_zh_all_maxi_2020-04.zim`.

**Comment by kelson42** [comment]
@chenshaoju Thank you for the detailed information. I think we have everything so a developer can try to reproduce the problem and fix it. Hopefully in next release.

**Comment by go2211greg** [comment]
As a workaround, you can map a network drive to the location, and open the file from within Kiwix. 

On Windows 7, you can access the Tools menu and Map Network Drive by pressing the Alt key when browsing the files. For the target, copy and paste the location of the server from the address bar.

**Comment by chenshaoju** [comment]
This issue still not fix at 2.0.3 (07/02/2020)

Net disk mapping can be working fine but I'm unable mapping every computer in the network... 😅

**Comment by kelson42** [comment]
@mgautierfr Any chance we could fix this bug relatively quicly/easily? I know this is a Windows specific bug, but maybe the bug is so obvious we could fix it blindly and @chenshaoju could test with a nightky build?

**Comment by chenshaoju** [comment]
Hi, I just download and test `kiwix-desktop_windows_x64_2020-07-11.zip`, It same issue.

**Comment by mgautierfr** [comment]
@chenshaoju Can you test with http://tmp.kiwix.org/ci/mgautier/wip_compile_windows/2020-07-13/kiwix-desktop_windows_x64_2020-07-13.zip ?

**Comment by chenshaoju** [comment]
Hi, The `kiwix-desktop_windows_x64_2020-07-13.zip ` is working fine, but the console output some error message:
```
Library directory : "C:\\Users\\chens\\AppData\\Roaming\\kiwix"
Compiled with Qt Version  5.12.6
Runtime Qt Version  5.12.6
add widget
js: Uncaught SyntaxError: Unexpected end of input
js: Uncaught SyntaxError: Unexpected token .
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
```
![image](https://user-images.githubusercontent.com/515763/87371421-e632d700-c5b7-11ea-8821-168f84f85ba9.png)


Thanks for your hard work.👍
