### ISSUE TITLE
Zoom shortcuts don't work properly with Wayland

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/kiwix-desktop#431]
Steps to reproduce:

    open kiwix desktop
    open a zim file (wikipedia)
    try to zoom (Ctrl+0, Ctrl+-, Ctrl++)

From the menu it works (but not when the file is not opened yet - its menu is grey and doesn't work) (when the menu can be opened). Sometimes only Ctrl++ doesn't work, other shortcuts do.

I'm using the recent Kiwix-desktop 2.0.1 installed from flathub on Linux Fedora Core 29.

**Comment by kelson42** [comment]
There is no zoom feature if no file open. I don't understand the bug.

**Comment by ynikitenko** [comment]
There is still text (available libraries) when no files are opened. 
Otherwise the bug is mostly described for an already opened file.

**Comment by kelson42** [comment]
Here you seems to report two things. One is not a bug but a feature. The other (zoom in shortcut works only sporadically) can not be reproduced. @jetownfeve21 Any opinion?

**Comment by ynikitenko** [comment]
You can ignore the feature, if you want.
What software did you use when trying to reproduce that?

**Comment by kelson42** [comment]
@ynikitenko Last Flathub release 2.0.1-1 on Ubuntu 20.04 (so without Wayland). @mgautierfr You use Fedora, do you suffer of a similar problem?

**Comment by kelson42** [comment]
I'm probably going to close that ticket if nobody complains that the zoom shortcuts work only sporadicaly.

**Comment by ynikitenko** [comment]
@kelson42 I think it would be more appropriate to close that if someone else on Wayland (or with a more recent Kiwix Desktop) checks that they work reliably.
