### ISSUE TITLE
Video playing is sometimes buggy

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#433]
Following #425, here is a list of the identified problems with video on kiwix-desktop.

Note that the following issues are seen only with kiwix-desktop (Linux and Windows) and not on the other readers/browsers or media players. You can check our [compatibility table](https://github.com/openzim/youtube/wiki/Compatibility) for more details.

Fortunately, those three issues are visible on the [mali zim](http://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2020-04.zim). You'll see that only `LE PALUDISME - LMPLN #6` and `Le ramdan - LMPLN #3` plays correctly.

Videos are [downloaded from YT via youtube-dl](https://github.com/openzim/youtube/blob/master/youtube2zim/scraper.py#L526) requesting `videobest+audiobest` for webm (so youtube-dl muxes them together using ffmpeg) then [re-encoded for lower quality and smaller resolution](https://github.com/openzim/youtube/blob/master/youtube2zim/converter.py#L87).

I don't know how much of this goes into Qt, kiwix-desktop nor the HTML/JS code in zim so I open this ticket and you/we will figure out whether we need to create independent issues. Those seems related for now.

### video and audio disconnects

Visible on video: `La monnaie - LMPLN #4` `La monnaie 2 - LMPLN #5` `C'est quoi ? - LMPLN #0` `Le vocabulaire - LMPLN #1`

Video starts correctly with first sentence « Bonjour à tous, aujourd'hui une rap|» then audio restarts from beginning while video continues. Audio and video are then de-synchronized.

### video freezes while audio continues

Visible on video: `3mn contre la révision constitutionnelle`

Video starts correctly but very quickly the video freezes and some artifacts are visible but audio keeps playing. it is possible to pause/continue but that only affects audio.

![freeze](https://user-images.githubusercontent.com/57929/80487491-6ac47080-894c-11ea-9b10-96fe67bde08e.png)

### video running slow

Visible on video `Les funérailles - LMPLN #2`

Video starts then a mini freeze appears with artefacts while the  audio continues normally.

![artifacts](https://user-images.githubusercontent.com/57929/80487607-a2cbb380-894c-11ea-8d4f-053e7f46dd06.png)

**Comment by rgaudin** [comment]
Additional information, uncompressed videos (as downloaded+muxed by youtube-dl) doesn't work for some other reason. Haven't check the logs.

![err](https://user-images.githubusercontent.com/57929/80515734-f00e4c00-8971-11ea-8cc1-9a4b2f8f8612.png)

What's interesting though is that **uncompressed videos** are way larger and actually triggers an issue on the readers/browsers that **don't support webm natively** (apple). On those readers, s**ound plays smoothly but video is slow and jerky**.

This is most likely due to the codec being implemented with webassembly and its performances in decoding high bitrate frames but I think it might be a valuable information here.

**Comment by kelson42** [comment]
@mgautierfr has build a test appimage version with Qt5.14 and it is available at http://tmp.kiwix.org/Kiwix-test_qt514-x86_64.AppImage. Seems to work fine with it for me.

**Comment by kelson42** [comment]
To me, with latest appimage nightly (using Qt 5.15), these problems are fixed.
