### ISSUE TITLE
Delete confirmation dialog has incorrect title

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#435]
Confirmation dialog title upon ZIM deletion displays an unexpected ugly title. See screenshot:

![alert](https://user-images.githubusercontent.com/57929/80518225-bb03f880-8975-11ea-926c-aa97dd66d8e6.png)

**Comment by kelson42** [comment]
Should be fixed with #421

**Comment by kelson42** [comment]
Basically a duplicate
