### ISSUE TITLE
Changing download directory does not create it if necessary

### ISSUE THREAD

**Issue by Jheschl17** [kiwix/kiwix-desktop#437]
On Kiwix Desktop 2.0.1 with Linux Mint 19.3 whenever I try to change the download directory (F12 -> Download directory) a alert dialog with the message `Invalid download path` appears.
![image](https://user-images.githubusercontent.com/43889658/80927975-b25e5880-8da1-11ea-8bec-dbbedacd1d85.png)

**Comment by kelson42** [comment]
@Jheschl17 @jetownfeve21 I confirm! For me it does not work at all.

Steps:
* Open the settings
* Path is `/home/kelson/.var/app/org.kiwix.desktop/data/kiwix`
* Writtin `/home/kelson/.var/app/org.kiwix.desktop/data/kiwix2`
* Clicking on "Apply"
* Getting the error message reported earlier.

**Comment by mgautierfr** [comment]
This is because the directory doesn't exist.
We must create it when user set to a non-existant path.

If I create the directory myself, it works.

**Comment by kelson42** [comment]
@mgautierfr @jetownfeve21 Maybe a better idea would to have this workflow:
* It is impossible to change it manually
* We have a directory filepicker (which allows as well directory creation)
* One type with have pick one different from the original a confirm dialog is displayed (and it does the move if confirmed).
* This would allow use to remove the "Apply" button which is bad UX
