### ISSUE TITLE
Implement TTS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#44]
It looks like Windows has this builtin:
https://www.youtube.com/watch?v=-GCxNR3QsC8

Was reported first at:
https://sourceforge.net/p/kiwix/feature-requests/878/

**Comment by kelson42** [comment]
@mgautierfr The goal is like and Android, to read the whole article or part of it through a synthetic voice (for example for blind people).

**Comment by kelson42** [comment]
We can do that cross platform https://doc.qt.io/qt-5.9/qtspeech-index.html#getting-started

**Comment by kelson42** [comment]
@ShaopengLin While I clarify #594, you can work on this one.

**Comment by ShaopengLin** [comment]
QTextToSpeech is available for Qt 5, but not for Qt 6.4 and below. Until we migrate our Qt6 implementation to Qt 6.4+, I will have to keep it a Qt5 only feature.

**Comment by kelson42** [comment]
What stop us to implement for Qt 6.4+? We can implement the feature and then migrate our binaries to Qt 6.4.

**Comment by ShaopengLin** [comment]
The final app built isn't working properly as it uses openssl3 which doesn't seem compatible with our application?

@veloman-yunkan were you able to build it with Qt6.7/6.5? If not I can open an issue for the porting.

**Comment by kelson42** [comment]
We should not have (big) difficulties to build against Qt 6.4+, orherwise this means there is probably a problem somewhere else.
