### ISSUE TITLE
*.deb package for Linux users

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#444]
Hello.
I have a big request.
We have a file **_kiwix-desktop_x86_64_2.0.1-1.appimage_** for Linux users.
I downloaded it and tried to run it on Xubuntu 16.04.
Of course in the file **_Properties_** I checked the box next to **Allow this file to run as a program**.
But it didn't start!!!
So I ask you very much to release please for Linux users ***.deb** package.
Please let Linux users have a choice of what to download: ***.appimage** or ***.deb** package.

In addition, I tried to run ***. app image** on Linux Mint MATE and on Ubuntu 14.04 in Live modes.
The result was the same-the program did not start.
But it was **_Linux Mint MATE Live USB_** and  **_Ubuntu 14.04 Live USB_**.
I apologize for my poor English.

**Comment by kelson42** [comment]
@Ubuntu-2020 Xubuntu 16.04 is meanwhile quite old. I run it without any problem on Ubuntu 18.04 and 20.04. I would recommend to update your distribution. An alternative would be to give a try to our Flathub package https//flathub.kiwix.org which is an other official way to get Kiwix running on GNU/Linux.

**Comment by kelson42** [comment]
We don't provide `deb` for the moment, but there is already a ticket requesting it. See #204.
