### ISSUE TITLE
Improving the ZIM archive download page

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#447]
I think it will be good if the long table on [this page](https://wiki.kiwix.org/wiki/Content_in_all_languages) will be divided into several tables. In other words let the header appear with the following table of contents:
- Wiki
- - Wikipedia
- - Wiktionary
- - Wikivoyage
- - Wikiversity
- - Wikibooks
- - Wikisource
- - Wikiquote
- - Wikinews
- - Wikispecies
- Other resources

_PS: please tell me how to attach an image to a message?_

**Comment by kelson42** [comment]
Yes, this page is not user friendly. But we won't continue to build and improve it. The strategy is to use https://library.kiwix.org as entry point to provide downloadable content. Here is the ticket for the filtering by category.

**Comment by mgautierfr** [comment]
It seems that the ticket number for filtering by category is missing.
