### ISSUE TITLE
Displaying city names in the Book template

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#448]
I don't know how Kiwix displays books in other Wikipedia, but books in Russian Wikipedia in Kiwix without a hint about the city!
This is difficult to explain in words, especially when you do not know English well.
I would like to attach an image, but I don't know how.
Please tell me how to attach an image to a message?
I'll try to explain it in words.
Russian Wikipedia has a [template](https://ru.wikipedia.org/wiki/Категория:Шаблоны:Сокращения_городов_в_библиографии) with abbreviated names of cities.
For example, let's open the [Literature section](https://ru.wikipedia.org/wiki/Амазонка#Литература) in the article about the [Amazon river](https://ru.wikipedia.org/wiki/Амазонка).
Hover the cursor over the letter **М.** or the letter **Л.** and see popup hints: **Москва** and **Ленинград**.
But if you open this article in Kiwix, we will see the usual letters there: **М.** and **Л.**
In Other words, Kiwix doesn't display suggestions for abbreviated city names!
I hope I was able to explain.
If it is possible, make Kiwix display suggestions when you hover the cursor over the abbreviated city name in the Book template.

**Comment by Popolechien** [comment]
@Ubuntu-2020 I couldn't take a screenshot either but generally speaking you can simply drag-and-drop the image into the text box and github will upload it as well.

The question revolves around some Javascript that shows the city name when hovering over the letter.

Issue moved to Issue opened by @Ubuntu-2020
