### ISSUE TITLE
KiwixUbuntu18.04

### ISSUE THREAD

**Issue by Nicaraguakiwix** [kiwix/kiwix-desktop#452]
I have been using kiwix 1.0 in 32 and 64 bit( version 1.0) with Ubuntu 12/14/16 O/s configuration for years in Nicaraguan Schools. I downloaded theapp(s), store the app on a flashdrive  and then loaded them onto computers in Nicaragua. This has been of great help to the children to access the zim files. We are using free used laptops from FreeGeek and are mostly dual core (1.08 to 2.4 ghz)

This is a Charity serving 400 children that have no access to computer training( public schools do not supply any computer training). Recently i update some of the laptops to Ubuntu 18.04; kiwix 1.0 will no open on Ubuntu 18.04 so I have tried to load  Kiwix-desktop-86-64 2.010-1.   The file is downloaded and save; I then try to open it this Kiwix; I get message 'no program". I am doing someone wrong? if you could assist I would appreciate it? 
My goal would be to load Kiwix in the filed without internet however if the internet is necessary then we will adapt. I am not a programmer rather an educator.   thank you

**Comment by kelson42** [comment]
@Nicaraguakiwix Congratulation for your work in Nicaragua. Here, we love to hear about such stories. So you have downloaded the appimage file https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.0.1-1.appimage? If this is the case, I suspect you just need to put the execution flag on the file to run it like this:
```bash
$chmod +x kiwix-desktop_x86_64_2.0.1-1.appimage
```

**Comment by kelson42** [comment]
@Nicaraguakiwix I don't have heard anything back from you, so I guess the problem has been fixed :) Please reopen this ticket otherwise.
