### ISSUE TITLE
Open Link in New Tab (background)

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#455]
In a web browser, the user can right-click on the link and select **Open Link in New Tab** (or **Open Link in the background Tab**) from the drop-down list.
It will be nice if the user can do the same in **Kiwix**.

**Comment by jetownfeve21** [comment]
You can do this in Kiwix
![kiwix_open_newtab](https://user-images.githubusercontent.com/47149116/82807018-41cdc780-9e87-11ea-8da5-0cbcc004c606.gif)

**Comment by Ubuntu-2020** [comment]
I **can't open** the link in a **new tab** in the **Kiwix 2.0.1-1**:
![Kiwix-2 0 1-1-appimage](https://user-images.githubusercontent.com/65112331/82885448-e1558d80-9f4d-11ea-9b46-71e86951e689.gif)

If you use the **Kiwix 2.7.0 extension** in a **web browser**, then you can open it in a new tab, but it still opens an empty page with an **error**:
![Kiwix-2 7 0-Web](https://user-images.githubusercontent.com/65112331/82885886-6771d400-9f4e-11ea-8b1e-49334bd5688b.gif)

**Comment by jetownfeve21** [comment]
@Ubuntu-2020  Which kiwix-desktop version do you use (appimage or flathub) and which zimfile too ?

**Comment by Ubuntu-2020** [comment]
@jetownfeve21 - it was ***.appimage** (the top picture) and **Kiwix 2.7.0 extension** in a **web browser** (the bottom picture).
zimfiles: **wikipedia_ru_computer_maxi_2020-01.zim** and other **RU-zim** files.

**Comment by Ubuntu-2020** [comment]
I should note that in **Kiwix 2.0.1-1**, **Kiwix 2.0.3**, I can open the article in a new, or rather in the **background**, **tab**.
I accidentally noticed this by clicking on the link with the middle mouse button (wheel).
But in the **background tab**, all sections of the article are collapsed and I have to click on each section to read the text.
If possible, make sure that when you click the middle mouse button on the article, it would still open in the background tab, but that all sections of the article on it would be expanded.

**Comment by mgautierfr** [comment]
Which zim file are you speaking about ? (still wikipedia_ru_computer_maxi_2020-01.zim ?)
We do nothing at all about article's sections in kiwix-desktop.

**Comment by kelson42** [comment]
@mgautierfr I think this ticket is only about requesting a new context menu entry "Open Link in New Tab (background)". Not sure if this feature exists at all in Firefox.

**Comment by HanYoung-uwu** [comment]
I just noticed in git master, open some links in zim file *wikipedia_ab_all_nopic_2020-12.zim* will cause kiwix to freeze. Other links cause webengine to complain `Your file was not found` `ERR_FILE_NOT_FOUND`

**Comment by kelson42** [comment]
@HanYoung-uwu Can you please open an other ticket for that?

**Comment by kelson42** [comment]
I should reassess this issue, I believe we have implemented this….

**Comment by kelson42** [comment]
The function is implemented and works fine IMHO:
* Middle mouse click to open in new tab in background
* Use contextual menu to open new tab in foreground

**Comment by kelson42** [comment]
> I should note that in **Kiwix 2.0.1-1**, **Kiwix 2.0.3** (*.appimage), I can open the article in a new, or rather in the **background**, **tab**. I accidentally noticed this by clicking on the link with the middle mouse button (wheel). But in the **background tab**, all sections of the article are collapsed and I have to click on each section to read the text. If possible, make sure that when you click the middle mouse button on the article, it would still open in the background tab, but that all sections of the article on it would be expanded.

Seems related to https://github.com/kiwix/kiwix-desktop/issues/690
