### ISSUE TITLE
Feature request: Browse all of the pages of the archive one-by-one like a book

### ISSUE THREAD

**Issue by duytrung** [kiwix/kiwix-desktop#459]
Hello,
I'm wondering how to browse the archive I download as a book, such as the stackexchange topics, and hide the pages I have already read and taken notes. (as the topic and questions posted by users were arrange by date, etc...)

I have downloaded and used the zim on Manjaro linux and found that these functionalities have not been implemented.

Thank you very much

**Comment by kelson42** [comment]
Pages in a book are sorted in a linear fashion. A web site pages are not sorted and for sure not in a linear fashion. For this reason, the answer to your question is “no”. This is not doable.
