### ISSUE TITLE
Kiwix Desktop does not ignore other libraries when local library.xml is available

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#460]
I have a local Kiwix Desktop for Linux on my USB stick, with a local empty library.
```
$ find .
.
./library.xml
./kiwix-desktop_x86_64_2.0.1-1.appimage
kelson@camber:/media/kelson/Kiwix/Kiwix$ cat library.xml 
<library version="20110515"> </library>
```

But if I started, I don't get an empty local library:
![image](https://user-images.githubusercontent.com/1029718/84135784-ab82cf80-aa4a-11ea-9665-46d75a44bf99.png)

It seems to still read my other libraries.

**Comment by kelson42** [comment]
Will be fixed at the same time as #1166 IMHO

**Comment by sgourdas** [comment]
@kelson42 isn't this due to the monitor directory in settings? If you reset it, it should not transfer the zim files in the new `library.xml`.

```
All ZIM files in this directory will be automatically added to the library.
```

**Comment by kelson42** [comment]
@sgourdas AFAIK there is current a logic to load `library.xml` from local and profile directory if it exists. Can you please secure that it has been removed properly/it's not the case anymore?

**Comment by sgourdas** [comment]
@kelson42 it is not clear to me. From my experience and knowledge the only thing that loads information from other sources is through the "monitor" function. Am I wrong on this?

**Comment by kelson42** [comment]
@sgourdas I just verified and it works like in the documentation. To me this principle of mixing local and system configuration is made deprecated by the implementation of the `.portable` approach and should be therefore be removed.

**Comment by sgourdas** [comment]
@kelson42 the `KIWIX_DATA_DIR` option was removed with #1169.

I imagine you are referring to this and you are correct.
>As Kiwix Desktop can download and update the library.xml for you. It may be easier to use it. If your default library correspond to the files you want to put on your USB drive. You can simply copy the library.xml and all ZIM files in the user directory top the same directory than the Kiwix Desktop executable.

I will be coming back with a short PR to stop library loading from the executable's path as priority.

**Comment by sgourdas** [comment]
Should I also properly update the [relevant section](https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)#principle) after merging?

**Comment by kelson42** [comment]
@sgourdas Not necessary, this is a topic for #461
