### ISSUE TITLE
Simplification of portable USB creation

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#461]
For people wanting to distribute USB flash drives with Kiwix AND ZIM files, we have a working process. The process is documented at https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version).

The problem is that this is still a bit complicated. This ticket requires to simplify it and has this new workflow proposal: The local `library.xml` would be automatically based on ZIM files available at the same level like the binary if:
* There is no local `library.xml` already
* There is no other `library.xml` which include known local ZIM files.

**Comment by kelson42** [comment]
@mgautierfr Does that sound reasonable?

**Comment by mgautierfr** [comment]
Does it means that the "library discovering" order should be :

- `library.xml` in local directory.
- Default `library.xml` (in user directory)
- Temporary generated one from zim files in local directory ?

What happen if a user get a portable kiwix on a usb key and uses it on a computer where kiwix is already installed ?

**Comment by kelson42** [comment]
Another way to formulate the request is do like before and if there is no local `library.xml` and no other `library.xml` (on the system) which are not empty, then create the local `library.xml` from the local ZIM files (just aside the binary).

This does not change the discovery system order (even if a newly created `library.xml`) should be loaded obviously. The generation of the local `library.xml` is not temprary (even if this might be an idea....).

I think the local `library.xml` has anyway always priority on any other one of the system?! So this would not change.

**Comment by mgautierfr** [comment]
> Another way to formulate the request is do like before

This is not a spec :)
But it seems that you agree with the order I've given.

1.  Use `library.xml` in local directory if it exists
2. Use system/user `library.xml` if it exists
3. Move `library.xml` from old/wrong directory to new/good one. (Compatibility with a bug about a wrong directory on windows).
4. If no `library.xml` exists (local and system) and local zim files exists. Create a local `library.xml` with local zim files and use it.
5.  Else, create a system `library.xml` and use it.

What missing is the step 4.

**Comment by rocky-III** [comment]
Hi,
first of all: I LOVE KIWIX - thanks so much, I´, using it for quid some time now.

Now I want to use kiwix for offline content on a LIVE USB MX-Linux system with persistent. https://mxlinux.org/
unfortunate this does not work - I can install kiwik by appimage or flatpack and the app does start as well. I can download content but if I try to open the downloaded and installed ZIM files kiwix crashes all the time. This does also happend with smale ZIM files..

I studied this page:
https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)

any of this "Kiwix manage" files:
https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64.tar.gz
do not work
I can´t start them... don´t now why... do I need this files to work in order to open the ZIM files?
thanks for your Help.

**Comment by kelson42** [comment]
@rocky-III Can you please open a new ticket with the exact step-by-step procedure you do and then the result? We don't need the whole story we just need one concrete example of something not working, but in detail.

**Comment by rocky-III** [comment]
will open a new ticket - what kind of details you need? is there e.g. a log file I could look for?

**Comment by kelson42** [comment]
@rocky-III For example if it crash, what is written on the terminal.

**Comment by sgourdas** [comment]
@kelson42 is this a good next issue to work on?

> If no library.xml exists (local and system) and local zim files exists. Create a local library.xml with local zim files and use it.

If yes, is this what there is to do?

**Comment by sgourdas** [comment]
@kelson42 is this a good place to continue to?

**Comment by kelson42** [comment]
One #1166 is implemented things will looks differently. Basically, either the USB based Kiwix uses local stuff OR it is based on the system, but we don't mix them... and I think this is good enough. That said we still have to update the documentation and configure things in a way that for example the "data" directory is monitored. I will probably revamp this tickets one we have a PR about #1166.

**Comment by kelson42** [comment]
@sgourdas Here I believe there is two things to do:
* Updating the [wiki page](https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)) 
* Securing that the local storage directory for ZIM is monitored per default in portable mode. Is that the case?

**Comment by sgourdas** [comment]
> Securing that the local storage directory for ZIM is monitored per default in portable mode. Is that the case?

Which directory are you referring to with "local storage directory for ZIM"?

**Comment by kelson42** [comment]
> > Securing that the local storage directory for ZIM is monitored per default in portable mode. Is that the case?
> 
> 
> 
> Which directory are you referring to with "local storage directory for ZIM"?

./data

**Comment by sgourdas** [comment]
> > > Securing that the local storage directory for ZIM is monitored per default in portable mode. Is that the case?
> > 
> > 
> > Which directory are you referring to with "local storage directory for ZIM"?
> 
> ./data

This is not the case currently. What exactly is the point to this though? Wouldn't it be more beneficial to monitor a different location or maybe even clear it?

**Comment by kelson42** [comment]
> > > > Securing that the local storage directory for ZIM is monitored per default in portable mode. Is that the case?
> 
> > > 
> 
> > > 
> 
> > > Which directory are you referring to with "local storage directory for ZIM"?
> 
> > 
> 
> > ./data
> 
> 
> 
> This is not the case currently. What exactly is the point to this though? Wouldn't it be more beneficial to monitor a different location or maybe even clear it?

The point is that you can create an USB drive preconfigured with your content without having to create the library.xml manually. If "./data" is monitored automatically in portable mode then you just have to add ZIM files there and they will be available.

**Comment by sgourdas** [comment]
Got it. That is a great idea. Will make the PR soon.
