### ISSUE TITLE
Downloading multiple ZIM files at the same time (Win 10) returns error message

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#465]
Kiwix-desktop 2.0.1-1
It's a little bit disturbing because after closing the alert the download _does_ start
![image](https://user-images.githubusercontent.com/21675885/85829541-1e9a7e80-b78b-11ea-979c-a51b1db88396.png)

**Comment by kelson42** [comment]
@Popolechien May I ask you please to test again with https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0.3.zip ? I suspect more a platform issue here than a problem on Kiwix Desktop side. Which content was it exactly?

**Comment by Popolechien** [comment]
Tested on another Windows machine and though the application froze for a few seconds it all went fine (downloaded three large Wiktionaries (es/fr/it)).

**Comment by kelson42** [comment]
Yes, the freeze problem is handled here #87
