### ISSUE TITLE
bad location problem

### ISSUE THREAD

**Issue by abdoboussekoum** [kiwix/kiwix-desktop#467]
Hi I downloaded the "wikipedia_ar_all_maxi_2020-06" zim file , i try to read it by kiwix , but it told me that the location is bad and it cannot open the file
i hope that you have the solution of this problem because i need it 
NB; other wikimedia products are working good 
Thanks

**Comment by mgautierfr** [comment]
Hi @abdoboussekoum 

Do you have the exact error message ?

**Comment by abdoboussekoum** [comment]
i downloaded two times because i think that it could be corrupted during the download but the same problem
![image](https://user-images.githubusercontent.com/60586835/86032904-fc755a80-ba2f-11ea-8f8c-fe50af05bc66.png)

**Comment by abdoboussekoum** [comment]
other wikimedia products are working good
![image](https://user-images.githubusercontent.com/60586835/86033015-30508000-ba30-11ea-81f3-b6a5a632b53b.png)

**Comment by kelson42** [comment]
@mgautierfr @abdoboussekoum I woud wait next Kiwix-Desktop release and next ZIM release.

**Comment by abdoboussekoum** [comment]
so i should wait the update ? and delete this version? 
when i could be notified for the newest version plaise??

**Comment by kelson42** [comment]
@abdoboussekoum You will be notified when this ticket will be closed. Otherwise you have a relase feed for Kiwix-Desktop here https://mirrors.dotsrc.org/kiwix/release/kiwix-desktop/feed.xml

**Comment by mgautierfr** [comment]
Can you try with this version of kiwix-desktop please ? https://tmp.kiwix.org/ci/mgautier/wip_compile_windows/2020-06-30/kiwix-desktop_windows_x64_2020-06-30.zip

**Comment by kelson42** [comment]
@abdoboussekoum Thank you for your bug report. We confirm the bug. The problem is that we have generated a few ZIM files which are invalid and `wikipedia_ar_all_maxi_2020-06.zim` is one of them. The problem at the source of these corrupted ZIM files has been reported & fixed a few days ago, see https://github.com/kiwix/kiwix-tools/issues/389. There is nothing more you can do with this ZIM file, you can delete it. We will within a few days generated a new version of the file without this problem. We are really sorry for the inconvenience.

**Comment by abdoboussekoum** [comment]
hello @kelson42  i downloaded wikipedia_ar_all_maxi_2020-06.zim  for the third time still doesn't work
please , can you give an exact time beacause you closed the issue then i think that the problem is resolved

**Comment by kelson42** [comment]
@abdoboussekoum New ZIM file is available at https://download.kiwix.org/zim/wikipedia/wikipedia_ar_all_maxi_2020-07.zim

**Comment by abdoboussekoum** [comment]
i downloaded 
same error 
not opened
![image](https://user-images.githubusercontent.com/60586835/86862314-e0715900-c0c0-11ea-9a36-2633036a70de.png)

**Comment by kelson42** [comment]
@abdoboussekoum What is the exact version of your Kiwix Desktop?

**Comment by abdoboussekoum** [comment]
Now is good, i'm sorry for your efforts 
thanks for your time
