### ISSUE TITLE
can't read articles with + sign except if I replace it manually with %2B

### ISSUE THREAD

**Issue by AntiMortal** [kiwix/kiwix-desktop#472]
Hi. I noticed this bug in any kiwix zim file for example english wiktionary and english wikipedia.
Example article that produces this error in both these projects is: "C++"
When I convert C++ word in Notepad++ via plugins-mime tools-full url encode, and paste it into url, then it works!
It occurs when I host file via server and use Chrome or Firefox to view specific url.
Hope you will fix it...

**Comment by kelson42** [comment]
@AntiMortal Thank you for your bug report. I can not reproduce the problem with the latest version of Kiwix-Desktop and https://download.kiwix.org/zim/wikipedia/wikipedia_en_computer_maxi_2020-06.zim. Maybe you use old ZIM files which suffered from that bug. Otherwise (if the ZIM file is recent), please share with me the detailed step-by-step procedure to reproduce it.

**Comment by AntiMortal** [comment]
I did not say that bug occurs on kiwix desktop, but on Firefox, Chrome and other web browser when file is served by kiwix desktop or kiwix serve. Kiwix desktop app, even old one for xp, does not have this bug.

**Comment by kelson42** [comment]
@AntiMortal OK, so which article has a broken link to the article "C++". One example is enough.

**Comment by AntiMortal** [comment]
Links are not broken, but simply not readable. Can't be opened because of + sign in url. Just search for "C++" in wikipedia or wiktionary in some web browser. For example if I open this url in Firefox when I serve wiktionary: `http://192.168.43.48:8000/wiktionary_en_all_nopic_2020-03/A/C++`
then web page says:
`Not Found
The requested URL "/A/C " was not found on this server.`
Or find link to C++ on wikipedia article `General-purpose programming language`

**Comment by kelson42** [comment]
I don't have this older ZIM file but `http://localhost:8085/wiktionary_en_all_nopic_2020-04/A/C++` works fine for me.

**Comment by AntiMortal** [comment]
I tested windows xp kiwix 0.9. And I tested a month ago on new kiwix on windows 10. Did you try both chrome and firefox? Unfortunately I can't anymore download any zim files or install windows 10 or new kiwix, because I switched to xp.

**Comment by kelson42** [comment]
Kiwix 0.9 is deprecated. Please use latest version of Kiwix Desktop and ZIM files and if it still fail with them, please reopen this ticket (or open a new one).
