### ISSUE TITLE
Latest Wikipedia_en_all_maxi_2020-06.zim is Corrupted File!

### ISSUE THREAD

**Issue by OrionRafi3345** [kiwix/kiwix-desktop#473]
![Screenshot (20)](https://user-images.githubusercontent.com/47520335/86518395-9cc5e780-be53-11ea-912a-07ec67651edb.png)
![Screenshot (22)](https://user-images.githubusercontent.com/47520335/86518397-9e8fab00-be53-11ea-854a-da333dc68be4.png)

Latest "wikipedia_en_all_maxi_2020-06.zim"  zim file has issue! its the corrupted one, probably corrupted during the zim generation!
See the difference! I already checked every valid working zim file. and try to compare it with "wikipedia_en_all_maxi_2020-06.zim" i notice every valid zim file contains some value after (61 69 6E)... But in "wikipedia_en_all_maxi_2020-06.zim" those values are only zeroes! I downloaded it through torrent. this zim file Doesn't recognize by kiwix, when i try to open this file just a blank white page appear with "about/blank" title in kiwix

**Comment by kelson42** [comment]
How does that not respect the ZIM open specification?

**Comment by OrionRafi3345** [comment]
I dont have any problem,  the file show respect the zim specification or not! The main problem is the file itself not work! 

> How does that not respect the ZIM open specification?

I dont have any problem,  the file show respect the zim specification or not! The main problem is the file itself not work!

**Comment by kelson42** [comment]
What do you do exactly? What do you get? What do you expect?

**Comment by OrionRafi3345** [comment]
I follow this step
1)Download the file through torrent!
2)Launch Kiwix and try to open the downloaded content
3) The file Doesn’t  work,  just in kiwix title it shows "about/blank"
4)Then I try to investigate what's the problem is. With a hex editor! 

I expected the file would work!

**Comment by OrionRafi3345** [comment]
I just expected the file would work! And the reason is the file is corrupted! Thats all -_-

**Comment by OrionRafi3345** [comment]
And its not that the file is corrupted during the download! I think the scrapper used to generate this zim, gave that corrupted file as an output!

**Comment by kelson42** [comment]
“Won’t work” tells me nothing and if you don’t answer my questions nobody can help you. Here is a guide about how to report a bug properly https://github.com/kiwix/overview/blob/master/REPORT_BUG.md. Last attempr, what is your version of Kiwix Desktop?

**Comment by OrionRafi3345** [comment]
> “Won’t work” tells me nothing and if you don’t answer my questions nobody can help you. Here is a guide about how to report a bug properly https://github.com/kiwix/overview/blob/master/REPORT_BUG.md. Last attempt, what is your version of Kiwix Desktop?
Version 2.0
This one : http://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip

**Comment by kelson42** [comment]
Please secure you use latest version 2.0.3 http://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0.3.zip

**Comment by OrionRafi3345** [comment]
Thanks! But why the website give me the old version instead of this?
