### ISSUE TITLE
Fonts appear to be non-free

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-desktop#474]
Both of the bundled fonts, Segoe UI and Ubuntu appear to be under a non-free license, incompatible with Kiwix's GPL license.

Segoe UI is a font licensed by Microsoft and as far as I can tell, not available under any free license. [Wikipedia](https://en.wikipedia.org/wiki/Segoe#Related_fonts) mentions that Selawik is a similar font by Microsoft, that is released under the free Open Font License. See https://github.com/microsoft/Selawik.

Ubuntu font is licensed under the Ubuntu Font License, which Debian and Fedora both consider to be non-free. See <https://en.wikipedia.org/wiki/Ubuntu_(typeface)#Ubuntu_Font_Licence>. I didn't immediately find any listing of similar free fonts.

**Comment by kelson42** [comment]
@legoktm OK, that is a bit of a silly error we made here.
