### ISSUE TITLE
Don't encode current date in build

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-desktop#476]
Encoding the current date in the build makes it non-reproducible - see https://reproducible-builds.org/

They recommend getting the date from something consistent, e.g. the timestamp of the git commit: `git log -1 --pretty=%ct` (see https://reproducible-builds.org/docs/source-date-epoch/).

However, as pointed out in https://github.com/kiwix/kiwix-desktop/issues/470#issuecomment-652401126 always shelling out to git (for this and the pre-existing GIT_VERSION) is problematic because packages for Debian/Fedora are building from a tarball, not git.

My suggestion is to do something like:
```bash
BUILD_DATE="$(date --utc --date="@${SOURCE_DATE_EPOCH:-$(git log -1 --pretty=%ct)}")"
BUILD_VERSION="${BUILD_VERSION:-$(git describe --dirty=* --tags --always)}"
```

Then it would be the packagers responsibility to set $SOURCE_DATE_EPOCH and $BUILD_VERSION, and for normal builds, it falls back to using the info from git.

cc @xvitaly

**Comment by kelson42** [comment]
@mgautierfr This is something I have not strong opinion (I mostly don't know what depends exactly on this strings). Please let us know what you want.

**Comment by xvitaly** [comment]
I agree. Please don't use direct git calls, because we use the release tarballs, which has no git metadata.

On Fedora we need to patch this rows manually.
