### ISSUE TITLE
Provide a more specific error if kiwix-serve isn't available

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-desktop#477]
If `kiwix-serve` isn't available, when you click "Start server" an error box just pops up and says "An error has occurred!"

Ideally it would say something more like "kiwix-serve not found." Bonus points if it is trivial for me in Debian to add "Please install it with `sudo apt install kiwix-serve`".

**Comment by kelson42** [comment]
Agree, even if `kiwix-serve` is a hard dependence of kiwix-desktop.

**Comment by legoktm** [comment]
Is kiwix-tools needed anymore after bbfbf2bf1eab766b0275f0f2850622a9c79cb3d8?

**Comment by kelson42** [comment]
@legoktm No, kiwx-tools is not necesary at all. We start the HTTP daemon directly via the libkiwix. Kiwix-tools should be removed from the dependences. This ticket is now invalid.
