### ISSUE TITLE
*.appimage doesn't start in Ubuntu Studio 20.04

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#480]
**Kiwix 2.0.1-1** (*.appimage) doesn't start in **[Ubuntu Studio](https://en.wikipedia.org/wiki/Ubuntu_Studio) 20.04**.

**Comment by kelson42** [comment]
This is an old version, please test with latest version.

**Comment by Ubuntu-2020** [comment]
>@kelson42 This is an old version, please test with latest version.

**Kiwix 2.0.3** (*.appimage) doesn't start in **[Ubuntu Studio](https://en.wikipedia.org/wiki/Ubuntu_Studio) 20.04** (Xfce).

**Comment by kelson42** [comment]
@Ubuntu-2020 It works on Ubuntu 20.04, surprised it does not work with Ubuntu Studio 20.04. Can you please start it from the command line and share the full log? Do you use Ubuntu 20.04 in a VM?

**Comment by Ubuntu-2020** [comment]
>@kelson42 Do you use Ubuntu 20.04 in a VM?

No. This is not a virtual machine! The Ubuntu Studio operating system was installed on the hard disk!

>@kelson42 Can you please start it from the command line and share the full log?

I'm not a hacker. If you explain in detail how to do this, then I will try to launch Kiwix from the terminal.
