### ISSUE TITLE
*.appimage doesn't start in Ubuntu MATE 20.04

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#481]
**Kiwix 2.0.1-1** (*.appimage) doesn't start in **[Ubuntu MATE](https://en.wikipedia.org/wiki/Ubuntu_MATE) 20.04**.

**Comment by kelson42** [comment]
Please https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.0.3.appimage like I said in #480

**Comment by kelson42** [comment]
If it still fails iwth 2.0.3 on Mate, please update #393
