### ISSUE TITLE
Adding a horizontal line

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#488]
**Kiwix 2.0.3** (*.appimage).
I suggest adding a horizontal line to the drop down list. This way the lines with images will be better separated.
![Add-line](https://user-images.githubusercontent.com/65112331/87400006-e7b4cd00-c5c0-11ea-922d-dd372f214eaf.gif)

**Comment by kelson42** [comment]
I'm not sure this is really an improvement. Firefox does not have that for example. I think we should as well remove "Copy Image URL" which is useless.

**Comment by kelson42** [comment]
We could try to make it.

**Comment by kelson42** [comment]
@juuz0 Do you think this is a good idea? Would you be able to implement this ine quickly please?

**Comment by juuz0** [comment]
@kelson42 There are already horizontal lines for groups (Forward/Backward as one group, Image options as another)

https://user-images.githubusercontent.com/26814569/147381589-de0c913e-a0cc-4600-9325-a735332e2c5d.mp4

Do you mean to add after every option? Not sure if that will be any good, havent seen any designs do that.
I can implement if you want though :+1:

**Comment by kelson42** [comment]
@juuz0 I'm not sure how the first screencast has been obtain, but from your comment, it seems this ticket has already been implemented?!

**Comment by juuz0** [comment]
@kelson42 Yes 👍

**Comment by kelson42** [comment]
@juuz0 Good :) Then I close the ticket!
