### ISSUE TITLE
Save Image - answer

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#489]
**Kiwix 2.0.3** (*.appimage).
While reading the **ZIM** file, the user can right-click on an image and select the item `Save Image`.
After successfully saving the image a message appears stating that the document was saved successfully:
![The-document-has-been-downloaded-2 0 3](https://user-images.githubusercontent.com/65112331/87531593-9711a280-c69a-11ea-87cb-5f8354c0a858.png)

But this is not a **document** but a **picture**! So I suggest replacing the word **document** with **picture** / **image**.

**Comment by kelson42** [comment]
@Ubuntu-2020 In your case this is an image, but it can be anything else, like an Epub for example.
