### ISSUE TITLE
Kiwix must check for available space for download drive, not system drive.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#492]
It seems Kiwix checks space only on system drive. I have enough space on the disk download directory's disk, but no enough on system disk. And I got "not enough storage available" error message.
(Windows 7, Kiwix Desktop x64 2.0.1-1)

_Originally posted by @autolyk in https://github.com/kiwix/kiwix-desktop/issues/170#issuecomment-639015770_

**Comment by autolyk** [comment]
@kelson42 Unfortunately, it's still there :(
