### ISSUE TITLE
Kiwix Desktop 2.0.4 extremely unstable on Windows 10

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-desktop#493]
Having just downloaded and unzipped 2.0.4 from Kiwix.org download page, the app crashed and exited three times consecutively on opening (after about 3 seconds each time). On the fourth attempt, it remained open, but when I tried to open the latest full Wikipedia English file, it crashed and exited again.

This is on Windows 10 Pro 64bit version 2004 (that is the latest fully patched and updated version of Windows 10).

**Comment by kelson42** [comment]
Which ZIM file do you have in your local library?

**Comment by Jaifroid** [comment]
I tried to open `wikipedia_en_all_maxi_2020-06.zim` from a directory using the open directory icon.
But now the app won't open again, and is showing gobbledygook on the Library page. (which stays open for 2-3 seconds before crashing and closing). I managed to get a screenshot while it was briefly open. See below. I suspect the issue is to do with automatic scanning of folders. Maybe scanning should be an option launched by user action and limited to a picked folder (at least on Windows).

![image](https://user-images.githubusercontent.com/4304337/87961533-b864fb00-caad-11ea-951c-da0e20a96a47.png)

**Comment by kelson42** [comment]
@Popolechien You have no problem on your windows I guess with this particular ZIM file?

**Comment by kelson42** [comment]
@mgautierfr Might that be we have a kind of problem with the translation file?

**Comment by Popolechien** [comment]
@kelson42 All good here.

**Comment by kelson42** [comment]
@Jaifroid What is the path where Kiwix Desktop is located?

**Comment by Jaifroid** [comment]
It's in `C:\UTILS\kiwix-desktop_windows_x64_2.0.4\`.

In `C:\UTILS\` I also have the 2.0_beta5 version, `C:\UTILS\kiwix-desktop_windows_x64_2.0-beta5\`, and that loads without crashing (though obviously it struggles with recent ZIM files due to the relocation of the URL Pointer List.

**Comment by Jaifroid** [comment]
I've so far tested all the 2.0.x series.

* **Version 2.0** doesn't crash when I launch it, but it does crash as soon as I try to open any ZIM archive with it using the Folder icon (including old, standard ZIM archives) -- please see below for how I *can* open a ZIM file with this version.
* **Versions 2.0.1 and above** all crash approx 2-3 seconds after the window appears (and all briefly show the window as in screenshot above, with what look like template placeholders).

Curiously, although Version 2.0 crashes when I try to pick a ZIM file (using the open-folder icon, or the three dots (see screenshot below), if I *first run Version Version 2.0_beta 5*, and pick the ZIM file, then it subsequently appears in the Version 2.0 library. I can then open it successfully by clicking "Open" next to the library entry.

![image](https://user-images.githubusercontent.com/4304337/88067647-29b4b480-cb67-11ea-9c98-a5550bce2918.png)

**Comment by mgautierfr** [comment]
What is the content of `C:\Users\<user>\AppData\Roaming\kiwix` directory and `C:\Users\<user>\AppData\Roaming\kiwix\library.xml` ?

**Comment by Jaifroid** [comment]
@mgautierfr Conents of `...\Roaming\kixix`:

![image](https://user-images.githubusercontent.com/4304337/88069773-d132e680-cb69-11ea-9671-3cbc3ece4600.png)

Contents of `library.xml` (after cutting out all the encoded favicon data to make it possible to paste it here):

![image](https://user-images.githubusercontent.com/4304337/88070039-2111ad80-cb6a-11ea-9098-b069cba6c939.png)

**Comment by mgautierfr** [comment]
Can you remove the line for the book `wikipedia_en_all_maxi_2020-06.zim` and confirm that kiwix-desktop works again ?

---
(Textual pasts are better than screenshot :) )

**Comment by Jaifroid** [comment]
@mgautierfr Just removing that entry made no difference.
However, deleting the entire Kiwix directory in `..,\AppData\Roaming\` allows the latest version (2.0.4) to launch correctly and open archives. Thank you! 😊
Now the library shows 5 ZIM archives, though in fact I have many more ZIM archives in `D:\WIKI\`. It has not found the most recent full English Wikipedia (2020-06), but the older one (2018-06) - both in same directory.
I guess the bug causing the app to crash is in the library parsing routine.
Sorry about screenshots yesterday, I was in a hurry.

**Comment by mgautierfr** [comment]
> Now the library shows 5 ZIM archives, though in fact I have many more ZIM archives in D:\WIKI\

The content manager list what is in the `library.xml`. Not what is in the fs.
(But opening a file and go to `D:\WIKI\` in the explorer dialog should work)
When you open a file, it is automatically added to the `library.xml`  (and so, displayed the next time you launch `kiwix-desktop`)

> I guess the bug causing the app to crash is in the library parsing routine.

I don't know what append here :/
A bug in the reading of a zim file should hide the zim file (or crash the app). But not something like your first screenshot.

**Comment by Jaifroid** [comment]
@mgautierfr To clarify, the first screenshot was shown only for about 2-3 seconds before the app crashed, so I still think it was trying to read ZIM files in the library.xml and crashed the app for whatever reason.

With the app now stable, on launch for about 0.25s I see a brief flash of that screen before the fields are filled, so that screen appears to be a template with placeholders that get filled after library.xml is successfully read. In my first attempts, clearly the crash was happening while verifying files listed in the existing library.xml, so it got stuck on that screen before crashing.

**Comment by mgautierfr** [comment]
Ok.
But one of your file in the library.xml is probably wrong/buggy it would be nice if you can try to open them to know which one.

**Comment by Jaifroid** [comment]
@mgautierfr I think I can now narrow this bug down to a crash while reading a corrupt ZIM archive, as you suggested. The new full English Wikipedia (`wikipedia_en_all_maxi_2020-06.zim`), which I had downloaded with a BitTorrent client, had a minor corruption issue in one of the sectors downloaded, affecting titles from `Dad` to `Deir` in the Title Pointer List (or maybe URL pointer list). The file was readable (by both Kiwix JS and Kiwix Desktop) but it caused a crash in Kiwix Desktop (not Kiwix JS) whenever I tried to search for a title. On doing a full file recheck with qBitTorrent, it identified the corrupt sector and re-downloaded it.

Nevertheless, it's clearly undesirable for Kiwix Desktop to crash when encountering a buggy ZIM file, especially if it is not actually trying to load that file. Maybe more robust code is needed to catch exceptions and skip the operation in course?

There is one thing that puzzles me: the crash in 2.0.4 occurred *before* I ever tried to open `wikipedia_en_all_maxi_2020-06.zim` in Kiwix Desktop (and Kiwix JS does not use `library.xml`). It appears in above `library.xml` only because I **subsequently** tried out an old copy of 2.0 beta 5 to see if the crash was a new issue or not.  There is no code to scan for common ZIM archives in the file system, like there is in Android?

**Comment by kelson42** [comment]
@Jaifroid Thank you again for helping narrowing down the problem. There is no question about the fact that there is a bug here. Kiwix Desktop should not crash. Please keep a copy of the corrupted ZIM file (it still not too late).

**Comment by Jaifroid** [comment]
@kelson42 I fear qBitTorrent has now repaired the (huge) file as I forced a recheck yesterday, and the missing title pointers / url pointers are no longer missing.... I guess the only thing now would be "theoretically" to check the code for potential fail points in the archive scanning process (e.g. when verifying library.xml entries). and add some more error trapping Clearly the verification of library.xml (or any other automated scanning like in the Android app) seems to depend on reading part of the ZIM file, or accessing ZIM metadata table. Sorry about that!

**Comment by kelson42** [comment]
@mgautierfr Do you what to do next?

**Comment by kelson42** [comment]
We can not do more unfortunately.
