### ISSUE TITLE
Language filter does not apply on local library

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#498]
**Kiwix 2.0.4** (*.appimg).
Sorting by language in the library doesn't work.
I'm sorry that there is no picture. I have two files in my **Library**.
One ZIM file from the **Russian Wikipedia**. The second ZIM file is from the **English Wikipedia**.
In the side column, I chose **German**, then **English** language, and nothing happened.
I think that when choosing **German**, the two ZIM files mentioned above should have disappeared from the **library**.
And when choosing **English**, the ZIM file from the English Wikipedia should have appeared.
But nothing happened.

**Comment by kelson42** [comment]
I confirm

**Comment by HanYoung-uwu** [comment]
I'd see this as a feature not implemented rather than bug. ZIM file format doesn't store language information so there isn't a reliable way to determine the language of a local file. The current language filter set the URL query language parameter, the language information is stored remotely. However, it's still possible to parse the file name and try to determine the language, then implement the feature to filter the local files by language.

**Comment by mgautierfr** [comment]
> ZIM file format doesn't store language information so there isn't a reliable way to determine the language of a local file

Yes, it is. You can access it from the reader (https://github.com/kiwix/kiwix-lib/blob/master/include/reader.h#L184) and from the book (https://github.com/kiwix/kiwix-lib/blob/master/include/book.h#L56)
The local library also handle it and you can filter it using the language (as for the remote library) (https://github.com/kiwix/kiwix-lib/blob/master/include/library.h#L99)

---

In fact, the remote library runs the exact same code that the local library, the "remote languages" are determined using the languages stored in the zim files.

**Comment by HanYoung-uwu** [comment]
> > ZIM file format doesn't store language information so there isn't a reliable way to determine the language of a local file
> 
> Yes, it is. You can access it from the reader (https://github.com/kiwix/kiwix-lib/blob/master/include/reader.h#L184) and from the book (https://github.com/kiwix/kiwix-lib/blob/master/include/book.h#L56)
> The local library also handle it and you can filter it using the language (as for the remote library) (https://github.com/kiwix/kiwix-lib/blob/master/include/library.h#L99)
> 
> In fact, the remote library runs the exact same code that the local library, the "remote languages" are determined using the languages stored in the zim files.

Sorry, I must have missed it. I'll try to implement it.
