### ISSUE TITLE
PPA deb package for Ubuntu 18.04 / Bionic

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#503]
Hello,
In the #204 issue you proposed me to test the ppa. I did. But no kiwix-desktop package is available. And I use Bionic, the ppa begins with eoan. Maybe you can add the bionic.

**Comment by kelson42** [comment]
@legoktm Would you be able to help @LAfricain please? What is the exact reason to not have 18.04 in the PPA?

**Comment by legoktm** [comment]
#501 adds kiwix to the PPA. I'll look into adding bionic support, mostly making sure all of our dependencies are available.

**Comment by kelson42** [comment]
@legoktm Considering that 18.04 is LTS and therefore broadly deployed, I believe this would be really good to provide packages for it.

**Comment by kelson42** [comment]
We have now the libkiwix in the PPA, so we just need the package for kiwix-desktop for bionic.

**Comment by kelson42** [comment]
@legoktm This is great. Thank you.
@LAfricain Let us know please if you have any problem

**Comment by LAfricain** [comment]
I have not yet a kiwix-desktop package for bionic.

**Comment by kelson42** [comment]
@legoktm It is true that I still see nothing in https://launchpad.net/~kiwixteam/+archive/ubuntu/dev. You know why?

**Comment by legoktm** [comment]
It's under the name `kiwix`, where it has the version `2.0.4+git202009011314.8bfbc1e~bionic`. 

And it'll appear in the release PPA whenever a new tag/release happens.
