### ISSUE TITLE
Quits after one or two articles

### ISSUE THREAD

**Issue by aweasadbek** [kiwix/kiwix-desktop#507]
I'm using Ubuntu Desktop 20.04.1 LTS.
After loading one or two articles properly, kiwix-desktop gives the following error and quits:
`
Library directory : "/home/aweasadbek/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
js: Uncaught SyntaxError: Unexpected end of input
js: Uncaught SyntaxError: Unexpected token .
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
terminate called after throwing an instance of 'zim::ZimFileFormatError'
  what():  Invalid compression flag
zsh: abort (core dumped)  ./kiwix-desktop_x86_64_2.0.3.appimage
`
I'm using this dump http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2020-06.zim.
Also the same dump works without any problems with Kiwix browser extension.

With Phet dump kiwix-desktop works without any problem.

**Comment by kelson42** [comment]
@aweasadbek Please use latest version https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.0.4.appimage

**Comment by aweasadbek** [comment]
I first used kiwix-desktop version 2.0.2 - same problem mentioned above. Then used this version https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64.appimage. Also tried one that you provided but same problem as above.

**Comment by mgautierfr** [comment]
> 'zim::ZimFileFormatError' what(): Invalid compression flag

Can you do a `zimcheck -C wikipedia_en_all_maxi_2020-06.zim` (Using zim-tools here http://download.openzim.org/release/zim-tools/) ?

If it fails it means that your file is corrupted.

**Comment by aweasadbek** [comment]
[INFO] Checking zim file ../wikipedia_en_all_maxi_2020-06.zim
[INFO] Verifying Internal Checksum.. 
  [ERROR] Wrong Checksum in ZIM file
[ERROR] Invalid checksum :
  ZIM File Checksum in file: f1e101af77b6a67c3debe463b6056ae1

[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 1815 seconds.

**Comment by aweasadbek** [comment]
So the problem is in wikipedia_en_all_maxi_2020-06.zim.
Is it the case with my copy or the file in the server was already corrupted?

**Comment by mgautierfr** [comment]
@kelson42 may confirm, but I think we check all zim file before putting them on the server.

**Comment by aweasadbek** [comment]
Anyone can confirm that http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2020-07.zim is cont corrupted.
Please help, cause I have low internet speed to re-download!

**Comment by mgautierfr** [comment]
md5sum of wikipedia_en_all_maxi_2020-07.zim on the server is 5957e19fec43cc3e7304049b1273ad67

**Comment by kelson42** [comment]
We don’t have this ZIM file hosted, bit this is improbable that the ZIM file was corrupt.
