### ISSUE TITLE
Search bar doesn´t appear in Kiwix 2.0.4/3

### ISSUE THREAD

**Issue by runikk** [kiwix/kiwix-desktop#512]
Hi, I downloaded Kiwix desktop windows version from your webpage yesterday, the packet is called "kiwix-desktop_windows_x64_2.0.4" I excuted it, and I tried to open "wikipedia_es_all_maxi_2020-08.zim" but the search bar doesn´t appear. 

Then I installed kiwix extension 2.5.0.xpi for Firefox, and it worked fine, the search bar appeared.

Also, I could see, that in the desktop version, if I go to Help/About kiwix, instead version 2.0.4, it shows version 2.0.3

Then I went to Sourceforge, and I also tried desktop version 2.0.1-1, but it crashed inmediately when I try to open the .zim file.

Best regards,

**Comment by runikk** [comment]
Hi Kelson, thank you. I found what happened to me.

Time response of the searching.

I used to use an old version of kiwix, and it was really fast, but the new 2.0.4 version stucked with two searchs and I thought that I wasn´t using the righ place to search, but in fact, I wasn´t waiting enough time for the results.

I did the same searching in firefox, and it shows the first 50 results very quickly (almost instant). But the result is totally different than in the desktop app. I attach you a snapshot.

If I search for example "ciencia" (science) in desktop app, it seems that it looks for this word in every article of the .zim archive. But if I do the same search in the firefox extension, it shows me the first 50 articles that have this term in the title (that it is much better and user friendly)

So if I search "ciencia" and hit enter in the desktop app, the status bar said "the program is not responding ", but it is working in the background... and I should wait 20-30sec, this is why I thought that I wasn´t using it properly, because it stucked in every search, but in fact, it didn´t.
![ciencia](https://user-images.githubusercontent.com/70091036/90984428-2c933280-e575-11ea-81a7-38213691d970.png)

**Comment by kelson42** [comment]
If you type "cienca" you should get quickly the list of article titles with that word, like with Kiwix JS.

Your seconf screenshot shows the fulltext search which is slower but does not exist at all in Kiwix JS. We work currently to make it faster.
