### ISSUE TITLE
Fail to show many English characters in Chinese Wikipedia

### ISSUE THREAD

**Issue by wdscxsj** [kiwix/kiwix-desktop#520]
- Kiwix version: 2.0.4
- Affected local file: wikipedia_zh_all_maxi_2020-07.zim
- OS: Windows 10 Enterprise 2004 Simplified Chinese Edition

On my machine, Kiwix often fails to show English characters in the Chinese Wikipedia zim. 

For example, this is the display of the online item "纽约" (New York) in Chrome:

![ny-chrome](https://user-images.githubusercontent.com/863369/93014443-bfa71180-f5e3-11ea-85c8-f39a71db0853.png)

And this is the same item displayed in Kiwix:

![ny-kiwix](https://user-images.githubusercontent.com/863369/93014449-c2096b80-f5e3-11ea-85b2-005dd1b86711.png)

Kiwix doesn't provide a "devtools" to examine the zim data, but it's unlikely that the English text is missing in the zim. Judging from the online page, text snippets **with a `lang` attribute**, like `<span lang="en">City of New York</span>` and `<span lang="la">Novum Eboracum</span>`, fail to render properly. "Plain" text like `41 °C` is OK.

By the way, the English Wikipedia works perfectly on the same machine. And it'll be so nice if **custom CSS** can be allowed, because the default choice of Chinese fonts is not quite visually appealing. Thanks.

**Comment by kelson42** [comment]
@wdscxsj Thank you fr your bug report. To better see the HTML of an article you can start the server mode and look via your usual Web browser.

**Comment by wdscxsj** [comment]
@kelson42 Thank you so much for the pointer! It's quite surprising to see the English characters are missing from the DOM:

![1](https://user-images.githubusercontent.com/863369/93015059-bd938180-f5e8-11ea-998a-a19d5dd97e48.png)

and the page source:

![2](https://user-images.githubusercontent.com/863369/93015055-b9fffa80-f5e8-11ea-848c-f60e801e993a.png)

Any way to directly check the zim data?
