### ISSUE TITLE
meson.build:28:0: ERROR:  Native dependency 'libzim' not found, yet it does exists

### ISSUE THREAD

**Issue by gnusupport** [kiwix/kiwix-desktop#526]
I have installed "libzim" in /package/lib/libzim and then stowed it by using stow to /ust/local/lib and I did "ldconfig" after. I can see:

/usr/local/lib/libzim.so  /usr/local/lib/libzim.so.6  /usr/local/lib/libzim.so.6.2.2 

there.

Then I went to kiwix-lib directory, and tried:

meson --prefix=/package/lib/kiwix-lib . build 

but I got this:

meson --prefix=/package/lib/kiwix-lib . build 
The Meson build system
Version: 0.47.2
Source dir: /home/data1/protected/Programming/git/kiwix-lib
Build dir: /home/data1/protected/Programming/git/kiwix-lib/build
Build type: native build
Project name: kiwix-lib
Project version: 9.4.0
Native C++ compiler: ccache c++ (gcc 6.3.0 "c++ (GCC) 6.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency icu-i18n found: YES 59.1

meson.build:28:0: ERROR:  Native dependency 'libzim' not found

A full log can be found at /home/data1/protected/Programming/git/kiwix-lib/build/meson-logs/meson-log.txt

This is beacause pkg-config is not finding it. But library is there. 

Does anybody know what to do to make it work?

Kiwix is important project. I am using Hyperbola GNU/Linux-libre and it does not have some packages. So I have to build it myself.

**Comment by kelson42** [comment]
@legoktm Might that be that we have forgotten to package th `.pc` file for the libzim?
