### ISSUE TITLE
cannot start appimage, it should not depend of my OS (Hyperbola GNU/Linux-libre)

### ISSUE THREAD

**Issue by gnusupport** [kiwix/kiwix-desktop#527]
admin-> ./kiwix-desktop_x86_64_2.0.4-1.appimage
./kiwix-desktop_x86_64_2.0.4-1.appimage: /usr/lib/libQt5Core.so.5: version `Qt_5.9' not found (required by ./kiwix-desktop_x86_64_2.0.4-1.appimage)
./kiwix-desktop_x86_64_2.0.4-1.appimage: /usr/lib/libQt5Core.so.5: version `Qt_5.9' not found (required by /home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libQt5WebEngineWidgets.so.5)
./kiwix-desktop_x86_64_2.0.4-1.appimage: /lib/libm.so.6: version `GLIBC_2.27' not found (required by /home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libQt5WebEngineCore.so.5)
./kiwix-desktop_x86_64_2.0.4-1.appimage: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libzim.so.6)
./kiwix-desktop_x86_64_2.0.4-1.appimage: /lib/libc.so.6: version `GLIBC_2.27' not found (required by /home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libsystemd.so.0)

**Comment by kelson42** [comment]
@mgautierfr why there is such a dependence with the system?

**Comment by mgautierfr** [comment]
One possibility is that we generate the appimage on a "recent" ubuntu distribution (bionic) to use available Qt packages. On old distribution the glibc may not be available (not the needed version). But bionic glibc is 2.27 and Hyperbola glibc seems to be 2.30 (https://www.hyperbola.info/packages/core/x86_64/glibc/). So it should not be this problem.

One another possibility is that the system is 32bits and we are 64bits only (for kiwix-desktop).

**Comment by gnusupport** [comment]
* Matthieu Gautier <notifications@github.com> [2020-10-05 13:06]:
> One possibility is that we generate the appimage on a "recent" ubuntu distribution (bionic) to use available Qt packages. On old distribution the glibc may not be available (not the needed version). But bionic glibc is 2.27 and Hyperbola glibc seems to be 2.30 (https://www.hyperbola.info/packages/core/x86_64/glibc/). So it should not be this problem.
> 
> One another possibility is that the system is 32bits and we are 64bits only (for kiwix-desktop).

My system is 64 bits.

I see Qt files missing, and if you make appimage only for Ubuntu, that
narrows the usability, isn't it?

I was expecting I will get everything in the appimage required to be
run.

**Comment by mgautierfr** [comment]
> I see Qt files missing, and if you make appimage only for Ubuntu, that
narrows the usability, isn't it?
>
> I was expecting I will get everything in the appimage required to be
run.

We are not doing the appimage only for ubuntu. We are doing the appimage on ubuntu.
The appimage is containing (should contains) everything but the low glibc/libc++ libraries (and opengl drivers, ...).
So the only known constraint is that your (running) glibc must support our (building) glibc.
And it should be the case as you are using a glibc 2.30 and we are building using glibc 2.27

So this is probably a new issue. It seems that `/home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libQt5WebEngineWidgets.so.5` try to load the native libQt5Core (`/usr/lib/libQt5Core.so.5`) but it should load the packaged one.

Maybe @probonopd has a quick idea. Else we will have to investigate what's going on.

**Comment by gnusupport** [comment]
* Matthieu Gautier <notifications@github.com> [2020-10-05 15:14]:
> > I see Qt files missing, and if you make appimage only for Ubuntu, that
> narrows the usability, isn't it?
> >
> > I was expecting I will get everything in the appimage required to be
> run.
> 
> We are not doing the appimage only for ubuntu. We are doing the appimage on ubuntu.
> The appimage is containing (should contains) everything but the low glibc/libc++ libraries (and opengl drivers, ...).
> So the only known constraint is that your (running) glibc must support our (building) glibc.
> And it should be the case as you are using a glibc 2.30 and we are
> building using glibc 2.27

Obviously it is asking for Qt. 

> So this is probably a new issue. It seems that
> `/home/data1/protected/tmp/.mount_kiwix-YFCNu3/usr/bin/../lib/libQt5WebEngineWidgets.so.5`
> try to load the native libQt5Core (`/usr/lib/libQt5Core.so.5`) but
> it should load the packaged one.

I mean that.

**Comment by mgautierfr** [comment]
> Obviously it is asking for Qt.

The first error is about Qt (`/usr/lib/libQt5Core.so.5`) and we should load the packaged one (I've check `libQt5Core.so.5` is present in the appimage). The question is why we are not loading it.
The other errors are about ` /lib/libm.so.6` and `/lib/libc.so.6` clearly stating that `version CXXABI_1.3.11` and `version GLIBC_2.27` are not found.

The error message may mislead us. Maybe we are trying to load the packaged `libQt5Core.so.5` and fail for any reason (glibc version may be one) and fallback to the system one.

**Comment by mgautierfr** [comment]
@gnusupport What is your installed version of glibc ?
From https://www.hyperbola.info/packages/core/x86_64/glibc/ it seems that last version is 2.30 but I cannot found in the mirror. The "download from mirror" link is broken and in https://repo.hyperbola.info:50012/gnu-plus-linux-libre/stable/core/os/x86_64/ there is only 2.25

**Comment by gnusupport** [comment]
* Matthieu Gautier <notifications@github.com> [2020-10-05 17:50]:
> @gnusupport What is your installed version of glibc ?

Name                     : glibc
Version                  : 2.25-1.hyperbola8
Beschreibung             : GNU C Library, with OpenRC support

**Comment by mgautierfr** [comment]
So we know what is the problem. You glibc is too old for what we package (or we package to a system to recent)

You can try to update you system to glibc2.30 if possible (It may need a full update of your system. I don't know about Hyperbola policies about update). 
Or we have to build (and package) on a older system (using older glibc). This is a known issue (https://github.com/kiwix/kiwix-build/pull/375, https://github.com/kiwix/kiwix-build/pull/369, https://github.com/kiwix/kiwix-build/pull/377) I hadn't time to fix.

**Comment by gnusupport** [comment]
* Matthieu Gautier <notifications@github.com> [2020-10-05 19:10]:
> So we know what is the problem. You glibc is too old for what we
> package (or we package to a system to recent)

OK, so problem with you package is my system, even though I can
normally import and run majority of software without problem, ah is
not serious.

> You can try to update you system to glibc2.30 if possible (It may
> need a full update of your system. I don't know about Hyperbola
> policies about update).

System is working well. I need not update, will not do. I could
compile and build kiwix-serve, I will use that one.

Then I will see if I can compile Qt5 as that was major problem to make
it myself.

> Or we have to build (and package) on a older system (using older
> glibc). This is a known issue
> (https://github.com/kiwix/kiwix-build/pull/375,
> https://github.com/kiwix/kiwix-build/pull/369,
> https://github.com/kiwix/kiwix-build/pull/377) I hadn't time to fix.

Can appimage really deliver what is promised, to have all dependencies inside?

**Comment by probonopd** [comment]
> Can appimage really deliver what is promised, to have all dependencies inside?

Yes. E.g., using @azubieta's https://github.com/AppImageCrafters/appimage-builder it is possible to build AppImages that bundle _everything_. (Whether this is a good idea in all cases is another question.)

**Comment by azubieta** [comment]
> Whether this is a good idea in all cases is another question

With a great power comes a great responsibility. Bundling everything means that also critical libs such (as libssl) are also included. This means that the developer must keep those libs up to date on every release. That can be done with out stress with a simple CI tool such as Github Action, Travis or something else.

Let me know if you need help on this task.

**Comment by mgautierfr** [comment]
> Let me know if you need help on this task.

Good to know. I will remember this if I have problem when I try to move to `appimage-builder` (if we are moving to it) :)
