### ISSUE TITLE
unnecessary images loaded from wikimedia

### ISSUE THREAD

**Issue by ghost** [kiwix/kiwix-desktop#529]
When I use kiwix-serve on Windows and open any article, I noticed in network monitor or via umatrix that upload.wikimedia.org two images are being loaded, which even if I let them to download, do not appear in article ever, meaning they are useless:
`https://upload.wikimedia.org/wikipedia/commons/d/d6/Lock-gray-alt-2.svg`
`https://upload.wikimedia.org/wikipedia/commons/6/65/Lock-green.svg`

**Comment by kelson42** [comment]
@NijazM which content is that exactly?

**Comment by NijazM** [comment]
wikipedia_en_all_maxi_2020-07.zim
