### ISSUE TITLE
No content shown for Bulbagarden

### ISSUE THREAD

**Issue by Agetian** [kiwix/kiwix-desktop#534]
I downloaded the latest version (identified as 2.0.3 in the About box) of Kiwix from the website, and downloaded the Bulbagarden package 2020.10 from the Kiwix website as well (tried both the "full" and "nopic" versions). When attempting to load the package in Kiwix, it displays only a single line for the root element of the MediaWiki:

![изображение](https://user-images.githubusercontent.com/24357441/99057737-427d2600-25ad-11eb-8453-fb18960f6e0d.png)

I tried this on Linux, but also confirmed that it's the same on Windows 10.
Either the web site is dumped incorrectly, or, if the website is dumped correctly, then the application fails to work correctly with this package for some reason. I tried several other dumps from the download page and they displayed correctly.

I tried going back to the previous dump (2020.09) also available at your resource to see if it was just a problem with the current dump, but the effect was exactly the same as shown on the screenshot above.

Expected behavior: Supposedly, the contents of the Bulbagarden dump should be correctly displayed and it should be possible to  navigate the offline resource.

Thank you very much for investigating this, and thank you very much for the project!

**Comment by kelson42** [comment]
This quite certainly a bug with the ZIM file itself, checking out...

**Comment by Agetian** [comment]
Ok, thank you very much in advance for looking into it! Having an offline readable copy of Bulbagarden would be a valuable asset in my opinion :) As I understand from what I found online, this used to work in the past, so most likely something has changed with the website's API then or something like that that's breaking the ZIM dump. Sadly, I can't find a working copy of the previous ZIM builds for this website, so hopefully it won't be impossible to continue supporting this interesting resource. Once again, thanks for Kiwix!

**Comment by kelson42** [comment]
Newest ZIM file looks good https://mirror.download.kiwix.org/zim/other/bulbagarden_en_all_maxi_2020-11.zim. Should appear tomorrow in the library. And "yes" this was a regression.

**Comment by Agetian** [comment]
Thank you very much for resolving this! I noticed that some other ZIM files are affected too with the exact same symptoms (e.g. the Gentoo one), hopefully this will resolve those as well as the ZIMs are updated. If I notice anything broken once the November update ZIMs are in, I'll open it as a separate ticker (probably on mwoffliner then, since it seems to affect the ZIM making process as opposed to the viewer?)
