### ISSUE TITLE
Unable to download Kiwix-desktop Windows with Google Chrome on Windows 10

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#537]
I'm not even given the choice to confirm my choice. Download simply is a hard _No_ from Chrome
![image](https://user-images.githubusercontent.com/21675885/99876692-a67c9b80-2bf8-11eb-8c90-4c9da9febf37.png)

**Comment by kelson42** [comment]
@Popolechien what is the exact link you try to download?

**Comment by kelson42** [comment]
@Popolechien Pretty sure this is a problem at Chrome level. Probably because of https://github.com/kiwix/web/issues/126. Please confirm so I can close this ticket as duplicate.

**Comment by Popolechien** [comment]
Downloading from http://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip
Looks like 126 indeed

**Comment by kelson42** [comment]
@Popolechien You mean https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64.zip ?

**Comment by Popolechien** [comment]
Well both. The link used to be http, I moved it to https but the problem remained (as reported in https://github.com/kiwix/web/issues/126). Apparently the issue now is with the mirror link.

**Comment by kelson42** [comment]
@Popolechien Yes, we have many problems. But if HTTPS is used everywhere in www.kiwix.org, I will do my best to solve the others.

**Comment by kelson42** [comment]
Mirror part should be solved now.
