### ISSUE TITLE
Feature: Alt + <digit> to switch between tabs

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#543]
It would be nice to all a possibility to switch between opened tabs by
ALT + <digit> hotkeys, like it work in Firefox and Chrome.

For example, Alt+1 activates the first opened tab, Alt+2 activates the second, and so on.
Alt+0 activates the 10-th tab.

**Comment by rishabh-soni** [comment]
Hi, I am working on this feature for sometime and have made it to work, but was unable to find a way to pass a parameter into an action, so I had to make 10 different actions namely ToggleTab1Action, ToggleTab2Action... and so on. So can someone please tell that is this solution okay or there's some another way to do it?

**Comment by kelson42** [comment]
@rishabh-soni Good, would you be able please to make a draft PR so we can see what you have done so far and better understand the work left to do?

**Comment by kelson42** [comment]
@asashnov @mgautierfr would of of you please give a hint (see his PR)?

**Comment by asashnov** [comment]
@rishabh-soni Answered in PR: https://github.com/kiwix/kiwix-desktop/pull/567#issuecomment-755436957
