### ISSUE TITLE
Usability: Settings tab should be activated if already opened

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#545]
Found in current 'master' (830e19bb)

## Steps to reproduce:

1. Run the program
1. Open any file from library (it was 11 Gb EN Wikipedia in my case)
1. click + in tabbar to create an empty tab
1. From ... menu choose `Settings` to open Settings tab
1. Switch back to the opened file (Wikipedia in my case)
1. Again go to ... menu and choose Settings

## Actual result

Nothing happens, the current tab is still Wikipedia tab.

## Expected result

Once we have `Settings` tab already opened, it should be activated (switched in), so the user can see it.

**Comment by homeboy445** [comment]
Hi there, I am completely new to this organization and would like to tackle this task but would need some guidance for the same. Thanks!

**Comment by asashnov** [comment]
@homeboy445 The process is quite straight-forward. Once you are able to build and run 'master' branch locally, you should make a new branch, put your fix there, and create a new pull request.
