### ISSUE TITLE
Missing Fonts for Hieroglyphs (Unable to display SVG)

### ISSUE THREAD

**Issue by gcast20** [kiwix/kiwix-desktop#547]
Zim-File: wikipedia_de_all_maxi.zim (2020-11) and wikipedia_en_all_maxi.zim (2020-09)
kiwix desktop 2.0.3 (Build Thu 07/02/2020)
Where the Egyptian hieroglyphs should be shown in the articles "Ägyptische Hieroglyphen" and "Egyptian hieroglyphs", respectively, error codes appear.

**Comment by kelson42** [comment]
This is definitly a regression we should fix

**Comment by kelson42** [comment]
Might that be that Kiwix Desktop can not display SVG properly?

**Comment by kelson42** [comment]
@mgautierfr Looks like a Qt problem, but maybe something badly done on our side?

**Comment by gcast20** [comment]
@kelson42 same issue with kiwix for Android

**Comment by kelson42** [comment]
I believe this is a problem around the question mark. Moving the ticket to openzim/mwoffliner.
