### ISSUE TITLE
Sorting by Other category returns no result

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#553]
While this should be one of the most populated category, selecting `Other` in browse by category returns exactly zero files.
![image](https://user-images.githubusercontent.com/21675885/101652496-9826e000-3a3e-11eb-88f3-f4c2caf9eea3.png)

**Comment by kelson42** [comment]
Works this morning, again a platform outage because of https://github.com/kiwix/maintenance/issues/162
