### ISSUE TITLE
Rename "All files" to "Online files" in the sort menu

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#555]
`All files` is kind of misleading, at least for first-time users. `Online` is the opposite of `Local files` so there's some coherence to it.

**Comment by kelson42** [comment]
Kiwix Android has "Library" and "Download", might be even clearer?

**Comment by mgautierfr** [comment]
"All files" also contains downloaded files. So "Online" would be misleading.

I agree with "Library". But "download" means "file currently downloading" for me.
Maybe "Library"/"Zim files" ?

**Comment by Popolechien** [comment]
`Library` is fine by me and `Local files` also

**Comment by rishabh-soni** [comment]
Hi, I am new to this project and wanted to work upon this issue, can someone tell me that do I have to rename All files to Online files or Library? And are there any tools for translating the languages, as some them are not supported by google translate?

**Comment by kelson42** [comment]
@rishabh-soni Thank you for proposing yourself, would like to get a bit more time to make a decision on this. Would you be able to pick an other ticket?

**Comment by rishabh-soni** [comment]
@kelson42 Thanks a lot for responding, yeah sure I'll find some other issue to work upon in the meantime.

**Comment by ApoorvaKashyap** [comment]
@kelson42 I would like to fix this, if the names have been decided yet.

**Comment by kelson42** [comment]
> "All files" also contains downloaded files. So "Online" would be misleading.

They should be move to the local library during the download.

**Comment by kelson42** [comment]
It seems the "All files" does only show meanwhile the "Online files¨, see here:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/2ead995e-9e69-4f3d-9d21-7cbf9def6eda)
and
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/36c5d299-9a8f-4599-9e7f-6f9b7849019f)

**Comment by kelson42** [comment]
I will rename it to "Online files", it's not perfect but doing better implies to discuss more. By doing so we will fix 80% of the problem without creating new one. Good enough.

**Comment by kelson42** [comment]
@juuz0 Would you be able to do that quickly please?

**Comment by mgautierfr** [comment]
For reference : https://github.com/kiwix/kiwix-desktop/issues/68
