### ISSUE TITLE
Missing "printsupport" in .pro

### ISSUE THREAD

**Issue by Ambrevar** [kiwix/kiwix-desktop#556]
When packaging this for Guix, compilation failed with

```
src/kiwixapp.cpp:12:10: fatal error: QPrinter: No such file or directory
```

Adding QT+= printsupport to the .pro file fixed it, as suggested in
https://stackoverflow.com/questions/19145763/qt-cannot-open-include-file-qprinter.

**Comment by kelson42** [comment]
Would you be able to make a PR?

**Comment by Ambrevar** [comment]
Done in #557.
