### ISSUE TITLE
Crash saying "No disk error" when start up, with External Hard Drive plugged in

### ISSUE THREAD

**Issue by jeexop** [kiwix/kiwix-desktop#566]
Firstly, thank the authors for providing this soft. Here I want to report a bug.

**Affected Version**: from `2.0` to the latest version `2.0.5`. (`2.0-rc4` doesn't have this bug.)
**OS**: Win 8.1 x64

**Steps to reproduce the bug:**
1. Store `.zim` file on an external hard drive (2TB).
2. Plug in the drive **before** launching kiwix.
3. Launch `kiwix-desktop.exe`.
4. About 90% of possibility, it will crash (and then exit) with the "No disk error". (`Exception Processing Message 0xc0000013 - Unexpected parameters`)
Screenshot:
![kiwix-error](https://user-images.githubusercontent.com/48157836/103336688-e6feed00-4ab3-11eb-9049-411aa75bd7ef.png)

(Note that using a USB flash drive instead of external hard drive **can't** reproduce this error.)

**Analyze**
Possible reason: kiwix attempts to search across all the hard drive to find the zim file when initializing, but it may contain some bugs.

# Workaround
1. Rename `*.zim` file to `*.zim.bak` on the external hard drive.
2. And then, launch `kiwix-desktop.exe`.
3. Open the `zim.bak` file from the menu, by manually selecting the file path.

**Comment by kelson42** [comment]
@jeexop Thx for your bug report. Do you know if this bug still occur with latest nightlies http://download.kiwix.org/nightly/ ?

**Comment by jeexop** [comment]
Thanks for reply!
I visited the nightly build page [2021-09-04](http://download.kiwix.org/nightly/2021-09-04/), but **windows build** of kiwix-desktop doesn't appear in the file list.

**Comment by kelson42** [comment]
Indeed, something is broken here, but you can check with http://download.kiwix.org/nightly/2021-08-15/

**Comment by kelson42** [comment]
@jeexop Donyou still have the problem with latest 2.1.0 version?

**Comment by jeexop** [comment]
Thanks for reply.
I reinstalled the operating system a few months ago (still using Win8.1). Now I can't reproduce this bug in both v2.0.5 and latest [v2.1.0](https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.1.0.zip).

**Comment by kelson42** [comment]
Thx for coming back to me. Glad to hear it works now. I Will close then the ticket as non of us has a reproduction case.
