### ISSUE TITLE
Library pagination seems to be wrong

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#57]
My language is English and "All Files" tells me that I have 44 pages, but if I click on "Last", I get no content. Page number 43 seems OK.

An other problem (probably related) with pagination is that, if I just start Kiwix and click on last and then click on previous, then even page 43, 42, 41, etc... are empty.

**Comment by mgautierfr** [comment]
In the last version (beta) there is no pagination.
Pagination was added to workaround a slow update of the view. As now we are updating the view asynchronously we don't have this problem anymore. So I remove the pagination system.
