### ISSUE TITLE
Making kiwix accessible to screenreaders, adopt inclusive design approach 

### ISSUE THREAD

**Issue by kaveinthran** [kiwix/kiwix-desktop#570]
HI,

As a blind user, I find it disappointing that I can't use kiwix at all. 
Previously, I've been using v0.9 and all the controls are accessible and the wikipedia pages are presented in a browser like form.
When I used the latest version, there's no way for me to read articles, search or access kiwix control through keyboard.
NO controls are visible to my screenreader and I can't operate the application with keyboard at all.

as a blind user, I use screenreader which depend on the application programming structure to convey information to me. I really hope the developer will put an effort to adopt inclusive principle to design the app so that the app will be accessible to all,

You can try using the opensource and free screenreader nvda with kiwix get the bigger picture,
download nvda here
https://www.nvaccess.org/download

/

**Comment by asashnov** [comment]
As Qt documentation says, should not be difficult:

https://doc.qt.io/qt-5/accessible.html#making-applications-accessible

> Assistive Tools (or ATs) come in great variety and help users with different tasks. For this reason what individual applications offer (with the help of Qt) is a generic API that allows to inspect what is on screen in a semantic way and offers the typical interactions with the UI elements.
> 
> Applications do not usually communicate directly with the assistive tools, but through a platform specific API. Generally the communication with the ATs works though an IPC mechanism. Semantic information about user interface elements, such as buttons and scroll bars, is exposed to the assistive technologies. Qt supports UI Automation on Windows, macOS Accessibility on macOS, and AT-SPI via DBus on Unix/X11. The platform specific technologies are abstracted by Qt, so that applications do not need any platform specific changes to work with the different native APIs. Qt tries to make adding accessibility support to your application as easy as possible, only a few changes from your side may be required to allow even more users to enjoy it.

**Comment by kelson42** [comment]
@asashnov How much time would be needed to fix the problem?

**Comment by asashnov** [comment]
@kaveinthran  Sorry for that. I checked the latest (released) Kiwix application (2.0.4) with NVDA screen reader under Windows 7 x64 (build 7601, Service Pack 1).

Kiwix-0.9 was build as Mozilla XUL application, using Firefox applications engine.
Kiwix 2 is Qt-based application, using web engine from google chrome to display web pages content, so they are completely different internally. 

The problems I see with Kiwix-2.0.4 and the screen reader:
* 'Search' control on top is silent
* 'Main menu' is silent and no tooltip also (the button ... between 'Open file' and 'Set fullscreen'
* In old Kiwix 0.9 an entire paragraph is read when mouse over it. It was tested with the default file that Kiwix 0.9 opens. But in Kiwix 2.0.4 when I open wikipedia_en_all_mini_2020-04.zim the paragraphs are not read on mouse over.

As the workaround, you may follow this using usage pattern:
1. run Kiwix application
2. add zim files you want to read by 'Open file' button on the top right (Control + O)
3. Open 'Local Kiwix Server Settings' dialog that you can get by pressing Control + I shortcut, or via a menu which can be accessed by clicking on a hidden from screen reader button also on the top right, between 'Open File' and 'Set fullscreen' buttons;
4. In this dialog, push 'Start Kiwix Server' button
5. Then a bit up of the previous button a new button 'Open in browser' appears. Push it.
6. Your system default web browser will be run, pointed to local built-in Kiwix server, so you can browse your library (the set of previously opened zim files) and their contents.

**Comment by patrick-emmabuntus** [comment]
> @kaveinthran Sorry for that. I checked the latest (released) Kiwix application (2.0.4) with NVDA screen reader under Windows 7 x64 (build 7601, Service Pack 1).
> 
> Kiwix-0.9 was build as Mozilla XUL application, using Firefox applications engine. Kiwix 2 is Qt-based application, using web engine from google chrome to display web pages content, so they are completely different internally.
> 
> The problems I see with Kiwix-2.0.4 and the screen reader:
> 
>     * 'Search' control on top is silent
> 
>     * 'Main menu' is silent and no tooltip also (the button ... between 'Open file' and 'Set fullscreen'
> 
>     * In old Kiwix 0.9 an entire paragraph is read when mouse over it. It was tested with the default file that Kiwix 0.9 opens on start. But in Kiwix 2.0.4 when I open wikipedia_en_all_mini_2020-04.zim the paragraphs are not read on mouse over.
> 
> 
> As the workaround, you may follow this usage pattern:
> 
>     1. run Kiwix application
> 
>     2. add zim files you want to read by 'Open file' button on the top right (Control + O)
> 
>     3. Open 'Local Kiwix Server Settings' dialog that you can get by pressing Control + I shortcut, or via a menu which can be accessed by clicking on a hidden from screen reader button also on the top right, between 'Open File' and 'Set fullscreen' buttons;
> 
>     4. In this dialog, push 'Start Kiwix Server' button
> 
>     5. Then a bit up of the previous button a new button 'Open in browser' appears. Push it.
> 
>     6. Your system default web browser will be run, pointed to a local built-in Kiwix server, so you can browse your library (the set of previously opened zim files) and their contents with your web browser, that you are used to.

This is a good workaround approach but it is not sufficient.

This must be done automatically with a script [emmabuntus_accessibility_kiwix.sh.tar.gz](https://github.com/kiwix/kiwix-desktop/files/14911474/emmabuntus_accessibility_kiwix.sh.tar.gz)  launched via a shortcut and also add shortcuts in the Kiwix-Server articles template, see our proposal here https://github.com/kiwix/libkiwix/issues/1072
