### ISSUE TITLE
Fix fullscreen if there is no current webview (zim)

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#571]
The fullscreen functionality works by putting the current (zim) webview fullscreen.
But there is no safeguard if there is no current zim displayed and we end by passing a nullptr to the FullScreen class.

We have a technical bug (using a nullptr) and a functional point to fix (what to do if there is no current webview)

The simpler seems to deactivate the fullscreen if there is no current zim.
But then we have to deactivate the action, not just add a safeguard.
And we probably need to test corner use case (closing the webview while we are fullscreen, ...)

Or we may want to keep the fullscreen functionality if there is no current zim, but we must decide what is the correct behavior.

**Comment by asashnov** [comment]
From the initial report:

> The fullscreen functionality works by putting the current (zim) webview fullscreen.
> ...
> we may want to keep the fullscreen functionality if there is no current zim, but we must decide what is the correct behavior

What I see now in 'master' (cb5cfdce) is not putting the current webview to fullscreen. Instead, full screen mode just illuminates the window header and border, but the entire window content is show: 'Search',  'Main menu', 'Full screen' buttons, tabbar. And it works as expected, without crashed in this mode.

So, if we are happy with the current 'master' (cb5cfdce) there is nothing to fix, all tabs, including Settings, are shown perfectly in this window mode.

Chrome and Firefox works differently in fullscreen mode:
* Firefox show tabbar and address bar when the mouse hit upper screen side.
* Chome just shows a round (X) button to exit from fullscreen mode, not showing tabbar, but it's still possible to switch between tabs with Ctrl+TAB hotkey.

**Comment by kelson42** [comment]
It should work like for Firefox. Like @asashnov said, first, this is the the windows content which is put fullscreen, not the webview. I think this is OK, and therefore there is no point to deactivate the option if we there is no WebView visible (we display the library). But what needs to be done, is that the top bar with tab header need to disappear and only appear when we display a tab and we have the mouse pointer at the top. That way we could have a "real" article fullscreen.

**Comment by asashnov** [comment]
@HanYoung-uwu  Do you have any changes to review now?

The only PR associated with this issue (#580) is closed.
And no changes in https://github.com/HanYoung-uwu/kiwix-desktop/tree/master

**Comment by HanYoung-uwu** [comment]
> @HanYoung-uwu Do you have any changes to review now?
> 
> The only PR associated with this issue (#580) is closed.
> And no changes in https://github.com/HanYoung-uwu/kiwix-desktop/tree/master

I was referring to the solution I proposed in the closed PR. If you're okay with that, I'll implement it and open a new PR.

**Comment by kelson42** [comment]
@HanYoung-uwu There is no problem with your work, secure it works like expected, see https://github.com/kiwix/kiwix-desktop/issues/571#issuecomment-773942473. For the rest, keep working on the same PR, reopen the closed one if necessary.

**Comment by kelson42** [comment]
@juuz0 Would you be interested to take over this ticket?

**Comment by juuz0** [comment]
@kelson42 Sure, thanks

**Comment by kelson42** [comment]
@juuz0 Thx, looks to all the comments and to the two PR already links to build a global view on the issue please.
