### ISSUE TITLE
Improper top bar display on Windows 10 Pro

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#576]
Opening Kiwix-desktop (2.0.5) on Windows 10 pro led to the display issue whereby the top of the window covers the top of the screen.
![image007](https://user-images.githubusercontent.com/21675885/104481971-ab414880-55c6-11eb-9437-39c5f60fa7ea.png)

Expanding the window crashes the application, but clicking on the fullscreen icon solves the issue (the issue comes back when leaving fullscreen)

**Comment by kelson42** [comment]
@mgautierfr @asashnov I'm really clueless about that one. First time I see this on Windows with Kiwix. Looks like a bug in Qt.

**Comment by kelson42** [comment]
@Popolechien I close the ticket as we don’t have had new complains about this bug. We have in addition released version 2.1.0 which uses an upgraded version of Qt which might have as well fixed the problem. Finally, without reproduction case, there is nothing we can do. In case this happens again, please reopen the ticket.
