### ISSUE TITLE
White stripes on the left and right in Kiwix

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#578]
Previously, articles from Wikipedia were unfolding on the **full screen**:
![Kiwix=full screen](https://user-images.githubusercontent.com/65112331/104843497-a2f15200-58d3-11eb-892d-17b26f366d2f.png)

But now the width of the article in **Kiwix** (*.appimage) is about **1000 px**:
![Kiwix 1017px](https://user-images.githubusercontent.com/65112331/104843548-e3e96680-58d3-11eb-9746-8252db6d4863.png)

And if you expand the Kiwix to full screen, we will see white stripes on the left and right. So the wikipedia article will still be about 1000 px wide:
![Kiwix 1363px](https://user-images.githubusercontent.com/65112331/104843583-1eeb9a00-58d4-11eb-84f8-9698fe4b51de.gif)

Which raised an interesting question: **Why doesn't a Wikipedia article expand to full screen**?

**Comment by kelson42** [comment]
Ticket of `openzim/mwoffliner`.
