### ISSUE TITLE
Support for the mhtml format in Kiwix

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#579]
Now the program **Kiwix** opens only **ZIM** files.
But the Wikipedia article can be saved in the webbrowser in ***.mhtml** or ***.html** or ***.mht** format.
So I want to suggest that **Kiwix** open files at least in the ***.mhtml** format.

**Comment by kelson42** [comment]
All of this can be done properly with a standard browser. I don't really see the value of Kiwix being able to do so.
