### ISSUE TITLE
Where is the "home" button

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#58]
I'm missing the "Home" button which brings me to the welcome page of a ZIM. It seems to be absent from the design too! @schoenbaechler What that on purpose?

**Comment by kelson42** [comment]
@mgautierfr @schoenbaechler Any clue?

**Comment by schoenbaechler** [comment]
Hi @kelson42, this was done on purpose. Those were my considerations: 

1. It has been aligned with recent development of web browsers, where the Home button is disappearing from the interface. In short: the address bar (search) at the top is the new home. 

2. From the ZIM files I looked at, I assessed that the homepage doesn’t add a lot of value. I thought of it more of as a welcome page, that could be pinned when users would have the need to access it. 

3. Most of the homepages of the ZIM files haven’t been maintained very well. I think it makes sense to point users to this page if it’s carefully curated. I mentioned this in one of our earlier calls and remember Stéphane coming up with “Netflix“ as an example.

Thanks!

CC @mgautierfr

**Comment by sgourdas** [comment]
@kelson42 how do you think we should proceed with this?

**Comment by kelson42** [comment]
@sgourdas yes

**Comment by sgourdas** [comment]
I am not sure what is the plan for this. Based on the referenced issues I understand that having a home button is not up to spec. What was done is implement the `Alt+Home` shortcut to go to home instead. Should I add the home button?

**Comment by kelson42** [comment]
> Should I add the home button?

Yes please

**Comment by kelson42** [comment]
@sgourdas BTW can you please implement that one? somehow it has been forgotten?
