### ISSUE TITLE
library catalog downloaded over HTTP

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-desktop#587]
Originally filed at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981466 - can these URLs be switched to use HTTPS? Or is there a reason they still use HTTP?

----
I noticed that the data feed is not downloaded using https, so network
attackers could modify the data feed to change my choice of downloads
to something I didn't want to download.

Also most of the datasets point at http instead of https URLs even
though the servers do support https. It would be good if kiwix had a
list of download servers that support https and then always use https
to contact those download servers.

```
   $ kiwix-desktop 
   QSocketNotifier: Can only be used with threads started with QThread
   Compiled with Qt Version  5.15.1
   Runtime Qt Version  5.15.2
   add widget
   
   (kiwix-desktop:1410327): GLib-GObject-WARNING **: 23:11:12.766: The property GtkSettings:gtk-fallback-icon-theme is deprecated and shouldn't be used anymore. It will be removed in a future version.
   Downloading "http://library.kiwix.org:80/catalog/search?lang=eng&count=0"
   session saved
```

**Comment by kelson42** [comment]
In the past, AFAIK mostly if not only on Android, we had cases where the SSL trustore of the device did not have the Letsencrypt SSL issuer certificate and therefore was not able to download the catalog. For this reason, we tend to be cautious of using SSL for the library download. That said, we could probably give a try on Kiwix Desktop with the HTTPS link, will fix and test.

**Comment by legoktm** [comment]
Got it, thanks. Should I file a different bug about some of the URLs in the catalog itself being over HTTP?

**Comment by kelson42** [comment]
@legoktm Not sure what you mean exactly... but yes.
