### ISSUE TITLE
Russian Wikipedia subsets crash kiwix-desktop 2.0.5

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#591]
Steps to reproduce:
- Open Kiwix-desktop 2.0.5
- Download Wikipedia_ru_xxx_yyy_2021_02 (latest version available): I've tried with wikipedia_ru_geography_maxi_2021-02.zim, wikipedia_ru_physics_maxi_2021-02.zim, wikipedia_ru_physics_mini_2021-02.zim
- Open zim files: the landing page appears, but then clicking on any image will have the program freeze.
- Typing in search bar works and articles open.
- Same files will work on Android.
- The issue is not reproduced with other zim files from February in other languages (e.g. fr_football_maxi_2021-02.zim)

**Comment by kelson42** [comment]
@Popolechien I confirm the bug, it happens on both GNU/Linux and Windows. The root cause is unclear. But it is fixed, I tried with a nightly build and the problem has vanished: pages are loaded properly.
