### ISSUE TITLE
UI Text color should be specified

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#592]
We have a custom/explicit background color, but the color of the text is the "default" them one. As a consequence, if someone as an "incompatible" UI theme then Kiwix Desktop will be unusable. We need to have an explicit color for the text color.

See more explanations at https://github.com/kiwix/kiwix-desktop/issues/320#issuecomment-775329595

**Comment by GODFATHER0054** [comment]
Will you give me chance to do this.

**Comment by kelson42** [comment]
@GODFATHER0054 yes

**Comment by kelson42** [comment]
@asashnov Could you please secure that text color is specified so it is aleasys readable?

**Comment by asashnov** [comment]
Steps to reproduce:

1. During login into system, choose 'KDE Plasma' session (this is the default for Kubuntu, or it can be installed on Ubuntu by 'kde-plasma-desktop' package)
2. In Plasma desktop session, choose System Settings -> appearance -> Colors -> Breeze Dark
3. run the program

### Actual result

![Screenshot_20210806_173738](https://user-images.githubusercontent.com/5078434/128499386-5820f3d9-59b5-4e76-b711-1b15449e284f.png)

### Expected result

Text should be visible.

**Comment by kelson42** [comment]
@asashnov Great, so bug confirmed. Do you have an idea how to fix it?

**Comment by asashnov** [comment]
Idea of the fix: just explicitely specify font color black, as it is in light themes by default.
Dark theme makes font color white by default, this is the cause of this issue.

**Comment by kelson42** [comment]
@asashnov OK, I'm supportive of this. My title was explicit about that, ie. "UI Text color should be specified". As long as we don't support properly multiple/dark theme. We have to do so.

**Comment by alexfreyre** [comment]
I have color problems with KDE theme. Would be great if Kiwix app had their won themes.
