### ISSUE TITLE
Buttons in toolbar drawn incorrectly in right-to-left layout

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#594]
Found on current 'master' (ca776b46)

### Steps to reproduce:

1. Run Kiwix application with right-to-left interface layout by adding -reverse CLI option
2. See the buttons in toolbar
3. Open any .zim file from library
4. See the buttons in toolbar again

### Actual result:

![Screenshot from 2021-02-12 20-10-29](https://user-images.githubusercontent.com/5078434/107772817-52083880-6d6f-11eb-9631-1b11fefc2f0e.png)

![Screenshot from 2021-02-12 20-10-38](https://user-images.githubusercontent.com/5078434/107772834-57fe1980-6d6f-11eb-8fe1-3d9e78bac266.png)

### Expected result:

Graphical items in toolbar should not overwrite each other, no duplicate drawings.

### Additional info

There is another issue about Back/Forward buttons order: #595

**Comment by kelson42** [comment]
@asashnov and the icons should be on the right!!!

**Comment by asashnov** [comment]
@kelson42 inside tab headers the order of icon and close button also reverted- that's right, the expected behaviour of QTabbar and other programs, for example:

![web_phishing_zoom75](https://user-images.githubusercontent.com/5078434/107801708-023b6880-6d93-11eb-833f-59b18ff942f2.png)

Source: https://help.eset.com/ees/6/ar-EG/index.html?idh_config_antiphish.htm

**Comment by asashnov** [comment]
Actually the example above shows the opposit of what I wanted to say.

Qt manual says (https://doc.qt.io/qt-5/qtquick-positioning-righttoleft.html):
> The general rule of thumb is that content (like photos, videos and maps) is not mirrored, but positioning of the content (like application layouts and the flow of visual elements) is mirrored.
> ...
> Also, there are some special cases you may need to take into account where right-to-left language speakers are used to left-to-right positioning, for example when using number dialers in phones and media play, pause, rewind and forward buttons in music players.

But it says nothing clearly about tabs header.

So I'm confused here. I think we can rely on the default behaviour of QTabbar now, and may `setLayoutDirection(Qt::LeftToRight);` in Tabbar constructor if users ask us about it:

![Screenshot from 2021-02-13 00-47-23](https://user-images.githubusercontent.com/5078434/107803746-9a3a5180-6d95-11eb-8456-6905b78b5f5b.png)

**Comment by kelson42** [comment]
@asashnov One #525 is fixed, we shoukd really fix this one.

**Comment by kelson42** [comment]
@asashnov Sorry for my lack of feedback. I did not meant the tab headers. I meant the context of the search box:
* The text should be aligned right (like the suggestions)
* Any magnify logo should be on the right as well

**Comment by ShaopengLin** [comment]
@kelson42 May I have a summary on what is left to do? They seem to be looking ok in reverse mode on Linux.

I did spot this one, where the text is wrongly shadowed as if it is still in left-to-right mode:
![Screenshot from 2024-06-20 15-51-59](https://github.com/kiwix/kiwix-desktop/assets/39098000/5089f7ee-9b17-4e35-9c1d-d9dc006f1deb)
![Screenshot from 2024-06-20 16-01-52](https://github.com/kiwix/kiwix-desktop/assets/39098000/519a71c1-7dae-4206-9456-925548124466)

**Comment by kelson42** [comment]
@ShaopengLin Please rebase and then I will do a new review

**Comment by ShaopengLin** [comment]
> @ShaopengLin Please rebase and then I will do a new review

You might have commented on the wrong place. I assume you meant to put it on the save page PR.

**Comment by kelson42** [comment]
@ShaopengLin Now that #1146 has been merged, do you believe you could revamp (superseed) old PR #797 so we can fianally fix completly this issue?

**Comment by ShaopengLin** [comment]
@kelson42 I believe the SearchBar was already refactored in #1060.

**Comment by kelson42** [comment]
@ShaopengLin So from your point of view, the issue (even after checking comments) has been fully implemented?

**Comment by ShaopengLin** [comment]
@kelson I don't see any issues now with the buttons in the tool bar and tab bar, including the forward/backward button.

**Comment by kelson42** [comment]
@ShaopengLin OK, then I will reasse the issue.

**Comment by kelson42** [comment]
@ShaopengLin I had briefly a look, at least the string in the searchbox is not aligned properly:
![image](https://github.com/user-attachments/assets/0993bccc-b773-4230-b7be-3d0dbddb4330)

**Comment by ShaopengLin** [comment]
@kelson42 My mistake, the comment came before #797 and when I looked at that PR this behavior was kept instead so I ignored it.

This isn't a hard change and I can fix it relatively easily. The RTL issues with suggestions will be fixed with my PR for #413.

I also notice the filter checkbox and search edits also have bad alignments in RTL. (everything resrts to aligns to the left whenever you type anything.) Should this be in a new issue or just fix it in this one? I believe at least as the title goes it is somewhat out of topic.

**Comment by ShaopengLin** [comment]
@kelson42 Also one important question, how are we testing things for RTL? I am using reverse mode and here from what I saw you only changed the language of the application. This wouldn't trigger any RTL alignment. The image you used confused me at first as in a LTR application this is the expected alignment to the search string.

**Comment by kelson42** [comment]
@ShaopengLin I don't understand at all what you are doing or attempting here. I can can not test your PR because there is basically no instruction about how to do that. The previous PR had a clear way to do that and I told you many times to reuse what already works. So I don't understand why you ask how it should be testable?

**Comment by ShaopengLin** [comment]
@kelson42 I'm sorry if my question sounded like I was asking how is this testable. I was simply questioning the example you used [here](https://github.com/kiwix/kiwix-desktop/issues/594#issuecomment-2304136790). I do not know how the screenshot is a misaligned example. The application layout you used is Left-to-Right, and the text is correctly aligned to the left same as the suggestions.

Here is an example of an incorrectly aligned search bar text according to [this comment](https://github.com/kiwix/kiwix-desktop/issues/594#issuecomment-1050797097)
![Screenshot from 2024-09-03 01-45-50](https://github.com/user-attachments/assets/da609a1a-9856-40a2-88a1-2843e4c0f846)


I have posted the detailed testing procedures on the PR.

**Comment by ShaopengLin** [comment]
@kelson42 
**1.** when search bar text is LTR but in reverse (RTL) mode, we see text not aligning with the suggestions.
![Screenshot from 2024-09-03 02-27-22 (1)](https://github.com/user-attachments/assets/9e24277b-b6b7-4200-a70a-fc704b1ba26a)
Similarly when text is RTL but in LTR mode:
![Screenshot from 2024-09-03 02-30-26 (1)](https://github.com/user-attachments/assets/df7ff02b-ffd7-44b8-bd29-3dc1dc7757fd)
The first change should align them to their respective positions:
![Screenshot from 2024-09-03 02-41-44 (1)](https://github.com/user-attachments/assets/1636c21f-1e5b-40a1-859f-9c9bff383d5c)
![Screenshot from 2024-09-03 02-41-21 (1)](https://github.com/user-attachments/assets/15b96306-5356-4881-8b3f-1d791dfe94de)

---

**2.** When placeholder text "search" is in RTL language, it is aligned to the opposite position of suggestions:
In RTL mode: ![Screenshot from 2024-09-03 02-54-54](https://github.com/user-attachments/assets/56ca6caa-1bc2-4f84-9c02-1a9cd611c0b8)
In LTR Mode: ![Screenshot from 2024-09-03 02-54-42](https://github.com/user-attachments/assets/3c050ea7-f79f-45cf-ba08-ad02ea7a7a7d)
You can test this by changing the locale of Kiwix Desktop. The second change should align them:
![Screenshot from 2024-09-03 02-59-47](https://github.com/user-attachments/assets/3e3819f8-f693-4603-bc70-d40266a8914f)
![Screenshot from 2024-09-03 02-59-56](https://github.com/user-attachments/assets/404b81f3-03c9-4913-bad8-b8d1a75abcc7)

---

**3.** The displayed text for fulltext-search on the search bar does not match what it is in the suggestions.
LTR search text in RTL Locale (Not reverse mode):![Screenshot from 2024-09-03 05-35-00](https://github.com/user-attachments/assets/9be7c0d7-9e1a-48c7-9ee9-8589324c809d)
RTL search text in LTR Locale (Not reverse mode): ![Screenshot from 2024-09-03 03-31-58](https://github.com/user-attachments/assets/ac74b7bf-753c-4e97-8f93-29367f1182ec)

In addition, if you are in reverse mode for both RTL and LTR locale, the '(Fulltext search)' can get inserted in between:
     1. In LTR reverse mode, Type `ه`
     2. copy paste s
     3. you see `s (Fulltext search) ه`
![Screenshot from 2024-09-03 03-42-26](https://github.com/user-attachments/assets/fc50dcd1-3a66-40f8-8a8c-a193f29e3ad5)
     1. In RTL reverse mode, Type `s`
     2. copy paste ه
     3. you see `sه (بحث في النص الكامل)`
![Screenshot from 2024-09-03 03-43-59](https://github.com/user-attachments/assets/c8dcc440-56fd-492b-8590-eb9749c3da8f)

This third change should align them properly to the text direction:
Mismatch Resolved:
![Screenshot from 2024-09-03 05-36-50](https://github.com/user-attachments/assets/986be5ca-5ee0-4203-9d6d-2674a3cb8b4c)
![Screenshot from 2024-09-03 05-40-16](https://github.com/user-attachments/assets/e6176a0b-c94f-4308-8932-bc823cb0f603)
Wrong placeholder insertion Resolved:
![Screenshot from 2024-09-03 05-44-45](https://github.com/user-attachments/assets/e8ef0671-f2ab-455d-9940-db55bb194d65)
![Screenshot from 2024-09-03 05-42-00](https://github.com/user-attachments/assets/b64e32f5-1394-4af0-922b-85976f0df37a)

**Comment by ShaopengLin** [comment]
@kelson42 In the case I do not worried about LTR text in RTL layout or vice versa as mentioned [here](https://github.com/kiwix/kiwix-desktop/pull/1187#issuecomment-2327820505), then I only identify one issue:

> 
> The cursor position is incorrectly aligned to the right in RTL layout:
> ![Screenshot from 2024-09-03 23-48-28](https://github.com/user-attachments/assets/5ca3db21-1229-416f-a1ce-030387e32282)
> 

Otherwise, the texts all align with the suggestion as requested previously [here](https://github.com/kiwix/kiwix-desktop/issues/594#issuecomment-1050797097):

LTR text in LTR layout:
![Screenshot from 2024-09-03 23-57-36](https://github.com/user-attachments/assets/27961e3c-6901-4d15-a7fb-96265a9632fa)

RTL text in RTL layout:
![Screenshot from 2024-09-03 23-59-13](https://github.com/user-attachments/assets/0bd31cfc-56fd-4714-88bf-f44321bf3cfb)
