### ISSUE TITLE
Wrong order of Back / Forward buttons in right-to-left layout

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#595]
Found on current 'master' (ca776b46)

### Steps to reproduce:

1. Run Kiwix application with right-to-left interface layout by adding -reverse CLI option
2. See to Back / Forward buttons in the toolbar

### Actual result:

![Screenshot from 2021-02-13 00-08-33](https://user-images.githubusercontent.com/5078434/107799804-82ac9a00-6d90-11eb-99ec-f97e75e7b491.png)

### Expected result:

Back / Forward buttons should be mirrored. So Back goes the first on the right, Forward the second.

### Additional information

There is separated issue on how the other buttons drawn: #594

**Comment by patelaryan7751** [comment]
can i work on this issue @kelson42 @asashnov ?

**Comment by kelson42** [comment]
Yes!

**Comment by patelaryan7751** [comment]
> Yes!

okay!

**Comment by patelaryan7751** [comment]
can you give more info on the path of files where this can be found @kelson42 ?

**Comment by kelson42** [comment]
@GODFATHER0054 Yes, but please explain first here how you plan to fix it.

**Comment by GODFATHER0054** [comment]
Once, I saw the code and understand how the button are defined their.

**Comment by kelson42** [comment]
@asashnov Would you please have a look to this bug?
