### ISSUE TITLE
Too Slow

### ISSUE THREAD

**Issue by EliasPereirah** [kiwix/kiwix-desktop#596]
Kiwix is very slow when doing a search.
The search is fast, just if the word searched is a name of one article, exemplo: Biology. 
But if you search for, just for exemplo: What is biology, the search is very slow, take almost 1 minute or more.

**Comment by EliasPereirah** [comment]
I downloaded the file you indicated, but nothing has changed. It remains slow, very slow. I don't know if it's something on my computer, but everything is working ok on my PC, which is very powerful.

**Comment by kelson42** [comment]
@EliasPereirah If this is still taking more than 60s to make a search, then probably something is wrong with your computer. What is the search pattern taking so long?

**Comment by EliasPereirah** [comment]
I really don't think that is my PC.
The pattern is http://192.168.0.101:8181/search?content=5149203d-1c60-a927-0095-278e34e6897a&pattern=estrutura+biologica
How can i download ther Kiwix version of 2017? this version worked for me in 2017

**Comment by GoblinLegislator** [comment]
You can download all versions from here: https://ftp.acc.umu.se/mirror/kiwix.org/release/kiwix-desktop/
But if you mean kiwix 0.9: https://ftp.acc.umu.se/mirror/kiwix.org/archive/kiwix/kiwix-xulrunner/0.9/
It is normal that full text search is slow. Same is true even in other apps like Xowa and mediawiki. That's why I never use full search but only exact, only what appears in autocomplete.

**Comment by kelson42** [comment]
@GoblinLegislator To the contrary to what you say this is not "normal". Either this is a problem with the system or something has to be fixed in the software. We will try to reproduce the problem first.

**Comment by GoblinLegislator** [comment]
I don't understand why that is not normal. Any search of more data should be slower than search of less data.
In first case we search only titles and redirects, while in 2nd case we do full search of whole indexed data.
Comparable to speeds of Windows search of indexed and non-indexed files. Ratio of speeds should be about second vs minute.

**Comment by EliasPereirah** [comment]
I used Kiwix in 2017 and it worked well, it didn't take long to do a full text search.
I remember it took Kiwix a long time to index the files when we first sent the ZIM file, but then it was smooth and fast.

**Comment by kelson42** [comment]
> I really don't think that is my PC.
> The pattern is http://192.168.0.101:8181/search?content=5149203d-1c60-a927-0095-278e34e6897a&pattern=estrutura+biologica

You don't test with `wikipedia_pt_all_maxi_2021-02.zim`

**Comment by kelson42** [comment]
@EliasPereirah I have tested on my workstation which is 5+ years old and `wikipedia_pt_all_maxi_2021-02.zim` and Kiwix Desktop 2.0.5. The given fulltext search pattern "estrutura biologica" takes <1s if the file is on my SSD and ~1s if this is on a slow mechanical hard disk. So either you have a super limited HW (does not seem to be the case) or you don't test with the latest ZIM file/Software or you have any other problem with your setup.

**Comment by EliasPereirah** [comment]
> > Realmente não acho que seja meu PC. 
> > O padrão é http://192.168.0.101:8181/search?content=5149203d-1c60-a927-0095-278e34e6897a&pattern=estrutura+biologica
> 
> Você não testa com `wikipedia_pt_all_maxi_2021-02.zim`

You are right, now i see that i downloaded the version of one month less, this one wikipedia_pt_all_maxi_2021-01.zim

**Comment by EliasPereirah** [comment]
I haven't tested wikipedia_pt_all_maxi_2021-01.zim
But I will close here.
Thanks
