### ISSUE TITLE
can you not bookmark articles in kiwix wikipedia 2.0?

### ISSUE THREAD

**Issue by wimdin** [kiwix/kiwix-desktop#597]
I was able to bookmark articles in kiwix 0.9. It was pretty easy. So far I'm not seeing any way to do this in 2.0. Surely this wasn't removed, right? Any guidance would be appreciated. Thanks.

**Comment by GoblinLegislator** [comment]
No that ability. Best to use local server, and bookmark via web browser like Firefox. Also headingsMap will allow you to have contents (index) of each article.

**Comment by kelson42** [comment]
There is a reading list feature, so I don't understand this ticket.

**Comment by wimdin** [comment]
> There is a reading list feature, so I don't understand this ticket.

How do you add articles to the reading list feature? I see nowhere in the kiwix interface to do this. Any help is appreciated.

**Comment by kelson42** [comment]
There is the sunglasses icon in the icon bar to display the reading list and if you want to add an article to the feading list, click on the sunglasses icon at the left of the searchbar.
