### ISSUE TITLE
Visualize clickable items

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#60]
Currently, I see no way to see if an element is clickable or not.

Usually, and as far I know, following approaches are used:
* Change the pointer style
* Change the clickable item backgroudn color (/forground color).

What is the approach to do that in Kiwix Desktop?

**Comment by schoenbaechler** [comment]
Hey @kelson42 👋 I think you already figured it out! Just checked an initial design file where I defined the hover states. And yeah, it’s as you said, or in CSS terms:

`cursor: pointer;`
`background-color: #d9e9ff;`

It’s basically the same as for the active state, but without the blue (`#3366cc`) border. Also, if you’re wondering about the focus state for keyboard interaction on these elements: that’d be the same but with an added 2px ´3366cc` border, to differentiate it from the enabled state, which has a 1px border.

CC @mgautierfr

**Comment by kelson42** [comment]
@schoenbaechler Thank you for your confirmation. We should now apply it.

**Comment by kelson42** [comment]
To a large extend, this has been done. We should open a dedicated ticket if a new case appear.
