### ISSUE TITLE
Add command-line --version flag

### ISSUE THREAD

**Issue by legoktm** [kiwix/kiwix-desktop#602]
Debian CI has the option to run a command to verify the package runs properly after being installed, usually by running --help or --version. This would catch runtime errors like a missing dependency not being installed or the wrong library version being present. You can see what I've done for [kiwix-tools so far](https://salsa.debian.org/legoktm/kiwix-tools/-/blob/master/debian/tests/control).

So could kiwix-desktop also have a CLI `--version` option that just printed the version and quit?

Currently I get something like:
```
root@d290802461b3:/# QT_QPA_PLATFORM=minimal kiwix-desktop --version          
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
This plugin does not support createPlatformOpenGLContext!
[6276:6276:0219/223902.567966:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
root@d290802461b3:/# QT_QPA_PLATFORM=minimal kiwix-desktop --version --no-sandbox
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
This plugin does not support createPlatformOpenGLContext!
Compiled with Qt Version  5.15.1
Runtime Qt Version  5.15.2
This plugin does not support application fonts
This plugin does not support application fonts
This plugin does not support application fonts
This plugin does not support application fonts
This plugin does not support application fonts
kiwix-desktop: Unknown options: version, no-sandbox.
```

**Comment by kelson42** [comment]
@HanYoung-uwu Maybe something you would be interested to have a look? The version is defined in the `.pro` file.

**Comment by kelson42** [comment]
Adding a minimal help for `-h` and `--help` would be welcomed as well.
