### ISSUE TITLE
zim file don't open

### ISSUE THREAD

**Issue by DataRobot333** [kiwix/kiwix-desktop#603]
I try to open wikipedia_en_all_maxi.zim that i just downloaded but I get a **blank window**. what should I do to fix this?

**Comment by kelson42** [comment]
I guess your zim file is corrupted. Will check.

**Comment by kelson42** [comment]
I have tested and it works perfectly for me. What is the md5sum of your file? How have you downloaded it?

**Comment by DataRobot333** [comment]
I check it in my kernel and it return this:

~/Documents/wiki$ md5sum wikipedia_en_all_maxi.zim 
874b717bec544a8e76966dceee333e01  wikipedia_en_all_maxi.zim

**Comment by DataRobot333** [comment]
I download it from wikipedia zim files through the wget( but it was not consistent and use `wget -c` later on)
this is the link that I download the file 'https://download.kiwix.org/zim/wikipedia_en_all_maxi.zim'

**Comment by kelson42** [comment]
Your file is corrupted. The md5sum is Not OK, see http://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2021-02.zim.mirrorlist. Better use Bittorrent for such a big file.
