### ISSUE TITLE
Search / Suggestions  are totally broken with latest (dev) libzim 7.0.0

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#604]
I always get a blank page if:
* click on any suggestion
* click on a suggestion which is a redirect
* make a fulltext search

**Comment by kelson42** [comment]
@asashnov Do you think you could explain/fix this regression?

**Comment by asashnov** [comment]
Tested on recent versions of libzim (700d430d), kiwix-lib (971374e0) and kiwix-desktop (0183274f) on Ubuntu 18.04 x64.

Tested scenario:
1. Open wikipedia_en_all_mini_2020-04.zim  (11 Gb)
2. Type 'raspberry' in the search box
3. Click on 'American Raspberry' in search results

Actual result:  about:blank page 

Expected result: the article 'American Raspberry' should be displayed.

**Comment by asashnov** [comment]
```c
void SuggestionListWorker::run()
...
    QUrl url;
    url.setScheme("zim");
...
        url.setHost(currentZimId + ".zim");
...
            url.setPath(QString::fromStdString(suggestion[1]));
            qDebug() << "URL:" << url;
```

Prints:
> URL: QUrl("")

**Comment by asashnov** [comment]
Returned `kiwix::SuggestionsList_t` line is OK:
"American Raspberry"
"A/American_Raspberry"
"american raspberry"

But QUrl::isValid() returns `false`. QUrl::errorString() returns:
> "Path component is relative and authority is present; source was \"A/Raspberry\"; scheme = \"zim\", host = \"59bd7f21-70e3-f2d0-4eab-243a40178c34.zim\", path = \"A/Raspberry\""

**Comment by asashnov** [comment]
Previously there was a method `getNextSuggestion()`:
```c
    auto reader = KiwixApp::instance()->getLibrary()->getReader(currentZimId);
    QUrl url;
    url.setScheme("zim");
    if (reader) {
        url.setHost(currentZimId + ".zim");
        reader->searchSuggestionsSmart(m_text.toStdString(), 15);
        std::string title, path;
        while (reader->getNextSuggestion(title, path)) {
            url.setPath(QString::fromStdString(path));
            suggestionList.append(QString::fromStdString(title));
            urlList.append(url);
        }
    }
```

And this `Reader::searchSuggestionsSmart()` from kiwix-lib returned '/' at the beginning:
```c
/* Try also a few variations of the prefix to have better results */
bool Reader::searchSuggestionsSmart(const string& prefix,
                                    unsigned int suggestionsCount)
{
...
      std::vector<std::string> suggestion;
      suggestion.push_back(current->getTitle());
      suggestion.push_back("/A/" + current->getUrl());
      suggestion.push_back(kiwix::normalize(current->getTitle()));
```

Current version doesn't add '/', and using getPath() from libzim:
```c
bool Reader::searchSuggestions(const string& prefix,
                               unsigned int suggestionsCount,
                               SuggestionsList_t& results)
{
...
  for (auto& entry: zimArchive->findByTitle(prefix)) {
...
    auto item = entry.getItem(true);
    std::string articleFinalUrl = item.getPath();
...
      std::vector<std::string> suggestion;
      suggestion.push_back(entry.getTitle());
      suggestion.push_back(articleFinalUrl);
      suggestion.push_back(normalizedArticleTitle);
```

In libzim:
```c
std::string Item::getPath() const
{
  if (m_file->hasNewNamespaceScheme()) {
    return m_dirent->getUrl();
  } else {
    return m_dirent->getLongUrl();
  }
}
```

Probably `m_dirent->getUrl()` doesn't start with / 

So libzim and kiwix-lib didn't start path with /  so QUrl rejected it.

@mgautierfr  Therefore, my Pull Request maybe not correct, because I added this / in Kiwix-desktop. But maybe it should be added at 'kiwix-lib' layer.
