### ISSUE TITLE
Usability: unclear toggle button in the Search box

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#605]
Found in current 'master' (0183274f)

![Screenshot from 2021-02-26 01-24-02](https://user-images.githubusercontent.com/5078434/109199198-b98fa080-77d1-11eb-979f-f3b2cfaaa42c.png)

![Screenshot from 2021-02-26 01-24-09](https://user-images.githubusercontent.com/5078434/109199211-bd232780-77d1-11eb-9ef2-1d91a85c0620.png)

'Glasses' icon does not have a tooltip. Also, a placeholder text in Search bar repeats the current page title.

It would be more logical (and useful) if the placeholder text in Search explains which kind of search will be performed, for example:

When the button is on, placeholder says:
> Type here to search in all the articles of the current document

When the button is off, the placeholder says:
> Type here to search in the current page only

As I don't know the use of this toggle button, the texts above are just an examples, they should be written to really describe the current search tool state.

**Comment by asashnov** [comment]
Got it!  It's kind of bookmarks. So maybe it would be more expected by users to replace it with a star (☆) icons (favorites).

**Comment by kelson42** [comment]
@asashnov I believe, like you suggested, the best thing to do current,y is to add the tooltips:
* "Add to the reading list"
* "Remove from the reading list"

**Comment by kelson42** [comment]
@asashnov I'm not eager to change the behaviour of printing current page in the searchbox. This has a decision which has been carefully taken if I correctly remember. Same for the logo choice. Maybe @schoenbaechler can give a bit more background explanation why it has been done that way.

@asashnov If you could quickly add the tooltip, this would be great.

**Comment by kelson42** [comment]
@asashnov @Popolechien I would like to move on with this ticket. I believe the best thing to do is:
* Replace the current icon set with the standard « bookmark star »
* Add the tooltip

OK for both of you!

**Comment by Popolechien** [comment]
fine by me!

**Comment by sgourdas** [comment]
I made a PR to solve this issue. A few example screenshots below:

![Screenshot_1](https://github.com/kiwix/kiwix-desktop/assets/57002743/d53c0a94-1955-4df9-a4ba-daa8cc77b714)
![Screenshot_2](https://github.com/kiwix/kiwix-desktop/assets/57002743/d5813da8-2346-4044-b822-f6f147ba06f0)
