### ISSUE TITLE
[regression] Crash scenario with suggestions

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#607]
Running brand new kiwix-serve (with cutting edge dev version of libzim and libkiwix).

```
$ ./kiwix-desktop /home/kelson/Downloads/wikipedia_en_all_maxi_2021-02.zim
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
js: Uncaught SyntaxError: Unexpected end of input
js: Uncaught SyntaxError: Unexpected token .
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
terminate called after throwing an instance of 'zim::EntryNotFound'
  what():  Cannot find entry
Aborted (core dumped)
```

The only thing I made is that I typed `emmanuel` in the search bar.

The bug is 100% reproduceable and is a regression.

**Comment by kelson42** [comment]
@asashnov Would be really great if you could look at that one as well.

**Comment by kelson42** [comment]
Fixed

**Comment by kelson42** [comment]
@asashnov ping?

**Comment by kelson42** [comment]
@maneeshpm Do you think this is something you could look at? This might be an interesting task as there is multithreading in action here.

**Comment by maneeshpm** [comment]
Sure @kelson42, I'll look into this.

**Comment by maneeshpm** [comment]
@kelson42 can we still recreate this issue? I tried just typing `emmanuel` in the search bar. It gives all the suggestions for this query without causing any crash. Hitting enter takes me to an article, without causing a crash.

Am I missing any intermediate step for recreating this issue?
```
$ kiwix-desktop wikipedia_en_all_mini_2021-01.zim         
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
js: Uncaught SyntaxError: Unexpected end of input
js: Uncaught SyntaxError: Unexpected token .
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
js: Uncaught ReferenceError: mw is not defined
Handling request QUrl("zim://7fe4cca9-607f-5932-c685-9a22c1c410b5.search?content=7fe4cca9-607f-5932-c685-9a22c1c410b5&pattern=emmanuel")
```

**Comment by kelson42** [comment]
@maneeshpm will try again with latest libzim/libkiwix, but this is related to your speed of typing.

**Comment by kelson42** [comment]
@maneeshpm Tested again and the soft crash in the same manner. I believe you should check around:
```
terminate called after throwing an instance of 'zim::EntryNotFound'
  what():  Cannot find entry
```

**Comment by asashnov** [comment]
@kelson42  I couldn't reproduce the crash either.

> Running brand new kiwix-serve
Does it mean the crash happens when type in search inside web browser window?

I tried both search boxes in the UI, when some .zim opened; and in Library page. Also tried the web interface. Everything works as expected.


So need a detailed step-by-step instruction how the crash reproduces. This way I can trace in the source code, add some 'try/catch' and print debug logs.  It really seems to be related to multithreading and different CPU cores/speed characteristics.

PS. Once I have seen something similar- only one developer in the team was experiencing the bug because he had the most powerful machine.

**Comment by kelson42** [comment]
Reassinging the ticket to @mgautierfr as it really seem to be a subtil one.

**Comment by kelson42** [comment]
Tried with latest libzim/libkiwix and I'm not able to reproduce the crash scenario. Closing for the moment.
