### ISSUE TITLE
Allow option to export bookmarks

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#61]
Core should be in the libkiwix and available through JNI (see https://github.com/kiwix/kiwix-android/issues/822)

**Comment by kelson42** [comment]
I think we should stick to the Firefox/Chrome HTML export format.

**Comment by kelson42** [comment]
See https://github.com/kiwix/kiwix-desktop/issues/61

**Comment by kelson42** [comment]
@ShaopengLin Please make a UI proposal, the primitive to export the bookmarks is in the libkiwix.

**Comment by ShaopengLin** [comment]
If we just want the functionality, this should be it.
![Screenshot from 2024-07-21 21-24-56](https://github.com/user-attachments/assets/1166d234-809c-40c6-aae8-de79fdb501c7)

Are there any other features you were thinking of?

**Comment by mgautierfr** [comment]
> Are there any other features you were thinking of?

Import bookmarks ?

**Comment by kelson42** [comment]
@ShaopengLin You can carry on with implementation
