### ISSUE TITLE
can't use kiwix-serve over Proxifier

### ISSUE THREAD

**Issue by GoblinLegislator** [kiwix/kiwix-desktop#614]
When Proxifier is used with option **handle direct connections** and appropriate rules I made, when I am not using any proxies, but only Proxifier for purpose of observing connections and data usage, it does not work. I will repost here my discussion with Proxifier developer. Hope they will make it able to ignore localhost when handling direct connections. Only your app does not work with it, all others like Firefox, XAMPP (Apache...), Xowa as server...are fine. I tried both using it directly via command line, and via gui from app last version. Yes I tried turning off any firewalls...

Me:

> I noticed last version of Proxifier interferes with local connections of servers such as kiwix (kiwix-serve.exe) when option "handle direct connections" is used. I tried disabling firewall.
> 
> Command line I used for kiwix-serve is: D:\portable\kiwix\kiwix-serve.exe -p8181 -l C:\Users\Administrator\AppData\Roaming\kiwix\library.xml
> 
> It says if entered in cmd: Unable to instantiate the HTTP daemon. The port 8181 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.
> 
> I checked via nirsoft CurrPorts that port is not occupied and problem disappears when I disable "handle direct connections".
> 
> Reason I want to handle direct connections is to see which sites I am accessing. Earlier I told you for Firefox that it shows some connections in such case with no received data, but you said it is not problem.
> 
> I would also like to see option to ignore localhost when using handle direct connections.

> Proxifier Standard Edition v4.03 x64
> Windows 10 Pro x64 20H2
> Kiwix Desktop 2.04
> Debug log:

[debug log.zip](https://github.com/kiwix/kiwix-desktop/files/6151738/debug.log.zip)

Dev:

> Thanks for the info.
> 
> Your log looks OK. I guess the problem is kiwix-serve.exe specific. When Proxifier processes its loopback connection directly, the program has a problem with open port detection.
> The current version of Proxifier does not allow you to bypass "Handle direct connection" option for Localhost. We will consider adding this in the next version.
> I recommend you to try to contact the developers of kiwix-serve.exe. Maybe they will be able to suggest a solution.
> 
> Please let me know if you have any questions.

**Comment by kelson42** [comment]
I don't know Proxifier and don't have I believe, so what is your question exactly for kiwix-serve?

**Comment by GoblinLegislator** [comment]
Well maybe this is something wrong with Proxifier. Just hope you can make it compatible with it.
I don't need kiwix-serve to be used over Proxifier, but that is Proxifier's limitation, handle or none, when handling direct connections.

**Comment by kelson42** [comment]
We can not investigate any third party software possible for you. Either you have a clear technical bug report or feature requirement for kiwix serve or I will close it.
