### ISSUE TITLE
[regression] Pagination problem with fulltext search.

### ISSUE THREAD

**Issue by playerblest** [kiwix/kiwix-desktop#617]
Two questions please:

Is there a Kiwix To windows Shortcut key to return to the previous page?
When I do a full text search it shows me only the first 25 results. Do you know such a problem?
Thank you!

**Comment by mgautierfr** [comment]
> Is there a Kiwix To windows Shortcut key to return to the previous page?

No, there is not. But we may want to add one.

> When I do a full text search it shows me only the first 25 results. Do you know such a problem?

The search result is paginated with page of 25 results yes.
You can change pages by using the links at the end of the search result page.

**Comment by playerblest** [comment]
@mgautierfr 
Thanks for treatment.
About the second question - for some reason I do not have the list of pages below ... Attached is a screenshot. Do you know of such a problem?
(Note in the second image that the scroll bar is at the bottom of the page.)
I will mention that I use Hebrew. it's connected?

![תמונה](https://user-images.githubusercontent.com/81560060/113052667-1525c300-91b0-11eb-8af5-8514e6e70288.png)

![תמונה](https://user-images.githubusercontent.com/81560060/113052712-253da280-91b0-11eb-9772-d4bffd826c43.png)

**Comment by playerblest** [comment]
@kelson42 > 

> 
> הכוונה כאן היא קיצורי מקשים לניווט בהיסטוריה? מהם הסטנדרטים?

I mean back to the previous page I looked at (the arrow that appears above). In the first version of KIWIX they would do this with Backspace and it was very comfortable.

**Comment by mgautierfr** [comment]
I confirm there is something wrong with the search using kiwix-desktop.
On my side, I have the links at the end of the page, but the pagination is broken, I have only one page even in we display only 25 results.

Launching a local server (from kiwix-desktop) and doing the search using a browser, everything is ok.

**Comment by kelson42** [comment]
@mgautierfr @playerblest I would recommend to open a new ticket with the exact step by step reproduction case.

**Comment by kelson42** [comment]
@maneeshpm Do you think this is something you could look at?

**Comment by maneeshpm** [comment]
@kelson42 Sure, this should make me familiar with kiwix-desktop codebase!

**Comment by kelson42** [comment]
@maneeshpm thx a lot
