### ISSUE TITLE
Implement history navigation shortcuts

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#618]
* ALT+left key to go back in the history (if possible)
* ALT+right key to go forward in the history (if possible)

**Comment by Goutte** [comment]
Mouse shortcuts (thumb buttons) would be appreciated as well !  Since the feeling is the one of a browser, I keep trying to use them.

**Comment by kelson42** [comment]
@Goutte Yes, By experience those buttons might be harder to get well supported (at least it was harder with xulrunner and kiwix desktop v1... I even had to buy a mouse with these buttons to get it working). I might move this request to another ticket.

**Comment by Goutte** [comment]
That's too bad !   I found https://doc.qt.io/qt-5/qt.html#MouseButton-enum which mentions `ForwardButton` and `BackButton`.

**Comment by Goutte** [comment]
It's rather complicated with the `QShortcut` API but really forward with the `QEvent` API.

I monkey-tested, and it worked !  So I took the liberty of submitting a MR about this.

Feels great to satisfy my muscle memory  :partying_face:

**Comment by asashnov** [comment]
@kelson42 I have no experience with working additional mouse buttons. QEvent API sounds good to solve this.

@Goutte Did you send your patch somewhere?

**Comment by Goutte** [comment]
@asashnov Yes !  It is linked above : #646
