### ISSUE TITLE
Unable to open "Translations" in wiktionary:Offline

### ISSUE THREAD

**Issue by Fabrika2Grafem** [kiwix/kiwix-desktop#620]
There's no [show] or [hide] on the bar.
Version of Kiwix : 2.0.4
Version of Wiktionary : wiktionary_en_all_maxi_2021-03.zim

Thank you!

**Comment by Fabrika2Grafem** [comment]
- [bug]

**Comment by kelson42** [comment]
Thx for the bug report, but this is a duplicate of https://github.com/openzim/mwoffliner/issues/1033
