### ISSUE TITLE
Make the "home" keyboard key focus the search form

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#622]
It's a suggestion done via e-mail by RMS.

The "home" key of the keyboard scrolls the current page (or frame) to its top (in most browsers).
RMS would find it useful that it also puts the cursor in the search form, so that the user can immediately type another search (without using the mouse)

Same as https://github.com/kiwix/kiwix-js/issues/704 for Kiwix JS

**Comment by mgautierfr** [comment]
I'm not sure about what is the "search form", but there is already :
- Ctrl+L to focus the search bar (as for any web browser)
- F3 to search in the page

I see no reason to change the behavior of well known shortcut shared with a lot of (if not all) tools.

---

There is a action planned in our code to search in the library but it is not used.
We probably want to use/activate it but it is another problem.

**Comment by kelson42** [comment]
> I see no reason to change the behavior of well known shortcut

This ticket does not request to change the behaviours you have listed above. It asks to implement a behaviour which is to be found in any browser (with a focus on the search box)... a behavirour which is currently not implemented in Kiwix Desktop.

**Comment by mgautierfr** [comment]
The title `Make the "home" keyboard key focus the search form` makes me think that it is asked to make the home key focus the search box.
But as you mention it, the "home" key is used to go to the top of the page. I'm speaking about this well known shortcut behavior.

> It asks to implement a behaviour which is to be found in any browser (with a focus on the search box)... a behavirour which is currently not implemented in Kiwix Desktop.

As said in my previous comment, it depends on what is "search box" but there is already the shortcut `Ctrl+l` to focus the top searchbar.

**Comment by kelson42** [comment]
The searbox is the box to make searches ft/suggestions in the zim files.

**Comment by mgautierfr** [comment]
So Ctrl+l is your shortcut.

**Comment by kelson42** [comment]
No, CTRL+L does not satisfy fully the requirement, only half of it.

**Comment by mgautierfr** [comment]
What is the requirement missing ?

**Comment by kelson42** [comment]
> The "home" key of the keyboard scrolls the current page (or frame) to its top

**Comment by mgautierfr** [comment]
This is not a requirement, this is a statement about what is currently implemented.

**Comment by kelson42** [comment]
Nothing to do.
