### ISSUE TITLE
How to retrieve the library metadata by RESTful API endpoint with OPDS?

### ISSUE THREAD

**Issue by leanhdung1994** [kiwix/kiwix-desktop#624]
I'm using local Kiwix server from Kiwix desktop. From this [page](https://wiki.kiwix.org/wiki/Kiwix-serve), I found information about [OPDS](https://wiki.kiwix.org/wiki/OPDS).

Could you please elaborate on how to use RESTful API endpoint with OPDS to retrieve the library metadata from my local Kiwix server?
![image](https://user-images.githubusercontent.com/28704090/113888178-62aebb00-97c2-11eb-910a-7b596ba5946d.png)

**Comment by kelson42** [comment]
Documentation is here https://wiki.kiwix.org/wiki/OPDS
