### ISSUE TITLE
Unable to open local file

### ISSUE THREAD

**Issue by Bam92** [kiwix/kiwix-desktop#63]
OS: Windows 10
Kiwix: v2.0 - alpha6

When I click the **Open** button the app crashes as you can see on the image

![crash-after-open-btn-click](https://user-images.githubusercontent.com/14941675/49305972-84eceb80-f4d9-11e8-9e0c-614265f01e30.PNG)

**Comment by kelson42** [comment]
@Bam92 Which content exactly? Have you tried with other content?

**Comment by Bam92** [comment]
Any content. Wikimed, Vikidia, etc.

**Comment by kelson42** [comment]
@Bam92 Additional questions: How was this local file downloaded? What is the full path of that file?

**Comment by Bam92** [comment]
Downlaoded from my Debian 9 computer with wget. files as well as  kiwix-desktop.exe are in a USB key. Didn't try to open the .exe from the console.

**Comment by kelson42** [comment]
@Bam92 Beta1 has been published https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_windows_x64_2.0-beta1.zip. Please try again from the command line and if still fails, make a copy of the whole command line and error message you get please.

**Comment by kelson42** [comment]
@Bam92 Have you been able to test the new beta and confirm the bug has disappear?

**Comment by kelson42** [comment]
@Bam92 You can still open file like always through the menu > File > open file. Concerning the problem why you did not tried to just exec `vc_redist.x64.exe` which is available in the ZIP?
