### ISSUE TITLE
Aria2 only downloads to local storage

### ISSUE THREAD

**Issue by jetownfeve21** [kiwix/kiwix-desktop#630]
In the case of a download from a kiwix-desktop app running on an usb-driver, it will be downloaded to the local storage and the library.xml of the usb-drive file will not matching the zim files of the usb-drive

**Comment by kelson42** [comment]
I should reassess this issue

**Comment by kelson42** [comment]
Situation reassessed with cutting edge (`2.4.0`) dev version:
* If Kiwix started from an USB drive, per stores ZIM files and library.xml in the local user home confi (so not on the USB drive)
* If you change the download directory then new ZIM files are saved to the new download directory, but all the rest is left on the local user home config. No option is provided to migrate the data from the old to the new location.

**Comment by kelson42** [comment]
I believe a few things should be changes like:
* Document the multiple things which are store on the disk
* Allow to migrate current content (library.xml included?) to the new download directory if changed
* Configuration of this should be able to be specified on the USB drive somehow (so changing default behaviour)

But we should look to all of this later. Postponing.

**Comment by sgourdas** [comment]
@kelson42 so everything is clear:

> Allow to migrate current content (library.xml included?) to the new download directory if changed

On download directory change, a popup will give the option to the user to copy all zim files and library.xml to the new path.

> Configuration of this should be able to be specified on the USB drive somehow (so changing default behaviour)

What does this refer to exactly?

**Comment by sgourdas** [comment]
@kelson42 if we decide to proceed with the popup method I proposed, we should consider what we want to do with the current popup when changing download directory, that asks the user if he is sure that he wants to change directories.

What I propose is a combined popup with 3 options like the one below:
![image](https://github.com/user-attachments/assets/988a3e46-1938-408a-8fe1-40f6c436b24a)

Regardless of this, is copying over all library files what we want in the migration case?

**Comment by kelson42** [comment]
@sgourdas Sorry for my lack of feedabck, coming back tomorrow on this

**Comment by kelson42** [comment]
In a case of a portable Kiwix (running on a portable USB drive for example), none of the files should be written [at the usual locations](https://github.com/kiwix/kiwix-desktop/wiki/Data-and-Configuration-Files).

A portable Kiwix is when there is (an empty) file `.portable` just beside the Kiwix binary. Detecting the presence of that file will activate the portable mode.

The portable mode will read/write the data files to another (predefined) location positioned relatively position to the Kiwix binary:
* `data/kiwix-desktop.session`
* `data/kiwix.session`
* `data/*.zim`
* ...

In such a mode nothing should be written to the hard disk.

**Comment by sgourdas** [comment]
@kelson42 thanks for the clarification. This makes things more clear, but I still have some questions.

I understand that when we have the `.portable` presence the app will use the library files in the USB's predefined location. 
- Where does the "migration" part come in?
- Will this `.portable` file be created by the user?

**Comment by kelson42** [comment]
> * Where does the "migration" part come in?

I'm not sure about what should be migrated, but I believe nothing should be migrated. If someone execute Kiwix portable on a computer where Kiwix is already installed/running, this will be fully ignored (all the data files will be read/written locally and the one on the system will be ignored).
 
> * Will this `.portable` file be created by the user?

The packager, we can discuss about this later.

**Comment by sgourdas** [comment]
The parts I am referring to regarding the migration are:

> At the time the profile path is changed, propose to migrate the current profile (with content).

> If you change the download directory then new ZIM files are saved to the new download directory, but all the rest is left on the local user home config. No option is provided to migrate the data from the old to the new location.

> Allow to migrate current content (library.xml included?) to the new download directory if changed

**Comment by kelson42** [comment]
> The parts I am referring to regarding the migration are:
> 
> > At the time the profile path is changed, propose to migrate the current profile (with content).
> 
> > If you change the download directory then new ZIM files are saved to the new download directory, but all the rest is left on the local user home config. No option is provided to migrate the data from the old to the new location.
> 
> > Allow to migrate current content (library.xml included?) to the new download directory if changed

I understand now. This comment is 5 years old and we have already an option to change the location to save data. I think it might make sense to close this old ticket and reopen a new one properly. But the [core idea](https://github.com/kiwix/kiwix-desktop/issues/630#issuecomment-2259159893) stays the same: we need to be able to tell for each of the parts we read/write on the fs to customize programmatically for each the path.

**Comment by sgourdas** [comment]
> > The parts I am referring to regarding the migration are:
> > 
> > > At the time the profile path is changed, propose to migrate the current profile (with content).
> > 
> > > If you change the download directory then new ZIM files are saved to the new download directory, but all the rest is left on the local user home config. No option is provided to migrate the data from the old to the new location.
> > 
> > > Allow to migrate current content (library.xml included?) to the new download directory if changed
> 
> I understand now. This comment is 5 years old and we have already an option to change the location to save data. I think it might make sense to close this old ticket and reopen a new one properly. But the [core idea](https://github.com/kiwix/kiwix-desktop/issues/630#issuecomment-2259159893) stays the same: we need to be able to tell for each of the parts we read/write on the fs to customize programmatically for each the path.

Clear. I will start working on it soon then and we see what problems arise.

**Comment by kelson42** [comment]
This issue has been superseeded by #1166 and #1167
