### ISSUE TITLE
Tabs navigation

### ISSUE THREAD

**Issue by Oblike** [kiwix/kiwix-desktop#635]
Hi, 
I'm a kiwix user, giving some feedback about navigation fluidity mainly about tabs.
I often open a lot of new tabs when working on kiwix.
1- It would be useful to have possibility of rearranging them.
2- When you open (right clic) a link in a new tab, would be better to have it just after the current active one.
3- When you open (right clic) a link in a new tab, would be better to just create it and keep the current active one open.
Maybe those propositions have been made before, then sorry for disturbances.
English is not my primary language, i'm on the edge of my technic, hope i made myself clear enough. 

Thx to all of you, Kiwix is great. As I don't have stable internet connexion, it changes my life.

**Comment by mgautierfr** [comment]
Rearranging tabs has already been implemented (but not release yet) (https://github.com/kiwix/kiwix-desktop/pull/573)

**Comment by kelson42** [comment]
We still need to evaluate point 2 and 3. I believe the point 3 has already been discussed in the past.

**Comment by kelson42** [comment]
For more clarity we try to have only one topic per ticket. I have open #636 and #637 for your points 2 and 3 which seem valid to me. thank you!
