### ISSUE TITLE
Open new tab just right after the current one

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#636]
When you open (right clic) a link in a new tab, would be better to have it just after the current active one.

First reported in #635

**Comment by kelson42** [comment]
I’m supportive

**Comment by kelson42** [comment]
@asashnov Could you please implement this?

**Comment by juuz0** [comment]
Basically this, right?

https://user-images.githubusercontent.com/26814569/140073653-5ecb5e9b-4b1d-43ba-b0a9-30f31db4bd9f.mp4

**Comment by mgautierfr** [comment]
Yes. Even if I'm disturbed by the change of focus (but to be handled in #637)

Firefox has this behavior that if you open several tabs in a row (without changing tab), the new tabs are created just after the previously created tab. (No directly after the current tab, but more just before the next already existing tab). It would be nice (but not mandatory) to also have this behavior (and it would need #637 fixed as we must not change the current tab).

**Comment by kelson42** [comment]
@juuz0 Seems you have implemented it?!

**Comment by juuz0** [comment]
@kelson42 
Yes. I have. Not sure how to implement that Firefox behaviour as @mgautierfr  though.
