### ISSUE TITLE
Open new tab in background

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#637]
When you open (right clic) a link in a new tab, would be better to just create it and keep the current active one open.

First reported in #635

**Comment by kelson42** [comment]
It seems to be the default behaviour in Firefox and Chrome. I'm supportive.

**Comment by alex-ie** [comment]
I have middle button on trackpad and clicking it on link opens it in background. So I have a choice current way. Can Kiwix retain current way and in resolving that issue add another line to right-click menu with "open in new background tab"? Right-click menu is not overloaded now.

**Comment by kelson42** [comment]
At this stage my strategy is to do like Firefox/Chrome. I kind of assume that whatever how they do, this is the right way to follow. Hoep this would OK for users.

**Comment by mgautierfr** [comment]
If I do a middle click on a link in kiwix-desktop, the link is opened in a new tab. The current tab is keep selected and we don't switch automatically to the newly created tab.

So it seems this issue is irrelevant (or already fixed)

**Comment by alex-ie** [comment]
@kelson42, by "(right clic) a link in a new tab," do you mean "Open in new tab" from right-click menu? If so it is different way from what @mgautierfr mentioned (middle click). That is just to make sure all clear. I've already voiced my opinion that current functionality (having two clicks working two different ways) seems better than having two clicks working the same. Thank you.
