### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by nkduodu** [kiwix/kiwix-desktop#639]
I have downloaded Kiwix-server and kiwix-Rear. I run these 2 files and i don't see any dialogue box or message that this has been installed.
Are there detailed instructions on how to install this? for the windows environment? i thought this was supposed t be an easy and simple tool to use?

**Comment by kelson42** [comment]
@nkduodu There is no installer, this is directly usable.

**Comment by nkduodu** [comment]
What does directly usable mean? @kelson...I don't understand your comment.
What are the .exe files then?

**Comment by kelson42** [comment]
The kiwix softwares.
