### ISSUE TITLE
How tu run Kiwix flatpak file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#64]
We have started to publish the flatpak files in the nightlies, but how to get Kiwix running from it?

**Comment by mgautierfr** [comment]
- Install flatpak on your system using instructions here : https://flatpak.org/setup/
- Download the flatpak file from the nightlies directory (ie http://download.kiwix.org/nightly/2018-11-30/org.kiwix.Client.2018-11-30.flatpak)
- Install the downloaded flatpak using `flatpack install --user org.kiwix.Client.2018-11-30.flatpak`.
Double clicking on the download file on your file explorer may also launch the installation process depending of your system (I'm not sure about this)

**Comment by kelson42** [comment]
@mgautierfr I have an error
```
$ flatpak install --user org.kiwix.Client.2018-11-30.flatpak
error: The Application org.kiwix.Client/x86_64/master requires the org.kde.Platform/x86_64/5.11 which was not found
```

**Comment by kelson42** [comment]
@mgautierfr I have an error
```
$ flatpak install --user org.kiwix.Client.2018-11-30.flatpak
error: The Application org.kiwix.Client/x86_64/master requires the org.kde.Platform/x86_64/5.11 which was not found
```

**Comment by mgautierfr** [comment]
Have you installed flathub ?

**Comment by Bam92** [comment]
This is how I did install and run flatpak file

OS: Debian 9
Kiwix: 2.0-beta

- follow instructions as  @mgautierfr  has pointed out above

- download the flatpak file from https://download.kiwix.org/release/kiwix-desktop/ 

- install it as this: `flatpak install org.kiwix.Client.2.0-beta1.flatpak ` (double-clicking also launches the install process)

- to run it do `flatpak run org.kiwix.Client` and enjoy!

Hope that it can help!

![image](https://user-images.githubusercontent.com/14941675/49580648-19cb6b00-f958-11e8-9aee-b5ce94bcce13.png)

**Comment by kelson42** [comment]
I finally achieved this following these commands:
```
# Install Flatpk
$ sudo apt-get install flatpak

# Install Flathub (for the dependencies)
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Download the Kiwix Desktop Flatpak
$ wget https://download.kiwix.org/release/kiwix-desktop/org.kiwix.Client.2.0-beta1.flatpak

# Install Kiwix Desktop
$ flatpak install org.kiwix.Client.2018-12-10.flatpak

# Run Kiwix Desktop
flatpak run org.kiwix.Client
```

```
