### ISSUE TITLE
On Startup detect new zim files added to download directory and ask to add them to local files library (all at once)

### ISSUE THREAD

**Issue by haniobaid** [kiwix/kiwix-desktop#644]
This should be a bandwidth saver (both server and client side) for people who download once and load on multiple devices. Right now you would have to add files one at a time

**Comment by kelson42** [comment]
This sounds a good idea. I beliece we have a similar bug open already somewhere. But I would like to think more about it and frame it properly before implementation.

**Comment by juuz0** [comment]
@kelson42 
Almost done with this, 
but while doing I thought of this : 

A new option in Settings to load all zim files from a directory (user chooses from a dialog box) 

Would like to know your views on it ^^

**Comment by kelson42** [comment]
@juuz0 Nice, impatient to test the PR. Regarding your idea, please open a new ticket. I will do a new assessment when this ticket will be closed.

**Comment by kelson42** [comment]
With @mgautierfr, we would like to close this ticket as `WONTFIX` in favor of #713.

We are not 100% comfortable of:
* Having per default a process of monitoring a full directory.
* Having it per default on the same directory like "Download directory".

If someone wants to monitor its "Download directory", then he will have to configure the - still to be created - "Directory to monitor" to be the same.

@juuz0 @haniobaid Does that make sense that way to you?

**Comment by juuz0** [comment]
@kelson42 Sounds good to me :+1:

**Comment by kelson42** [comment]
Duplicate of #713
