### ISSUE TITLE
Kiwix x64 2.0.5 crashes on startup Windows 10 20H2

### ISSUE THREAD

**Issue by VincentXE** [kiwix/kiwix-desktop#650]
When I try to launch Kiwix 2.0.5, it pops up a windows for about 5 seconds, then closes. I tried moving it to different drives and directories, but nothing I've tried works. 

![image](https://user-images.githubusercontent.com/17298607/120820557-460cd600-c51a-11eb-92d4-e1581eb1ebd7.png)

**Comment by kelson42** [comment]
Definilty not normal. What is your OS? What that your first first (or it was working before)? What is display on the dialog box which is displayed before crashing? What is display on the terminal if you start Kiwix from the command line?

**Comment by VincentXE** [comment]
> Definilty not normal. What is your OS? What that your first first (or it was working before)? What is display on the dialog box which is displayed before crashing? What is display on the terminal if you start Kiwix from the command line?

OS: Windows 10 Pro 20H2

I used Kiwix 2.0 beta fine, but I just downloaded 2.0.5 and 2.0.5 doesn't work. It just crashes

What is displayed when I try to open it is this:
![kiwix-desktop_SK3owz8GmF](https://user-images.githubusercontent.com/17298607/120823353-f7147000-c51c-11eb-97d3-8bc633db4bd8.png)

If I try to start it with cmd, it just starts up the same
![image](https://user-images.githubusercontent.com/17298607/120823507-1e6b3d00-c51d-11eb-8034-9828d17c4347.png)

But something weird happened, when I tried starting it up, it started up normally. I got it recorded

https://user-images.githubusercontent.com/17298607/120823582-2f1bb300-c51d-11eb-9a55-26578d98c86f.mp4

I'm trying to open it right now and it just won't work.

**Comment by kelson42** [comment]
@VincentXE Thx for the details and the video, this is helpful. So 2.0.5 fails to start sporadicaly (or it sporadicaly starts properly), right?

**Comment by VincentXE** [comment]
> @VincentXE Thx for the details and the video, this is helpful. So 2.0.5 fails to start sporadicaly (or it sporadicaly starts properly), right?

Yep

**Comment by VincentXE** [comment]
Alright, so I seemed to have fixed it.....strange issue though.

It seemed to have been picking up the 3 zim files I had. they were english Wikipedia 2018, English wikiquote 2018, and English wikisource 2018. I downloaded completely new zim files of each, deleated the old ones, and now it boots up perfectly.

BUT, it does not detect my new zim files, while when it did sometimes start correctly, it detected only my Wikipedia one. 

it DOES NOT WORK with the 2018 files in this directory, but when deleted, kiwix boots up. The new files are in the "zim files" folder, and it doesn't pick up the new files at all......
![image](https://user-images.githubusercontent.com/17298607/120875875-a8de8b80-c573-11eb-924e-9efeb6cd5250.png)

**Comment by Jaifroid** [comment]
@VincentXE I had this issue some time ago with a full Wikipedia English download that would cause Kiwix Desktop to crash. Eventually, I discovered that the problem was a corrupted ZIM file causing the software to fail with very similar symptoms (the curly braces on the front page). I think Kiwix Desktop error catching could be improved, but the issue might be your ZIM file. If you downloaded it with Torrent software, e.g. qbittorrent, then you can force a recheck of the file, and it will fix it. Of course it could be something completely different in your case.

**Comment by kelson42** [comment]
@VincentXE If you can identify and upload the broken zim file that would be really helpful to reproduce/fix this bug.

**Comment by kelson42** [comment]
Without the problematic file, we can not fix this problem.
