### ISSUE TITLE
Unable to download zim files on Kiwix 2.0.5 on Windows 10

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#651]
Running Kiwix-desktop 2.0.5 downloaded minutes ago, I get the below error message when trying to download any zim file:
![image](https://user-images.githubusercontent.com/21675885/121346017-d89be380-c925-11eb-8d1f-0dab84882dcf.png)

Download works on android, so I assume this to be a desktop issue.

**Comment by kelson42** [comment]
Does it works now?

**Comment by Popolechien** [comment]
Yes. do we know what happened?

**Comment by kelson42** [comment]
No but we had a full mirror offline for many days and for an unknown reason, the mirror manager was still routing users to it. Might be the reason.
