### ISSUE TITLE
Trying to open Wikipedia_ar_top_maxi_2021_04 crashes Kiwix for Windows 10

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#652]
Downloaded Wikipedia_ar_top_maxi_2021_04.zim and tried to open it on my Windows 10 machine. When on the zim's landing page, if I click on an image to open an article, the application freezes.
This behaviour is not reproduced when trying with other Wikipedia-related zim files of a similar size (e.g. Wikipedia_en_physics_maxo_2021-03.zim, about 1.7 Gb as well)

Running Windows 10 Family edition version 20h2 build 19042.985

**Comment by Popolechien** [comment]
Same issue with Wikipedia_ar_top_maxi_2021_05.zim

**Comment by kelson42** [comment]
I have to try this with the latest code base.

**Comment by kelson42** [comment]
@Popolechien Can you please try with latest nightly http://download.kiwix.org/nightly/2021-06-12/kiwix-desktop_windows_x64_2021-06-12.zip? Good chances it will work.

**Comment by Popolechien** [comment]
The nightly won't open the download library so that's a rather bad start :-/

**Comment by kelson42** [comment]
You just have to open the zim file in theblocal storage... why do you need to download anything?

**Comment by kelson42** [comment]
No problem for me on Linux with latest dev version.

**Comment by Popolechien** [comment]
Because I'm on a different computer (home vs office). Will download the Zim directly and try again

**Comment by Popolechien** [comment]
Works here to on the latest nightly for Windows as well.
