### ISSUE TITLE
Clicking on links within "wikipedia_ja_all_maxi_2021-03.zim" causes the app to freeze

### ISSUE THREAD

**Issue by EsterLoken** [kiwix/kiwix-desktop#653]
I downloaded "[wikipedia_ja_all_maxi_2021-03.zim](https://download.kiwix.org/zim/wikipedia_ja_all_maxi.zim)" and it opens up just fine:

![image](https://user-images.githubusercontent.com/33354862/121804833-98e83b00-cc48-11eb-9a01-10067d89c178.png)

but as soon as I click a link there the app completely freezes.
I'm using kiwix-desktop_windows_x64_2.0.5.

If there's any way to produce a debug log that might be helpful, let me know.

**Comment by kelson42** [comment]
Thank you for your bug report. Do you have the same problem with the latest nightly? http://download.kiwix.org/nightly/2021-06-12/kiwix-desktop_windows_x64_2021-06-12.zip

**Comment by EsterLoken** [comment]
> Thank you for your bug report. Do you have the same problem with the latest nightly? http://download.kiwix.org/nightly/2021-06-12/kiwix-desktop_windows_x64_2021-06-12.zip

Hey Kelson, the nightly actually does work, I can click links and it takes me to the article instead of freezing up.

Thanks!

**Comment by kelson42** [comment]
I guess the problem has been already fixed then. But you will have to run this development version until we make a new official release.
