### ISSUE TITLE
Zoom in/out/reset shoold work forthe current tab only

### ISSUE THREAD

**Issue by asashnov** [kiwix/kiwix-desktop#654]
Currently (57162a79) Zoom in/out/reset action applied to all the opened tabs.

## Actual result

Pressing Ctrl++  Ctrl+-  (or zoom in/out with mouse wheel) is applied to every opened tab at the moment.

## Expected result

Pressing Ctrl++  Ctrl+-  (or zoom in/out with mouse wheel) should be applied to the current (active) tab only, as it is in all major web browsers.

## Additional details

In code that happens because Zoom in/out/reset is connected to every tab object created, regardless of the current tab:

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/zimview.cpp#L21

Suggested solution:

Handle Zoom in/out/reset like we handle 'Print' command (only the currently active tab is printed):

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/kiwixapp.cpp#L305

https://github.com/kiwix/kiwix-desktop/blob/57162a79ed21b46a65622093aa12cf5d99738cff/src/kiwixapp.cpp#L184

**Comment by ShivamJhaa** [comment]
I would like to fix this issue.
Thank you.

**Comment by kelson42** [comment]
@ShivamJhaa please, make a PR

**Comment by vaish567** [comment]
If this issue is still engaged with someone, I would like to go through this issue @kelson42 👍🏻

**Comment by kelson42** [comment]
@vaish567 I'm supportive, but explain first here how you plan to fix the problem.

**Comment by juuz0** [comment]
Hi, I think we can use the same if condition as used in Back and Forward buttons to only apply the zoom in/out effect on current tab

```cpp
if (mp_tabBar->currentZimView() != this) {
                    return;
```
If no is one currently working on this, I would like to do this :)

**Comment by kelson42** [comment]
@juuz0 Not sure what you exactly mean with your technical proposal, but yes, your are welcome to propose a patch.
