### ISSUE TITLE
Articles are not displayed on Windows (any file, any Kivix flavor)

### ISSUE THREAD

**Issue by smargo171** [kiwix/kiwix-desktop#658]
I have installed: kiwix-desktop_windows_x64_2.0.5, Kivix JS from Microsoft store, Kivix extension on Chrome.

I have downloaded 2 files: 
- wikivoyage_en_all_maxi_2021-05.zim
- wikipedia_en_all_maxi_2020-09.zim

If I open either of the files with any tool, I can open them without any error message, but when I try to search for a article, e.g. "Italy", no articles are displayed. On kivix-desktop there is an error message:

Your file was not found
It may have been moved or deleted.
ERR_FILE_NOT_FOUND

On Kivix JS or Chrome extension, there is no error message, just an empty page is shown.

My system:

Edition	Windows 10 Home
Version	20H2
Installed on	‎23/‎06/‎2021
OS build	19042.1081
Serial number	018364604351
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by kelson42** [comment]
For some reason, the file is not readable (anymore).Try to put the ZIM file on the same disk like the software.

**Comment by smargo171** [comment]
The smaller wikivoyage ZIM file is already on the same disk (C:) as the executable.
exe:
C:\Users\s3rg\kiwix-desktop_windows_x64_2.0.5\kiwix-desktop.exe
File:
C:\Users\s3rg\wikivoyage_en_all_maxi_2021-05.zim

The bigger ZIM (97 GB) is on the SD card. 
Both files show the same behavior.

**Comment by kelson42** [comment]
You can try with the latest dev version of Kiwix Desktop https://download.kiwix.org/nightly/2021-06-28/kiwix-desktop_windows_x64_2021-06-28.zip. But pretty sure this is something related to your install.

**Comment by smargo171** [comment]
The latest build can't be launched , have the following error message:
"Entry Point Not Found".

![image](https://user-images.githubusercontent.com/12448225/123751285-dccd7800-d8b7-11eb-8fb8-e9785333ce68.png)

**Comment by smargo171** [comment]
I have a fresh Win 10 install from a couple of days ago, new Surface Go 2, all latest updates installed and basically nothing more.

**Comment by kelson42** [comment]
OK, I will put this ticket in the milestone.... for the moment this is unclear what is going on.

**Comment by kelson42** [comment]
@smargo171 latest nightly should start now properly http://download.kiwix.org/nightly/2021-07-14/kiwix-desktop_windows_x64_2021-07-14.zip

**Comment by smargo171** [comment]
Thanks. I've installed the build from 01.07, it was also Ok.
