### ISSUE TITLE
WIP: Separating search for archives (ZIM's) and search for content (in articles)

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-desktop#664]
_Work in progress_
This issue proposes a concrete solution to the issue at hand in https://github.com/kiwix/kiwix-desktop/issues/554
The aim is to somewhat mimick the behavior of the Firefox browser with regards to searching for content and searching in settings.

- The tabs bar is ALWAYS the topmost UI element.
- Below is some "menu bar" that displays the appropriate navigation within the visible tab's content.
- Below is the content, respective to the tab type.

Imho, these are the advantages:

- This design avoids the "double search bar" from issue https://github.com/kiwix/kiwix-desktop/issues/554
- Since it is similar to an existing application, it does not reinvent the wheel much (Least Surprise)
- The displayed search bar is always where the searched items are (IN the tab, not above the tab bar)

Screen mockups:

:todo:

Clearly, this proposal is only a first draft, out of my own experience as a new kiwix user, and should be refined.

**Comment by kelson42** [comment]
@suterma Thank you for your proposal. Can you please just move this discussion to #554? There is not need to duplicate the ticket.

**Comment by suterma** [comment]
Closing this issue as per recommendation by @kelson42 and introduced it in #554 as a comment.
