### ISSUE TITLE
Additionally show the keyboard shortcuts for buttons in their tooltip

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-desktop#665]
Most applications show a description of the action of a button, along with the assigned keyboard shortcut (if any)  in a tooltip, when hovering. As a first-time user, I was expecting this, especially since the F11-Fullscreen shortcut "did not work". (See separate issue https://github.com/kiwix/kiwix-desktop/issues/304)

Here's how it looks like currently:
![hovering-tooltip](https://user-images.githubusercontent.com/11473920/126448019-60665e95-1a2d-4e92-a074-2d79c9fdeaea.png)
_The tooltip on hover is displayed without keyboard shortcut information_

Hovever, in the menu, however, the shortcut (CRTL+T in this case), is displayed properly.

Expected behaviour: The tooltip should display the keyboard shortcut along the text.
![hovering-tooltip-with-shortcut](https://user-images.githubusercontent.com/11473920/126448463-98e6f376-2047-43ba-87b3-56963a20ce75.png)
_The proposed tooltip with keyboard shortcut information_

Note: I experience this on a fresh, updated Ubuntu 20.04, using Version 2.0.5

**Comment by kelson42** [comment]
Agree, similar to #666
