### ISSUE TITLE
Tooltips inconsistency: not shown, when application is not focused

### ISSUE THREAD

**Issue by suterma** [kiwix/kiwix-desktop#666]
Most applications (e.g. Firefox, Thunderbird, LibreOffice on Ubuntu OS at least) show their tooltips when hovering the mouse over a button, even when they are not have focus (are not receiving actual keyboard input at the moment).

Kiwix, in this case, is highlighting the action, if available (lighting up in blue style), but the respective tooltip is not shown. Clicking the button however, immediately transfers the focus to the app and excecutes the action, as expected.

Here's how it looks like, when the mouse hovers over an actionable item, when the app does not have focus:
![notfocusednotooltip](https://user-images.githubusercontent.com/11473920/126449579-7acd3899-a5e5-470b-9c65-09cdc6bfdf31.png)

The expected behaviour would be that the tooltip is shown, as if the application had focus.

Note: 
- This might be an issue releated to some default behaviour of Qt.
- I experience this on a fresh, updated Ubuntu 20.04, using Version 2.0.5

**Comment by kelson42** [comment]
@suterma Agree

**Comment by kelson42** [comment]
@suterma Is that not something you could fix?

**Comment by Aryan-Mohanty** [comment]
@kelson42, Hey, I am willing to work on this. Can you tell me where to find the source code?

**Comment by suterma** [comment]
@kelson42 @Aryan-Mohanty That's fine with me, as I have no prior knowledge of Qt anyways.
@Aryan-Mohanty The source code is of course in this repo. To actually build it, you might want to use the tools at https://github.com/kiwix/kiwix-build

**Comment by kelson42** [comment]
@suterma I can not reproduce the problem with a cutting-edge version of Kiwix Desktop, see (this is without clicking):
![image](https://user-images.githubusercontent.com/1029718/131219788-b48e8cb1-15c9-4fef-9a09-109e80bf9fb2.png)

Or I misunderstand the ticket... I would recommend to test with the latest nightly https://download.kiwix.org/nightly/2021-08-28/. Would be interesting to know if the problem is still there.

@juuz0 You have work around the tooltip stuff, how does it behave for you?

**Comment by juuz0** [comment]
@kelson42 Yea I could reproduce the problem. 
These are the steps I followed -
Open two windows, one of Kiwix and one of Chrome. 
Unmaximised both.
Made Chrome active by clicking on it
and then hovered over the buttons in Kiwix, they don't show the tooltips. 

And as suterma said, Firefox does show.

**Comment by kelson42** [comment]
OK.... then indeed I'm not sure this is fixable. @juuz0 Do you?

**Comment by juuz0** [comment]
Yes, I think there's an attribute. I have tried it and working for me, just need a little more tests
