### ISSUE TITLE
Switching to a hanzi version of a page in the Min Dong Wikipedia causes Kiwix to freeze

### ISSUE THREAD

**Issue by programmeruser2** [kiwix/kiwix-desktop#668]
Download the [Min Dong Wikipedia .zim](https://docs.google.com/document/d/1fOColiO1NcbShUJqN3v0nMZh6hW6zYwfWgCdJQGbzw0/edit) and click on the link that says "頭頁" on the mainpage. This causes Kiwix to freeze.
(Another more minor issue is that the other links below the large mainpage boxes and above the sister project links don't work)

**Comment by kelson42** [comment]
@programmeruser2 Can you please try with latest nightly? http://download.kiwix.org/nightly/2021-07-27/

**Comment by programmeruser2** [comment]
> @programmeruser2 Can you please try with latest nightly? http://download.kiwix.org/nightly/2021-07-27/

It works, thanks.
