### ISSUE TITLE
HTTP service pretty broken with cutting-edge dev version of libkiwix

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#671]
The bugs I see:
* Icon is not displayed properly
* Download link is visible, but it should not
* Preview leads to a 404 URL

**Comment by MananJethwani** [comment]
@kelson42 there are 2 problems I detected which leads to such situations - 
1) kiwix-server for preview provides a url like this `http://192.168.1.6:8181/wikipedia_en_100_nopic_2021-07`
but for kiwix-serve started using kiwix-desktop humanFriendly naming is not enabled and this name leads to a 404, similar is the case for the icon.

2) download link in my case is only available for those zim files which were downloaded using the kiwix-dektop app, those which were imported from local folder didn't had a download button.

**Comment by kelson42** [comment]
@MananJethwani Can you fix the problems?

**Comment by MananJethwani** [comment]
@kelson42 I am not well aquainted with the processes undergoing here will take me a few days but I can try if you want.

**Comment by mgautierfr** [comment]
- Enabling human friendly naming should be pretty easy. You must pass a namemapper to the server. See what is done on kiwix-tools side : https://github.com/kiwix/kiwix-tools/blob/master/src/server/kiwix-serve.cpp#L250-L251

- I'm not sure of how the download button is added but it should be if the book has a url address. We have one if we download the book using kiwix-desktop (this is the url we used to download the book), but we don't have one for local zim file.

**Comment by kelson42** [comment]
>     * I'm not sure of how the download button is added but it should be if the book has a url address. We have one if we download the book using kiwix-desktop (this is the url we used to download the book), but we don't have one for local zim file.

Not sur if we could just remove the url once this is fully downloaded? This shoudl fix the problem.

**Comment by kelson42** [comment]
@MananJethwani We should take problems/bugs separatly to avoid confusion. The priority is to make content readable, ie. the "human friendly" problem. @mgautierfr Is that the same bug like https://github.com/kiwix/libkiwix/issues/456 ?

**Comment by mgautierfr** [comment]
Yes. The first point is the same than kiwix/libkiwix#456 (but it should be fixed in kiwix-desktop)

**Comment by kelson42** [comment]
@mgautierfr I have transered the ticket to kiwix/kiwix-desktop at #676.
@MananJethwani To fix this ticket we need to fix #676 first. Does the previous comment https://github.com/kiwix/kiwix-desktop/issues/671#issuecomment-892766057 from @mgautierfr is enough for you to know what to do?

**Comment by MananJethwani** [comment]
@kelson42 I will try to solve it on my own....if I get stuck will contact mgautier.

**Comment by kelson42** [comment]
@MananJethwani Now that is seems you have fixed #676, do you know why the icon is not displayed properly?
