### ISSUE TITLE
Library should be rewritten in Qt

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#683]
The library is the view which allows to handle books, locally (when books are already downloaded) or remotely (from the online catalog) to download them. Here is how it looks like.

Local library (with filters):
![image](https://user-images.githubusercontent.com/1029718/160275963-65083d9c-376f-433d-bdb5-5029e23d30b6.png)

Online library (with filters):
![image](https://user-images.githubusercontent.com/1029718/160275996-ffe9a2ac-c6d0-4c32-8e9f-a4fa81dc4152.png)

Although the whole Kiwix-Desktop software is written in C++, this part is a HTML rendering widget and the details are handled in HTML/JS/CSS with the framework vue.js. The problem with vue.js is that it needs a special effort to keep the visual coherence with the rest of the app in Qt. Actually there is no "real" reason why this part should not be in Qt. We should rewrite it in Qt.

Implementing this ticket is the first part of a larger effort to improve the usability of the library of Kiwix-Desktop which is currently really not good enough. See the project for a broader understanding https://github.com/kiwix/kiwix-desktop/projects/8.

The work to do is to provide something similar (maybe a few things can be changed at that time as well, but this is not the primary goall). The primary goal is to get rid of js/css/html. So, same sidebar and similar filters and on the righ pane the list of books with same features. All the core code is already in C++ in Kiwix-Desktop or Libkiwix, so this is to 90% only a UI work.

Here are the resources to have a look to:
* [resources/texts/_contentManager.html](https://github.com/kiwix/kiwix-desktop/blob/master/resources/texts/_contentManager.html)
* [https://github.com/kiwix/kiwix-desktop/blob/master/resources/js/_contentManager.js](https://github.com/kiwix/kiwix-desktop/blob/master/resources/js/_contentManager.js)
* [https://github.com/kiwix/kiwix-desktop/blob/master/resources/css/_contentManager.css](https://github.com/kiwix/kiwix-desktop/blob/master/resources/css/_contentManager.css)

**Comment by mgautierfr** [comment]
I wonder if QML/QtQuick could be a solution here.
I know a very little about QML (mainly the main principles/behaviors) so it is maybe a wrong idea.
It would be nice to have a pro/cons comparison. (And the main question is : is it possible to have QML "widget" inside a Qt "cpp" widget)

Else, `QTable*` is probably a good idea if we stick to "cpp" widgets.
