### ISSUE TITLE
sort offers longer matches first, extremely difficult to find short named entries

### ISSUE THREAD

**Issue by alex-ie** [kiwix/kiwix-desktop#685]
I have not found such issue in kiwix issues via google. E.g search for "revel" in wiktionary offers dozen matches, all longer. If I select "Revell", then from that "revell", then from that "revel" I find out what I'm looking for and that "revel" entry is indeed in the dictionary. Longer words can be further searched for by typing additional letters, but how to find short one???  
Linux, Kiwix desktop 2.0.5 (both standalone and flatpack).

**Comment by kelson42** [comment]
I would either put a space after "revel" or clickong on the item to make a fullteyt search. @MananJethwani You confirm?

**Comment by maneeshpm** [comment]
Yes @kelson42 that should work. Even though exact match should have the highest priority in the current version. I'll just check if something's wrong.

**Comment by maneeshpm** [comment]
@kelson42 I tested wiktionary on the latest libzim/libkiwix. The feature is working as expected! :smiley:  We can close this issue.

@alex-ie This has already been fixed and should be available to you in an upcoming update. I am attaching a screenshot below to share the anticipated behavior. Please let us know if there is an issue.

![Screenshot from 2021-09-04 09-26-46](https://user-images.githubusercontent.com/45821104/132081682-171ec9fd-eb12-45d2-933b-aa4488e000f3.png)

**Comment by alex-ie** [comment]
> I would either put a space after "revel" or clickong on the item to make a fullteyt search. @maneeshpm You confirm?
Neither space not tab not Enter helps. Full search gives 1000+ matches of which on 1st page neither one is "revel". I'm going to look at next version then.

**Comment by alex-ie** [comment]
> @kelson42 I tested wiktionary on the latest libzim/libkiwix. The feature is working as expected! smiley We can close this issue.
> 
> @alex-ie This has already been fixed and should be available to you in an upcoming update. I am attaching a screenshot below to share the anticipated behavior. Please let us know if there is an issue.
> 
> ![Screenshot from 2021-09-04 09-26-46](https://user-images.githubusercontent.com/45821104/132081682-171ec9fd-eb12-45d2-933b-aa4488e000f3.png)

You mention "libzim/libkiwix" I don't know exactly what its role in desktop app. What I know is that interface of standalone and flatpack are different for same 2.0.5 : It looks strange to me that "open link in new tab" is present in flatpack one but not in standalone. It is surely another issue, but pertaining to this one I just wanted to know if new search behavior would apply to all versions?

**Comment by maneeshpm** [comment]
> @maneeshpm You mention "libzim/libkiwix" I don't know exactly what its role in desktop app. What I know is that interface of standalone and flatpack are different for same 2.0.5 : It looks strange to me that "open link in new tab" is present in flatpack one but not in standalone. It is surely another issue, but pertaining to this one I just wanted to know if new search behavior would apply to all versions / builds?

@alex-ie libzim and libkiwix are essentially the backends on which most of the kiwix projects are based. So updating the search backend in libzim will enhance search functionalities on all subprojects including kiwix-desktop. So to answer your first question, yes the new search behavior will apply to kiwix-desktop as well with the update. As far as the specific build is concerned, I will let @kelson42 take that question.

> P.S. it is also seems strange nobody complained before. In wikipedia simple terms are hard to open, like /A/Light - if somebody want just to learn physics, it is difficult to find it. In full text "Light (disambiguation)" is somewhere on 10th place.

Be assured that the behavior with "Light" search has also been fixed. Next update shall bring a lot of improvements to search/suggestions.

> BTW, another search issue - "next page nav button" on full text opens same 1st page (flatpack at least) - should I open separate one?

Yes please! :)

**Comment by kelson42** [comment]
@alex-ie New versions of libkiwix/libzim should be release in the next weeks. Same for Kiwix Desktop. The improvements will apply from this release and the next ones. Please open new tickets if you see other iddities or bugs.
