### ISSUE TITLE
Different interface of flatpack and standalone appimage (Linux).

### ISSUE THREAD

**Issue by alex-ie** [kiwix/kiwix-desktop#687]
I have both appimage and Kiwix installed from flatpack, both say version 2.0.5 in "About". But flatpack one have "Open link in new tab" in right-click menu, but appimage has not. "Instead" appimage has "Follow link" which does about same as just left-clicking. Why are they different? Could appimage be made as flatpack now - IMHO obviously more useful?

**Comment by kelson42** [comment]
@alex-ie Would you be able please to uninstall them and install the nightlies, both flatpak and appimage, and see if this oddity still happens? http://download.kiwix.org/nightly/

**Comment by alex-ie** [comment]
@kelson42, I downloaded http://download.kiwix.org/nightly/2021-09-06/kiwix-desktop_x86_64_2021-09-06.appimage and the right-click menu looks same as flatpack one I installed previously -  so that appimage looks good to me, no issues noted. 

I have a side question, kind of related:
1) When I started new appimage it opened same books as previous one, where the app stores its data? (help menu is the app contains only "about", is there a place such questions are already answered maybe?) Thanks!

**Comment by kelson42** [comment]
Not sure if flatpak uninstall automatically the older version, I would do it manually to secure this. But the nightly version even is a dev version with many more thing that the official 2.0.5, you can see the milestone https://github.com/kiwix/kiwix-desktop/milestone/3?closed=1.

More info about where is your profile here: https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)#principle. It is not properly documented, you are right. Asking here is OK.
