### ISSUE TITLE
Search is not finding matches in collapsed views (Linux)

### ISSUE THREAD

**Issue by alex-ie** [kiwix/kiwix-desktop#688]
Page opens in background (by middle clicking on link) in collapsed view. In might be personal preference with mine it better be expanded by default, but search is not working in collapsed sections, which IMHO makes collapsed view much less useful than expanded. Could background be opened in expanded view by default (or better give user a choice somewhere in options or right-click menu) - [might be idea for different issue]? Could search feature be easily amended to include collapsed sections?

**Comment by kelson42** [comment]
@alex-ie I guess you mean "find in page"? Sounds normal to me. AFAIK this is how it works on a browser.

**Comment by alex-ie** [comment]
@kelson42, yes, I've checked and you are right - e.g. Firefox is not searching in collapsed sections. I will make another one asking specifically to open background in expanded view cause I think it is more convenient and I don't mind closing this one.
