### ISSUE TITLE
Unhandled `kiwix::AriaError` exception if KIWIX_DATA_DIR is set to a unexisting directory.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#694]
`KIWIX_DATA_DIR` env variable can be used to force a specific directory to put all configuration/zim somewhere (instead of the default user data dir).
At exist, we tell aria2 to save the session in the data directory and if it not exists, a exception is raised.

We must catch it and handle it correctly.

**Comment by kelson42** [comment]
Shares similarities with #566

**Comment by kelson42** [comment]
@mgautierfr I don’t understand why we need this env. variable and I don’t like the idea that the software does not follow what is in the configuration. Why we need it?

I don’t understand either the steps to reproduce the bug not how it should behave.

**Comment by DivyaPamecha** [comment]
Hi, is this issue up for grabs? I am new to Open Source but would love to learn more.

**Comment by kelson42** [comment]
@DivyaPamecha yes, if you know how to fix it.

**Comment by kelson42** [comment]
To reproduce the problem this is quite easy on Linux:
```
$ KIWIX_DATA_DIR=/tmp/foobar ./kiwix-desktop
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Segmentation fault (core dumped)
``

**Comment by kelson42** [comment]
Here there is an other bug: `KIWIX_DATA_DIR` seems somehow not used. If I set it, the ZIM is still downloaded in the one specificed in the Settings of Kiwix!

**Comment by veloman-yunkan** [comment]
> Here there is an other bug: `KIWIX_DATA_DIR` seems somehow not used. If I set it, the ZIM is still downloaded in the one specificed in the Settings of Kiwix!

That's normal. Settings are stored in a location determined by Qt and unrelated to `KIWIX_DATA_DIR` (under Ubuntu it's `~/.config/Kiwix/Kiwix-desktop.conf`). Each download is started with a target directory corresponding to the active value of the download directory setting. `KIWIX_DATA_DIR` affects the location of the following files:

- `kiwix-desktop.session`: application session information (as of now consisting only of the list of open tabs)
- `kiwix.session`: aria2 pending/incomplete download state/information
- `library.xml`
- `library.bookmarks.xml`
