### ISSUE TITLE
Flatpak version of Kiwix Desktop do not find my local files (settings).

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#70]
My local library of content is empty. But if I close it and start the appimage version, then everything is there.

Additional finding: it seems I can download a content.. but nothing will appear in the local library at the end of the downloading process.

**Comment by mgautierfr** [comment]
> My local library of content is empty. But if I close it and start the appimage version, then everything is there.

We are following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). It defines a set of env variables to read to know where to search for configuration or store data. We are especially using the env variable `XDG_DATA_HOME` to know where to store the library and its content.

The default is `~/.local/share`, but flatpak redefines this value to `~/.var/app/<app-id>/data`(see http://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories). (It's not a bug, it a feature of flatpak sandboxing)

I understand the need to switch from a packaging to another one, but I don't know how to fix easily this.
I will not change the code to explicitly not follow the system configuration. Maybe some documentation ?
BTW, it is already possible to override the configuration by setting the env variable `KIWIX_DATA_DIR`

---

> Additional finding: it seems I can download a content.. but nothing will appear in the local library at the end of the downloading process.

It is probably a different issue, please open a new issue.

**Comment by kelson42** [comment]
@mgautierfr Thank you for the answers. I think we can live with this problem first. Let us do the best to promote the Flatpak/Flathub version first, we could later find a workaround to deal with an other profile directory. In general I also miss a way to know where the profile is, IMO this information should be somehow available in a "settings" dialogbox (or similar)..

For the second problem I have open a ticket here #72
