### ISSUE TITLE
Update install instructions for Ubuntu 21.04 

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#701]
Ubuntu 21.04 doesn't have the `qt5-default` package. 
Better to write its individual dependencies. 

```
sudo apt-get install libqt5gui5 qtbase5-dev qtwebengine5-dev \
     libqt5svg5-dev qt5-image-formats-plugins aria2 \
     qttools5-dev-tools qtchooser qt5-qmake qtbase5-dev-tools
```

**Comment by kelson42** [comment]
Yes, foloowing command should do the job: sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
