### ISSUE TITLE
`ctrl`+`+` & `ctrl`+`=` - please make both for `zoom in` to get rid of `Shift`

### ISSUE THREAD

**Issue by alex-ie** [kiwix/kiwix-desktop#703]
Some apps use `ctrl`+`+` and some `ctrl`+`=` to zoom in. Only some allow to customize. If all used same, I would just remap the keyboard not to use `Shift`. Please make Kiwix user friendly to respond to both. (I guess it is easy as apposed to making GUI for hot keys customization).

P.S. I can try it as my `good first issue`.

**Comment by kelson42** [comment]
Actually both work on FF.
