### ISSUE TITLE
Monitor ZIM files from a user-chosen directory

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#713]
Some people like to put all of their files at a different directory (usually case with windows users).
If I'm not mistaken, the current way right now is to open each zim file so it adds that in the local library.

A good way could be to :
Add an option in Settings to import all zim files from a directory (user chooses dialog box) [check the load local zim files option]
![Settings (1)](https://user-images.githubusercontent.com/26814569/139694547-20562f5c-b3a2-46f7-adb0-7c499b0309b5.png)

In a way, this can also simplify https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version) 

This is a follow-up of https://github.com/kiwix/kiwix-desktop/issues/644#issuecomment-955949075

**Comment by kelson42** [comment]
For the moment I think this is actually a good idea and would allow (like written in the description) to solve #461 as well. For that we should have the following workflow:
* Per default the "local directory"(we need probably to rething a bit the naming/wording) would be the one of the binary.
* I someone changes it, then it looks to another place
* There is a button reset/browse like for the download directory.

**Comment by kelson42** [comment]
Regarding the naming, one idea would be "Monitor Directory". We could add a hint on it to help users to understand what this is about.

**Comment by kelson42** [comment]
@juuz0 With @mgautierfr we agree to do so. I propose to call is « Monitored Directory ». Per default it should be not defined. Probably a toolotip or a snall question mark badge should be happen proposing a simgle sentence explanation of what it is. We shoukd wait that libkiwix proposed all the primitives to live update the library before first working on it.

**Comment by juuz0** [comment]
Noted :+1:

**Comment by kelson42** [comment]
@juuz0 https://github.com/kiwix/libkiwix/pull/636 has been merged, so libkiwix should provide the necessary to implement this feature properly, ie.:
* dedicated settings entry
* Check periodically the directory for new files (non recursively, only first level)
* Add new files to library and ask refresh (to remove automatically the ZIM files which have been removed)

**Comment by juuz0** [comment]
@kelson42 Thanks :+1: Will do it

**Comment by juuz0** [comment]
@kelson42 
How do the changes in https://github.com/kiwix/libkiwix/pull/636 work? 
The library isnt reloading for me in kiwix-serve :/
Steps I followed:
* Downloaded a small zim file from the wiki
* Put it in download directory
* Start kiwix-serve

The book wasnt visible

**Comment by kelson42** [comment]
@juuz0 It should work that way:
* configure directory to monitor in kiwix-desktop
* monitor directory changes in kiwix-desktop (add/remove/update of zim files)
* if change detected, update library with libkiwix (not sure exactly how to do, but look how it is done with kiwix-serve news library monitoring option).

Have you done the first 2 bullets laready?

**Comment by juuz0** [comment]
@kelson42 Yes, I've done the first two.
Only a trivial amount is remaining - to reload the library.
That should be easy since it's already done in libkiwix and kiwix serve (which somehow isn't working for me - library doesn't reload, I'll check again)
