### ISSUE TITLE
Few things to fix/discuss around zoom

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#718]
In general the zoom works like this:
* There is a default zoom level at 100%
* This default zoom level can be changed in the settings
* This default zoom level applies to any ZIM, ZIM article if not defined differently.
* Each ZIM file can have its own level of zoom which is saved in the settings (but not available via UI)
* This ZIM dedicated ZOOM settings can be changed (and automatically saved in the settings) with the wheel, button, meny entry or shortcuts

To me all of this works properly and as it should. I see only a few things to improve/fix:
* The settings entry should be labeld "Default zoom level" instead of just "Zoom level"
* The settings should apply immediatly to all tabs (which don't have already a manually set zoom level).
* <s>Zoom reset seems not to bring to default zoom level, it seems to bring to 100%</s> works!

**Comment by kelson42** [comment]
@juuz0 Remember you talking about zoom level (as you were working on the settings panel)... to me it seems to work pretty well.

**Comment by juuz0** [comment]
@kelson42 Oh yea, I forgot to update. That was working correct for me too later. 

> Zoom reset seems not to bring to default zoom level, it seems to bring to 100%

Weird, this works as expected for me.

**Comment by kelson42** [comment]
@juuz0 I have restested, and indeed it seems to work.

**Comment by juuz0** [comment]
Also, is it better to remove this line (bothers me for some reason lol) and making the arrows black
![image](https://user-images.githubusercontent.com/26814569/141302282-9d15e37b-8322-4bee-bd57-8766a7f2f126.png)

**Comment by juuz0** [comment]
@kelson42 How do you generate translations for all these languages?

**Comment by kelson42** [comment]
@juuz0 strings in english are uploaded to translatewiki.net and once a week translatewiki.net makes a PR with the translated strings.
