### ISSUE TITLE
Open multiple ZIM files from command line is broken

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#720]
If I launch `./kiwix-desktop Australia.zim`

I get this:
![image](https://user-images.githubusercontent.com/1029718/141446919-6a0991f1-c527-4724-92ed-59653b893f73.png)

We should see the welcome page of the ZIM file and the ZIM file should be added to the local library.

This seems to be a regression, quite sure it was working before.

**Comment by juuz0** [comment]
Works well for me

**Comment by kelson42** [comment]
@juuz0 You are right, the problem is the ZIM file itself. But I have discovered an other bug... if I launch:
```
$ ./kiwix-desktop wikipedia_fr_all_mini_2021-10.zim wikipedia_es_history_maxi_2021-10.zim 
```
Only the first one is open. I guess the two of them should be open right?

**Comment by juuz0** [comment]
@kelson42 Yep! Can confirm that bug and yeah both should be open.

**Comment by kelson42** [comment]
It seems we should loop instead of taking only one argument in `main.cpp`. Should be easy.

**Comment by kelson42** [comment]
@juuz0 Would you be able to fix that one in the meantime we wait your other PR can move forward?

**Comment by juuz0** [comment]
@kelson42 Yes, sure. On it
