### ISSUE TITLE
Kiwix from ubuntu ppa crashes when browsing zim

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#734]
Kiwix is crashing again when I browse a zim, when opening I have this error:
```
Impossible de lancer le système de téléchargement, Kiwix-desktop fonctionnera mais sans les fonctionnalités de téléchargement !

Cannot connect to aria2c rpc. Aria2c launch cmd : /usr/bin/aria2c --enable-rpc --rpc-secret=kiwixariarpc --rpc-listen-port=42042 --dir=/home/damien/.local/share/kiwix --input-file=/home/damien/.local/share/kiwix/kiwix.session --save-session=/home/damien/.local/share/kiwix/kiwix.session --auto-save-interval=10 --stop-with-process=2385 --allow-overwrite=true --dht-entry-point=router.bittorrent.com:6881 --dht-entry-point6=router.bittorrent.com:6881 --quiet=true --bt-enable-lpd=true --always-resume=true --max-concurrent-downloads=42 --rpc-max-request-size=6M --file-allocation=none 
```
And when it crashes:
```
damien@R519-R719:~$ kiwix-desktop 
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
ERROR: aria2 RPC request failed. (7).
Failed to connect to localhost port 42042: Connexion refusée
add widget
js: jQuery.Deferred exception: $sortable.tablesorter is not a function
js: Uncaught TypeError: $.debounce is not a function
js: jQuery.Deferred exception: $sortable.tablesorter is not a function
nouveau: kernel rejected pushbuf: Aucun fichier ou dossier de ce type
nouveau: ch4: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch4: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch4: buf 00000001 00000006 00000004 00000000 00000004
Erreur de segmentation
```
And this on the second test without internet connection:
```
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
js: Uncaught SyntaxError: Unexpected identifier
js: Uncaught ReferenceError: articleId is not defined
js: jQuery.Deferred exception: $sortable.tablesorter is not a function
double free or corruption (fasttop)
Abandon
```

Thank you for help

**Comment by LAfricain** [comment]
> What happens if you run the aria2c command separatly?

Can give me a command to run manually please.

**Comment by kelson42** [comment]
@LAfricain The one given in the log: `/usr/bin/aria2c --enable-rpc --rpc-secret=kiwixariarpc --rpc-listen-port=42042 --dir=/home/damien/.local/share/kiwix --input-file=/home/damien/.local/share/kiwix/kiwix.session --save-session=/home/damien/.local/share/kiwix/kiwix.session --auto-save-interval=10 --stop-with-process=2385 --allow-overwrite=true --dht-entry-point=router.bittorrent.com:6881 --dht-entry-point6=router.bittorrent.com:6881 --quiet=true --bt-enable-lpd=true --always-resume=true --max-concurrent-downloads=42 --rpc-max-request-size=6M --file-allocation=none`. Considering the PPA, do you use the stable or the dev PPA?

**Comment by LAfricain** [comment]
```
/usr/bin/aria2c --enable-rpc --rpc-secret=kiwixariarpc --rpc-listen-port=42042 --dir=/home/damien/.local/share/kiwix --input-file=/home/damien/.local/share/kiwix/kiwix.session --save-session=/home/damien/.local/share/kiwix/kiwix.session --auto-save-interval=10 --stop-with-process=2385 --allow-overwrite=true --dht-entry-point=router.bittorrent.com:6881 --dht-entry-point6=router.bittorrent.com:6881 --quiet=true --bt-enable-lpd=true --always-resume=true --max-concurrent-downloads=42 --rpc-max-request-size=6M --file-allocation=none
damien@R519-R719:~$
```
No error reported.

**Comment by kelson42** [comment]
@LAfricain But do you have to stop it, or does it stops on its own?

**Comment by LAfricain** [comment]
>@LAfricain But do you have to stop it, or does it stops on its own?

No I entered the command in the terminal, and it worked by itself.

**Comment by kelson42** [comment]
@LAfricain The problem is that kiwix is not able to connect to aria2c daemon. So either aria2c does not run or there is something which make kiwix impossible to connect to aria2c. Not clear what happen here as I can not reproduce the problem. Donyou have the problem as well on a fresh ubuntu 20.04 in a vm?

**Comment by LAfricain** [comment]
I have to check the disk...

**Comment by kelson42** [comment]
@LAfricain Any news on this, maybe with the latest dev version?

**Comment by kelson42** [comment]
@LAfricain Do you still have this problem with latest version on dev PPA https://launchpad.net/~kiwixteam/+archive/ubuntu/dev ?

**Comment by LAfricain** [comment]
Hello,
I live the place. Maybe in march I can test again.

**Comment by kelson42** [comment]
I will close this issue because probably either it has been fixed already or there is something special in that env.... but we have no way for the moment to investigate further. If the problem is still there with 2.1.0+, then it should be reopen.

**Comment by LAfricain** [comment]
I did new tests. First I thought the problem may be with Mate desktop, then I used Unity. It crashes again. But now I have an idea, maybe it is related to the graphic card nvidia and the nouveau driver?
Look the error report:
```
(kiwix-desktop:8064): Gtk-WARNING **: 13:49:37.097: Theme parsing error: gtk.css:6083:16: Junk at end of value for color
add widget
kiwix-desktop: ../nouveau/pushbuf.c :723 : nouveau_pushbuf_data:  l'assertion « kref » a échoué.
Abandon (core dumped)
```
You can see the "nouveau" reference. And the problem is only with this Nvidia graphic card. Maybe I can try something with this?

**Comment by kelson42** [comment]
Which PPA? release or dev?

**Comment by LAfricain** [comment]
PPA ubuntu 20.04 but I think I have to change the title. Because the problem is probably not with the ppa, but as I said with the nouveau nvidia driver.

**Comment by kelson42** [comment]
@LAfricain What is the URL of the PPA you use, we have many, see https://wiki.kiwix.org/wiki/Ubuntu_PPA
