### ISSUE TITLE
[REGRESSION] Latest dev Kiwix-Desktop freezes by download

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#737]
If I click and download a content, my Kiwix-desktop freezes.

It is clearly a regression, but I can not say since when.

**Comment by juuz0** [comment]
Probably due to the new libkiwix x kiwix desktop changes 
Works fine till kiwix desktop (ad1e52ee833878a36a490828df14a69c1d3021a5) and an older version of libkiwix (c7b88398bd1a8daa6c06214ea7d71ce6a985ad41)

**Comment by kelson42** [comment]
@juuz0 Thank you for the clarification of the problem
@mgautierfr @veloman-yunkan Any feedback on our side.

**Comment by veloman-yunkan** [comment]
I will investigate it.

**Comment by veloman-yunkan** [comment]
This is caused by kiwix/libkiwix#641

**Comment by kelson42** [comment]
Works for me now with https://github.com/kiwix/libkiwix/pull/642, thx @veloman-yunkan. @juuz0 Please reopen ticket if the problem still occurs on your side.
