### ISSUE TITLE
Latest dev Kiwix-desktop doesn't close 

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#738]
Latest master
Environment: Ubuntu 21.10 Gnome

Steps to reproduce:
Start kiwix-desktop
Close using "X" button
Start again and it shouldnt start

`pgrep kiwix-desktop` returns the PID. Have to use `pkill` for restarting.

PS - Works ok till https://github.com/kiwix/kiwix-desktop/commit/ad1e52ee833878a36a490828df14a69c1d3021a5

**Comment by kelson42** [comment]
I confirm, I have the same behaviour. Kind of hope this isn5e same regression like #737.

**Comment by veloman-yunkan** [comment]
This is caused by kiwix/libkiwix#641
