### ISSUE TITLE
 Broken images in latest en zim

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#74]
In the latest enwiki zim file, wikipedia_en_all_novid_2018-10, images are broken in some articles. It is true for several large articles. Se attached image.

![united states](https://user-images.githubusercontent.com/45800554/49825499-e12af780-fd84-11e8-9243-338c98edfa51.png)

**Comment by mossroy** [comment]
I confirm this issue

**Comment by kelson42** [comment]
It is a problem in the ZIM file, moving the ticket to mwoffliner.

**Comment by kelson42** [comment]
This issue was moved to openzim/mwoffliner#462
