### ISSUE TITLE
Zooming in and out doesnt affect Settings Page

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#741]
Different to how its done in Firefox

**Comment by kelson42** [comment]
@juuz0 Seems normal to me. You can not increase font size that way in rich apps.

**Comment by juuz0** [comment]
I was taking Firefox as a reference in behaviour
But now that you mention "font size",  I realised we are changing the zoom of the ZIM only and not the full UI so yes fine :)
