### ISSUE TITLE
Export article in pdf

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#749]
It should be possible to export an article in pdf format without having to you pront to pdf sysmtem feature.

**Comment by AniruddhaGawali** [comment]
hi i would like to contribute in this,
can you tell me from where should i start

**Comment by kelson42** [comment]
@AniruddhaGawali You should know how to fix the ticket first!

**Comment by AniruddhaGawali** [comment]
which type of ticket

**Comment by kelson42** [comment]
Print to PDF does work (since a long time actually). Should be good enough IMO.
