### ISSUE TITLE
Titles should be left aligned

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#75]
Today article titles are centered, even when they are too long. It would look much better if they were left aligned I think. See attached image.

"History of the United S" is better then
"story of the United Stat" imho.

![history of the united states](https://user-images.githubusercontent.com/45800554/49825572-0fa8d280-fd85-11e8-984d-9244468c87d4.png)

**Comment by kelson42** [comment]
Yes, I confirm. A fadeout effect on the right (or at least an ellipsis) should be added if the title is too long. This should be the other way around if UI language is RTL.

**Comment by softgengaurav** [comment]
@jargony can i try this issue?

**Comment by kelson42** [comment]
@softgengaurav Thank you for proposing yourself. This bug has been fixed quickly. But you have a few other "good first issue" here https://github.com/kiwix/kiwix-desktop/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
