### ISSUE TITLE
Shortcut to zoom in (Ctrl + +) not working on Kiwix desktop

### ISSUE THREAD

**Issue by try-catch-stack** [kiwix/kiwix-desktop#752]
I have tested on kiwix desktop 2.0.5 for windows x64 and the zoom in shortcut does not seem to work. The zoom out shortcut does work properly though.

**Comment by kelson42** [comment]
@try-catch-stack I believe this is fixed in dev version. Give a try to https://download.kiwix.org/nightly/2021-12-20/

**Comment by try-catch-stack** [comment]
> @try-catch-stack I believe this is fixed in dev version. Give a try to https://download.kiwix.org/nightly/2021-12-20/

Yes it works fine in this version.
I have a suggestion for the same. Don't you think it would be nice to have a visual alert or something to show current zoom level when we zoom in or out, similar to the way browsers does it.

![image](https://user-images.githubusercontent.com/77742477/146924400-ebf2bc38-feff-4087-b406-2a8146da97d7.png)

**Comment by kelson42** [comment]
@try-catch-stack I have nothing like this on Firefox. But it seems ot be a Chrome browser screenshot. I have no strong opinion on this. 

@juuz0 @Popolechien @asashnov Any opinion?

**Comment by Popolechien** [comment]
No strong opinion. Nice to have, but at the end of the day I'm comfortable because I see things correctly, not because it says 80, 100, or 110%

**Comment by try-catch-stack** [comment]
If not an alert , we can have a single option to zoom with two buttons (+ and -) to zoom in and out rather the way it currently is as it makes really inconvenient to those who would use mouse to zoom in and out.Also the menu closes on clicking either of those buttons and we have to open it again to zoom further.

Adding this image for reference 
![image](https://user-images.githubusercontent.com/77742477/146929906-f27b77cf-66ea-40c9-9c85-7d2890452862.png)

**Comment by juuz0** [comment]
Similar to Popo, I increase/decrease and wouldn't bother what percentage it is if it looks good to my eyes.

Also, Firefox does have an indicator - in the address bar. Check by pressing CTRL + +

**Comment by kelson42** [comment]
Thx for your feedbacks, will take a few days to make a decision how we should go forward.

**Comment by juuz0** [comment]
> If not an alert , we can have a single option to zoom with two buttons (+ and -) to zoom in and out.....

@try-catch-stack I believe they already are in settings (in reference to latest builds)? You can also zoom in/out using the mouse wheel by Ctrl + wheel-forward/backward

**Comment by kelson42** [comment]
After thinking twice about it, I'm not convinced by the added value of the proposal. Will close it.
