### ISSUE TITLE
Allow keyboard shortcut configuration

### ISSUE THREAD

**Issue by adigitoleo** [kiwix/kiwix-desktop#753]
I wonder if you would consider allowing for configuration of at least some of the keyboard shortcuts. I come from the land of vim, I even use vim-style shortcuts in the browser. I would like to put some of that muscle memory to use.

Cheers

**Comment by kelson42** [comment]
@adigitoleo Do I get that right, you are not happy with standart browser shortcuts?

**Comment by adigitoleo** [comment]
Essentially, yes, I use a browser that has "non-standard" shortcuts ([qutebrowser](https://qutebrowser.org/)).

In particular, I would mostly like to change shortcuts for the following actions:
- search-in-page (Ctrl-f)
- go to top of page (Home)
- go to bottom of page (End)
- scroll up/down (upwards/downwards arrows)
- navigate to next/prev page (I don't think there are currently shortcuts for this? browsers sometimes use Alt-<right>/<left>)

I could live with the rest of them as they are, but configuration for all of them might be more consistent.

**Comment by adigitoleo** [comment]
On second thought, I've discovered that I can always use kiwix-serve to read the zim files in my browser, which removes the need for me to maintain a separate shortcuts configuration. For now this is likely the solution that I will use. I still think there should be a few more navigation shortcuts in the client, as mentioned, but that might deserve its own issue.
