### ISSUE TITLE
Zim without language metadata is not displayed in the local library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#754]
From https://github.com/kiwix/libkiwix/issues/657#issuecomment-1001387566
> Would like to mention here that Kiwix-desktop doesn't show a zim in the libary if language metadata is missing

**Comment by kelson42** [comment]
@juuz0 Wiukd be good to confirm with a clear step by step reproduction case.

**Comment by juuz0** [comment]
@kelson42 
1. Open `libray.xml`, remove the `language="lang_code_here"` of any book.
2. Start kiwix desktop
3. It won't show up.

**Comment by kelson42** [comment]
@juuz0 OK, but do you have a real case where this will happen? I guess with language="" it works?

**Comment by juuz0** [comment]
@kelson42 Doesn't work with language="" also
Real case scenario probably the zim reported in https://github.com/kiwix/libkiwix/issues/624
I don't have it so cant check

**Comment by kelson42** [comment]
The file is http://download.kiwix.org/zim/wikipedia/wikipedia_en_wp1-0.7_2009-05.zim, we should check.

**Comment by juuz0** [comment]
:+1: Downloading

**Comment by kelson42** [comment]
@juuz0 I confirm that I can open the ZIM file but it is not added to the local library.

**Comment by kelson42** [comment]
@juuz0 You are right, it see it now that I don't have put the filter. So everything works as expected right?

**Comment by juuz0** [comment]
@kelson42 Yes looks like it 👍
