### ISSUE TITLE
Opening Nautilus zim files should be done in-app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#756]
I was browsing https://mirror.download.kiwix.org/zim/other/zimgit-post-disaster_en_2021-12.zim when I realized that Kiwix-desktop does not open files (even somewhat mundane PDFs) but always offers them for local download, which forces a couple of extra steps (and a duplicate download) before one can actually browse the zim's content:
![Untitled presentation](https://user-images.githubusercontent.com/21675885/147653536-fc2076af-f669-487d-be78-7d2b8c9c5726.png)

Other versions of Kiwix (serve, macOS, etc.) simply open the file and this looks like what normal behaviour should be.

**Comment by juuz0** [comment]
Same as this https://github.com/kiwix/kiwix-desktop/issues/697?

**Comment by Popolechien** [comment]
@juuz0 Correct! Closing this as duplicate then.
