### ISSUE TITLE
Error by opening a file is not handled properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#758]
Steps:
* Have a file in the local library
* Delete or rename that file in the filesystem
* Click "open" on that file in the local library

I get:
* A crash with:
```
$ ./kiwix-desktop
Compiled with Qt Version  5.12.8
Runtime Qt Version  5.12.8
add widget
terminate called after throwing an instance of 'std::runtime_error'
  what():  error 2 opening file "/home/kelson/Downloads/5.zim
Aborted (core dumped)
```

I would like:
* A proper error dialog with an error... and probably the entry should be deleted from the local library.

**Comment by kelson42** [comment]
@juuz0 Would you be able please to have a look to that nasty bug? To me, it looks like the exception generated in the libzim/libkiwix is just not handled in kiwix-desktop.

**Comment by juuz0** [comment]
@kelson42 
On it 👍

**Comment by kelson42** [comment]
@juuz0 Thank you very much!
