### ISSUE TITLE
Problem with special characters in search bar

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#76]
When you start a search with e.g. åäö it doesn't give any article suggestions.
If you start writing other letters and then there is a åäö in the middle of the title, it is emptied when you write the character.

"Öland" is possible to write, but with no results.
"Göteborg" cancels the search when typing the "ö".

I use kiwix-desktop_windows_x64_2.0-beta1

**Comment by kelson42** [comment]
@jargony With which file/content have you tried? What the result expected?

**Comment by jargony** [comment]
When I type "Ö" there is no suggestions at all, and not if I continue with "land". So the article "Öland" can't be reached using the search bar.

I first write the "G" and get lots of suggestions as usual. But when I then write "ö" the "G" is erased and the search bar is empty. So "Göteborg" can't be reached from the search bar either.

I use kiwix-desktop_windows_x64_2.0-beta1 and have tried with both
wikipedia_en_all_novid_2018-10.zim and wikipedia_en_all_novid_2018-06.zim

**Comment by kelson42** [comment]
This should have been fixed in 2.0 rc2.
