### ISSUE TITLE
Settings panel is broken

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#764]
![image](https://user-images.githubusercontent.com/26814569/149661461-cb6bf8d6-36a9-4576-a3f1-24b6288d28ed.png)

Looks like recent changes from https://github.com/kiwix/kiwix-desktop/commit/5d0f1bd096acd88fde4f752fa2031eb3e8ec37cf caused this

**Comment by kelson42** [comment]
@juuz0 Sorry to see that @asashnov PR has created this regression, but woukd you be able to fix it?

**Comment by juuz0** [comment]
@kelson42 Will look into it, haven't checked the changes done in that PR yet :+1:

**Comment by kelson42** [comment]
@juuz0 I can not confirm that bug with current `git master`.

**Comment by juuz0** [comment]
@kelson42 It's inconsistent but it's there
Will show up when there aren't any books/tabs open.
Open settings from menu.
If bug doesn't show up, close settings. Open with F12

It should come!

**Comment by asashnov** [comment]
@juuz0  good catch and fix
@kelson42 sorry for missing that case in my tests
