### ISSUE TITLE
Zooming function is functionally flawed

### ISSUE THREAD

**Issue by edo0** [kiwix/kiwix-desktop#770]
OS: elementary OS, Ubuntu 20.04-based
Kiwix-desktop version: 2.0.5, flatpak edition from flathub

My main issue is that, using the search function, the zoom level gets reset to 100% by Kiwix.
Therefore, even if I have set the default zoom at 130%, that will apply only to the homepage of the Wiki loaded on Kiwix, and the hyperlinks clicked from there. But it will *not* work for any page belonging to the same Wiki when accessed through the search function.

For all users who search wiki pages, rather than navigating them through hyperlinks only, this is a major obstacle to usage of the software.
Please refer to the video below for a demonstration of the behaviour

https://user-images.githubusercontent.com/16632292/150642804-668b4277-a4c7-47c6-915b-642a942a920a.mp4

**Comment by kelson42** [comment]
Many things around zoomin have been fixed in 2.1.0. Please give a try to http://download.kiwix.org/release/kiwix-desktop/org.kiwix.desktop.2.1.0.flatpak (will be later published to Flathub).

**Comment by edo0** [comment]
Thank you for the reply!
Unfortunately the version you have posted, 2.1.0, does not seem to address in any way usability issue I have reported. Please let me know if I have missed anything

**Comment by kelson42** [comment]
@edo0 We will try to reproduce the bug and have a look in detail why. Thx for your report.

**Comment by kelson42** [comment]
I confirm the bug! @juuz0 Do you have a clue why the zoom is reseted when a page is loaded from the fulltext search result page?
