### ISSUE TITLE
[REGRESSION] Searching for "All files" crashes application on Windows

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#775]
On Windows 10, running Kiwix-desktop 2.1.0 

Clicking on All files in the library causes the application to close unexpectedly.

**Comment by kelson42** [comment]
@Popolechien If you start from the command line, what is written on the console?

**Comment by Popolechien** [comment]
@kelson42 I can open Kiwix-desktop from the command line (and nothing much happens, Kiwix opens), but you'll have to tell me how to reach All files from there.

**Comment by kelson42** [comment]
Just start ir, run your crash scenario from the UI and dump the log here.

**Comment by juuz0** [comment]
Confirmed with App image. Same count = 0 problem
Was fixed in https://github.com/kiwix/kiwix-desktop/pull/769 but release didnt include that I think

**Comment by kelson42** [comment]
I can reproduce the bug

**Comment by kelson42** [comment]
I have run a small analysis based on Github and the nightly builds. Here are the findings:
* https://download.kiwix.org/nightly/2022-01-09/kiwix-desktop_windows_x64_2022-01-09.zip works fine
* After the 2022-01-09 and up to the 2022-01-20, there is no nightly Windows build. But the https://download.kiwix.org/nightly/2022-01-20/kiwix-desktop_windows_x64_2022-01-20.zip is there and suffers from the bug. As a conclusion the bug has been introduced between the 09 and 20 January 2022.

**Comment by kelson42** [comment]
@juuz0 @mgautierfr @mgautierfr @asashnov We will have to identify quickly what has been broken (for Windows) beetween the 9th and the 20th of January and make a new release. It can be in kiwix/kiwix-desktop (probably) but as well in libkiwix, libzim or even kiwix-build.

**Comment by juuz0** [comment]
```
Faulting application name: kiwix-desktop.exe, version: 0.0.0.0, time stamp: 0x61e97ad3
Faulting module name: kiwix-desktop.exe, version: 0.0.0.0, time stamp: 0x61e97ad3
Exception code: 0xc0000005
Fault offset: 0x000000000003fde0
Faulting process id: 0x1ed0
Faulting application start time: 0x01d813523009e9e2
Faulting application path: C:\Users\2002n\Downloads\kiwix-desktop_windows_x64_2022-01-20\kiwix-desktop_windows_x64_2022-01-20\kiwix-desktop.exe
Faulting module path: C:\Users\2002n\Downloads\kiwix-desktop_windows_x64_2022-01-20\kiwix-desktop_windows_x64_2022-01-20\kiwix-desktop.exe
Report Id: bf503dcc-5277-42ee-b5e2-f686bddfe7cf
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by juuz0** [comment]
More observation:
If you tap on filter under Content-Type category, app crashes

**Comment by kelson42** [comment]
@Popolechien @asashnov @juuz0 Might that be that #751 has fixed the problem?!?! I just have tried with latest nightly https://download.kiwix.org/nightly/2022-02-01/kiwix-desktop_windows_x64_2022-02-01.zip and it seems to work now !?! Please try on your side.

**Comment by juuz0** [comment]
Unfortunately, not working for me. Still crashing

**Comment by kelson42** [comment]
Wrong input on my side, I restested and it still fails. I think I have mixed-up 01-02-2022 with 02-01-2022.
