### ISSUE TITLE
The library is always empty on new launch

### ISSUE THREAD

**Issue by xvitaly** [kiwix/kiwix-desktop#776]
Version 2.1.0 doesn't save the list of previously opened zim files. The library is always empty on new launch.

Version 2.0.5 works fine.

**Comment by juuz0** [comment]
Which OS and if GNU/Linux how did you install 2.1.0 (Flathub/AppImage)?

**Comment by xvitaly** [comment]
> Which OS and if GNU/Linux

OS: Fedora Linux 35.

> how did you install 2.1.0 (Flathub/AppImage)?

Our native build: https://bodhi.fedoraproject.org/updates/FEDORA-2022-958c193c6a

>  By library always empty, do you mean "Local Files" don't show any anything?

![image](https://user-images.githubusercontent.com/966711/151585478-773aa49e-b955-41af-bef1-73c23bfdd1bf.png)

**Comment by kelson42** [comment]
@xvitaly So everythin works fine, ie. Files are added to the local library if you download then or load them manually... as long as you don't restart Kiwix. Then the local library is again empty?

**Comment by xvitaly** [comment]
> So everythin works fine, ie. Files are added to the local library if you download then or load them manually... as long as you don't restart Kiwix. Then the local library is again empty?

Press Open file -> select zim -> it will be loaded -> switch back to the Library tab and it is still empty.

**Comment by xvitaly** [comment]
@kelson42 When I select **Browse by language** -> **any** language and then switch back to the **Local Files**, it finally find them.

**Comment by kelson42** [comment]
@xvitaly The problem is that you don't filter properly by language? Can we have otherwise a full step by step procedure with what you expect and what you get?

**Comment by xvitaly** [comment]
> The problem is that you don't filter properly by language?

It should list all downloaded zim files on startup.

> Can we have otherwise a full step by step procedure with what you expect and what you get?

Actual behavior:

Run Kiwix Desktop and you will see an empty window.

Expected behavior:

Kiwix Desktop should list all downloaded zim files like the previous version 2.0.5 did.

**Comment by kelson42** [comment]
@xvitaly Here what I expected in terms of step-by-step procedure:
* Open kiwix-desktop and got to local library, this is empty
* Go to "Browse by language" and select "All", local library is still empty
* Open a local ZIM and once this is open got to local library, your sole ZIM file is listed
* Close kiwix-desktop and restart it
* I see the local library and my sole ZIM file (I have open in first run) and this is what I expect

So, works fine for me. Looks like I can not reproduce your bug.

**Comment by xvitaly** [comment]
> I see the local library and my sole ZIM file (I have open in first run) and this is what I expect

Empty library after restart.

**Comment by kelson42** [comment]
@xvitaly In the settings you see where the profile is stored. The list of local zim files is in "library.xml", in this directory. Coukd you please check that everything is OK with this directory? That library.xml is written properly?

**Comment by kelson42** [comment]
@xvitaly Any news?

**Comment by xvitaly** [comment]
I will test it with a clean profile soon.

**Comment by xvitaly** [comment]
@kelson42 Clean profile has the same problem.

Video of this bug: https://xvitaly.fedorapeople.org/bug-reports/kiwix-bug.mkv

**Comment by mgautierfr** [comment]
@xvitaly can you check that the language filter in the local library is "correctly" set (all or Russian). The added zim file is in Russian, if the library display only English book, it is normal it doesn't appear.

I have the same behavior on my side (with a English zim file and a default French filter)

**Comment by kelson42** [comment]
@xvitaly Glad to see that this a filtering problem like I had first guessed https://github.com/kiwix/kiwix-desktop/issues/776#issuecomment-1024424826. It is obvious that the current filter system is massively user unfriendly and this is a priority to rewrite the UI in Qt and fix the usability of the library. I really hope we can achieve to finally do that before the summer. I'm against having "all" as default filter, but the idea and the alternatives have already been discussed in #416. As such does not make sense to continue that discussion here.
