### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#78]
* It should be possible to close tabs with the scroll wheel. It is possible in most browsers and many other programs so it feels natural to do it.

* If you have typed a correct article title it should be possible to press enter to load the page. If you write the full title, e.g. "United States", and then press enter, it feels like a strange behavior that the search bar is just emptied and you stay on the old page. It is often obvious what the title is and it is much faster to type the entire title then to wait for the suggestions.

* Just a minor thing, but the back and forward buttons should be disabled when you are on the first or last page in the history. Now it is possible to press the buttons even when there are now pages in the history, though nothing happens.

* I think it would be better to stay in the current tab when you search for a new article or try a random article. At least I am not used to new tabs opening all the time. However, if you make this change, then you also have to add a small "tab" to the right of the last article with a plus sign or something for creating a new tab, as it is in many browsers and other programs.

* On the whole I think you should strive to make Kiwix behave as similar to common internet browsers as possible. It feels like you are browsing the internet when using Kiwix so one expects the same behaviour.

**Comment by kelson42** [comment]
@jargony Please open one ticket per suggestion/idea.

**Comment by jargony** [comment]
I have created the tickets now and will remember this for any future issues.

**Comment by kelson42** [comment]
@jargony Thank you very much for your quality reporting. We won't be able to fix or even answer everything immediatly but will try to fix the most important things soon. I'll close this ticket now.
