### ISSUE TITLE
Zim files requiring Service Workers should be hidden from the library if SW are not available

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#780]
Following up on [Libkiwix#696](../../libkiwix/issues/696)

Currently zimit-generated files can only be read on Kiwix-Android and Kiwix-serve (K-Desktop has a workaround but it's not main stuff). Kiwix-desktop cannot read these files at the moment, yet it is likely that at least some users will invest data transfers (and costs) into downloading files they ultimately cannot access.

Since zimit-generated files are tagged as such, it would make sense that they be hidden from the app's internal library if we know it cannot be read.

**Comment by kelson42** [comment]
Actually this is a bit more subtil IMO because these files are perfectly usable with the server feature. I would instread recommend to build a message explaining that they should use the server for the time being the feature is still not fully implemented in the rich application.

**Comment by Popolechien** [comment]
I strongly disagree. This complexifies the products as most users are unable / unwilling to read notices. This will marginally alleviate the current level of frustration.

**Comment by Jaifroid** [comment]
I would suggest you have an option in the UI: "Allow download of Zimit-based archives (for expert users)". If a user turns this on, they get a message explaining that they will need to serve the file to a browser. This will put off naive users, but not frustrate expert users.

JFYI, there is reasonable click-and-play support for Zimit ZIMs now in Kiwix JS Windows/Linux, including the [PWA](https://pwa.kiwix.org) (but not in the browser extensions).

**Comment by kelson42** [comment]
Indeed, the implementation of Zimit ZIM files keeps being postponed... we should really implement this quickly, this is a super easy fix. Doe someone knows how to filter out the ZIM with `_sw` tag with an OPDS API request?

**Comment by juuz0** [comment]
@kelson42 Though I don't know about any such OPDS API request, it is easy to hide based on if the book has a `_sw` tag or not.
And should there be a Settings option as Jailfroid suggests?

**Comment by kelson42** [comment]
@juuz0 Great, then If I understand you right you coukd do easily a PR? Considering that the prio is to implement support of SW base ZIM, i don't think we need a setting.

**Comment by Jaifroid** [comment]
It's up to you @kelson42 , but I'm sure you'll have to deal with enquiries from users who will say "why can't I find my Zimit files in the app any more?".... Of course they can get them from library.kiwix.org, so it's no great loss I guess.

**Comment by kelson42** [comment]
@Jaifroid I prefer this than complains that it does not work. Hopefully within a few months the support will be introduced anyway.
