### ISSUE TITLE
Flatpak freezes the whole desktop when searching

### ISSUE THREAD

**Issue by skbzk** [kiwix/kiwix-desktop#782]
When attempting to search something in a local zim file (i.e. entering atleast two characters in a search bar of an opened file tab) Kiwix freezes and the desktop environment with it. It is even impossible to switch to a different tty, so I can not copy any logs after the freeze happens. There is the output of Kiwix after the lauch:
`[2:29:0203/191657.230446:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
[49:66:0203/191657.355030:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
add widget
js: Uncaught TypeError: Cannot read property 'addPortletLink' of undefined`

`js: jQuery.Deferred exception: Cannot read property 'addPlugin' of undefined TypeError: Cannot read property 'addPlugin' of undefined
    at zim://7c066be5-afb9-f94d-dcc2-716700f328b2.zim/-/mw/site.js:416:13
    at mightThrow (zim://7c066be5-afb9-f94d-dcc2-716700f328b2.zim/-/mw/jquery.js:3766:29)
    at process (zim://7c066be5-afb9-f94d-dcc2-716700f328b2.zim/-/mw/jquery.js:3834:12) undefined`
This bug occurs no matter what file I open. Temporary solution is to simply roll back to a previous version of Kiwix:
`flatpak update --commit=7ff958865776ffc415edb7a2faadbffe28b882cc269f9d8abe17c31c37532370 org.kiwix.desktop`

Kiwix-desktop (flatpak) Kubuntu 20.04 (kde-plasma)

**Comment by kelson42** [comment]
Thank you for your bug report. Can you please give one of this ZIM file (full ZIM filename) not working fine and the pattern you give to make it freezes?

**Comment by skbzk** [comment]
Those files are `wikipedia_en_all_maxi_2021-12` and `wikipedia_ru_all_maxi_2021-12`. But it is of little importance now, because version 2.0.5 has the same problem. I think it has been caused by a recent update, because everything was fine yesterday.
The same bug occurs when trying to open a zim file from the file manager using Kiwix

**Comment by skbzk** [comment]
Latest entry in `/var/log/apt/history.log`, these are the packages that were upgraded:
`libnm0:amd64 (1.22.10-1ubuntu2.2, 1.22.10-1ubuntu2.3), network-manager:amd64 (1.22.10-1ubuntu2.2, 1.22.10-1ubuntu2.3), python3-update-manager:amd64 (1:20.04.10.9, 1:20.04.10.10), libmysqlclient21:amd64 (8.0.27-0ubuntu0.20.04.1, 8.0.28-0ubuntu0.20.04.3), libmysqlclient21:i386 (8.0.27-0ubuntu0.20.04.1, 8.0.28-0ubuntu0.20.04.3)`

**Comment by kelson42** [comment]
@skbzk I have tested with flathub kiwix-desktop 2.1.0 (released yesterday) on recent Ubuntu with wikipedia_en_all_maxi_2021-12 and everything works fine: both suggestions and fulltext search.

**Comment by skbzk** [comment]
@kelson42 I'll mark this as closed then? It seems to be some local issue with my system, if someone besides me will be able to reproduce the bug then it would make sense to continue.
