### ISSUE TITLE
Allow aarch64 on Flathub

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#784]
See https://github.com/flathub/org.kiwix.desktop/pull/7, which shoykd be merged.

**Comment by kelson42** [comment]
Can you please give me owner (or write permission otherwise) permission on the flathub repo?

**Comment by mgautierfr** [comment]
> Can you please give me owner (or write permission otherwise) permission on the flathub repo?

I cannot, I'm not the owner of the repository. It seems that @nedrichards (or others) can.
@nedrichards, can you give write permissions to @kelson42 (or whatever the same permissions as I have) please ?
