### ISSUE TITLE
Empty online library

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#785]
Tested on Kiwix-desktop 2.0.5 as well as on a test zip from PR #783 and the library manager shows zero files.
![image](https://user-images.githubusercontent.com/21675885/152955088-0fb79a54-3173-45e6-a93c-bace78ed1389.png)

Just for the sake of it I downloaded a couple of zims separately and opened them locally, no issue whatsoever.

**Comment by juuz0** [comment]
Can confirm, but it only happens when Category "Other" is selected

**Comment by kelson42** [comment]
@juuz0 I think we shoukd open a ticket for the "other" case which is an other bug

**Comment by kelson42** [comment]
@Popolechien Have you been able to reproduce this problem an an other windows computer?

**Comment by Popolechien** [comment]
@kelson yes I tried on a different machine (also Windows 10), different network: same issue.

**Comment by kelson42** [comment]
Just tested, works for me :( I suspect that this is a network problem. For example we reach a timeout. It would be great to verify:
* What are the client and server timeouts
* Do we effectively use HTTP compression
* What is the behaviour when a timeout is reached - or even if internet is not available (we should display an error).

**Comment by kelson42** [comment]
This is a typically example if something goes wrong at the HTTP level. We should print a meaningfull error.

**Comment by mgautierfr** [comment]
@Popolechien Can you test with the version here : https://tmp.kiwix.org/ci/publish_tmp_build_on_windows/kiwix-desktop_windows_x64_2022-02-14.zip

It will open a console window with some trace. Especially a `Downloading "https://library.kiwix.org:443/...."`
What is this line on your computer ? Can you access the url from your browser ?

**Comment by Popolechien** [comment]
@mgautierfr this failed as well. Here's what I get:
```
add widget
"2543adef440f6459"
"31b95ea653ba8604"
"3cfeb41732f53fd3"
"5428424c81d64929"
"9316d635aa066307"
"b12a25125b76d841"
"f2b58d36cb359a6a"
Downloading "https://library.kiwix.org:443/catalog/search?lang=fra&count=-1"
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

**Comment by mgautierfr** [comment]
> qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

This is definitively a connection error.
The question is why kiwix-desktop fails to initialize the secured connection on your computer when we can on our side (and even your browser on your computer)...

This is strange as you've used two different computers and networks.

**Comment by kelson42** [comment]
@Popolechien Can you please secure that your MS Windows has the latest updates installed?

**Comment by Popolechien** [comment]
@kelson42 Yep, everything is/was there.
Just tested https://tmp.kiwix.org/ci/publish_tmp_build_on_windows/2022-02-14/kiwix-desktop_windows_x64_2022-02-14.zip and it works.

**Comment by kelson42** [comment]
@Popolechien So now it works, but it was not before.... and nothing else has changed... so we don't know why it works now?

**Comment by Popolechien** [comment]
@kelson42 Those are two different builds that I tried (the second one was sent to me later in the day, hence the identical build name). @mgautierfr will know the difference.

**Comment by kelson42** [comment]
@mgautierfr Do we embed a truststore? Have you changed anything related to TLS?

**Comment by mgautierfr** [comment]
It is a issue with packaging. The openssl library are not embedded with Qt. We have to do it ourselves. We are probably using a dll already installed by another application on computer where it works (python and git do this at least)
The test package was a bit greedy as I've added a lot of library. I have few test to do to know what need to be included exactly (@Popolechien you will be rope in), be we know what is the problem.
