### ISSUE TITLE
Online library "other" displays zero book

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#786]
See screenshot:
![image](https://user-images.githubusercontent.com/1029718/153361226-c419c4ac-29ae-4ad0-a82e-a6e7420cb99c.png)

Although, the OPDS feeds returns hundreds of results!
https://library.kiwix.org/catalog/search?count=-1&notag=_category:gutenberg;_category:mooc;_category:phet;_category:psiram;_category:stack_exchange;_category:ted;_category:vikidia;_category:wikibooks;_category:wikihow;_category:wikinews;_category:wikipedia;_category:wikiquote;_category:wikisource;_category:wikiversity;_category:wikivoyage;_category:wiktionary

Detected/related in/to #785

**Comment by mgautierfr** [comment]
Which version of kiwix-desktop are you using ?

**Comment by kelson42** [comment]
@mgautierfr This has been tested with your ZIP or your latest PR
