### ISSUE TITLE
OPDS requests are not compressed

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#788]
They should, this would allow to get a feedabck really quicker with save 70% of the bandwidth.

Wie shoudl add a https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding header in the request and uncompress the response.

I still really wonder why Qt does not provide a solution out-of-the box!

**Comment by mgautierfr** [comment]
> I still really wonder why Qt does not provide a solution out-of-the box!

It seems that it should :

```cpp
    // If the request had a accept-encoding set, we better not mess
    // with it. If it was not set, we announce that we understand gzip
    // and remember this fact in request.d->autoDecompress so that
    // we can later decompress the HTTP reply if it has such an
    // encoding.
    value = request.headerField("accept-encoding");
    if (value.isEmpty()) {
#ifndef QT_NO_COMPRESS
        request.setHeaderField("Accept-Encoding", "gzip, deflate");
        request.d->autoDecompress = true;
#else
        // if zlib is not available set this to false always
        request.d->autoDecompress = false;
#endif
```

It may not if QT_NO_COMPRESS flag is set and it is set only if we are compiling the code to compile qmake. We use a pre build release of Qt.
Either the Qt build is buggy (but I doubt about this) or we have something wrong on our side (potentially on the server side).

On which system have you tested this ?

**Comment by mgautierfr** [comment]
I have tested on my computer (fedora) and wireshark with a kiwix-desktop using http instead of https (to please wireshark).
The OPDS content is compressed.
