### ISSUE TITLE
Close tabs with the scroll wheel

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#79]
It should be possible to close tabs with the scroll wheel. It is possible in most browsers and many other programs so it feels natural to do it.

**Comment by kelson42** [comment]
@jargony How would you do that exactly? I'm not familliar with this browser feature.

**Comment by jargony** [comment]
As it is now one has to click with the left mouse button on the X on the tab. But usually you can also click (not scroll) anywhere on the tab with the scroll wheel on the mouse to close it.

It is often also possible to click with the scroll wheel on the empty space to the right in the tab bar to create a new, empty tab. That feature could also be nice to add.

**Comment by xurror** [comment]
I'll like to work on this issue

**Comment by kelson42** [comment]
@xurror thx
