### ISSUE TITLE
Remove "fulltext index" from library selector

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#794]
This selector is a) hard to understand and b) provides no visible information value to the end user ("what's a fulltext index? Can I get the same content with and without index? What am I losing and how do I know it?") and thus could be removed so as to de-clutter the library interface.
![image](https://user-images.githubusercontent.com/21675885/153945942-ba819c7c-d1fd-46dd-aaa0-031f6519a126.png)

**Comment by kelson42** [comment]
Agree with this remark.
