### ISSUE TITLE
Open articles by pressing enter

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#80]
If you have typed a correct article title it should be possible to press enter to load the page. If I write the full title, e.g. "united states", and then press enter, I would assume the article will open. It feels like a strange behavior that the search bar is just emptied and one stays on the old page. It is often obvious what the title is and it is much faster to type the entire title then to wait for the suggestions.

**Comment by kelson42** [comment]
Ticket is probably related to the implementation of the fulltext search result page. On 1.0, the behaviour was, that if the article can be found directly then it open it, otherwise it opens the fulltext result page.

**Comment by jargony** [comment]
That feature sounds like what I was thinking about. Like how online wikipedia behaves too.

**Comment by kelson42** [comment]
I have open a separate ticket for the fullltext search https://github.com/kiwix/kiwix-desktop/issues/159
