### ISSUE TITLE
Not loading online article list

### ISSUE THREAD

**Issue by RatorLP** [kiwix/kiwix-desktop#802]
tried it on 2.0, 2.1.0 and today's nightly, as well as two different computers, kiwix desktop doesn't seem to load the online library. Running Windows 10 20H2 on one and 21H2 on the other machine, even tried it with a completely disabled firewall over 2 different networks from different ISPs, just for the funzies, but it didn't work either. I'm kinda lost here, don't have any idea where this might be coming from. I assumed some server downtime or sth, but the web version seems to work fine, so i'm clueless.

When opening "All files"  (or "Alle Dateien" in german) the blue spinner shows, after a while it disappears, but nothing else happens.
![kiwix1](https://user-images.githubusercontent.com/46613254/155806670-85f518da-e024-44b6-8cb8-781b0bd52e1b.png)
![kiwix2](https://user-images.githubusercontent.com/46613254/155806682-9db77f83-8525-48ad-85ed-3753b7b4fb41.png)

**Comment by RatorLP** [comment]
maybe i'm just missing something in the process, in that case this is to be treated as an UI intinuitivity issue

**Comment by RatorLP** [comment]
> @RatorLP Try with latest nightky build http://download.kiwix.org/nightly/2022-02-25/kiwix-desktop_windows_x64_2022-02-25.zip. Shoukd work.

That's exactly the build I tried

**Comment by kelson42** [comment]
@RatorLP Works for me now with my computer (Linux). In the console window you can see the API URL which is loaded. If you load it in the your browser, does it load properly?

**Comment by RatorLP** [comment]
@kelson42 about the update, yeah the 20H2 machine is a bit behind, but 21H2 ist the most recent version of win10, there is nothing newer. 

After a couple of reboots it loads the lib on the 20H2 PC, but does this:

https://user-images.githubusercontent.com/46613254/155845663-6d4363fd-7009-499f-9b70-d458c55d1e72.mp4

**Comment by juuz0** [comment]
@RatorLP can you show settings of kiwix desktop?
Top right, 3 dots -> Settings

**Comment by kelson42** [comment]
@RatorLP Your latest screenshot is wrong because the URL you have given is wrong (and not the one Kiwix Desktop requested). I should be http://library.kiwix.org/catalog/search?lang=deu&count=-1, not http://library.kiwix.org/catalog/search?lang=deu?count=-1

**Comment by juuz0** [comment]
@RatorLP may you please try http://download.kiwix.org/nightly/2022-02-26/kiwix-desktop_windows_x64_2022-02-26.zip also?
That's the latest build with some changes which might've fixed all problems

**Comment by laurens94** [comment]
For me the stable version of Kiwix crashed (app shutdown) when clicking 'All Files'. Same happened with the nightly 2022-02-25 build. The 2022-02-26 build worked however! :)

**Comment by RatorLP** [comment]
> @RatorLP may you please try http://download.kiwix.org/nightly/2022-02-26/kiwix-desktop_windows_x64_2022-02-26.zip also? That's the latest build with some changes which might've fixed all problems

Yes, it works, thanks!

**Comment by kelson42** [comment]
@RatorLP New official release `2.2.0` should be done this week.
