### ISSUE TITLE
Corrupt download after system disconnected through ether power lost in desktops

### ISSUE THREAD

**Issue by sorath72** [kiwix/kiwix-desktop#804]
Is it possible to recover and refresh a download link apon sudden disconnect? Cause I did just that by kicking my power supply under my computer by mistake and it seems like it corrupted the links associated to the downloads. Any fixes? I tried searching here but found nothing apparently talking about this :(

**Comment by kelson42** [comment]
@sorath72 What happens exactly? What is broken?

**Comment by sorath72** [comment]
[image: Screenshot_20220226_141830.png] THIS IS WHAT HAPPENS. Photo in
e-mail cause I can't really post it on github for some reason. It says
Error: This download in not available and shows java garble Thanks

**Comment by kelson42** [comment]
Which email? Kiwix desktop is not coded in Java! Please upload screenshot here.

**Comment by sorath72** [comment]
![Screenshot_20220226_141830](https://user-images.githubusercontent.com/48688496/155856263-5aabf3d9-c353-4f60-a450-d4ae96a090e3.png)

**Comment by kelson42** [comment]
@sorath72 You click on "download" and you get this error? Or you do something else?

**Comment by sorath72** [comment]
No just the ones I was downloading then the computer forced shut down. So click on a download and then force shutdown computer and redo it. You'll see same error. Thanks.

**Comment by mgautierfr** [comment]
It will be probably difficult to have a proper kiwix recover from a hard shutdown (especially than the downloading is not really made by kiwix but by aria2 software) but we will be able to do a manual recovery.
What is the content of your data directory ? (`C:\Users\<You>\AppData\Roaming\kiwix` by default). Especially the content of `library.xml` and `kiwix.session`

**Comment by kelson42** [comment]
> It will be probably difficult to have a proper kiwix recover from a hard shutdown (especially than the downloading is not really made by kiwix but by aria2 software) but we will be able to do a manual recovery.
> What is the content of your data directory ? (`C:\Users\<You>\AppData\Roaming\kiwix` by default). Especially the content of `library.xml` and `kiwix.session`

@sorath72 Would you be able please to answer this question?

**Comment by sorath72** [comment]
I don't have it anymore I switched to windows again but for me linux wise if you did a hard shutdown with the computer it would corrupt the file somehow. So just wanted to let you guys know this. I'm not able to recover files anymore so. Sorry for the inconvenience.

**Comment by mgautierfr** [comment]
We understand the problem. But the "corruption" can be done different way depending of when you did the hard shutdown. If there is something we can do, it is to investigate how it has been corrupted and check if we can make our system to recover (or at least be able to download again) the file.

Without the information of how the corruption is made, we cannot adapt our system.

> English isn't my native language :)

No problem, few of us use English as native language.

**Comment by kelson42** [comment]
No feedback of the user, not enough information ot understand what happened
