### ISSUE TITLE
Monitoring directory picker is somehow buggy

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#806]
Test with latest dev version:
* Pick `/home/kelson/Downloads` directory for monitoring
* In Settings I see `/home/kelson/Downloads`, which is right
* If I then pick `/home/kelson/Downloads/tmp` for monitoring
* In Settings I see `/home/kelson/Downloads/tmp` for monitoring
* If I then pick `/home/kelson/Downloads` again
* Nothing is changed, which is wrong.
* If I then pick `/home/kelson`
* It is changed but for `/home/kelson/Downloads` which is wrong as well

**Comment by juuz0** [comment]
Can't reproduce

https://user-images.githubusercontent.com/26814569/155951405-805352c5-c557-4fa7-913b-bf1367c734fa.mp4

**Comment by kelson42** [comment]
![Peek 2022-03-05 18-06](https://user-images.githubusercontent.com/1029718/156893197-93dac57a-7a91-41c2-a549-79b96cd61bea.gif)

**Comment by mgautierfr** [comment]
This is the standard behavior of gnome file picker (and I personally dislike it).
When you select a directory, the file picker doesn't return the directory you are in, but the directory you have selected.
In your video, when you go "up", by clicking on "Download", the subdirectory "storybox" is still selected and so you pick it.
When you click on "kelson", it is "Download" which is selected and you pick it.

If you dislike it, open a issue on "gnome" side. There is nothing we can do.
