### ISSUE TITLE
Kiwix 2.1.0: How to change the language?

### ISSUE THREAD

**Issue by Bernhardino** [kiwix/kiwix-desktop#808]
In C:\Program Files\Kiwix, there is a subfolder "translations", but I can't find a way to change the names of the menus and buttons  from english to german. Am I blind, or isn't there a possibility to switch the language of the GUI of Kiwix (I expected "..." -> "Settings" -> etc.)?

**Comment by kelson42** [comment]
It is not possible to change the UI language. It takes the language of the OS. But this would be a feature to develop. As such this ticket seems to be a ducplicate of #478
