### ISSUE TITLE
Stay in current tab when opening a new article

### ISSUE THREAD

**Issue by jargony** [kiwix/kiwix-desktop#81]
I think it would be better to stay in the current tab when you search for a new article or try a random article. At least I am not used to new tabs opening all the time.

However, if you make this change, then you also have to add a small "tab" to the right of the last article tab with a plus sign or something for creating a new tab, as it is in many browsers and other programs.

**Comment by kelson42** [comment]
@mgautierfr @schoenbaechler I think @jargony is right and the "+" tab is anyway in the UI design.

**Comment by kelson42** [comment]
@jargony "New tab" button is tracked here #36

**Comment by schoenbaechler** [comment]
Thanks for bringing this up @jargony. And you are exactly right, search result items or internal ZIM links should always open in the existing tab, as it is the case in common web browsers. It would be helpful though to incorporate a right or ctrl click feature that lets users open a link in a new tab if they prefer to.

**Comment by kelson42** [comment]
@jetownfeve21 Could you also please fix these small problems? That sounds quite straight to me.
