### ISSUE TITLE
kiwix-desktop appimage webengine is broken on Fedora (and ubuntu 22.04)

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#810]
kiwix-desktop appimage (both released (https://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.1.0-1.appimage) and nigthly (https://download.kiwix.org/nightly/2022-03-02/kiwix-desktop_x86_64_2022-03-02.appimage)) do not display anything in the web views (library and zim) on Fedora 35

Appimage is run with the workaround explained here https://github.com/kiwix/kiwix-desktop/issues/745#issuecomment-1017530749
`MESA_LOADER_DRIVER_OVERRIDE=i965 ./kiwix-desktop_x86_64_2022-03-02.appimage`

![Capture d’écran du 2022-03-02 15-00-18](https://user-images.githubusercontent.com/86161/156375978-72cfd7da-a32f-41bf-80dd-ba49a18b9239.png)

Else kiwix-desktop seems to work correctly. It is possible to open a zim file (but we cannot see its content. Traces are ok....
kiwix-desktop compiled localy works fine.

**Comment by mgautierfr** [comment]
AppImage build on local system works correctly.

**Comment by mgautierfr** [comment]
Few more information :

- Last nightly version (https://download.kiwix.org/nightly/2022-03-16/kiwix-desktop_x86_64_2022-03-16.appimage) doesn't need the workaround as it as been fixed by https://github.com/kiwix/kiwix-build/pull/520
- Running kiwix-destkop appimage with env var `QTWEBENGINE_REMOTE_DEBUGGING=8080` start a server to debug QtWebengine but connecting to localhost:8080 show no page to inspect.
- However, subprocesses `QtWebEngineProcess` have been correctly (?) started.

I've tried to trace dynamic libraries loaded if somethings seems wrong but I've found nothing relevant.
Pinging @probonopd maybe he has a idea of what going on or a lead to follow.

**Comment by probonopd** [comment]
@mgautierfr 

> AppImage build on local system works correctly.

Are you saying you have a working and a non-working AppImage? Then it's probably a matter of tracing/comparing the two...

**Comment by mgautierfr** [comment]
Yes, I've tried to compare strace/`LD_DEBUG=1`/`QT_DEBUG_PLUGINS=1 QML_IMPORT_TRACE=1` but I've found nothing convincing.
But I can provide you the two appImage if you want to try. Maybe you will have a better idea of what to check/what is important.

**Comment by juuz0** [comment]
Same problem on Ubuntu 22.04

**Comment by kelson42** [comment]
@mgautierfr I confirm, this is now urgent to fix this problem and make a new release.

**Comment by caralu74** [comment]
With the new version I use: kiwix-desktop_x86_64_2.3.0.appimage the trouble looks the same. The GUI open but I can open ZIM files. (I am using Linuxmint Vanessa)The output is:
$ ./kiwix-desktop_x86_64_2.3.0.appimage
add widget
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1184, resource id: 27263409, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1544, resource id: 27263444, major code: 40 (TranslateCoords), minor code: 0

No se encuentra el paquete que proporciona /tmp/.mount_kiwix-VCo6MO/usr/libexec/QtWebEngineProcess.
Si desea generar un seguimiento de la pila para este informe de error, reinstálelo.

No se encuentra el paquete que proporciona /tmp/.mount_kiwix-VCo6MO/usr/bin/kiwix-desktop.
Si desea generar un seguimiento de la pila para este informe de error, reinstálelo.

**Comment by kelson42** [comment]
We struggle to fix the problem. In the mean time, better use flathub/flatpak

**Comment by kelson42** [comment]
@probonopd If we setup a Bounty, would you be interested to have a look and fix this ticket?

**Comment by caralu74** [comment]
I think so!, I would love to help on it.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Enviado con [Proton Mail](https://proton.me/) correo seguro.

------- Original Message -------

**Comment by mgautierfr** [comment]
I have opened a issue upstream (https://github.com/probonopd/linuxdeployqt/issues/554) with a small repro case without all the kiwix stack.
