### ISSUE TITLE
Wikipedia: Categories and Templates in the footer of each article

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-desktop#812]
When will the **Categories** and **Templates** from the footer of each article appear in Wikipedia ZIM files?
**[Article Sample](https://en.wikipedia.org/wiki/2022_Sumatra_earthquake#External_links)**:
![Categories_Templates](https://user-images.githubusercontent.com/65112331/156575093-f1abdc66-8ac4-428c-9ac7-3abd01232946.GIF)

**Templates** and **Categories** from the footer of the article make Wikipedia much easier to navigate!
**Templates** and **Categories** contain a large number of links to related articles!
Please add **Templates** and **Categories** to ***.ZIM** Wikipedia files.
Or at least in **Mileston** for the future, make such a note.

**Comment by kelson42** [comment]
This is a ticket for openzim/mwoffliner
