### ISSUE TITLE
Kiwix destkop doesn't open .zim file

### ISSUE THREAD

**Issue by Phoenixof94** [kiwix/kiwix-desktop#814]
When I gonna to open the first configuration of my Wikipedia file , I put the select the directory when is the .zim file and the kiwix desktop software show this:

Your file couldn’t be access
edIt may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

I hope someone can help me with this problem.

**Comment by kelson42** [comment]
What is:
* your OS?
* version of Kiwix?
* the filename of the zim file?
* thw way you have used to download it?

**Comment by Phoenixof94** [comment]
> 

SO: Linux Mint 20.3 Mate x64 
Kiwix: Kiwix Desktop vertion 2.1.0 
Zim: wikipedia_es_all_2017-01.zim
I download the file by Google. I don't remember where.
