### ISSUE TITLE
Math formulars are not rendered

### ISSUE THREAD

**Issue by pityhero233** [kiwix/kiwix-desktop#819]
Hi all,
I was trying to read proofwiki on Kiwix. It looks like this:
![image](https://user-images.githubusercontent.com/24752033/158161498-51f9686b-24db-474f-8a36-2ddb430bde44.png)
I am not sure if this is due to file itself or Kiwix-desktop though. I am on Arch Linux, with kiwix-desktop 2.1.0-2. Thanks!

**Comment by kelson42** [comment]
Thx for the bug report, but this is a duplicate ticket of https://github.com/openzim/mwoffliner/issues/1371
