### ISSUE TITLE
Launcher/installer doesn't load? 

### ISSUE THREAD

**Issue by Acluff1** [kiwix/kiwix-desktop#822]
I'm running Raspian OS on a PI 3 b+. I double click the kiwiks exe, and nothing happens. I try to sudo execute with terminal and I get a ". /kiwix-hotspot: 1: Syntax Error:" (" unexpected.

Any help?

**Comment by kelson42** [comment]
Kiwix-hotspot is a solution to build and image to write on the RPI SD card. It is conceived to run on a PC with x86 architecture.

**Comment by Acluff1** [comment]
OK... But following the how-to for rpi says there should be a launcher or some kind of program that runs for hours... But the launcher never launches anything. Are there steps missing in the process? Can you help me get this running instead of being less than helpful?

**Comment by kelson42** [comment]
Run kiwix-hostpot on your PC, not on the RPI.
