### ISSUE TITLE
Utterly useless app, needs a total rewrite.

### ISSUE THREAD

**Issue by zohozer** [kiwix/kiwix-desktop#823]
The title sayis it all. It is the most useless and frustrating app I've ever used.

This peace of crap needs a total rewrite to be useful for something.

**Comment by juuz0** [comment]
Well, even if it was completely rewritten, you may face the same problem which you are doing right now.

The current comment is hardly constructive at all, specific problems would be much better

**Comment by zohozer** [comment]
Sorry for the harsh words but I am so upset that it is not working at all. Seems that everything in this app it is just broke.

**Comment by kelson42** [comment]
@zohozer Completly useless and disrespectful feedback. Closing.

**Comment by mgautierfr** [comment]
I'm really sorry for you that a application we provide free of charge and without any warranty (I let you read the license carefully) doesn't fulfill your need.

But if you are not even motivated enough to create proper bug report (pull request would been even better) be sure that we will not be motivated enough to help you (and I'm not even speaking about you disrespectful tone)
