### ISSUE TITLE
Crash scenario with Ubuntu 20.04 + nouveau Nvidia driver

### ISSUE THREAD

**Issue by LAfricain** [kiwix/kiwix-desktop#828]
Kiwix ppa used: https://launchpad.net/~kiwixteam/+archive/ubuntu/release
On Ubuntu 20.04
Zim used: wikipedia_fr_all_maxi_2021-09.zim
Kiwix Version : 2.0.5

Error when it crashes:
```
(kiwix-desktop:8064): Gtk-WARNING **: 13:49:37.097: Theme parsing error: gtk.css:6083:16: Junk at end of value for color
add widget
kiwix-desktop: ../nouveau/pushbuf.c :723 : nouveau_pushbuf_data:  l'assertion « kref » a échoué.
Abandon (core dumped)
```

The crash occurs when we are browsing in the wiki.

**Comment by kelson42** [comment]
I don't have this older ZIM file anymore, but works for me.

![image](https://user-images.githubusercontent.com/1029718/162581373-38883b7e-5d5c-44d6-a16e-bfde1587cb02.png)

Please use latest version of Kiwix.

**Comment by LAfricain** [comment]
Are you using a nvidia card with the nouveau driver?
Please don't close so quick the issue!
My version is not 2.0.5 but 2.2.1~focal. The 2.0.5 is what I can read in the About in kiwix, some error?

**Comment by kelson42** [comment]
You are probably mixing things between two versions of kiwix-desktop installed on your computer

![image](https://user-images.githubusercontent.com/1029718/162589262-de435505-a13b-43b9-bdb1-9b74b4c04446.png)

No, I have an Intel based graphic card.

**Comment by LAfricain** [comment]
> You are probably mixing things between two versions of kiwix-desktop installed on your computer

You are right, the update was not applied

> No, I have an Intel based graphic card.

Then why did you close this issue?

**Comment by kelson42** [comment]
I have closed the issue because we only treat bug reports corresponding to latest version of Kiwix. Here you report is made with a pretty old version.

**Comment by LAfricain** [comment]
Hi kelson42,
>to latest version of Kiwix

Ok I wrote I was wrong, I did the update. The issue is the same.

> I have also no clue why you you keep writting about NVidia

It's just an idea because I have this issue only with one computer, and you can see in the error log a reference to the "nouveau" driver. The nouveau driver is the free driver for nvidia cards.

**Comment by kelson42** [comment]
@mgautierfr maybe you have an idea?

**Comment by kelson42** [comment]
This is a problem beetween Qt and nouveau driver. Look at https://github.com/rstudio/rstudio/pull/6571. Maybe using a more recent Qt version will just fix the problem. Would be interesting to test with Ubuntu 22.04.

**Comment by kelson42** [comment]
No feedback. This is probably fixed with recent versions od dependences.
