### ISSUE TITLE
Bookmark icon not always available

### ISSUE THREAD

**Issue by h-b** [kiwix/kiwix-desktop#832]
I am using version 2.2.1 on Linux. When I click on a link in a book, an icon appears to the left of the title that allows me to bookmark it:

![image](https://user-images.githubusercontent.com/24413995/163276704-2f2adff8-0546-40be-a3a4-049a17d1645e.png)

Alternatively, it is possible to search pages and then select one of the search results. Then the article is loaded, but no bookmark icon appears to the left of the title:

![image](https://user-images.githubusercontent.com/24413995/163276795-09d27640-74e9-4252-adc8-afe2138f5402.png)

Trying to make the icon visible by pressing the escape key or clicking in the article does not work. The only solution I have found is to click on an arbitrary link in the article I want to bookmark, and then return to the previous article (Alt-Left). Only then does the icon appear.

I would expect that after clicking on a search result, the magnifying glass icon is replaced by the bookmark icon and the cursor disappears. This is not the case - instead you can even continue typing, which makes no sense because you have selected a search result.

**Comment by kelson42** [comment]
@h-b Interesting... looks really like a bug.

**Comment by thestarsahil** [comment]
Well Interesting to work on this bug 
@kelson42 Can I take this responsibility to fix this problem?

**Comment by kelson42** [comment]
@thestarsahil Yes, if you know how to fix it.

**Comment by thestarsahil** [comment]
Can I do this in Window OS?

**Comment by LadyDhaga** [comment]
I want to work on this issue please assign me this issue.

**Comment by kelson42** [comment]
@LadyDhaga Do you know how to fix it? Can you explain it?

**Comment by h-b** [comment]
So both thestarsahil and LadyDhaga would like to work on a bugfix? That is good news because when working with bookmarks, at least for me, it is a usual workflow to bookmark something after searching for it – which does not work because of this bug. @thestarsahil I am using kiwix under Linux, but it should be easy to see if the problem occurs under Windows and MacOS. If you like, I can check both for you. At least on Linux, version 2.3.1, the problem still occurs, I just checked it:

![image](https://user-images.githubusercontent.com/24413995/228494821-3b12de73-d65d-4c35-917e-6bd52ad4538d.png)

**Comment by thestarsahil** [comment]
@h-b Stefan Can I work on PopOs Version 22.07 system?
If Yes Then I have to Install that Linux PopOs

**Comment by h-b** [comment]
@thestarsahil Thank you for your interest in working on the bug fix for this issue. As far as I understand, the bug seems to affect all operating systems, and the main goal is to resolve the issue in the project, regardless of the specific OS used for testing. However, I am not a maintainer or collaborator of this project, so I may not be the best person to answer your question about working on the Pop!_OS version.

I would suggest reaching out to the maintainers or collaborators of the project for further guidance on this matter. Meanwhile, you may proceed with testing the bug on any operating system you have access to and submit a pull request with your proposed fix. This would allow the project team to review and potentially approve your contribution.

Good luck, and I hope to see this issue resolved soon!

Stefan

**Comment by thestarsahil** [comment]
@h-b Can you redirect me to the maintainer or collaborator?

**Comment by kelson42** [comment]
@thestarsahil Thank you for your interest, but why you just not try first to compile the source code reproduce the bug? This is how it works. People are short on time and want to discuss concrete proposals.

**Comment by ShaopengLin** [comment]
This PR would solve the issue. There is an explicit check that tells the button to not switch if the search bar has text (so it doesn't remove the text and replace it with the current page title). The check should not be relevant to when the button should switch so I separated the two. Though I feel like the button could be more easily managed as a separate button..., discussion for another time.

**Comment by veloman-yunkan** [comment]
Why don't we separate the bookmark button from the search icon and always display it on the right of the searchbar (like in Firefox)?

**Comment by kelson42** [comment]
> Why don't we separate the bookmark button from the search icon and always display it on the right of the searchbar (like in Firefox)?

Right with LTR UI languages, and left otherwise. This might be not that easy.
