### ISSUE TITLE
Kiwix Desktop fails to launch on a Windows (since beta1)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#84]
I've downloaded and extracted beta1 on my Windows machine, and double-clicked on Kiwix-desktop.exe : a background process appears in my process list and takes about 7.5 Mb of memory. But then no window opens and the process shuts down after a couple of minutes. 

No error message, nothing :-/

FWIW it worked perfectly fine on another windows machine I have.

**Comment by kelson42** [comment]
@Popolechien Which Windows version? 32 or 64 bits architecture?

**Comment by Popolechien** [comment]
Win10 x64 in both cases. Haven't started from the command line, on account of me not being smart enough to do it.

**Comment by kelson42** [comment]
@Popolechien Have you installed `vc_redist.x64.exe` available in the ZIP?

**Comment by Popolechien** [comment]
Yes I did - and no it did not change anything.

**Comment by kelson42** [comment]
@mgautierfr Testing with @Popolechien with beta4, same sympton. We tried again with the beta3 which fails also now (but it has worked1).

**Comment by Popolechien** [comment]
Downloaded beta5 on two machines. While this works on the first one, I get an error message (no Qt platform could be initialized) on the second one: 
![image](https://user-images.githubusercontent.com/21675885/58632591-4bf5ce00-82e6-11e9-900d-a5fa1a63a00b.png)
Note: I've renamed/moved the old Kiwix folderS (I have two) in user/AppData

**Comment by Popolechien** [comment]
We're good! You can close the ticket, thanks

**Comment by kelson42** [comment]
Wonderful.
