### ISSUE TITLE
Kiwix-serve does not work with new ZIM files

### ISSUE THREAD

**Issue by markknit** [kiwix/kiwix-desktop#849]
I run a set of offline education servers in Africa that host a wide range of ZIM files using Kiwix-Server (along with Kolibri, etc.). The servers run Ubuntu 18.04 with Nginx, PHP, SQL, etc. The servers are accessed strictly through web interfaces on notebooks, phones, etc. I've never had a problem with ZIM files that until I added a couple of new ZIM files - Boundless and GCFLearnFree. Both seem to have the same issue that they will not load with the Kiwix-Server (or desktop) unless I use 'localhost', which clearly won't work for devices that are connecting to the server over a wireless connection. I've tried enabling HTTPS in Nginx, but that didn't make a difference, including routing all traffic to https. I also upgraded to the latest server version.

What can I do to resolve this? Should I use a reverse proxy? I'm willing to try anything to make it work as I suspect that this problem will appear in many more ZIM files going forward. 

Thanks, Mark K

**Comment by kelson42** [comment]
Answer to be found in this other ticket https://github.com/openzim/zimit/issues/106#issuecomment-1068907042
