### ISSUE TITLE
Kiwix incorrectly claims "not enough storage available"

### ISSUE THREAD

**Issue by VorpalBlade** [kiwix/kiwix-desktop#854]
I had wikipedia with pictures downloaded since before. I now noticed there was a newer version available and decided to download it.
I removed the old version of wikipedia and went to download the new version. However the following popup shows up:
![image](https://user-images.githubusercontent.com/3315306/176871227-87e4af16-fa95-4487-afaa-e4a7ff567f9f.png)

This is incorrect. According to the listing Wikipedia should be 89 GB. 

Note output below may look a bit strange looking since kiwix is on it's own btrfs subvolume (to prevent automatic snapshots from including kiwix). However, as can be seen, there is more than double the required space available on this file system.

```console
$ df -h ~/.var/app/org.kiwix.desktop/data
Filesystem      Size  Used Avail Use% Mounted on
-               300G  102G  197G  35% /home/arvid/.var/app/org.kiwix.desktop/data
$ df -h /
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/linux-root  300G  102G  197G  35% /
```

kiwix also complains about storage space for much smaller downloads, such as the 12 GB "introduction only" wikipedia download. However, really small downloads, like wikiquite (684 MB) starts correctly.

System info:
* Arch Linux x86-64 (rolling release)
* Kiwix 2.2.2
* Desktop environment is KDE Plasma 5.25.2
* File system is btrfs.
* I installed kiwix via flatpak.

**Comment by juuz0** [comment]
I can confirm the bug, anything above 4GB shows this problem for me.

Ubuntu 22.04
Kiwix 2.2.2
Available Space: 67GB
Filesystem: ext4

**Comment by kelson42** [comment]
I don't understand why the bug only appears now! This is a regression? A bug specific to btrfs?

**Comment by VorpalBlade** [comment]
> @VorpalBlade Thx for your tickrt. Which version of Kiwix did you have before?

Not sure, flatpak auto updates. But it was the latest flatpak from late last year / early this year when I downloaded wikipedia data.

> What is the output of btrfs filesystem usage ~/.var/app/org.kiwix.desktop/data ?

It complained that it needed to be run with sudo, so I did that.
```
$ sudo btrfs filesystem usage ~/.var/app/org.kiwix.desktop/data
Overall:
    Device size:		300.00GiB
    Device allocated:		114.07GiB
    Device unallocated:		185.93GiB
    Device missing:		    0.00B
    Used:			102.21GiB
    Free (estimated):		195.82GiB	(min: 102.85GiB)
    Free (statfs, df):		195.82GiB
    Data ratio:			     1.00
    Metadata ratio:		     2.00
    Global reserve:		162.38MiB	(used: 0.00B)
    Multiple profiles:		       no

Data,single: Size:110.01GiB, Used:100.12GiB (91.01%)
   /dev/mapper/linux-root	110.01GiB

Metadata,DUP: Size:2.00GiB, Used:1.04GiB (52.25%)
   /dev/mapper/linux-root	  4.00GiB

System,DUP: Size:32.00MiB, Used:16.00KiB (0.05%)
   /dev/mapper/linux-root	 64.00MiB

Unallocated:
   /dev/mapper/linux-root	185.93GiB
```

> I don't understand why the bug only appears now! This is a regression? A bug specific to btrfs?

Definitely a regression. It worked before for me on btrfs late last year or early this year. I don't have any non-btrfs system to test with.

**Comment by VorpalBlade** [comment]
> I can confirm the bug, anything above 4GB shows this problem for me.

That sounds to me like someone used an unsigned 32-bit integer by mistake somewhere.

**Comment by mgautierfr** [comment]
I suspect this commit https://github.com/kiwix/kiwix-desktop/commit/b49ea7cbce83777d1c68d2ec4a8fae1e4df59fb1 and especially the appearing 'unsigned'

**Comment by juuz0** [comment]
Yeah right. That must be it since a build from 9e0575a225775e173fcbeb0cc9b82a56c64cef9c works fine

**Comment by kelson42** [comment]
@juuz0 Woukd you be able to make a PR to fix it? We will have to make a new release irgently.

**Comment by kelson42** [comment]
A nightly, with the fix, will be available in a few hours at http://download.kiwix.org/nightly/2022-07-03/

**Comment by Bleda412** [comment]
> A nightly, with the fix, will be available in a few hours at http://download.kiwix.org/nightly/2022-07-03/

I am a bit of a boomer. How exactly do I install this fix?

**Comment by kelson42** [comment]
@Bleda412 download http://download.kiwix.org/nightly/2022-07-03/kiwix-desktop_windows_x64_2022-07-03.zip

**Comment by Bleda412** [comment]
@kelson42 I just did that. Not sure if this is intended but when I run the program, a command prompt comes up and stays up. When I tried to download Wikipedia, it stopped responding after 39MB, which happened almost instantly.
I don't mean to pester you with this reply, just letting you know it doesn't work for me just yet. Thanks for working on a fix.

**Comment by scottmayo** [comment]
Fails on ubuntu with 600G free, as described by others. Also, I can't find any version other than 2.2.2, so while a fix has been merged I have no idea how to get the fixed version.

**Comment by kelson42** [comment]
@scottmayo Have you tried with a nightly?

**Comment by kelson42** [comment]
Yes, we are working on the release
