### ISSUE TITLE
How to add file into Local Files area

### ISSUE THREAD

**Issue by Emnolope** [kiwix/kiwix-desktop#86]
So I've downloaded the 79Gb version of Wikipedia, but no matter how many times I open it with the File->Open it will not appear in the local files list in the start up screen. This normally wouldn't be a problem, but I'm going to be giving this to a kid in the Philippines, who probably won't know to navigate to that zim file. Is there a way I can get it to go in the Local File area, as if it was a natively downloaded file?

**Comment by kelson42** [comment]
To me this seems to be a duplicate of #46
