### ISSUE TITLE
Kiwix-desktop (v.2.2.2; Windows) defaults downloads on a non-existent drive

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#861]
It took me a bit to figure it out:
When trying to download a file from the interface I get the following error message
![image](https://user-images.githubusercontent.com/21675885/178750590-d3302a5e-cb6d-4fd7-8d4d-41d093103704.png)
I have about 200Gb of Free space. I then looked at settings and saw that the default directory for downloads is D:/Zim files, which obviously does not exist. I changed the default to C: and the problem went away.

I would expect and suggest that zim files be downloaded to /whereever_Kiwix_folder_is/Zim_files

**Comment by kelson42** [comment]
@Popolechien Pretty sure this is something you have changed yourself manually. Right @juuz0 ?

**Comment by juuz0** [comment]
Yeah, this must have been changed manually (in an older version maybe?). The actual initial location can be found by pressing "Reset" in Download directory option.

**Comment by Popolechien** [comment]
Ah okay, interesting because that was a new install. Does Kiwix-desktop store these settings somewhere else that its own folder?

**Comment by juuz0** [comment]
Yep, it's in Windows registry. So different versions use the same settings.

OpenRegistry Editor
Under HKEY_CURRENT_USER > SOFTWARE > Kiwix
