### ISSUE TITLE
Reading list does not work (Kiwix-desktop 2.2.2 on Windows 10)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#862]
Adding any sort of page to the reading list does not add it anywhere.

![image](https://user-images.githubusercontent.com/21675885/178754374-52e09904-f091-46d1-ade7-2da68fc4e854.png)

**Comment by kelson42** [comment]
@juuz0 Have you been able to confirm that bug?

**Comment by juuz0** [comment]
No, cannot confirm.
![image](https://user-images.githubusercontent.com/26814569/184159134-3400a2e1-7c7a-4a95-aa44-05d576b5094f.png)

**Comment by kelson42** [comment]
@Popolechien We need a detailed/step-by-step bug report I guess.

**Comment by kelson42** [comment]
@Popolechien Any feedback?

**Comment by Popolechien** [comment]
@kelson42 No real additional feedback. Opening a wiki (wikipedia_fr_test_2022-06), open an article, click on the little glasses for reading list. They turn from transparent to black but the reading list pane remains empty. Closing and bringing Kiwix back on does not change anything.

Running on Windows 10.

![image](https://user-images.githubusercontent.com/21675885/188307979-b1195285-24c5-4b20-bd57-0836960487b6.png)

**Comment by Popolechien** [comment]
Tried on another Windows PC - same thing.

**Comment by alrepin** [comment]
Same on linux appimage build.

**Comment by kelson42** [comment]
Work for me as well... you click on which "little glass" icon exactly? The one from left (to add current article to reading list) in the search bar or the one of right (to display the reading list)?

**Comment by kelson42** [comment]
@Popolechien Would yoy be able please tobmake a screencast?

**Comment by Popolechien** [comment]
Tried with the latest release (2.3.0) -> no problem.
