### ISSUE TITLE
Feature Request: Cycle through tabs with <ctrl>+<tab> and <ctrl>+<shift>+<tab>

### ISSUE THREAD

**Issue by figueroa628** [kiwix/kiwix-desktop#866]
It'd be nice to be able to cycle through tabs with `<ctrl>+<tab>` and `<ctrl>+<shift>+<tab>`. Those two keyboard shortcuts are pretty fundamental to my workflow in typical browsers, and it's been pretty jarring to not have that available when eg browsing Wikipedia offline.

(Sorry if this isn't the right place for feature requests.)

**Comment by kelson42** [comment]
Sounds legit, @juuz0 woukd you be able please to quickly implement this?

**Comment by juuz0** [comment]
On it :+1:
