### ISSUE TITLE
I can't install any file over 1 gb 

### ISSUE THREAD

**Issue by fenix3435** [kiwix/kiwix-desktop#868]
So i install kiwix with the goal of installing wikipedia on a usb key, but i didn't work and a error appear not enough storage available so i try to solve the problem. I check the file type of my 2tb flash usb and it was exFAT like everyone was telling to have so i try to change for the only other option NTFS file but it didn't work too. So I try to install any of kiwix file to see if the problem was from the app but i can install any fill under 1 gb but any file with 1 gb and more don't want to be install and a error message appear saying not enough storage available so right now I doesn't know what to do since my usb key isn't in FAT32 i should be able to install anything over 4 gb. At this point i was suspect my usb key to be the problem so i try something else I use one of my hard drive that I have install ark (156gb) to install the 90 gb wikipedia file to transfert it after in my flash usb but the error message still appear even so if my hard drive still have 1.5 tb of storage and i try the same thing that i try my the usb key to try something under 4 gb and something under 1gb and the same thing that append with the usb key append with the hard drive. 

For the people who will ask what my confic
* intel core i9-9900k
*rtx 2070 asus rog
*32gb ram 3600
*2x 2tb hard drive seagate
*256gb ssd blue

So what should i do to install that wikipedia file?

**Comment by kelson42** [comment]
This is a known regression we have fixed, but not released yet. You can download a nightly build to get rid of it http://download.kiwix.org/nightly/

**Comment by Fubar1** [comment]
> This is a known regression we have fixed, but not released yet. You can download a nightly build to get rid of it http://download.kiwix.org/nightly/

There are 27 files on the Index...which one am I supposed to download to fix this issue?

**Comment by kelson42** [comment]
@Fubar1 what is your operating system?

**Comment by Fubar1** [comment]
> 

Window 10 Pro x64

**Comment by kelson42** [comment]
http://download.kiwix.org/nightly/2022-08-17/kiwix-desktop_windows_x64_2022-08-17.zip

**Comment by Fubar1** [comment]
> http://download.kiwix.org/nightly/2022-08-17/kiwix-desktop_windows_x64_2022-08-17.zip

Thank you very much!
