### ISSUE TITLE
Uncollapse navboxes

### ISSUE THREAD

**Issue by juuz0** [kiwix/kiwix-desktop#869]
From https://github.com/kiwix/kiwix-desktop/issues/42#issuecomment-1211873258 and the discussion around it

The navboxes at end of page should be shown.

**Comment by juuz0** [comment]
@kelson42 If you're in favour of getting them in kiwix desktop too, should it be an always forced option or a toggleable setting in Settings Panel.

@Jaifroid Ping! Can you please link me the PR (or related code) in kiwix JS which unhids the navboxes? (Or a brief explanation..anything works :)

**Comment by kelson42** [comment]
Kiwix-desktop is not the place to fix this. The problem we have currently is a bug in MWoffliner which has been discussed many times and has to be fixed there.
