### ISSUE TITLE
Appimage on LinuxMint, does not scan ZIM files.

### ISSUE THREAD

**Issue by caralu74** [kiwix/kiwix-desktop#874]
When I was on LM 20, the appimage works fine, but with LM 21 Kiwix open but could not open the ZIM files. I paste some of the output: 

$ ./kiwix-desktop_x86_64_2.2.2.appimage
add widget
Downloading "https://library.kiwix.org:443/catalog/search?lang=spa&count=-1"
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1642, resource id: 27263365, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2650, resource id: 27263375, major code: 40 (TranslateCoords), minor code: 0
Handling request QUrl("zim://aac6cce7-3e3c-3656-465d-a0209d9c1e76.search?content=aac6cce7-3e3c-3656-465d-a0209d9c1e76&pattern=a")
Handling request QUrl("zim://b4bad991-bf2b-832e-2607-487995adda07.search?content=b4bad991-bf2b-832e-2607-487995adda07&pattern=home")
Downloading "https://library.kiwix.org:443/catalog/search?lang=spa&count=-1"
session saved

$ ./kiwix-desktop_x86_64_2.1.0.appimage
add widget
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1572, resource id: 27263435, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2491, resource id: 27263447, major code: 40 (TranslateCoords), minor code: 0
session saved

$ ./kiwix-desktop_x86_64_2.0.1-1.appimage
Library directory : "/home/foo/.local/share/kiwix"
Compiled with Qt Version  5.9.5
Runtime Qt Version  5.9.5
add widget
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2031, resource id: 27263491, major code: 40 (TranslateCoords), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2880, resource id: 27263503, major code: 40 (TranslateCoords), minor code: 0
session saved
Violación de segmento (`core' generado)

QTWebEngineProcess
No se encuentra el paquete que proporciona /tmp/.mount_kiwix-1TzS3R/usr/bin/kiwix-desktop.
Si desea generar un seguimiento de la pila para este informe de error, reinstálelo.

No se encuentra el paquete que proporciona /tmp/.mount_kiwix-1TzS3R/usr/libexec/QtWebEngineProcess.
Si desea generar un seguimiento de la pila para este informe de error, reinstálelo.

**Comment by caralu74** [comment]
So, Should I report it on Kiwix-hotspot or keep an eye here?

**Comment by kelson42** [comment]
@caralu74 Sorry, no your ticket is ok, i have moved it.

**Comment by mgautierfr** [comment]
Can you describe a bit more what do you mean by don't open ?
You can "see" the zim file but can't open it or you cannot see it (kiwix-desktop doesn't scann zim files) ?

**Comment by caralu74** [comment]
Sorry for the poor description!
I mean, the GUI open, then I go to: Open a file, explore my PC and find Wikipedia-xxx.zim, then I click open and nothing happen, I could not search anything, the GUI keeps white, it opens a new tab, but I can not search or find any information. I hope I could explain a little better.

**Comment by mgautierfr** [comment]
Looks like a duplicated of https://github.com/kiwix/kiwix-desktop/issues/810
