### ISSUE TITLE
Not proper with Win + Arrows 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#878]
If I want to view in a half of the screen.
WinKey + <- / ->

From https://sourceforge.net/p/kiwix/bugs/787/

**Comment by juuz0** [comment]
Is this an OS dependent problem?
On my Ubuntu, it works fine

**Comment by kelson42** [comment]
@juuz0 Thank you for testing this. I have migrated straight this ticket for the very old bug tracker of Kiwix to Github in an attemps to finally close everything there on Sourceforge. So, I didn't test anything. Now, thanks to your feedback, I can confirm that it works fine on Ubuntu.

Considering that:
* This is basically Qt catching these event and forwarding things to the OS, we can assume that it works on Windows as well (I don't have one right now to test)
* The original ticket is anyway not clear about which OS was tested.

We can close confidently this ticket IMO.

**Comment by juuz0** [comment]
Hah, glad I helped. Been a long time
