### ISSUE TITLE
Problem opening a new tab

### ISSUE THREAD

**Issue by zevisvei** [kiwix/kiwix-desktop#884]
The only option to open a new tab is either by clicking on a link in the content of the article or by going back to the library and opening from there, why not have an option to open directly?

**Comment by kelson42** [comment]
There is a "+" tab!

**Comment by kelson42** [comment]
See the + tab beside the first tab 
![image](https://user-images.githubusercontent.com/1029718/189605499-f1f0e111-4dfb-4745-a515-845b8225bf04.png)

**Comment by zevisvei** [comment]
At least in Hebrew this is not the case, even when I open a new tab the tab remains empty
![צילום מסך 2022-09-12 050201](https://user-images.githubusercontent.com/101482799/189643098-06930892-e34e-43aa-8e2b-399ff8618b9c.png)

**Comment by kelson42** [comment]
Yes, you get a new tab.... what do you expect exactly?

**Comment by zevisvei** [comment]
Yes, but without the option to open anything, I want it to look like this:
![צילום מסך 2022-09-12 145956](https://user-images.githubusercontent.com/101482799/189647964-5dea3f0e-6f19-4fa2-8c01-8c0db1c14112.png)

[I did it through the library button, but I want to avoid the need for it]
