### ISSUE TITLE
Kiwix-desktop/libkiwix cutting-edge have fulltext results broken links

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#889]
I see the fulltext result, but each time I click on a link it seems the ZIM file is not readable!

![image](https://user-images.githubusercontent.com/1029718/190916646-6b1f8a1c-53e7-4bb0-a498-111662f34146.png)
![image](https://user-images.githubusercontent.com/1029718/190916669-6194638e-e478-45c0-be71-a34fecb02585.png)

**Comment by kelson42** [comment]
I'm not even sure the bug is not in `2.3.0` release as I can not test it, see #888

**Comment by veloman-yunkan** [comment]
I will take care of this issue.
