### ISSUE TITLE
Kiwix Reading List Doesn't Work on Windows 11

### ISSUE THREAD

**Issue by Kiwixiel** [kiwix/kiwix-desktop#890]
Just as the title. Kiwix x64 2.3.0, reading list is there but I can't add anything in it. Older kiwix versions I tried don't work on my laptop they don't load the zims so I hope it gets fixed soon.

**Comment by kelson42** [comment]
@Kiwixiel We have a similar bug report at #862... but we can not reproduce the bug. Woykd you be able to make a screencast?

**Comment by Popolechien** [comment]
@Kiwixiel Silly remark but did you notice that there are two "reading list" buttons on screen - one to tag a page (left, next to address bar), one to open the reading list (on the right)? I remember getting caught on this one once.
![Untitled presentation](https://user-images.githubusercontent.com/21675885/192221879-5522cfd0-7c75-4b81-91d0-0d10915384ea.png)

**Comment by Kiwixiel** [comment]
Apologies for that, I saw another ticket for "reading list" but I thought
it was for a different platform and it was weeks or months old iirc, and
anyway it didn't occur to me that it would have been better or necessary to
post there. Also another issue when I open an internal link in another tab
sometimes the search field doesn't work in the new tab? Thanks.

**Comment by kelson42** [comment]
There is aticket already open for this last point as well.

**Comment by Popolechien** [comment]
That would be #499, right?
