### ISSUE TITLE
Unable to download zim files on Kiwix 2.3.0 appimage

### ISSUE THREAD

**Issue by alrepin** [kiwix/kiwix-desktop#891]
https://i.imgur.com/RQkd8Aw.png

**Comment by kelson42** [comment]
@alrepin Difficul to say without more details, but might that be that this is a duplicate of https://github.com/kiwix/kiwix-desktop/issues/871 ?

**Comment by kelson42** [comment]
Closing, as the screenshot has disappeared because not upload here on Github.
