### ISSUE TITLE
Kiwix-desktop is not resilient to manual change in the library.xml

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#893]
The root cause is that `kiwix::Library::getArchiveById` (https://github.com/kiwix/libkiwix/blob/07ff4eab4397bc4fb208191374c1e7a6e9b1def4/src/library.cpp#L238-L252) return a nullptr if the requested book is existing in the library.xml but the archive path is invalid. (It throws a `std::out_of_range` if the bookId is not present at all in the library.xml).

But kiwix-desktop catch the `std::out_of_range` but never check if the returned archive (without exception) is not null.
This is done in several places in kiwix-desktop:
- https://github.com/kiwix/kiwix-desktop/blob/f1aafc1d9544677cdde5c3687552f2ac81ee5b3c/src/readinglistbar.cpp#L37-L40
- https://github.com/kiwix/kiwix-desktop/blob/c3eace12afdc23dfd0d839275d6e0c2d2f7de2a1/src/suggestionlistworker.cpp#L23
- https://github.com/kiwix/kiwix-desktop/blob/f1aafc1d9544677cdde5c3687552f2ac81ee5b3c/src/urlschemehandler.cpp#L44-L49
- https://github.com/kiwix/kiwix-desktop/blob/f1aafc1d9544677cdde5c3687552f2ac81ee5b3c/src/webview.cpp#L172-L176
- https://github.com/kiwix/kiwix-desktop/blob/e8478670755a1940bc8782c58bf550f69beb219e/src/kiwixapp.cpp#L241

Having a book in the library but not a valid path can be simply done by removing by hand a zim file referenced by the library.xml

In this case, the behavior is the following (at least):
- The book is not displayed in the local file. But the "All files" section do not propose to download the book but to open it. Of course, trying to open it leads to a crash as we try to use a nullptr.
- If a article in the book was bookmarked. kiwix-desktop crash at start as we try to populate the readinglist with the registered bookmark.

It **seems** that the simplest thing would be to make `kiwix::Library::getArchiveById` throw a `std::out_of_range` if the path is invalid. But I'm not sure this is the best thing to do:
- One may want to differentiate a book not in the library from a invalid path in the library, so we may throw different kind of exception
- I'm not sure that throwing a `std::out_of_range` would fix the strange behavior of not displaying the book in the local files but not being able to download the book again.
- We probably need to do some behavior specification to know what to do when we face this case: Ignore the book but keep it in the library (can be pretty useful if the file is one a removable drive that can be temporally missing) or remove it from the library ? Do we propose to the user to download a book if it is already in the library ?

Please note that the behavior of returning a nullptr is pretty old (if it is not the initial behavior).
Throwing a exception if the book is not in the library is a relatively new behavior (libkiwix 11)
Previous version of kiwix-desktop was checking for the nullptr but the check has been removed in favor of try/catch when moving to libkiwix 11.

**Comment by veloman-yunkan** [comment]
> * If a article in the book was bookmarked. kiwix-desktop crash at start as we try to populate the readinglist with the registered bookmark.

This manifestation of the bug has been custom-fixed in #1092 and is now being undone by #1096 in favour of a more general fix.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan I believe the riht behaviour is that it is part of the library but with an error state (not readable, not there, corrupted, …). Visually it should be visible but full greyed (like online books which can not be downloaded). It should only be possible to remove it from the library.

**Comment by veloman-yunkan** [comment]
In order to implement that, I am going to introduce the concept of book states. In the simplest approximation a book can be only in one of the following states:

1. Missing locally but (believed to be) available online
2. Downloading (we may also need an auxiliary state "preallocating the ZIM file" to be able to work around issues like those mentioned in #1094)
4. Download paused by the user
5. Download stopped due to an error
6. (Believed to be) available locally and healthy
7. Registered in the local library, but there is an error with the ZIM file:
  a. ZIM file is missing
  b. ZIM file is not readable
  c. ZIM file is corrupted
  d. etc

For each state a set of actions applicable to a book in that state is defined. When an action is carried out on a book the outcome may result in the state of the book changing.

Does it make sense?

**Comment by kelson42** [comment]
Fix completed by https://github.com/kiwix/kiwix-desktop/pull/1098
