### ISSUE TITLE
Kiwix Server Installation for Ubuntu 14.01.5

### ISSUE THREAD

**Issue by KaranBhart** [kiwix/kiwix-desktop#9]
Unable to Install Kiwix Server Installation for Ubuntu 14.01.5

**Comment by KaranBhart** [comment]
Please send me the steps to setup kiwix server at ubuntu 14.04.5   32-bit

**Comment by KaranBhart** [comment]
Hi,

 

     I have followed the following commands and getting an error:-

 

Issue èAfter Excecuting Step 5 . I am getting an error:image/library/kiwix-serve:latest not found

 

 

Step 1: Download some ZIM files

FTP site with ZIM files <https://ftp.fau.de/kiwix/zim/> .

Here are some smaller ones for testing:

1.	Assamese Medical Wikipedia (23 MB) <https://ftp.fau.de/kiwix/zim/wikipedia/wikipedia_as_medicine_2017-08.zim> 
2.	English Wikipedia Bollywood Articles (265 MB) <https://ftp.fau.de/kiwix/zim/wikipedia/wikipedia_en_bollywood_2017-01.zim> 
3.	Simple English Wikipedia w/ No Pictures (159 MB) <https://ftp.fau.de/kiwix/zim/wikipedia/wikipedia_en_simple_all_nopic_2016-08.zim> 

Step 2: Move the ZIM files to the 'zim' directory

# inside the folder where you downloaded the ZIMs (e.g. ~/Downloads)

$ mkdir -p ./dockerized-kiwix-server/zims

$ cp *.zim ./dockerized-kiwix-server/zims

Step 3: Build the Docker container

This will create the Linux machine, download the Kiwix tools (including kiwix-serve), copy the ZIMfiles over, then create the Kiwix library XML file.

$ pwd # -> ./dockerized-kiwix-server

$ docker build -t kiwix-serve .

Step 4: Run the container

This starts the container and the Kiwix server, and makes it available on your machine at http://localhost:8080.

$ docker run -p 8080:8080 kiwix-serve

To turn it off:

$ docker ps # -> find the container id

$ docker stop <container id>

Step 5: Try it out in the browser

Go to http://localhost:8080.

 

 

 

Best Regards

Karan Bharti

**Comment by kelson42** [comment]
The Docker stuff is not our stuff AFAIK. We provide kiwix-serve in the kiwix-tools statically compiled tarballs available here: https://download.kiwix.org/release/kiwix-tools/. The documentation is available here http://wiki.kiwix.org/wiki/Kiwix-serve

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-tools#190
