### ISSUE TITLE
Top text moved into the lead

### ISSUE THREAD

**Issue by uxelar** [kiwix/kiwix-desktop#900]
Why are the short texts at the top of many articles online moved into the lead section in Kiwix? It doesn't feel so smooth where it is located now, inside the text. Why not keep it at the top?

Kiwix: kiwix-desktop_windows_x64_2.3.0
Zim: wikipedia_en_all_maxi_2022-05.zim

![Kiwix](https://user-images.githubusercontent.com/117523906/200123946-4f56e6ac-a9e8-400a-9904-bed431a04b7d.png)

**Comment by kelson42** [comment]
There has been a ticket open about that at scraper level a long time ago https://github.com/openzim/mwoffliner/issues. I can not find it anynore. But, in a Nutshell, this is how the Wikipedia backend delivers the content in the API we use and this is not a bug (we have checked with them). Unfortunate I can not find the ticket...

**Comment by kelson42** [comment]
Here it is https://github.com/openzim/mwoffliner/issues/182
