### ISSUE TITLE
Please create a build for 32bit Linux.

### ISSUE THREAD

**Issue by tinkersaur** [kiwix/kiwix-desktop#903]
If anybody has an old 32bit computer, it would make much more sense to install Linux on it, rather than old windows such as Windows XP, or Vista. I have used Raspberry Pi for i386 and it works great on a tiny laptop with 1GHz CPU/1GB RAM. I downloaded that distro from this webpage: https://www.raspberrypi.com/software/raspberry-pi-desktop/  -- see the last link on that page.

Therefore I would like to ask for 32bit Linux build for kiwix-desktop. Either a Debian package of an appimage would be great. I think Debian Package would be smaller. Thank you!

**Comment by kelson42** [comment]
There is Debian package for i386 https://ci.debian.net/packages/k/kiwix/. But in general we don't invest resources on this very old architecture... but if someone wants to do the additional work, no problem.
