### ISSUE TITLE
Search capability not working with zim file

### ISSUE THREAD

**Issue by markknit** [kiwix/kiwix-desktop#906]
I'm running Kiwix-serve on an offline Ubuntu (18) education server that has about 10 modules loaded. All of them support a search capability, but one does not - Boundless. When I try a search I always get an empty result. I used the kiwix-search module against the zim file, and it works fine. However, when I look at the source code it appears to be using a php search tool, while all of the other modules are using a native kixix-search tool. The php tool is clearly not working, although I do have Php loaded and running with other apps.

Is there a way to fix this? I assume the actual web page is embedded in the Zim, so I can't easily replace the search module section. Any suggestions?

Mark K

**Comment by kelson42** [comment]
@markknit We don't provide any software using php, so no really sure if there is really a problem with Kiwix.

Boundless ZIM file is available online via kiwix-serve at https://library.kiwix.org/viewer#courses.lumenlearning.com_en_all_2021-03/A/courses.lumenlearning.com/catalog/boundlesscourses.

Do you still see the issue there? If yes, what do you type exactly in the search box?

**Comment by kelson42** [comment]
No feedback unfortunately. I have to close the ticket.
