### ISSUE TITLE
"Open file" file picker is not displayed "on the top".

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#91]
The file picker to open a ZIM file is created and available, but it is in the background instead of being in the foreground like it should.

Tested with beta2 flatpack.

**Comment by kelson42** [comment]
Looks like this has been fixed. I can not reproduce it.

**Comment by kelson42** [comment]
No, it is not.

**Comment by mgautierfr** [comment]
On what are you testing ? Still flatpak ?

**Comment by kelson42** [comment]
@mgautierfr Yes

**Comment by jetownfeve21** [comment]
it's strange, on mu ubuntu 18.04 it only appends if I lauch kiwix-desktop flatpak with a command line.
If I launch the flatpak directly by the app launcher it works

**Comment by kelson42** [comment]
@jetownfeve21 At least you have a reprocase. Have you been able to fix it?

**Comment by jetownfeve21** [comment]
According to the Qt documentation, the filedialog should be on top, I don't know why it is not always the case.
![image](https://user-images.githubusercontent.com/47149116/64428249-94761200-d0b3-11e9-8744-0e0f2984c5b1.png)

https://github.com/kiwix/kiwix-desktop/blob/384cbf0e81c9af03a5aacf27f479d7cb15728bfd/src/kiwixapp.cpp#L135-L145

**Comment by kelson42** [comment]
I can confirm the bug is still there in 2.0.5. Maybe @asashnov you have an idea?

**Comment by kelson42** [comment]
It seems to be fixed now, unsure if this is due to ne new style of dialog or if this is because of Qt 5.15.
