### ISSUE TITLE
Added ZIM does not show up in the library

### ISSUE THREAD

**Issue by Boruch-Baum** [kiwix/kiwix-desktop#910]
In debian, using appimage files "_kiwix-desktop_x86_64_2022-12-15.appimage_" or "_kiwix-desktop_x86_64_2.3.1.appimage_", File **diy.stackexchange.com_en_all_2022-05.zim** can be viewed but is not able to be added to the list of available collections.

This is specific to the aforementioned file, so it seems to be something malformed in it, or some bug in the parsing of it. Performing "_kiwix-manage library.xml show |less_" **does** show that the file is added to the xml. I have an old archived version of the diy zim file from year 2018, which does not exhibit this error.

I've tried the following:
1. launch the appimage
2. add the zim file using the GUI
3. the file is viewable and searchable in the created tab
4. Change to the 'first' tab, the one with the list of collections.
5. search (unsuccessfully) for a "diy" or "home improvement" collection
6. close the diy tab
7. . Change to the 'first' tab, the one with the list of collections.
8. search (unsuccessfully) for a "diy" or "home improvement" collection
9. launch the server from the GUI
10. search (unsuccessfully from the web interface
11. close the server and the GUI
12. delete the library.xml file
13. repeat steps 1 to 11
14. delete the library.xml file
15. use the command line "_kiwix-manage library.xml add_" to add several collections, including the diy file.
16. launch the appimage
17. search (unsuccessfully) for a "diy" or "home improvement" collection
18. the other added collections **are** available

**Comment by Boruch-Baum** [comment]
I think I may have figured this out. If you take a look at the xml being generated for the diy file, you'll notice that the 'language' is set to 'diy'. With the kiwix proceses closed/killed, I manually changed it to 'eng' and then the bug seems fixed. In order to continue this. verify this, I downloaded several Hebrew language files. They **ALL** also exhibited the same bug, and when manually editing the xml to change the language to "eng" the bug is repaired.

So, this ends up being strange, as it seems to mean that all non-English files aren't listed? How could I be the first one to notice this, with all the non-english collections and speakers worldwide out there?

If you verify this, you might want to change the title of the bug appropriately.

**Comment by kelson42** [comment]
@Boruch-Baum Thank you for the bug report, I will try to reproduce it.

**Comment by mgautierfr** [comment]
> I think I may have figured this out. If you take a look at the xml being generated for the diy file, you'll notice that the 'language' is set to 'diy'

This is surprising, what is the real language of `diy.stackexchange.com_en_all_2022-05.zim` ? `diy` or `eng` ?


Else, I think it is a duplicated of https://github.com/kiwix/kiwix-desktop/issues/902, kiwix-desktop is displaying only `eng` files by default. This is why if you change by hand the lang to `eng` it is displayed.

**Comment by kelson42** [comment]
@Boruch-Baum I can not reproduce the problem, I guess it has been meanwhile fixed one way or the other. @Boruch-Baum I guess if you use the [latest nightly](https://download.kiwix.org/nightly/2023-08-12/kiwix-desktop_x86_64_2023-08-12.appimage) you wont' have the problem either. Please reopen if you still suffer of it.
