### ISSUE TITLE
Kiwix by default shows only ZIM files with the system language

### ISSUE THREAD

**Issue by gmikhail** [kiwix/kiwix-desktop#911]
I downloaded several ZIM files, placed them in a folder and set it in the settings as "Monitor directory". But after each launch I have to manually turn off language filter (Browse By Language -> All) because only one ZIM file in the system language is displayed.

![](https://i.imgur.com/qjtyxw7.png)

Obvious bug. Make the language filter disabled by default (as other filters) or at least make sure that it is saved and not reset after each restart.

Version: 2.3.1
Windows 10 Pro 22H2 (build 19045.2364)

**Comment by gmikhail** [comment]
I noticed the same bug when creating a local server.

1. Launch Kiwix with several ZIM files in different languages.
2. Start local server (Ctrl+I).
3. Open the server address in the browser in incognito mode (it is important that no preferences are saved in the browser). By default, the system language will be selected, although the expected behavior is that all filters should be disabled by default and display all available libraries (they are called "books" in the web interface).

![](https://i.imgur.com/rPapAW5.png)

PS: also, it makes sense to hide "?lang=" part in the URL when all languages selected because this empty parameter is useless.

**Comment by kelson42** [comment]
@gmikhail Here we have two bug reports in one, please try to avoid this situation.

In general the wanted behaviour is:
* Default language is language of the reader: OS language for kiwix-desktop, and browser language for the server.
* If changed then this should be kept

For kiwix-desktop, this is already tracked with #902 and for kiwix-desktop it works already as expexted.

If you see another oddity with the server, please open a ticket in kiwix/kiwix-tools.
