### ISSUE TITLE
Missing links to topics on the main page in the Ukrainian Wikipedia / ZIM file generation bug

### ISSUE THREAD

**Issue by gmikhail** [kiwix/kiwix-desktop#914]
**Note: this bug is not related directly to the program, but describes a bug in the ZIM file. If there is a better place for it, please move this issue. Thanks.**

The last ZIM file of the Ukrainian Wikipedia is missing links to topics on the main page. Instead, they are plain text:

![](https://i.imgur.com/Tet9g4V.png)

This is what it looks like on Wikipedia:

![](https://i.imgur.com/HOpPT9Y.png)

ZIM: https://mirrors.dotsrc.org/kiwix/zim/wikipedia/wikipedia_uk_all_maxi_2022-12.zim

**Comment by kelson42** [comment]
If this would be a bug, then this would be a bug with mwoffliner: the scraper. but here these links point to articles which are simply not part of the  ZIM snapshot. Probably categories that we don’t scrape yet, see https://github.com/openzim/mwoffliner/issues/829.
