### ISSUE TITLE
Error by reading dev Phets ZIM file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#915]
With the file:
https://mega.nz/file/PYtnlIZB#cjqIOZ0wQNRRfrkFjDyW61_vMaDeOiLiuA1Iq04G_Xg

I get:
![image](https://user-images.githubusercontent.com/1029718/210133235-c0d17fae-c038-46c1-9859-bbb1406c8f63.png)

and on the console:
```
./kiwix-desktop /home/kelson/Downloads/phet_mul_2022-12\(1\).zim 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
add widget
js: The key "target-densitydpi" is not supported.
js: Fetch API cannot load zim://fbd2f790-5d36-fccc-df2d-c22f94be3a69.zim/-/en.json. URL scheme "zim" is not supported.
js: Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by rgaudin** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=522370#c26

**Comment by kelson42** [comment]
Would be interesting now to know from which version of Qt it is available.

**Comment by rgaudin** [comment]
Just looking at https://en.wikipedia.org/wiki/Qt_version_history I'd say 6.3+

**Comment by kelson42** [comment]
Available only in Debian bookworm/unstable https://packages.debian.org/bookworm/qt6-base-dev

**Comment by rgaudin** [comment]
Don't we bundle it with kiwix-desktop?

**Comment by kelson42** [comment]
@rgaudin No, this is forbidden by Debian, see https://packages.debian.org/unstable/kiwix

**Comment by rgaudin** [comment]
I understand for debian but what's inside those 100MB+ package if not Qt ?
http://download.kiwix.org/release/kiwix-desktop/?C=M;O=D

**Comment by kelson42** [comment]
@rgaudin Yes, in our own portable package, this is embeded and there should be no problem.

**Comment by kelson42** [comment]
Blocked by https://github.com/kiwix/kiwix-build/issues/594
