### ISSUE TITLE
Downloading a book keeps failing

### ISSUE THREAD

**Issue by Wild-Chicken** [kiwix/kiwix-desktop#916]
![image](https://user-images.githubusercontent.com/96213936/210116829-b5fc20f5-522c-4e6f-b6a4-58cd474627c4.png)

I'm not really tech-savy so I don't really know why it's failing or anything.

**Comment by kelson42** [comment]
@Wild-Chicken I have moved to the proper bug tracker. In your screenshot, I see that you have a download running, so the problem does not happen all the time I guess. Which content exactly fails?

**Comment by Wild-Chicken** [comment]
All of Wikipedia fails, the download starts a little bit, barely, and then it tells that the download failed

**Comment by Wild-Chicken** [comment]
Actually I'm unsure but, I'm trying to download the Wikipedia with pictures and the normal Wikipedia, those are the only ones that seem to fail

**Comment by Wild-Chicken** [comment]
The only thing I can think of that would make it fail is disk space.
![image](https://user-images.githubusercontent.com/96213936/210240408-ced221c8-f837-453a-9c00-9f68a86e41d2.png)

**Comment by kelson42** [comment]
Loks like massive network problems to download big contents. I would recommend to download the conteent via BitTorrent and using an external download client. Look at https://library.kiwix.org to get the BitTorrent download links.

**Comment by kelson42** [comment]
> The only thing I can think of that would make it fail is disk space.
> 
> ![image](https://user-images.githubusercontent.com/96213936/210240408-ced221c8-f837-453a-9c00-9f68a86e41d2.png)
> 
> 

Ok, then the problem is clear... but the error message is not.

**Comment by Wild-Chicken** [comment]
What do you mean?

**Comment by Wild-Chicken** [comment]
It fails at only 100 MB and I have 2.5 GB (I'm trying to store it on a removable drive, E:)

**Comment by Wild-Chicken** [comment]
What I mean is that I think that it's trying to store on %temp%, and not my removable drive first.

**Comment by Wild-Chicken** [comment]
Oh sorry I didn't look at your other comment.

**Comment by Wild-Chicken** [comment]
Sorry where do I find BitTorrent?
![image](https://user-images.githubusercontent.com/96213936/210243760-7763c008-a26d-4970-a959-5debf8f588d4.png)

**Comment by Wild-Chicken** [comment]
Or should I search it up?

**Comment by Wild-Chicken** [comment]
I couldn't find BitTorrent there on your link so I searched it up and found it.
![image](https://user-images.githubusercontent.com/96213936/210244010-55fc347f-ad53-40cc-9e6d-bec2ecb6fc1f.png)

**Comment by Wild-Chicken** [comment]
not gonna lie i'm actually tired of getting "virus" popups
![image](https://user-images.githubusercontent.com/96213936/210244182-2805cd05-51e2-4e22-bd04-5b139ba4cfa7.png)

**Comment by Wild-Chicken** [comment]
OH NOW I GET IT
![image](https://user-images.githubusercontent.com/96213936/210245376-d7045d56-606a-4eb7-8cfc-5a31fe04bf62.png)

**Comment by Wild-Chicken** [comment]
Where do I find the BitTorrent link?
![image](https://user-images.githubusercontent.com/96213936/210246250-5b401ea7-bd76-46ce-b304-615a33e326d2.png)

**Comment by Wild-Chicken** [comment]
Oh i found it

**Comment by kelson42** [comment]
> What do you mean?

You have not enough free space on C: to download any big content.

**Comment by Wild-Chicken** [comment]
I want to download it on a removable drive

**Comment by kelson42** [comment]
@Wild-Chicken can you please mAke a screenshot of the settings dialogue?

**Comment by TroudhuK** [comment]
He's right, the portable version isn't portable at all, the aria2c.exe commands tries to use %appdata%\kiwix (--dir, --input-file and --save-session).

**Comment by kelson42** [comment]
@Wild-Chicken I will make a ground check to verify if the settings is not taken in account properly in aria2c command line call.
@TroudhuK Nice/funny nickname ;)

**Comment by Wild-Chicken** [comment]
sorry i've been out for a day

**Comment by Wild-Chicken** [comment]
also i never knew i could download kiwix on a portable drive

**Comment by Wild-Chicken** [comment]
![image](https://user-images.githubusercontent.com/96213936/210778678-033a930c-c8fe-45c4-b635-f7ac3a2d5dad.png)

**Comment by kelson42** [comment]
@Wild-Chicken This is Kiwix JS, an other version of Kiwix. Why are you putting this screenshots here?

**Comment by Wild-Chicken** [comment]
i-

**Comment by Wild-Chicken** [comment]
ok

**Comment by wrstlrlp13** [comment]
@kelson42 - Just as a heads up, it's some kind of timing issue. If I spam click download, eventually it works, I'm guessing maybe ya'll need to put a 'wait' in place for the aria2c.exe or something.

**Comment by kelson42** [comment]
@veloman-yunkan Do we have some kind of security to avoid spam clicking?

**Comment by wrstlrlp13** [comment]
No, spam clicking it MAKES it work. Just clicking it once, it fails.

**Comment by kelson42** [comment]
@Wild-Chicken Out of curiosity, have you tried with latest nightly? https://download.kiwix.org/nightly/
@veloman-yunkan I would first complete https://github.com/kiwix/kiwix-desktop/pull/919 before looking at this.

**Comment by wrstlrlp13** [comment]
![image](https://github.com/kiwix/kiwix-desktop/assets/37849960/c3ae49d5-ae8e-4f12-9a20-3527cd232744)

In case you want info on the system.

**Comment by wrstlrlp13** [comment]
Some more information for ya'll.

This is what my Local C app data looks like after I got the download to start, paused and stopped them to change the location. 
![image](https://github.com/kiwix/kiwix-desktop/assets/37849960/07d08f55-de2d-45e1-9aa8-52debd431ec0)

If I try to copy those wikipedia files to my external drive, I get an errror saying there isn't enough space. But my D drive has 232 GB of free space... The math is not math'ing.

![image](https://github.com/kiwix/kiwix-desktop/assets/37849960/762c51c5-07f3-4d70-b052-a5265bdc13f4)

@kelson42

**Comment by wrstlrlp13** [comment]
Downloading to my C drive appears to be working... So maybe it's an issue with an External Drive. Will try to copy the files over once they're fully downloaded.

**Comment by kelson42** [comment]
We are just about tackling this ticket. We have fixed many things on the download procedure, maybe you could give a try with a nightly? https://download.kiwix.org/nightly/ ?

**Comment by TroudhuK** [comment]
> He's right, the portable version isn't portable at all, the aria2c.exe commands tries to use %appdata%\kiwix (--dir, --input-file and --save-session).

Nothing changes about it, it doesn't work.

**Comment by veloman-yunkan** [comment]
@kelson42 There seem to be multiple issues behind this ticket and #1118 definitely doesn't address all of them. In particular, the error message in [one of the updates to this ticket](https://github.com/kiwix/kiwix-desktop/issues/916#issuecomment-1837527681) suggests that a file larger than 4GiB was being saved to a FAT32 filesystem. #1118 doesn't have anything to do with it.

**Comment by kelson42** [comment]
@veloman-yunkan Remotes bookwhich can not be downloaded (too big for the free space, unappropriate fs, ...) should be greyed. Is that not something which is already implemented?

**Comment by veloman-yunkan** [comment]
@kelson42 There is no disabling/greying out of downloads that exceed the available storage requirements. An error is reported during the attempt to start such a download. And I think that the ability of the target file system to host such a file is not checked.

**Comment by kelson42** [comment]
I believe there is nothing much here to do. We belive to have fixed the problem and completiong will be total once #1148 will be implemented. Release `2.4.0` will happen soon and make it available for end-users. @Wild-Chicken and @wrstlrlp13 Thank you for reporting and your support.
