### ISSUE TITLE
Use http scheme instead of zim in our internal links.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#917]
kiwix-desktop use a specific scheme `zim://` in the webview to reference content provided by our `urlschemhandler`. This allow a well defined separation between http content which link to actual online content (which should be catch/blocked/opened with web browser) and our internal content which need a url.

However, few features (as service worker https://github.com/kiwix/kiwix-desktop/issues/487 or Phet zim file https://github.com/kiwix/kiwix-desktop/issues/915) need a `http://` scheme.

We should rethink how we build our internal urls and use http scheme all the time. (Use a specific host to reference internal content ?)

**Comment by kelson42** [comment]
@mgautierfr We have custom protocol handler on Android. We shozld keep it here, bit implement it in a way it works.

**Comment by mgautierfr** [comment]
I don't want to launch a http daemon. I want to change the scheme of the url from `zim://` to `http://`. Simply because a lot of technologies in the web word expect `http://` and using `zim://` breaks things.

**Comment by kelson42** [comment]
AFAIK nothing expect here the `http://` scheme (we have no URL of that type in ZIM files) and it would be abusing the HTTP protocol to provide ZIM access using it.

**Comment by mgautierfr** [comment]
In #915, I understand that ` Fetch API cannot load zim://fbd2f790-5d36-fccc-df2d-c22f94be3a69.zim/-/en.json. URL scheme "zim" is not supported.` means that the js content of the libzim itself refuse to load things using the zim scheme. It is not us refusing the request.

**Comment by kelson42** [comment]
@mgautierfr After reading [this](https://blogs.igalia.com/jfernandez/?s=Custom+handlers) I was somehow under the impression, the problem has been fixed recently.

**Comment by kelson42** [comment]
Considering that both#487 and 915 have been closed, this issue has lost its justification
