### ISSUE TITLE
Kiwix-desktop on Ubuntu 22.04 after using kiwix-build and manual build.

### ISSUE THREAD

**Issue by Martinc4321** [kiwix/kiwix-desktop#918]
(Using kiwix-build all test were OK)
Copied all stuff form INSTALL to /usr

Output from terminal:
```
$ kiwix-desktop 
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Aborted (core dumped)
```

Please ask for any additional information. 
Context: On Ubuntu there is nothing, but kiwix related stuff, because i want to use my laptop as offline lib. Extension in Firefox is working however JS ZIMs does not load in it.

**Comment by Jaifroid** [comment]
> however JS ZIMs does not load in it

@Martinc4321 As I am a developer of the extension version, could you kindly say which JS-based ZIMs aren't working for you, and did you ensure the extension is running in ServiceWorker Mode?

**Comment by kelson42** [comment]
@mgautierfr Any clue what is going on here?

**Comment by mgautierfr** [comment]
Are you able to run kiwix-desktop from `INSTALL/bin/` ?

**Comment by kelson42** [comment]
@Martinc4321 any feedback?

**Comment by kelson42** [comment]
No feedback, closing
