### ISSUE TITLE
Where i can find the downloaded files on Linux?

### ISSUE THREAD

**Issue by Ud4ba** [kiwix/kiwix-desktop#924]
Hello, im having some issues running Kiwix on old 32bit system on Debian stable.(outdated) When trying to search something app freezes , cpu consumption locks to 50% and nothing happens. When trying to relaunch app , it just launches a black page.
I have to wait for the latest update , though because the files catch up a lof o size where i can find them under Linux system? Thanks in advance.

**Comment by mgautierfr** [comment]
If you haven't change the default location, it should be in `~/.local/share/kiwix`
