### ISSUE TITLE
Opening a local file (with the file picker) does not update local library immediatly

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#93]
1 - go to local library
2 - open a local ZIM file with the file picker (so local file is not listed in the local library)
3 - file is open a welcome page of the ZIM is displyed
4 - Click on the library tab
5 - file is not listed in the local library

It should...

Test with Flatpak package of beta2

**Comment by soloturn** [comment]
after downloading it does not show up in local library with beta2 flatpak. just in case this is the same issue.

**Comment by jetownfeve21** [comment]
@kelson42 I can't reproduce this bug
tested with the master branch and the appimage 2.0-rc1

**Comment by kelson42** [comment]
Me neither.
