### ISSUE TITLE
 DEPRECATED const std::string& getLanguage() 

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#930]
```
src/contentmanager.cpp: In member function ‘QStringList ContentManager::getBookInfos(QString, const QStringList&)’:
src/contentmanager.cpp:50:85: warning: ‘const string& kiwix::Book::getLanguage() const’ is deprecated [-Wdeprecated-declarations]
   50 | #define ADD_V(KEY, METH) {if(key==KEY) values.append(QString::fromStdString((b->METH())));}
      |                                                                              ~~~~~~~^~
src/contentmanager.cpp:77:9: note: in expansion of macro ‘ADD_V’
   77 |         ADD_V("language", getLanguage);
      |         ^~~~~
In file included from src/library.h:4,
                 from src/contentmanager.h:6,
                 from src/contentmanager.cpp:1:
/usr/local/include/kiwix/book.h:82:33: note: declared here
   82 |   DEPRECATED const std::string& getLanguage() const { return m_language; }
      |                                 ^~~~~~~~~~~
```

Should be replaced/updated.

**Comment by mgautierfr** [comment]
There is two ways to solve this:
- The naïve way: replace `getLanguage` by `getCommaSeparatedLanguages`.
- The correct way: use `getLanguages` (which return a list of languages) and adapt the ui/behavior of kiwix-desktop to handle zim files with several languages.

Of course, I prefer the correct way.

**Comment by thestarsahil** [comment]
QStringList ContentManager::getBookInfos(QString fileName, const QStringList &keys)
{
    QStringList values;
    auto b = std::make_unique<kiwix::Book>(fileName.toStdString());

    for (const auto &key : keys) {
        if (key == "title") {
            values.append(QString::fromStdString(b->getTitle()));
        } else if (key == "author") {
            values.append(QString::fromStdString(b->getAuthor()));
        } else if (key == "language") {
            values.append(QString::fromStdString(b->language()));
        }
    }
    return values;
}

@kelson42 I hope this might help !

**Comment by kelson42** [comment]
@thestarsahil Please make a PR if you have a fix.

**Comment by mgautierfr** [comment]
@thestarsahil How it could help ?

**Comment by kelson42** [comment]
@juuz0 Hi, is that something you could quickly fix?

**Comment by juuz0** [comment]
This key is not used anywhere in current state of kiwix-desktop, we can also remove this - and add later (with modifications) if/when needed.

> Hi, is that something you could quickly fix?

```
        if (key == "language") {
            auto langStdVector = b->getLanguages();
            QStringList langList;
            for (const auto& lang : langStdVector) {
                langList.push_back(QString::fromStdString(lang));
            }
            QString s = langList.join(", ");
            values.append(s);
        }
 ```
 
 We can do this (similar to tagList) but content manager only needs these keys: https://github.com/kiwix/kiwix-desktop/blob/4e51485f8eb23ee9a5014e493df1a7944ac3f3ed/resources/js/_contentManager.js#L25
 
 Wouldnt just removing this unnecessary line be enough?
 
 @kelson42 @mgautierfr

**Comment by juuz0** [comment]
> I wonder how "Browse by language" works if this property of the books is not used.

In my understanding, the languages and categories for filters are a static list (irrespective of what books are in library).
Removing the key from `getBookInfos` (this function is only used by vue.js and it doesn't display language anywhere in the library) shouldn't be a problem & all the ZIM language features should work properly. The property isn't really used.

**Comment by mgautierfr** [comment]
Indeed, we don't use the "language" key.
We can remove it as @juuz0 suggests.
