### ISSUE TITLE
Unable to launch installer

### ISSUE THREAD

**Issue by Moordok314** [kiwix/kiwix-desktop#933]
I downloaded the windows installer on the "Kiwix for Raspberry Pi" page, however when I try to run the "kiwix-hotspot-win64-2.4.12" file on my Windows 11 machine, I receive the following error:
"
Failed to execute script '__main__' due to unhandled exception: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
"

**Comment by kelson42** [comment]
I have transfered your ticket to https://github.com/offspot/kiwix-hotspot/issues/675
