### ISSUE TITLE
Don't use a static list of language/categories in the catalog filtering.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-desktop#934]
When we have added the language selector, the catalog hadn't the language list feature.
So we've set a fixed list of languages in kiwix-desktop.

When next version of libkiwix will be released, catalog will have a API to get the list of languages and categories. We should use it.

**Comment by juuz0** [comment]
The API in question must be `/catalog/v2/languages`?

**Comment by mgautierfr** [comment]
There is two use cases:
- Exploring the remote catalog, we must use `/catalog/v2/languages`
- Exploring the local catalog (local zims), we should use the c++ api `Library::getBooksLanguages`.

(Of course, the same for categories)
