### ISSUE TITLE
Hotspot Installer Content Catalog Fail

### ISSUE THREAD

**Issue by mikejfeser** [kiwix/kiwix-desktop#941]
![image](https://user-images.githubusercontent.com/60615050/236714858-01a80b1c-9c9a-4035-a143-59308e0efe46.png)
![image](https://user-images.githubusercontent.com/60615050/236714898-48e0498a-0759-4232-af2e-506e67c27e4e.png)

Hello,

When running the hotspot installer, I am unable to load static content. It warns that I should check internet/proxy settings, however, when going to proxy settings and test connection, I can confirm that I can reach the Kiwix servers. Any assistance would be much appreciated!

**Comment by kelson42** [comment]
This is a ticket for https://github.com/offspot/kiwix-hotspot, I will move it.
