### ISSUE TITLE
Library error: Language option weird

### ISSUE THREAD

**Issue by Rexadev** [kiwix/kiwix-desktop#943]
![image](https://github.com/kiwix/kiwix-desktop/assets/62152714/1f3bea9e-2017-46fa-a5fb-9e85c74ebd72)

**Comment by kelson42** [comment]
@Rexadev Do you use kiwix-serve or the server version of kiwix-desktop? I believe this is a duplicate of https://github.com/kiwix/libkiwix/issues/908 and therefore fixed and released for kiwix-serve and in [nightlies](https://download.kiwix.org/nightly/) for kiwix-desktop. Can you please confirm?

**Comment by Rexadev** [comment]
@kelson42 screenshot is og the library website
