### ISSUE TITLE
module 'os' has no attribute 'sync'

### ISSUE THREAD

**Issue by Moordok314** [kiwix/kiwix-desktop#944]
After the last zim file copies in stage 4/6 of the instillation, I receive the following error and then the instillation terminates. I am running windows 11 pro if that helps. 

![kiwix-install-failed](https://github.com/kiwix/kiwix-desktop/assets/98748897/09e28bc2-d285-4107-b637-f80ee6876898)

**Comment by mgautierfr** [comment]
This to be a bug for kiwix hotspot. (ping @rgaudin)
