### ISSUE TITLE
Slow downloads on a fast connection

### ISSUE THREAD

**Issue by rickmacgillis** [kiwix/kiwix-desktop#948]
Hi guys. First, thank you for making so much content freely available to all. I don't know if the server is having issues with bandwidth, or what's going on, but all day today I've been trying to download Wikipedia, but with only slow speeds.

I've tried downloading them directly from https://download.kiwix.org/zim/ using Chrome, then I tried the associated torrent on https://wiki.kiwix.org/wiki/Content_in_all_languages (2 seeds with incomplete data), and of course I've tried using the latest AppImage (2.3.1) to download it through the interface. All of the downloads aside from Bittorrent, are coming from the same slow server.

Is there anything that can be done about this issue? Maybe there's a mirror somewhere that's faster?

**Comment by kelson42** [comment]
Wich ZIM file URL exactly are we talkin about? Wich slow speed are we exactly talking about?

**Comment by rickmacgillis** [comment]
It seems to be going faster today according to the 6MB/sec download speeds on Firefox. The file was https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2023-05.zim

Probably best to leave this open for a couple days to see if it happens again so we can catch it, though. The file did download successfully overnight using Kiwix, and I plan to download more files today.

**Comment by Popolechien** [comment]
@rickmacgillis Thanks. Do you have (or remember) a ballpark figure as to what the download speed was, and can we ask in which region you are based (US West/East, Europe, Asia, etc.)?

**Comment by rickmacgillis** [comment]
Update: I just found a file that downloads slow. (500KB/sec on FF) Wikipedia downloads normally, though.

Here's the one that's slow: https://download.kiwix.org/zim/stack_exchange/chemistry.stackexchange.com_en_all_2023-05.zim

**Comment by kelson42** [comment]
@rickmacgillis A download is slow can come from many factors, part of them are not under our control.

On Kiwix side we do all what we can do to garanty (1) the integrity of the files downloaded (2) a good speed of the downloads.

To do so we basically rely on file checksums and downloading from many sources. You can have a similar experience using Metalink or BitTorrent to download ZIM files through a thirst party solution. If you don't do so, then anything can happen, this is why we don't recommend it.

.Regarding the StackExchanges files and the US, we have no hosting on that continent, so it comes from Europe servers, and I guess this is the main reason why it is slow. As a reminder we rely on voluntereed bandwidth and storage to host mirrors of download.kiwix.org.

There is nothing we can do here, and for sure not in Kiwix Desktop, at middle term we want to better measure and audit download speed from different parts of the world to help diagnostic and fix this kind of problems... but this is another topic.

Closing as there is nothing concrete we can do.
