### ISSUE TITLE
Kiwix crashes when file fails to download sometimes.

### ISSUE THREAD

**Issue by rickmacgillis** [kiwix/kiwix-desktop#949]
I've found that Kiwix crashes and leaves the environment dirty, then the next time I load it, it tries to download multiple copies of the files that failed. Eventually it just doesn't open, and there's no debug data when loading it from the console.

Here's an in depth look at what's going on: https://www.loom.com/share/77b17f14bba440d2a80c0e9fcb356931

LMK what other data you need. `.config`, which I've mentioned in the video, just stores the download path data for the settings screen, so that's not it.

**Comment by mgautierfr** [comment]
There is a lot of things in you video, it would have been better to open different issues for each point.

- kiwix not opening: This is probably a issue with the "feature" of opening only one window and forcing kiwix to quit. You probably have a pipe somewhere open and the "launch" of kiwix-desktop only send a message (through the pipe) to the "supposed" already opened windows to load a file.
- Yes, we use aria2c to download zim files for us. And yes, it may come from bittorent.
- aria2c save its session to restart the download later (so you can quit kiwix-desktop even if download is not finished). The file should be `~/.local/share/kiwix/kiwix.session`. If you delete this file, aria2c should not try to download again the file.

**Comment by rickmacgillis** [comment]
A restart cleared the pipe and I deleted the session. It opens now, but I'll need to be home to see if that fixed the multiple downloads issue for the same file.

**Comment by rickmacgillis** [comment]
Yes that got rid of the duplicate downloads, too.
