### ISSUE TITLE
Wrong "Not enough storage available" error

### ISSUE THREAD

**Issue by ShuffleBit** [kiwix/kiwix-desktop#950]
Version 2.3.1 flatpack on Linux Mint 21.2

I installed the flatpack version because Reddit thinks this is fixed in 2.3.1, while the PPA version is older and exhibited identical behavior.

The desired destination, in this case, /localmedia/Kiwix, has 4.8TiB available, which is owned & 07 (rwx) by user, 07 by user's group, 05 (r-x) by others, and is an ext4 filesystem. Attempting to download anything, of any size, produces an error dialog: "not enough storage available."

An associated bug (educated hunch) in settings does not use the path as it has been specified by the user, and substitutes that path with its /run/user... equivalent. A very cute trick which, even if it worked, is guaranteed to confuse the end user: a cardinal sin in every field of engineering.

I haven't looked at the code which produces this error, but I'll guess that it's related to use of QFile which has never been quite right, not even back in the Troll days.

Tracking down the config file and editing it to use the correct path does not correct the error. Adding ".../." to the end of the config path (a workaround for ye olde QFile eccentricities) does not correct the error.

**Comment by mgautierfr** [comment]
> An associated bug (educated hunch) in settings does not use the path as it has been specified by the user, and substitutes that path with its /run/user... equivalent. A very cute trick which, even if it worked, is guaranteed to confuse the end user: a cardinal sin in every field of engineering.

We don't change the path given by the user. And we don't use QFile (at least not directly, we use [QStorageInfo](https://doc.qt.io/qt-5/qstorageinfo.html))

A nice way to know what is the issue would be to give at least more information when we detect we don't have enough storage. (I've just open the issue #959 for that)

**Comment by kelson42** [comment]
@ShuffleBit I would like to better understand the problem. How do you configure `/localmedia/Kiwix`?

What happens if you do? (Please share the console log as well)
```
$ KIWIX_DATA_DIR=/localmedia/Kiwix ./kiwix-desktop
```

**Comment by kelson42** [comment]
No feedback from the issue reported. I have tested myself by specifying a path to a small USB drive I have mounted and I get a proper error if the file I want to download exceeds the free space available on the flash drive.
