### ISSUE TITLE
Apt version stuck on 2.1.0

### ISSUE THREAD

**Issue by jojo2357** [kiwix/kiwix-desktop#951]
I encountered a bug regarding local file monitoring on my apt install of kiwix. Switching to flatpak bumped the version from 2.1.0 to 2.3.1 and removed the bug.

I have seen this happen with other softwares before, so I understand if nothing will change, just doing my job and reporting

**Comment by kelson42** [comment]
@jojo2357 I don't understand this bug report:
* What are the detailed steps to reproduce the problem?
* What do you get and what do you expect exactly?

**Comment by kelson42** [comment]
@jojo2357 I don't understand this bug report:
* What are the detailed steps to reproduce the problem?
* What do you get and what do you expect exactly?

**Comment by jojo2357** [comment]
Oh right,

Pop os 22.04

command to install via apt: `sudo apt install kiwix`
command to install via flatpak: `flatpak install kiwix`

going to help > about and finding the version for each install yields the described discrepancy, implying the apt package is not up to date, or my apt is terribly messed up.

result of `apt list --installed | grep -i kiwix`
```
kiwix-tools/jammy,now 3.2.0-2 amd64
kiwix/jammy 2.1.0-2 amd64
```

both versions should be `2.3.1` but apt clearly isnt

**Comment by kelson42** [comment]
Yes, newst version of Kiwix go to newest version of Debian, see https://tracker.debian.org/teams/kiwix-team/.

Maybe @legoktm, the deb packager, can tell more about that... but on Kiwix side, I don't see what we can do more.
