### ISSUE TITLE
Library filters components have to be improved

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#958]
Today the current solution to display a select list (used for languages, categories, content types) has the following weaknesses:
* It's not immediatly visible what is the current choice(s)
* Impossible to make multiple choices
* If the list is very long (like for the languages or categories), very combersome (no free text search)

**Comment by kelson42** [comment]
@juuz0 To me this is the main problem with the library UX challenge. Can you please propose a Qt component which would allow to fix the 3 listed problems?

**Comment by juuz0** [comment]
Currently working on this :+1:

**Comment by gmikhail** [comment]
I gave my opinion on resetting all filters to default here: https://github.com/kiwix/kiwix-desktop/issues/902#issuecomment-1666726289
