### ISSUE TITLE
ZIM without favicon should be displayed with a default icon

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#966]
In both local and remote library. Currently nothing is displayed:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/46285ba1-6483-4003-8ffa-17f2acb7a2d5)

https://github.com/kiwix/libkiwix/pull/664/files could be taken as example

**Comment by kelson42** [comment]
@juuz0 Do you think you could do that within  the #946

**Comment by juuz0** [comment]
@kelson42 also considering https://github.com/kiwix/kiwix-desktop/pull/946#issuecomment-1651972852, you may have noticed I displayed the default icon already. But seems like some books still go under the radar, can you share one of them which doesn't show the default icon?

**Comment by juuz0** [comment]
@kelson42 need a zim file (whose icon doesn't show up) for testing this!

**Comment by kelson42** [comment]
@juuz0 I will :)

**Comment by kelson42** [comment]
@juuz0 Strangly I can not reproduce it. Closing for the moment, will reopen if it appears again.

**Comment by Popolechien** [comment]
@juuz0 I have one:
[Documentation ubuntu française](https://library.kiwix.org/?lang=fr&q=ubuntu#lang=fra&q=ubuntu) does not seem to have an icon
![image](https://github.com/kiwix/kiwix-desktop/assets/21675885/888d9e35-4c86-422a-9a3c-61145d47994f)

**Comment by kelson42** [comment]
@Popolechien Works for me 
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/3a339d89-da65-4cae-a9a7-e64e24e8ebd9)

I guess you don't test with latest dev version/nightly?

**Comment by kelson42** [comment]
But I have discovered [another bug of the same kind](https://github.com/kiwix/kiwix-desktop/issues/975).

**Comment by kelson42** [comment]
@Popolechien I close again, but please reopen if you have a scenario with latest nightly.
