### ISSUE TITLE
Shortcuts `ctrl+f4` and `ctrl+w` should close current tab

### ISSUE THREAD

**Issue by FractalU** [kiwix/kiwix-desktop#968]
The shortcut `ctrl + f4` only works immediately after a tab has been clicked. What I expect is that that shortcut always closes the current tab regardless of what has been clicked or what is in focus like in any other browser e.g. chrome or firefox. Furthermore, any other browser support `ctrl + w` along with `ctrl + f4` to close the current tab.

Additional suggestion: Add `ctrl + w` to close the current tab.

Currently, I tested this issue on kiwix-desktop 2.3.1 on both windows 7 and 10.

**Comment by kelson42** [comment]
Thank you for your bug report. To me it does not work at all and I confirm that `ctrl+f4` and `ctrl+w` are shortcuts to close current tab in Chrome, FF and Edge. So we should implement it. Sounds easy.

**Comment by FractalU** [comment]
@kelson42 Thank you for your response. Actually, the bug turned out to be something else. If the mouse cursor is hovering over one of the tabs in the tab bar then `ctrl + f4` closes that tab, otherwise `ctrl + f4` does nothing. It only works for `ctrl + f4`. I thought it was the mouse click as reported above, but it turned out to be the mouse hover. I hope you can confirm that behavior.

**Comment by kelson42** [comment]
> If the mouse cursor is hovering over one of the tabs in the tab bar then `ctrl + f4` closes that tab

Does not work for me that way.

**Comment by FractalU** [comment]
That's weird. Did you test it on windows 10 or 7. Maybe it's windows specific. I definitely had that behavior on windows using kiwix-desktop 2.3.1. Maybe try again. The bug is very subtle.

**Comment by kelson42** [comment]
@FractalU No, I test on Ubuntu... but at this stage, I propose we just implement the feature the right way and see if this is OK for you.

**Comment by FractalU** [comment]
@kelson42 Yeah, I agree that you implement this feature the right way. I wanted to confirm whether there really is a buggy implementation already. If there is, then that implementation has to be replaced with this new one.

**Comment by kelson42** [comment]
@juuz0 Is that something you could briefly implement?

**Comment by juuz0** [comment]
We've a few things here

First we were getting the tab index from mouse position, which obviously was wrong. 
Secondly, about the shortcuts, we used `QKeySeqeuence::close` [which has inconsistent mappings](https://doc.qt.io/qt-6/qkeysequence.html#standard-shortcuts)

Both fixed in #981

**Comment by FractalU** [comment]
Ah, `ctrl + w` does indeed work on Pop!_OS 20.04 but not `ctrl + f4`. That's because Pop!_OS 20.04 uses the gnome desktop environment. I wonder why `ctrl + w` doesn't work on Windows. It should according to `QKeySeqeuence::close`.
