### ISSUE TITLE
App crash on mouse right click in local library

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#971]
Specificaly in the white zone at the bottom at of the screenshot (without any book)
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/a996ce82-c89d-4f29-9e12-ed0aceed26a0)

Clearly a regression (at least in `openFolder` git branch)

**Comment by juuz0** [comment]
Good catch. Added a commit to fix this in #970
