### ISSUE TITLE
Big space at bottom of library category list seems not appropriate

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#973]
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/7d1da09e-3d01-4c16-80fd-788f9a11b3ce)

Can we somehow adjust the list height dynamically based on amount of categories available?

**Comment by kelson42** [comment]
@juuz0 How complex is that to fix?

**Comment by juuz0** [comment]
It is possible that the recent PR fixes this

**Comment by kelson42** [comment]
@juuz0 which PR excactly?

**Comment by juuz0** [comment]
the new  filters one: https://github.com/kiwix/kiwix-desktop/pull/965
