### ISSUE TITLE
Remember library filter values over restart

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#974]
For:
* Categories
* Languages
* Content type

**Comment by kelson42** [comment]
@juuz0 Would you be able please to implement this quickly so we can get in usability?

**Comment by juuz0** [comment]
On it

**Comment by juuz0** [comment]
This is a simple thing but blocked by #965 since I changed a lot of stuff there and added multi selection. Once the design is approved there, I'll create a PR on top of #965 to do this.
