### ISSUE TITLE
Add "Open folder" command to right-click menu

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#98]
Windows/beta2: it would be nice to be able to figure out where previously downloaded and stored zim files are located. In my particular use case there's been several downloaded over time in different folders, and I have no idea where since Kiwix only lists these files in its library without telling me where they are.

**Comment by Its-Maniaco** [comment]
@Popolechien @kelson42 Hi, I am pretty new to open source and I would love to work on this issue. I went through the issue description, understood the idea but cannot figure out a way to initiate. Could you please help me with the issue more?

**Comment by kelson42** [comment]
@Its-Maniaco We might help if you have a few very precise question. But this is not a programming course. If you don't know roughly how to fix a ticket you should not pick it.
