### ISSUE TITLE
Error in the description of Gippsland

### ISSUE THREAD

**Issue by ZdZisl** [kiwix/kiwix-desktop#982]
I am submitting a correction to the wrong website address.
On the website https://en.wikipedia-on-ipfs.org/wiki/Gippsland under the paragraph "Following these expeditions ... See also" a link to the website was incorrectly given.
Now the address is wrong... /english/magic-name.htm/
It should be ... /english/magic-name.htm  - WITHOUT the trailing slash.
Zdz

**Comment by mgautierfr** [comment]
zim files are a snapshot of what was the content when zim file was created.
Correct the content in the source (wikipedia here) and next zim file will have the corrected content.

**Comment by Popolechien** [comment]
Was going to say the same - with the added mention that external links in the main body of text are usually to be avoided on Wikipedia.
