### ISSUE TITLE
Draging the vertical scrollbar does not work at all in fullscreen mode

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#984]

**Comment by sgourdas** [comment]
So, I noticed that clicking on the scrollbar without moving the mouse was moving it, even in fullscreen.  It seems like the MainWindow::eventFilter was handling the mouse move events and not letting the event go through for the scroll bar to move.

I added a check to see if the mouse is being clicked, which would indicate a drag event.

@kelson42 if you need a video showcasing the before/after, don't hesitate to ping me, before I make the PR.

**Comment by mgautierfr** [comment]
@sgourdas If you want us to see you commit and discuss it, please do a PR (even as draft).

**Comment by sgourdas** [comment]
Posting a gif, showcasing the fix, to ease the closing of this. Please inform me if anything else is needed.

![2024-03-2823-27-48-ezgif com-video-to-gif-converter](https://github.com/kiwix/kiwix-desktop/assets/57002743/5c5cca68-0df1-4c11-9632-a2ba0f5607f9)
