### ISSUE TITLE
After editing keyword in (Fulltext search) results differ from searching for that word from scratch

### ISSUE THREAD

**Issue by mars4science** [kiwix/kiwix-desktop#988]
Version: 
kiwix-desktop_x86_64_2.3.1-2.appimage 

Steps:
Opened wikipedia all maxi.
In search box entered kirtz, as no pages were suggested selected "kirtz (Fulltext search)". Got many results after `No results were found for "kirtz (Fulltext search)"`. Changed kirtz to kurtz. Only one link was listed after `No results were found for "kurtz (Fulltext search)"`. However, if I deleted all text in search bar and then typed "kurtz" I got many pages suggested and when selected  "kurtz (Fulltext search)" then many results were listed after `No results were found for "kurtz"` (btw Kurtz resulted in about the same).

Expected result: editing text in search bar results in same result as entering search query from scratch. As of now I did not find it working as narrowing results either, so current behavior is IMO not useful and strange. 

P.S. Why the phrase "No results were found" in results? What does it mean since for some there were pages and for some there seems to be no pages?

**Comment by kelson42** [comment]
I confirm the bug. If the user choose, in the suggestion list, the last item which is `foobar (fulltext search`, then:
* A fulltext search is made on `foobar`
* In the searchbox is printer `foobar (fulltext search)`

As a result if the searcbox content is modified, for example for `foobar2 (fulltext search)`, then no result will be found because with have included `foobar2 (fulltext search`.

We should just print `foobar` in the search bix IMO, not `foobar (fulltext search)`

**Comment by sgourdas** [comment]
Reading through the initial issue it seemed that in all "Fulltext search" searches, the dialog "No results were found for ..." was showing up. 

After a lot of going through the code of also libwikix, I realized the variables `start` and `search->getEstimatedMatches()` called on the SearchRenderer are inverted. 

I will link a PR with the simple fix...
![comparison](https://github.com/kiwix/kiwix-desktop/assets/57002743/7d25c170-9863-460b-b18b-912704177d22)

**Comment by sgourdas** [comment]
@kelson42 regarding your last comment, I feel like the `(fulltext search)` showing up in the search bar signifies that the search has been done differently than just choosing one of the dropdown options. Do you still feel like it should not be present there?
