### ISSUE TITLE
Flatpak package should associate *.zim files to itself

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#99]
If I click in a ZIM file in a file browser or just download a ZIM file via the web browser. Kiwix Desktop 2.0 installed via Flatpak should be open automatically.

**Comment by kelson42** [comment]
@birros Maybe you an idea how to achieve that?

**Comment by birros** [comment]
I did it for WebArchives, it's relatively simple, you have to create a description file for the mime type, then specify this mime type in the desktop file.

So I placed the [com.github.birros.WebArchives-mime.xml](https://github.com/birros/web-archives/blob/master/data/desktop/com.github.birros.WebArchives-mime.xml) file in the `/app/share/mime/packages` folder and added the definition of the mime type created `application/vnd.github.birros.web-archives.zim` in the `MimeType` field of the [desktop file](https://github.com/birros/web-archives/blob/master/data/desktop/com.github.birros.WebArchives.desktop.in).

I used a simple file extension pattern to target zim files, which works very well, it may be possible to target a magic number but I'm not sure.

**Comment by kelson42** [comment]
@birros Thank you very much for your help
@mgautierfr Great to see this implemented so quickly.
