### ISSUE TITLE
Kiwix don't download resources on windows 7

### ISSUE THREAD

**Issue by Zabihullah-Danish** [kiwix/kiwix-desktop#990]
I download and setup kiwix on windows 7 but right now when I want download resources it shows the following JavaScript Alert message. 
below is the screen shot that shows the error
anyone please?
 
![kiwix error](https://github.com/kiwix/kiwix-desktop/assets/65042690/c99f353c-b871-404d-acce-51f3a7b20842)

**Comment by kelson42** [comment]
@Zabihullah-Danish Thank you for your bug report. Sorry for that question, but are you connected to the Internet? If "yes", would you be able please to start the program from the command line/terminal, so I see if there is an error there?

**Comment by Zabihullah-Danish** [comment]
> @Zabihullah-Danish Thank you for your bug report. Sorry for that question, but are you connected to the Internet? If "yes", would you be able please to start the program from the command line/terminal, so I see if there is an error there?



> @Zabihullah-Danish Thank you for your bug report. Sorry for that question, but are you connected to the Internet? If "yes", would you be able please to start the program from the command line/terminal, so I see if there is an error there?


> @Zabihullah-Danish Thank you for your bug report. Sorry for that question, but are you connected to the Internet? If "yes", would you be able please to start the program from the command line/terminal, so I see if there is an error there?

So how to start program from command line?

**Comment by kelson42** [comment]
https://www.indeed.com/career-advice/career-development/how-to-run-program-in-command-prompt

**Comment by Zabihullah-Danish** [comment]
I have started the program from command line but the problem is when I click on downloading any resource I get that above JavaScript alert

**Comment by kelson42** [comment]
@Zabihullah-Danish What is written on the terminal when you do so? Please cut/past all the log printed on the terminal after you start `kiwix.exe`

**Comment by Zabihullah-Danish** [comment]
There is no issue with starting program from cmd below is the screen shot that the program starts normally but when I click on download any resource than I get that popup JavaScript Alert message.

![kiwix error](https://github.com/kiwix/kiwix-desktop/assets/65042690/b1205324-b62e-46b8-be5e-a62514b3187e)

**Comment by kelson42** [comment]
@Zabihullah-Danish OK, so nothing.... difficult to say at this stage. We will have a look. As a workaround: you can download manually the ZIM file from https://library.kiwix.org

**Comment by Zabihullah-Danish** [comment]
https://library.kiwix.org/
from here I just be able to browse contents but couldn't download any resources.

**Comment by mgautierfr** [comment]
You should have a blue `Download` button under each book titles.

**Comment by AyushSahoo19** [comment]
> You should have a blue `Download` button under each book titles.

Sir I want to know if the issue was solved or not , if not how I can contribute to this issue or bug

**Comment by kelson42** [comment]
@Zabihullah-Danish We are about to release new version 2.4.0 in the next weeks. Both backend and frontend of online library (and download mgmt) have been rewritten. We strongly suspect the bug you have reported has been fixed. Please give a try with the latest nightly https://download.kiwix.org/nightly/2024-04-29/kiwix-desktop_windows_x64_2024-04-29.zip and let us know.

**Comment by kelson42** [comment]
@Zabihullah-Danish I close the issue for now but please share your feedback with us and reopen if you still suffer of the bug.
