### ISSUE TITLE
when i try to open some zim files they do not work and ask replace the IP in your browser address bar with localhost

### ISSUE THREAD

**Issue by Zerium4** [kiwix/kiwix-desktop#995]
the full error is this
The requested URL can not be loaded because service workers are not supported here.
If you use Firefox in Private Mode, try regular mode instead.
If you use Kiwix-Serve locally, replace the IP in your browser address bar with localhost

it happens when you get or try to download and use the military medicine and or the cheatography zim file from the kiwix library site and a few others dont load in the same way i just try to open then the same as any other zim file and they dont work

if it is not clear i cant do that as im using kiwix desktop and would not even have a address bar to change

**Comment by mgautierfr** [comment]
This is a known issue. We are working on fixing this issue but for now, using `localhost` is the only way (or setup a server with http**s**)

Duplicated of https://github.com/kiwix/kiwix-desktop/issues/487
