### ISSUE TITLE
Language missing in language selector

### ISSUE THREAD

**Issue by stefangrotz** [kiwix/kiwix-desktop#997]
The Esperanto Wikipedia is available on the website (https://library.kiwix.org/#lang=epo) but it does not appear in the desktop app:

![grafik](https://github.com/kiwix/kiwix-desktop/assets/5982239/48dfcb4c-99bd-4fc3-8350-57c768768032)

 
Kiwix Desktop Version 2.3.0 on Ubuntu.

**Comment by kelson42** [comment]
Probably fixed in current dev version. I will verify.

**Comment by juuz0** [comment]
Yes, works in current dev
![image](https://github.com/kiwix/kiwix-desktop/assets/26814569/84101669-aeec-4c0a-a759-2c0946d4a306)
